#!/usr/bin/env python3
"""Extend The Cool of Evening's French gist to full per-passage coverage.
Merges into content/gist/cool-of-evening/fr.json, keeping existing entries and adding the rest.
French-first; native review: complete. Run: python3 scripts/build_gist_fr_full_ep04.py
"""
import json, os
SLUG = "cool-of-evening"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", SLUG, "fr.json")

FR = {
 2: "Vous rassemblez ce que le bus a à bord : quelques bouteilles d'eau, une petite trousse de secours, une grande bâche qui pourrait faire de l'ombre. L'air à l'intérieur s'épaissit déjà de chaleur, la sueur coule dans votre dos. Il faut décider quoi faire, et vite.",
 3: "Vous essayez la radio, morte, et aucun téléphone n'a de réseau. Le chauffeur, M. Bello, fait passer le mot : rien ne bouge par une chaleur pareille, les secours ne viendront qu'au soir. Restez tranquilles, dit-il, au frais. Mais Sami est petit et s'affaiblit, et le soir est loin.",
 4: "Vous mettez Sami dans la mince bande d'ombre contre le bus. Ça aide un peu, mais l'ombre seule ne suffira pas — l'enfant a besoin d'eau aussi, et vous d'un plan. Vous vous arrêtez un instant et comprenez : les mains vides, vous ne pouvez pas faire grand-chose ici.",
 5: "Vous descendez sur la route. La lumière est blanche et dure, les plaines ocre courant jusqu'à la crête tremblante, la chaleur assez épaisse pour s'y appuyer. La route est vide des deux côtés — sauf, au loin, une petite silhouette qui s'éloigne.",
 6: "Vous vous forcez à réfléchir. Régler d'abord les vivres — eau, ombre, un plan. Ou aller droit à Sami et rester près de l'enfant. Ou passer de siège en siège pour faire aider les passagers. Chaque choix coûte du temps, et par cette chaleur, le temps coûte de l'eau.",
 8: "Vous sentez la chaleur peser lourd dans votre poitrine, et vous pensez à Sami — petit, devenu silencieux, sans eau, dans un air de fournaise. Une telle chaleur peut tuer un enfant. Ce n'est pas une peur, c'est un fait. Personne d'autre ne bougera. Alors ce sera vous.",
 11: "Vous rejoignez Sami vite, avec le peu que vous avez — quelques gorgées, un linge mouillé, un bout d'ombre. L'enfant se stabilise un instant. Mais ça ne tiendra pas ; il faut de la vraie eau, et davantage, et vite. Vous ne pouvez pas rester là à espérer.",
 13: "Vous prenez en charge la caisse d'eau. Lourde, et chaque bouteille compte désormais. Partagée lentement et équitablement, il y en a assez pour tenir ; attrapée et gâchée, non. Alors vous la comptez, et vous la gardez près de vous.",
 14: "Vous prenez la bâche et les chiffons. Ils feront de l'ombre, ce qui aide — mais vous n'avez assuré aucune eau. L'ombre tient le soleil à l'écart ; elle ne mouille pas une bouche crevassée. Il vous faudra quand même trouver de l'eau, et vite.",
 15: "Tatie Rose connaît cette route ; elle l'a traversée bien des fois. « Reste loin des plaines ouvertes, dit-elle. Elles paraissent proches. Elles ne le sont pas. » Elle vous met aussi en garde contre l'homme au pick-up. « Rationne chaque goutte, attends que le soleil baisse. C'est comme ça qu'on vit ici. »",
 16: "Vous installez M. Danso à l'ombre et lui donnez une lente gorgée d'eau. Peu à peu ses yeux s'éclaircissent et reviennent à vous. « Merci », dit-il, la main tremblant dans la vôtre. Vous promettez de repasser le voir, et retournez à la journée.",
 17: "Vous continuez pour vous occuper de Sami ; l'enfant d'abord, le reste peut attendre un instant. Mais il faut encore décider comment — assurer d'abord de la vraie eau, ou aller droit au chevet de l'enfant.",
 18: "La chaleur est en vous aussi maintenant — tête légère, bouche sèche, jambes étrangement lointaines. Vous êtes près de votre limite, et vous le savez. Si vous tombez, il ne reste personne pour Sami. Alors bougez lentement, et faites attention.",
 19: "Le bus se réveille à lui-même. Les gens se mettent à bouger et à partager. Une femme sort un grand bidon d'eau ; un homme grée la bâche pour l'ombre ; et un plan prend forme, siège après siège. Vous n'êtes plus seul là-dedans — et cela change tout.",
 20: "Personne ne bouge. Les gens fixent leurs mains, ou le dehors éblouissant — effrayés, et les gens effrayés se taisent. Vous ne pouvez pas les forcer. Alors vous vous détournez et continuez seul ; c'est plus dur ainsi, mais Sami ne peut pas attendre leur courage.",
 21: "Les vivres sont réglés ; maintenant il faut de la vraie eau. Deux chemins vers la crête. La route, longue mais facile à suivre. Ou tout droit à travers les plaines ouvertes — bien plus court, mais sans piste, sans ombre, et inconnu.",
 22: "Vous prenez à cœur les mots de Rose. Rationner l'eau. Éviter les plaines. Ne pas faire confiance à l'homme au pick-up, et attendre que le pire du soleil passe. Un conseil simple, et bon. Reste à le suivre, vraiment.",
 23: "Vous vous sentez plus ferme après ce bon geste — aider quelqu'un semble, curieusement, vous aider aussi. La tête plus claire, le pas plus sûr. Il reste à faire, et le soleil est encore haut, mais vous vous sentez capable.",
 24: "Un pick-up est arrêté sur le bas-côté, moteur cliquetant dans la chaleur. Un homme y est appuyé, tout sourire, avec de l'eau en bouteille et des trajets en ville à offrir. Une petite foule s'est rassemblée autour — effrayée, assoiffée, et prête à payer.",
 25: "Vous menez un petit groupe vers Sami et l'ombre. À marcher ensemble, tous se sentent plus forts ; on porte de l'eau, des chiffons, un peu d'espoir. « Par ici », dites-vous, et ils suivent — un bon sentiment, dans une heure dure.",
 26: "La route est longue et éprouvante. Le bitume est mou sous les pieds ; des mirages d'eau brillent devant et disparaissent quand on les atteint ; et pas la moindre ombre nulle part. Mais elle est dégagée, et elle mène où il faut aller. Alors vous continuez de marcher.",
 28: "Vous vous avancez sur les plaines ouvertes, et aussitôt cela sonne faux. La crête ne se rapproche pas ; derrière vous, la route se brouille et se fond dans le tremblement de l'air. Il n'y a ici que chaleur et lumière dure — et vous êtes au milieu, seul.",
 29: "La bâche est déchirée et trop courte pour faire beaucoup d'ombre ; il ne vous reste que les chiffons, qui ne couvriront pas tout le monde. Il faudra faire avec — ou repartir vers les réserves chercher mieux.",
 30: "La route continue sous le soleil blanc, la chaleur empirant d'heure en heure, votre ombre réduite à une tache dure sous vos pieds. Devant, une voiture à l'arrêt sur le bas-côté ; le soleil cogne sur votre nuque ; et un panneau, sa peinture depuis longtemps cloquée.",
 31: "Une voiture est enlisée dans le sable, un vieil homme affaissé sur le volant, vitre baissée, tête pendante. Il a trop chaud et n'a plus la force de bouger. Vous arrêter, c'est perdre du temps ; ne pas le faire, c'est risquer qu'il ne passe pas l'après-midi.",
 33: "Vous poussez à travers le pire de la chaleur, chaque pas plus dur, l'air brûlant la gorge. Devant, des choix : l'homme au pick-up est peut-être proche, ou l'étrange fumée du relais — ou vous pouvez simplement foncer vers le bus.",
 34: "Vous mettez l'épaule, et la voiture se dégage. Les yeux du vieil homme s'emplissent ; il vous presse une bouteille chaude dans les mains. « Prends-la, dit-il, pour ta peine. » Elle n'est pas fraîche — mais c'est de l'eau, donnée de bon cœur, et vous la prenez et repartez.",
 35: "Vous ne pouvez pas rester — mais vous ne pouvez pas non plus les laisser. Alors vous promettez d'envoyer de l'aide. « Tenez bon, leur dites-vous. Restez à l'ombre. Je ne vous oublierai pas. » Et vous le pensez — puis vous tournez les talons et partez.",
 36: "Le bus se fait un coin d'ombre. La bâche est tendue haut, l'eau mise en commun au centre, les plus fragiles — les vieux, les petits — placés au plus frais. Ce n'est pas grand-chose. Mais c'est un plan, et il appartient à tous maintenant.",
 37: "Siège après siège, le bus effrayé devient un bus qui travaille. Chacun a sa tâche — l'un veille sur les enfants, l'un partage l'eau, l'un tient l'ombre. La peur devient action, et l'action vaut mieux que l'attente, à tous les coups.",
 38: "La chaleur ronge votre volonté. Une petite voix dit : arrête, assieds-toi, repose-toi — personne ne t'en voudrait, et ce serait si facile. Mais vous pensez à Sami qui attend, et vous repoussez la voix. Pas encore. Pas tant que l'enfant a besoin de vous.",
 39: "Vous atteignez le panneau, mais le soleil en a mangé toute la peinture ; pas un mot à lire. Une flèche indique la route, l'autre la fumée. Quel chemin ? Il faudra deviner, et bien deviner.",
 42: "Vous lui tournez le dos et le laissez à la foule effrayée et à son argent. Ça fait du bien de partir. Il vous hèle, mais vous ne vous retournez pas. Son genre trouve toujours quelqu'un — mais pas vous, et pas aujourd'hui.",
 43: "Vous comptez l'argent — ça fait mal de le donner — et il vous tend des bouteilles chaudes avec ce large sourire. « Le trajet viendra, dit-il. Attends ici. » Quelque chose en vous n'y croit pas. Mais c'est fait, et l'argent est parti.",
 44: "Vous demandez franchement : l'eau est-elle seulement fraîche ? propre ? Il sourit et détourne les yeux. « Elle est mouillée, non ? » dit-il, sans rien promettre. Voilà votre réponse — un homme qui ne promet rien a quelque chose à cacher.",
 45: "Vous rapportez les bouteilles, et dans vos mains elles sont chaudes — chaudes comme un bain, inutiles à un enfant. Et le trajet promis ? Il ne vient pas. Vous attendez, vous guettez la route : rien. Il a pris votre argent et ne vous a presque rien donné.",
 46: "Vous ouvrez une bouteille, et l'eau a mauvais goût — tiède, fade, un peu nauséabonde. Quelque chose cloche ; vous ne donneriez pas ça à un enfant. Vous avez payé le prix fort pour de la mauvaise eau, et le doute en vous avait raison depuis le début.",
 47: "Vous le cherchez, mais le pick-up est déjà parti — seule sa poussière flotte sur la route lointaine, se dissipant dans la chaleur. Le trajet n'a jamais existé. Vous restez là, dupé, au milieu de la route vide, avec votre mauvaise eau tiède.",
 48: "Le pick-up est parti, la foule dispersée — rien que la chaleur, la route vide, vos poches vides. Vous avez appris une dure leçon, payée bien trop cher. Vous continuez avec le peu qui reste, et ce n'est pas grand-chose.",
 49: "La foule lui fourre de l'argent — des mains pleines de billets, des visages qui le supplient de prendre. Et il prend, lentement, avec ce sourire, choisissant qui aider selon qui peut payer. Vous voyez tout le tour de passe-passe, clair. C'est laid.",
 50: "Loin sur les plaines, la crête paraît enfin plus proche — ou pas ? Vous n'en êtes plus sûr ; la chaleur tord l'air, tord ce que vous voyez, peut-être ce que vous pensez. Vous êtes si fatigué, si assoiffé. Mais vous continuez.",
 51: "Les plaines s'étirent sans fin, la crête ne grandit jamais, la tête vous tourne tandis que l'horizon se brise et flotte. Vos jambes ne sont plus à vous. C'est le moment : tomber ici, en plein découvert — ou faire demi-tour maintenant, tant que vous le pouvez.",
 52: "Vous atteignez enfin le pied de la crête, titubant, la langue épaisse et sèche — mais là. D'une façon ou d'une autre, vous avez traversé. Maintenant il faut décider : continuer, épuisé comme vous êtes, ou affronter ce que vous avez perdu en chemin.",
 53: "Vous faites demi-tour vers la route tant que vous le pouvez — le choix dur et juste. Vous rampez le dernier bout sur les genoux, et atteignez le bitume, secoué et lent. L'après-midi se consume. Mais vous êtes vivant, et encore capable d'aider.",
 54: "Vous tentez de bricoler un peu d'ombre à la famille — une portière calée, un linge tendu, ce que vous pouvez. Ça tient un peu le soleil à l'écart. Mais il n'y a pas d'eau à donner, et l'ombre sans eau ne gagne que du temps. Il faut choisir.",
 55: "Vous donnez votre propre bouteille, et la famille boit, lentement, avec soin, le soulagement passant sur leurs visages. Le petit enfant cesse enfin de pleurer. « Merci », répète la mère. Vous avez moins d'eau désormais — mais vous avez bien agi.",
 56: "Sans votre eau, la chaleur vous trouve vite — bouche qui sèche, tête qui bat. Vous avez donné pour aider, et vous recommenceriez ; mais le soleil s'en moque. Il pèse, c'est tout. Il faut garder la tête froide, et continuer.",
 57: "Un inconnu vous fait entrer dans une bande d'ombre. « Juste une minute, dit-il. Assieds-toi. Respire. » Hors du soleil, c'est délicieusement frais, et votre corps vous supplie de rester. Mais une minute peut glisser vers une heure — et Sami attend.",
 58: "Vous avancez dans l'éblouissement, la bouche comme du papier, la lumière assez vive pour faire mal. Chaque pas est un petit combat — mais vous les enchaînez, l'un après l'autre. Lent, c'est bien ici. S'arrêter, c'est ce qui tue.",
 60: "Quelqu'un montre la route : un passager s'est éloigné, dit-on, vers le tremblement de l'air, hébété par la chaleur. Seul, en plein soleil, sans rien par là que chaleur et distance. Si personne ne le suit, il ne reviendra pas.",
 61: "Vous le trouvez dans un ravin sec, titubant, clignant des yeux, ne reconnaissant pas votre visage. Le soleil l'a durement frappé ; sa peau est sèche, pas moite — mauvais signe. Vous lui prenez le bras. « Viens avec moi, dites-vous. Par ici. Doucement. »",
 62: "Vous ne pouvez pas tout faire à la fois, et Sami a le plus besoin de vous. Alors vous faites prévenir quelqu'un d'autre pour le passager perdu, et vous continuez. Cela vous pèse — mais il faut choisir, et vous choisissez l'enfant.",
 63: "Vous les ramenez sains et saufs au bus, où leur famille crie de soulagement. On vous presse une bouteille à partager et on vous fait une place à l'ombre. « Merci », répètent-ils — car une gentillesse ne reste jamais sur place ; elle se propage.",
 64: "Vous regardez la plaine — immense, vide, tremblant de chaleur, rien ne bougeant nulle part. Le monde entier semble immobile, attendant que le soleil baisse enfin. Et vous aussi, vous le réalisez.",
 65: "Le soleil monte à son pire ; c'est le cœur de la chaleur. Le bitume est mou, l'air lui-même semble brûler, et penser devient lent et difficile. C'est l'heure à survivre. Passez-la, et vous avez presque gagné la journée.",
 67: "Bello vous presse la dernière bouteille fraîche dans les mains. « Pour l'enfant, dit-il. Vas-y — je reste avec le moteur. » Ses mains sont noires de cambouis, et tremblent un peu. C'est l'aide qu'il peut donner, et il la donne. Vous la prenez, et le remerciez.",
 68: "À l'avant du bus, on se rue sur l'eau — voix qui montent, mains qui saisissent, la peur qui prend et se répand vite. Une bousculade de plus et c'est la bagarre. Vous pouvez tenter de les calmer et partager équitablement, ou forcer votre propre chemin jusqu'à la caisse.",
 70: "Sur le bas relais se dresse une vieille halte ferroviaire, fermée depuis des années — tout le monde le dit. Pourtant, aujourd'hui, un mince filet de fumée en monte, et un vieux moulin tourne lentement à côté. Personne ne sait l'expliquer. Quelque chose, ou quelqu'un, est là.",
 71: "Vous atteignez le vieux relais, moins mort de près. Vous frappez — pas de réponse. Encore — rien. Mais la porte n'est pas close ; elle est entrebâillée, et de l'air chaud et une odeur de fumée s'en échappent par l'ouverture.",
 72: "Vous entrez, dans une pièce sombre et étouffante — et là, par terre, un vieil homme gît près d'un poste radio mort, bougeant à peine. Son souffle est court, sa peau sèche et grise. Il est là depuis un moment, seul. Pas de temps à perdre.",
 73: "Vous appelez à la porte, et un instant, rien. Puis une voix répond — faible, sèche, âgée. « Ici, dit-elle. Là-dedans. » Quelqu'un est à l'intérieur, et a besoin d'aide. Vous ne pouvez pas vous en aller maintenant.",
 74: "Vous vous mettez au travail — de l'eau aux lèvres, lentement, un linge mouillé sur la nuque, l'air chaud éventé du visage. Peu à peu le vieil homme revient. Ses yeux s'ouvrent. « Le puits, souffle-t-il. Derrière. Profond et froid. Et la radio, si tu arrives à la faire marcher. »",
 75: "Vous vous retournez pour courir chercher de l'aide — puis vous vous arrêtez. Il n'y a pas d'aide ici ; pas avant le soir. Pas d'équipe, pas de téléphone, personne qui vienne. C'est vous ou personne, et le vieil homme par terre le sait aussi. Ses yeux vous suivent jusqu'à la porte.",
 76: "Le vieil homme lève les yeux, plus clairs à présent. « Tu viens du bus de midi ? dit-il. Alors il y a une vieille amie à moi à bord, je parierais — Rose. On se connaissait, autrefois, sur cette route. Dis-lui que Faro est toujours là. »",
 77: "Vous décidez de les mettre face à face avant la fin du jour — Rose et le vieux Faro, après toutes ces années. C'est peu de chose, à côté de l'eau et de l'ombre. Mais ce n'est pas rien ; certaines portes restent closes des années parce que nul ne songe à frapper. Vous frapperez.",
 78: "Dedans, l'endroit garde des années de poussière — l'air sec, vieux, immobile, le bois craquelé de chaleur, rien remué depuis longtemps. Et pourtant quelque chose a bougé ici : quelqu'un a allumé ce feu ; quelqu'un a mis ce moulin à tourner.",
 79: "Au mur pend une vieille photo, gondolée et jaunie. Dessus, un jeune homme se tient près de ce même moulin, une jeune femme à côté, riant tous deux. Vous connaissez ce visage — c'est Rose, du bus, il y a longtemps. Puis, de la pièce du fond, un bruit faible.",
 80: "Le pick-up revient une dernière fois, la vitre descendant. « Toujours en panne ? Toujours soif ? dit-il. Dernière chance, l'ami. » Le même sourire, le même mensonge. Il sait que vous êtes épuisé, et il compte là-dessus. À vous de choisir, pour de bon.",
 90: "Vous revoilà au bus, dans le dernier du pire de la chaleur, le souffle sec, la tête battante. Et voilà Sami — pâle à l'ombre, trop immobile. C'est l'heure qui compte ; quoi que vous fassiez, faites-le bien. La vie de l'enfant est proche.",
 91: "Vous vous agenouillez près de Sami. L'enfant est brûlant, le souffle rapide et court, les lèvres gercées — mauvais, et ça empire. Il faut le rafraîchir, et tout de suite. Tout ce que vous avez fait aujourd'hui se joue en cet instant.",
 92: "Puis l'aide atteint le bus derrière vous — des mains, de l'eau, des têtes calmes, des gens qui savent quoi faire. Vous n'êtes plus seul avec ça ; d'autres sont là pour partager le poids. C'est comme poser un lourd fardeau, et vous respirez enfin.",
 93: "Maintenant, rafraîchir l'enfant — et ce que vous pouvez faire dépend de ce que vous avez porté. Si vous avez gardé une bonne réserve d'eau, vous avez de quoi faire ; sinon, il faut tirer le meilleur du peu qui reste. Dans tous les cas, vous commencez.",
 94: "Vous examinez l'enfant, doux et attentif, et les yeux de Sami s'entrouvrent — de la peur d'abord, puis, en vous voyant, un peu moins de peur. « Tu es revenu », souffle l'enfant. « Je l'avais dit, répondez-vous. Maintenant, on te rafraîchit. »",
 95: "Vous ouvrez la caisse d'eau, et cela change tout. Des gorgées régulières, des linges mouillés souvent changés au cou et aux poignets, la fièvre de chaleur qui cède lentement. Le souffle de Sami ralentit et s'apaise. L'eau, bien partagée, c'est la vie ; vous le saviez, et vous le voyez maintenant.",
 96: "Vous n'avez pas de caisse à ouvrir, alors vous faites avec ce que vous avez. Des chiffons mouillés de votre dernière eau. Chaque bout d'ombre tiré sur l'enfant, Sami gardé éveillé et parlant. Ce sera peut-être assez. Peut-être pas. Mais vous ne cesserez pas d'essayer.",
 97: "La chaleur est profonde dans l'enfant maintenant, et vous craignez que chiffons et ombre ne la retiennent pas. Vous avez fait tout ce que vous pouviez — mais ce n'est peut-être pas assez. Il faut plus : de l'aide, de l'eau, ou les deux, et vite.",
 98: "Vous levez les yeux et la voyez : loin à travers les plaines, un filet de fumée, et à côté un moulin qui tourne lentement. C'est là où rien ne devrait être, où la vieille halte reste fermée. Cela tire votre œil, et quelque chose en vous.",
 99: "La fumée monte là où personne ne vit — tout le monde jure que l'endroit est mort. Mais la fumée veut dire un feu, et un feu une main pour l'allumer, et une main une personne. Et une personne seule ici, par un jour pareil, peut être en vrai danger. Vous le sentez.",
 100: "Vient maintenant la longue veille : vous gardez l'enfant au frais, l'eau qui circule, et vous attendez que le soleil baisse, heure après heure. Ce n'est pas palpitant — juste un travail régulier, dur, soigneux. Mais c'est le travail régulier qui sauve les gens, alors vous le faites, sans cesser.",
 101: "Et puis, enfin, ça bascule. L'éblouissement s'adoucit ; le soleil blanc glisse vers la crête ; l'air commence, à peine, à fraîchir. Et au loin sur la route, de la poussière s'élève — un camion, un vrai, qui vient. Vous avez atteint la fraîcheur du soir.",
 102: "C'est l'heure la pire, juste avant la rupture — la chaleur pas encore tombée, le corps épuisé, la volonté usée. Mais vous sentez le jour commencer à pencher. Tenez. Tenez encore un peu. La fin est proche.",
 103: "Au bout de la longue route, vous les voyez — poussière, éclats de verre dans le soleil bas, d'autres gens, d'autres véhicules. D'autres s'en sont sortis aussi. Vous n'étiez pas seul à lutter contre la chaleur, et cette pensée vous réchauffe dans la lumière déclinante.",
 104: "Enfin, des phares — et un long panache de poussière derrière, montant la route vers vous. Un camion. De la vraie aide, à vraie allure. Vous vous levez et faites signe, les jambes tremblantes. C'est presque fini. Presque. Vous vous autorisez à y croire.",
 105: "Le soir descend sur les plaines. La lumière devient longue, dorée et nette, la chaleur meurtrière se levant souffle après souffle, les ombres s'étirant de chaque pierre. La terre, si cruelle il y a une heure, est presque douce à présent. Vous la regardez, et vous respirez.",
 106: "Puis cela vient — le premier souffle frais du vent, traversant les plaines pour toucher votre visage. Après la journée que vous avez eue, c'est un cadeau non mérité. Vous fermez les yeux et le laissez rafraîchir la sueur sur votre peau. Vous avez réussi. Vous avez tous réussi.",
 107: "Du bus, vous guettez la route, où un panache de poussière s'élève au loin et grandit. Quelque chose vient enfin — trop loin pour qu'on voie, mais la poussière ici veut dire des roues, et des roues, à cet instant, veulent dire de l'espoir. Vous gardez les yeux dessus, et attendez.",
 110: "La fraîcheur du soir arrive enfin, et le jour s'additionne en ce qu'il est. Tout ce que vous avez fait ici, dans la chaleur, vous revient — de quoi être fier, et de quoi l'être moins. C'est ici que tout devient clair.",
 111: "L'après-midi s'additionne — pas toujours par un grand acte, mais par beaucoup de petits : ce que vous avez partagé, ce que vous avez refusé, pour qui vous vous êtes arrêté. Tout compte au bout du compte ; tout a fait le jour tel qu'il fut. Alors, à quoi le jour a-t-il abouti ?",
 112: "Il y a plus à peser ; le jour a tenu d'autres choses. Un inconnu aidé. De l'eau donnée d'une main ouverte. De petits choix faits dans la chaleur, quand détourner les yeux aurait été facile. Ils ont leur propre poids. À quoi ont-ils abouti ?",
 113: "Et que vous laisse le jour ? Peut-être pas une victoire nette. Peut-être juste le fait de vous être levé, d'avoir essayé — d'avoir, quand c'était dur, chaud et facile de rester assis, refusé de le faire. Cela compte pour quelque chose. Cela a toujours compté.",
 114: "Mais tous les jours ne finissent pas bien. Certains choix coûtent plus qu'on ne croyait ; certaines routes, une fois prises, ne se remontent pas. C'est la dure fin du jour, là où le pire revient. Ce n'est pas facile à regarder — mais c'est vrai. Alors regardez.",
}


def main():
    data = json.load(open(OUT, encoding="utf-8"))
    added = 0
    for nid, text in FR.items():
        k = str(nid)
        if k not in data:
            data[k] = text; added += 1
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"{SLUG}/fr.json: {len(data)} passages total (+{added} added)")


if __name__ == "__main__":
    main()
