#!/usr/bin/env python3
"""Extend The Keeper's French gist to full per-passage coverage.
Merges into content/gist/the-keeper/fr.json, keeping existing entries and adding the rest.
French-first; draft, pending native review. Run: python3 scripts/build_gist_fr_full_ep05.py
"""
import json, os
SLUG = "the-keeper"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", SLUG, "fr.json")

FR = {
 2: "Vous rassemblez ce que le phare a : un bidon d'huile, des mèches de rechange, une boîte d'allumettes, une bonne lampe-tempête. Dehors, le vent hurle dans la rambarde de la galerie et la pluie frappe la vitre comme des pierres. Il faut décider quoi faire, et vite.",
 3: "Vous essayez la radio. Elle grésille et crache, mais enfin la voix de Tam passe, depuis la station côtière. Aucun canot de sauvetage ne peut sortir par une mer pareille, dit-il — pas avant qu'elle se calme ou que l'aube vienne. Gardez la lumière allumée, si vous pouvez.",
 4: "Vous rejoignez Nan au pied de l'escalier et l'installez du mieux possible. Mais la lumière est toujours éteinte, et l'abri seul ne suffit pas — ce bateau là-bas a besoin du faisceau. Il faut de l'huile, un plan, et la tête froide avant de monter.",
 5: "Vous sortez sur la galerie. La mer est noire et immense, la pluie rabattue par le vent. Loin, au-delà de la pointe, les feux du bateau paraissent petits et en peine. En dessous, la crique est un puits d'ombre, et toute la côte gronde.",
 6: "Vous vous forcez à réfléchir. Allumer d'abord la lumière, et voir le reste après. Ou aller droit à Nan et aux chaumières. Ou ameuter la côte pour aider. Chaque choix coûte du temps — et cette nuit, le temps, c'est un bateau qui se rapproche des rochers.",
 8: "Vous sentez la tempête s'installer dans votre poitrine. Vous pensez à ce bateau au-delà de la pointe, approchant des rochers sans lumière pour se guider. Une nuit pareille peut noyer tout un équipage. Ce n'est pas une peur, c'est un fait. Personne d'autre ne grimpera ce phare. Alors ce sera vous.",
 11: "Vous montez vite jusqu'à la lampe avec le peu que vous avez. Une allumette, une étincelle, une flamme vacillante — elle prend, mais faible, et ne tiendra pas sans vraie huile. Vous ne pouvez pas la laisser ainsi et espérer.",
 13: "Vous prenez en charge l'huile et la mèche. Le bidon est lourd, et chaque goutte compte désormais. Bien entretenue, elle gardera la lampe allumée toute la nuit ; gaspillée, et la lumière s'éteint. Alors vous la serrez contre vous et commencez à monter.",
 14: "Vous prenez une lampe-tempête et un rouleau de corde. Elles donnent un peu de lumière et de quoi vous attacher — mais pas le faisceau, et vous n'avez aucune vraie huile en réserve. Il vous faudra quand même de l'huile, et vite, sinon le phare reste noir.",
 15: "Le maître d'équipage Carrick connaît cette côte ; il la surveille depuis des années. « Reste loin du sentier de la falaise, dit-il. Il paraît rapide. Il tue. » Il vous met aussi en garde contre le naufrageur. « Surveille ton huile, tiens la lumière — c'est tout le travail de cette nuit. »",
 16: "Vous installez Da Finch avec une lampe allumée et une couverture, et peu à peu ses tremblements s'apaisent. « Que Dieu te bénisse », dit-il en vous serrant la main. Vous promettez de repasser, et retournez à la tempête.",
 17: "Vous continuez pour tenir la lumière ; cela passe d'abord, le reste peut attendre un instant. Mais il faut encore décider comment — assurer d'abord de la vraie huile, ou monter droit à la lampe.",
 18: "La montée vous épuise — jambes en feu, poitrine haletante, le vent luttant contre vous à chaque marche. Vous êtes près de votre limite, et vous le savez. Si vous tombez ici, il ne reste personne pour tenir la lumière. Alors montez lentement, et tenez la rambarde.",
 19: "La côte se réveille à elle-même. Les gens se mettent à bouger. Un homme roule un fût d'huile, une femme tire du bois sec, et un plan prend forme, porte après porte. Vous n'êtes plus seul là-dedans — et cela change tout.",
 20: "Personne ne bouge. Les portes restent closes, les visages se détournent des fenêtres — ils ont peur, et les gens effrayés se taisent. Vous ne pouvez pas les forcer. Alors vous vous détournez et continuez seul ; c'est plus dur ainsi, mais ce bateau ne peut pas attendre leur courage.",
 21: "La lumière est réglée ; reste la crique et ce bateau. Deux chemins descendent. Le long sentier qui contourne la pointe est sûr mais lent. Le sentier de la falaise, droit en bas, est rapide — et un tueur par un vent pareil.",
 22: "Vous prenez à cœur les mots de Carrick. Surveiller l'huile avec soin, bien éviter la falaise, ne pas faire confiance au naufrageur, et tenir la lumière avant tout. Un conseil simple, et bon. Reste à le suivre, vraiment, ici, dans le noir et le vent.",
 23: "Vous vous sentez plus ferme après ce bon geste — aider quelqu'un semble, curieusement, vous affermir aussi. La tête plus claire, les mains plus sûres. Il reste une nuit dure à passer, mais vous vous sentez de taille.",
 24: "Un homme se tient dans le ressac, une lanterne au poing — le naufrageur. Il a de l'huile à vendre et des bras à prêter, et il sourit trop facilement. « La lumière, ce n'est pas ton affaire ce soir, l'ami », dit-il. Vous avez déjà croisé son genre.",
 25: "Vous menez une petite bande vers la lumière. À marcher ensemble, tous se sentent plus forts ; ils portent huile, bois, corde. « Par ici ! » criez-vous par-dessus le vent, et ils suivent — un bon sentiment, dans une heure dure.",
 26: "Le sentier de la pointe est noir et dur, la pluie y ruisselle, le vent vous pousse dans le dos, pas d'abri nulle part. Mais il est ferme sous les pieds, et il mène où il faut aller. Alors vous continuez de marcher.",
 28: "Vous vous avancez sur la corniche, et aussitôt cela sonne faux. Le vide bâille en dessous, noir et profond ; le vent cogne la falaise et tire sur votre manteau. Chaque pas est un pari — et vous y êtes, maintenant, seul.",
 29: "La mèche de la lampe à main est abîmée ; elle ne donne qu'une flamme basse et vacillante qui ne porte pas loin. Peu utile dans une tempête pareille. Il faudra faire avec — ou retourner au magasin en chercher une meilleure.",
 30: "Le sentier court le long de la pointe, la tempête empirant d'heure en heure. En contrebas, une chaumière basse où la mer entre. Devant, le vent manque de vous jeter à terre. Et il y a un poteau repère, à moitié arraché par la bourrasque.",
 31: "Une petite barque est submergée sur la cale, un vieil homme pris dans les cordages, la mer tirant sur lui — il ne peut se dégager. Vous arrêter, c'est perdre du temps ; ne pas le faire, c'est risquer que la prochaine grosse vague l'emporte.",
 33: "Vous poussez à travers le pire de la tempête, chaque pas un combat, la pluie cinglant votre visage. Devant, des choix : le naufrageur est peut-être proche, ou l'étrange lumière sur l'eau — ou vous pouvez simplement foncer vers le phare.",
 34: "Vous libérez le vieil homme des cordages, et la barque le lâche. Ses yeux s'emplissent ; il vous presse un ciré sec. « Prends-le, dit-il, pour ta peine. » Peu de chose — mais donné de bon cœur, et vous le prenez et repartez.",
 35: "Vous ne pouvez pas rester — mais vous ne pouvez pas non plus les laisser. Alors vous promettez d'envoyer de l'aide. « Tenez bon ! criez-vous. Restez en hauteur, restez ensemble — je ne vous oublierai pas. » Et vous le pensez — puis vous tournez les talons et partez.",
 36: "La côte allume un feu de signal sur la pointe — un fût en flammes, jetant lumière et chaleur dans la tempête. Les gens s'y pressent, les vieux et les faibles au plus près. Ce n'est pas le faisceau. Mais c'est une lumière, et elle appartient à tous maintenant.",
 37: "Chaumière après chaumière, la côte effrayée devient une côte qui travaille. Chacun a sa tâche — l'un entretient le feu, l'un love la corde, l'un guette la mer. La peur devient action, et l'action vaut mieux que l'attente, à tous les coups.",
 38: "La tempête ronge votre volonté. Une petite voix dit : arrête, rentre, repose-toi — personne ne t'en voudrait, et ce serait si facile. Mais vous pensez à ce bateau sur les rochers, et vous repoussez la voix. Pas encore. Pas tant que la lumière est éteinte.",
 39: "Vous atteignez le poteau repère, mais la bourrasque en a arraché la moitié ; à peine lisible. Un bras indique le sentier, l'autre vers l'eau. Quel chemin ? Il faudra deviner, et bien deviner.",
 42: "Vous lui tournez le dos et le laissez au ressac et à son commerce glacé. Ça fait du bien de partir. Il vous hèle, mais vous ne vous retournez pas. Son genre trouve toujours quelqu'un — mais pas vous, et pas cette nuit.",
 43: "Vous prenez son huile, sa pièce ; vos mains se referment dessus, et quelque chose en vous sait déjà. Son sourire s'élargit. « Sage », dit-il. Mais cela n'a rien de sage. Cela ressemble à une porte qui se ferme, quelque part dans le noir.",
 44: "Vous demandez franchement : que veut-il vraiment ? Pourquoi la lumière devrait-elle rester éteinte ? Il sourit et regarde la mer. « Les bateaux viennent sur les rochers, dit-il. La mer est généreuse, ensuite. » Il n'en dira pas plus — et voilà, justement, votre réponse.",
 45: "Vous montez son huile à la lampe. Mais en la versant, la flamme étouffe et crache — l'huile est souillée d'eau de mer, et ne nourrit pas la mèche. Le faisceau vacille, bas et brun. Il vous a donné la ruine, pas de l'aide.",
 46: "Vous ouvrez le bidon et l'odeur vous saisit — salée, fluette, coupée d'eau. Cette huile ne nourrira jamais de flamme ; vous l'avez payée, et elle ne vaut rien. Le doute dans votre ventre avait raison depuis le début.",
 47: "Vous le cherchez, mais la lanterne du naufrageur est déjà partie, vers la crique. Il ne vous aidait pas — il attendait le noir, le naufrage, le cadeau froid de la mer. Vous restez là, dupé, son huile sans valeur dans les mains.",
 48: "Le naufrageur est parti, la crique vide — rien que la tempête, le noir, et ce que vous lui avez donné pour rien. Vous avez appris une dure leçon, payée bien trop cher. Vous continuez avec le peu qui reste.",
 49: "Les gens effrayés lui fourrent leurs pièces — des mains pleines d'argent, des voix suppliant pour de l'huile, pour une issue. Et il prend, lentement, avec ce sourire, choisissant qui aider selon qui peut payer. Vous voyez tout le tour de passe-passe, clair et laid.",
 50: "Loin sur la corniche, la crique paraît enfin plus proche — ou pas ? Vous n'en êtes plus sûr ; le noir trompe, le vent trompe, vos yeux fatigués trompent. Vous êtes trempé et tremblant. Mais vous avancez à petits pas.",
 51: "La corniche, le vent, le vide noir en dessous — et votre pied glisse sur la roche mouillée. C'est le moment : basculer dans le noir, ou vous rejeter en arrière maintenant, tant que vous le pouvez.",
 52: "Vous atteignez enfin la crique, trempé et tremblant, les mains écorchées — mais en bas. D'une façon ou d'une autre, vous avez réussi. Maintenant il faut décider : continuer, épuisé comme vous êtes, ou affronter ce que vous avez perdu en chemin.",
 53: "Vous vous rejetez du bord tant que vous le pouvez — le choix dur et juste. Vous rampez le dernier bout à quatre pattes, et atteignez le sentier, secoué et lent. La nuit se consume. Mais vous êtes vivant, et encore capable d'aider.",
 54: "Vous tentez de barrer la porte contre l'eau — un coffre traîné, des sacs empilés, ce que vous pouvez. Cela retient un peu le pire de la mer. Mais pas de lampe à leur laisser, et une pièce noire qui s'inonde est un dur endroit où attendre. Il faut choisir.",
 55: "Vous donnez votre propre manteau et votre lampe, et la famille se blottit autour de la petite flamme, le soulagement passant sur leurs visages. L'enfant cesse enfin de pleurer. « Merci », répète la mère. Vous avez moins pour vous protéger désormais — mais vous avez bien agi.",
 56: "Sans votre manteau, le froid et l'humidité vous trouvent vite — dents qui claquent, doigts qui se raidissent. Vous l'avez donné pour aider, et vous recommenceriez ; mais la tempête s'en moque. Elle cogne, c'est tout. Il faut garder la tête froide, et continuer.",
 57: "Un inconnu vous fait entrer sous un porche. « Juste une minute, dit-il. Hors de la pluie — reprends ton souffle. » C'est chaud et sec, et votre corps vous supplie de rester. Mais une minute peut glisser vers une heure — et la lumière est toujours éteinte.",
 58: "Vous avancez dans la tempête, trempé jusqu'aux os, le vent luttant à chaque pas, la pluie vous aveuglant. Chaque pas est un petit combat — mais vous les enchaînez, l'un après l'autre. Lent, c'est bien cette nuit. S'arrêter, c'est ce qui tue.",
 60: "Quelqu'un montre la pointe : une silhouette est partie par là, dans la tempête, vers la pointe, seule. De ce côté il n'y a que roche, vent et le vide noir. Si personne ne la suit, elle ne reviendra pas.",
 61: "Vous la trouvez accrochée dans les rochers, à moitié noyée et perdue, le vent arrachant son manteau. Elle ne semble pas reconnaître votre visage. Vous lui saisissez fermement le bras. « Viens avec moi ! » criez-vous par-dessus la tempête. « Par ici. Doucement. »",
 62: "Vous ne pouvez pas tout faire à la fois, et la lumière a le plus besoin de vous. Alors vous faites prévenir quelqu'un d'autre pour elle, et vous continuez. Cela vous pèse — mais il faut choisir, et vous choisissez la lumière.",
 63: "Vous les ramenez sains et saufs aux chaumières, où leur famille crie de soulagement. On vous enveloppe d'un manteau sec et on vous fait une place près du feu. « Merci », répètent-ils — car une gentillesse ne reste jamais sur place ; elle se propage.",
 64: "Vous regardez la côte — toute noire, toute grondante. De grandes vagues se brisent, blanches, sur les rochers, et nulle lumière ne paraît, sinon le bateau lointain en peine. Toute la côte semble retenir son souffle, attendant que la tempête casse. Et vous aussi, vous le réalisez.",
 65: "Le vent monte à son pire et manque de vous jeter à terre. Vous vous accroupissez et vous tenez bon, l'air plein d'embruns et d'écume arrachée. Dur de voir, dur de respirer. C'est l'heure à survivre — passez-la, et ce bateau a encore une chance.",
 67: "Tam vous presse la dernière lampe sèche. « Pour la montée, dit-il. Vas-y — je reste à la radio. » Son visage est gris d'inquiétude. C'est l'aide qu'il peut donner, et il la donne. Vous la prenez, et le remerciez.",
 68: "Au magasin d'huile, on se rue sur les bidons — voix qui montent, mains qui saisissent, la peur qui prend et se répand vite. Une bousculade de plus et c'est la bagarre. Vous pouvez tenter de les calmer et partager équitablement, ou forcer votre propre chemin jusqu'à l'huile.",
 70: "Loin au-delà de la pointe, une seconde lumière monte et descend. Elle est là où aucun bateau ne devrait être cette nuit, paraissant et disparaissant dans la houle. Personne ne sait l'expliquer. Quelque chose est là-bas, ou quelqu'un.",
 71: "Vous descendez à la crique et appelez dans le noir. Nulle réponse que la mer — puis vous le voyez : la forme d'un bateau, bas sur les rochers, à demi avalé par les vagues. Quelqu'un a gréé cette lumière. Quelqu'un est là-bas.",
 72: "Vous entrez dans l'eau sur les rochers. Là, dans la barque submergée, un vieux pêcheur — Ash — emmêlé dans les cordages et tenant à peine. La mer tire sur lui à chaque vague. Pas de temps à perdre.",
 73: "Vous rappelez dans le noir, et un instant, rien. Puis une voix répond, faible et déchirée par le vent : « Ici ! Par ici ! » Quelqu'un est sur les rochers, et a besoin d'aide. Vous ne pouvez pas vous en aller maintenant.",
 74: "Vous dégagez Ash des cordages, le hissez sur les rochers et l'enveloppez de votre manteau. Lentement il revient, vous agrippant le bras. « La lumière, souffle-t-il. Garde la lumière. Il y en a peut-être d'autres là-bas. »",
 75: "Vous vous retournez pour courir chercher de l'aide — puis vous vous arrêtez. Il n'y a pas d'aide ici ; pas avant l'aube. Pas de canot, pas d'équipe, personne qui vienne. C'est vous ou personne, et Ash le sait aussi. Ses yeux vous suivent sur les rochers.",
 76: "Ash lève les yeux, plus clairs à présent. « La gardienne, là-haut dans le phare — Nan ? dit-il. C'est ma mère. On ne s'est pas parlé depuis des années. Pas depuis — enfin. C'est une longue histoire, et une nuit froide pour la dire. »",
 77: "Vous décidez de les mettre face à face avant la fin de la nuit — Ash et la vieille Nan, après toutes ces années. C'est peu de chose, à côté de la lumière et de la tempête. Mais ce n'est pas rien ; certaines portes restent closes des années parce que nul n'ose frapper. Vous oserez.",
 78: "La barque est éventrée, à demi submergée, la mer y travaillant à chaque vague — elle ne tiendra pas longtemps. Et pourtant quelqu'un y a allumé une lumière, quelqu'un a grimpé sur ces rochers dans le noir. Quelqu'un est là.",
 79: "Vous approchez dans l'eau et voyez le nom sur la proue, et vous le reconnaissez. C'est la barque de Nan — celle perdue il y a des années, disait-on. Puis, sous la coque brisée, un bruit faible : une toux. Quelqu'un est vivant là-dedans.",
 80: "Le naufrageur revient une dernière fois, sa lanterne oscillant. « Tu te bats encore ? dit-il. Laisse-la s'éteindre. Dernière chance d'être du côté des gagnants, l'ami. » Le même sourire, le même mensonge. Il sait que vous êtes épuisé, et il compte là-dessus. À vous de choisir, pour de bon.",
 90: "Vous revoilà au phare, trempé, le dernier du pire de la tempête cognant la vitre. En bas, Nan gît, grise, au pied de l'escalier ; en haut, la lampe brûle bas. C'est l'heure qui compte ; quoi que vous fassiez, faites-le bien. Ce bateau est proche des rochers.",
 91: "Vous atteignez la lampe : la flamme basse, la grande lentille immobile. Au-delà de la vitre, les feux du bateau sont tout près des rochers — bien trop près. Il faut rendre le faisceau plein et tournant, et maintenant. Tout ce que vous avez fait cette nuit se joue ici.",
 92: "Puis l'aide atteint le phare derrière vous — des mains, de l'huile, des têtes fermes, des gens qui connaissent la lumière. Vous n'êtes plus seul avec ça ; d'autres sont là pour partager le poids. C'est comme poser un lourd fardeau, et vous respirez enfin.",
 93: "Maintenant, tenir le faisceau — et ce que vous pouvez faire dépend de ce que vous avez porté. Avec de la vraie huile, vous avez de quoi faire ; sans elle, il faut coaxer chaque dernière lueur de la flamme. Dans tous les cas, vous commencez.",
 94: "Vous descendez voir Nan, et ses yeux s'entrouvrent — de la peur d'abord, puis, en vous voyant, un peu moins de peur. « Tu l'as gardée allumée », souffle-t-elle. « C'est fait, répondez-vous. Repose-toi maintenant. J'ai la lumière. »",
 95: "L'huile fait tout. Vous taillez la mèche, remontez la grande lentille comme une horloge, et le faisceau balaie, plein et doré, l'eau noire. Une lumière dans tout ce noir. Voilà à quoi sert le phare ; vous le saviez, et vous le voyez maintenant.",
 96: "Vous n'avez pas de vraie huile à verser, alors vous coaxez la flamme qui reste. Vous la protégez du courant d'air de votre corps, la nourrissant de bribes, de souffle, de volonté. Elle brûle, basse et mince. Ce sera peut-être assez. Peut-être pas. Mais vous ne la laisserez pas s'éteindre.",
 97: "La flamme est basse et faiblit, et vous craignez que la protéger ne suffise pas. Vous avez fait tout ce que vous pouviez — mais cela pourrait ne pas tenir. Il faut plus : de l'huile, des mains, ou les deux, et vite.",
 98: "Vous levez les yeux et la voyez. Loin en mer, une lumière flambe et retombe, là où aucun bateau ne devrait être, paraissant et disparaissant. Elle tire votre œil, et quelque chose en vous. Quelqu'un est là-bas.",
 99: "La lumière sur l'eau reparaît — là où tous jurent qu'aucun bateau ne serait. Mais une lumière veut dire une main pour l'allumer, et une main une personne, et une personne là-bas cette nuit est en vrai danger. Vous le sentez.",
 100: "Vient maintenant la longue veille : vous gardez le faisceau tournant, Nan au chaud et respirant, et vous guettez l'eau noire, heure après heure. Ce n'est pas palpitant — juste un travail régulier, dur, soigneux. Mais c'est le travail régulier qui sauve les gens, alors vous le faites, sans cesser.",
 101: "Et puis, enfin, ça bascule. Le vent baisse d'un ton, la pluie se calme, le ciel grisonne au bord de la mer. Et une lampe balaie, contournant la pointe — le canot de sauvetage, sorti enfin. Vous avez tenu la lumière jusqu'à l'aube. Vous avez réussi.",
 102: "C'est l'heure la pire, juste avant la rupture. La tempête n'a pas faibli ; vos bras souffrent de la lentille ; vos yeux brûlent. Mais vous sentez la nuit commencer à tourner. Tenez. Tenez encore un peu. La fin est proche.",
 103: "Le long de la pointe, vous les voyez — des lampes, des silhouettes sombres, des feux de signal brûlant bas contre la pluie. D'autres gens, dehors eux aussi. La côte a passé cette nuit, elle aussi, et vous n'étiez pas seul à veiller. Cela vous réchauffe, d'une certaine façon.",
 104: "Enfin, le canot — sa lampe et un panache d'embruns contournant la pointe, droit dans la mer. De la vraie aide, à vraie allure. Vous agrippez la rambarde et regardez, les jambes tremblantes. C'est presque fini. Presque. Vous vous autorisez à y croire.",
 105: "L'aube se lève sur la mer déchaînée, la lumière virant au gris, puis au pâle et au net, la tempête s'épuisant vague après vague. La grande houle court encore, mais le pire est passé. La côte, si cruelle toute la nuit, est presque douce à présent. Vous regardez, et vous respirez.",
 106: "Puis cela vient — la première mouette, au-dessus de l'eau grise, portée par le vent, comme s'il n'y avait jamais eu de tempête. Après la nuit que vous avez eue, cela paraît absurde, et beau. Vous la regardez partir. Vous avez réussi. Vous avez tous réussi.",
 107: "Du phare, vous guettez l'eau, où loin une lampe monte et descend dans la houle et grandit peu à peu. Quelque chose vient enfin, trop loin encore pour qu'on voie. Mais une lampe là-bas veut dire une main — et une main, à cet instant, veut dire de l'espoir. Vous gardez les yeux dessus, et attendez.",
 110: "La première lumière arrive enfin, et la nuit s'additionne en ce qu'elle est. Tout ce que vous avez fait là-haut dans le phare, dans la tempête, vous revient — de quoi être fier, et de quoi l'être moins. C'est ici que tout devient clair.",
 111: "La nuit s'additionne — pas toujours par un grand acte, mais par beaucoup de petits. Ce que vous avez gardé, ce que vous avez refusé, pour qui vous avez grimpé. Tout compte au bout du compte ; tout a fait la nuit telle qu'elle fut. Alors, à quoi la nuit a-t-elle abouti ?",
 112: "Il y a plus à peser ; la nuit a tenu d'autres choses. Un inconnu aidé. Un manteau et une lampe donnés d'une main ouverte. De petits choix faits dans la tempête, quand passer son chemin aurait été facile. Ils ont leur propre poids. À quoi ont-ils abouti ?",
 113: "Et que vous laisse la nuit ? Peut-être pas une victoire nette. Peut-être juste le fait d'avoir grimpé, d'avoir essayé. Quand c'était noir, déchaîné et facile de barrer la porte, vous ne l'avez pas fait. Cela compte pour quelque chose. Cela a toujours compté.",
 114: "Mais toutes les nuits ne finissent pas bien. Certains choix coûtent plus qu'on ne croyait ; certaines portes, une fois ouvertes, ne se referment pas. C'est la dure fin de la nuit, là où le pire revient. Ce n'est pas facile à regarder — mais c'est vrai. Alors regardez.",
}


def main():
    data = json.load(open(OUT, encoding="utf-8"))
    added = 0
    for nid, text in FR.items():
        k = str(nid)
        if k not in data:
            data[k] = text; added += 1
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"{SLUG}/fr.json: {len(data)} passages total (+{added} added)")


if __name__ == "__main__":
    main()
