#!/usr/bin/env python3
"""Build the coverage-tier dictionary: the book's high-frequency everyday words, so a
learner can tap ANY common word and get a translation (not only the curated hard words).

Emits one compact file per language at content/dict/<lang>.json → { lemma: translation }.
The reader lazy-loads the file for the selected language. Keyed by base form; the reader's
suffix rules catch inflections. This is the "coverage" tier — quick, everyday translations,
distinct from the hand-reviewed curated lexicon; it still flows through the review pipeline.
"""
import json, os

L = ["fr", "es", "pt", "it", "de", "ru", "ar", "zh"]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "dict")
os.makedirs(OUT, exist_ok=True)

# lemma : [fr, es, pt, it, de, ru, ar, zh]  — story-appropriate common sense
M = {
 "say":["dire","decir","dizer","dire","sagen","сказать","يقول","说"],
 "look":["regarder","mirar","olhar","guardare","schauen","смотреть","ينظر","看"],
 "letter":["la lettre","la carta","a carta","la lettera","der Brief","письмо","رسالة","信"],
 "street":["la rue","la calle","a rua","la strada","die Straße","улица","شارع","街道"],
 "door":["la porte","la puerta","a porta","la porta","die Tür","дверь","باب","门"],
 "night":["la nuit","la noche","a noite","la notte","die Nacht","ночь","ليل","夜晚"],
 "know":["savoir","saber","saber","sapere","wissen","знать","يعرف","知道"],
 "number":["le numéro","el número","o número","il numero","die Nummer","номер","رقم","号码"],
 "man":["l'homme","el hombre","o homem","l'uomo","der Mann","мужчина","رجل","男人"],
 "way":["le chemin","el camino","o caminho","la via","der Weg","путь","طريق","路"],
 "river":["la rivière","el río","o rio","il fiume","der Fluss","река","نهر","河"],
 "name":["le nom","el nombre","o nome","il nome","der Name","имя","اسم","名字"],
 "window":["la fenêtre","la ventana","a janela","la finestra","das Fenster","окно","نافذة","窗户"],
 "woman":["la femme","la mujer","a mulher","la donna","die Frau","женщина","امرأة","女人"],
 "hand":["la main","la mano","a mão","la mano","die Hand","рука","يد","手"],
 "someone":["quelqu'un","alguien","alguém","qualcuno","jemand","кто-то","شخص ما","某人"],
 "morning":["le matin","la mañana","a manhã","la mattina","der Morgen","утро","صباح","早晨"],
 "work":["le travail","el trabajo","o trabalho","il lavoro","die Arbeit","работа","عمل","工作"],
 "light":["la lumière","la luz","a luz","la luce","das Licht","свет","ضوء","光"],
 "sit":["s'asseoir","sentarse","sentar-se","sedersi","sitzen","сидеть","يجلس","坐"],
 "wait":["attendre","esperar","esperar","aspettare","warten","ждать","ينتظر","等待"],
 "read":["lire","leer","ler","leggere","lesen","читать","يقرأ","读"],
 "year":["l'année","el año","o ano","l'anno","das Jahr","год","سنة","年"],
 "money":["l'argent","el dinero","o dinheiro","il denaro","das Geld","деньги","مال","钱"],
 "desk":["le bureau","el escritorio","a secretária","la scrivania","der Schreibtisch","стол","مكتب","书桌"],
 "walk":["marcher","caminar","caminhar","camminare","gehen","идти","يمشي","走"],
 "cold":["froid","frío","frio","freddo","kalt","холодный","بارد","冷"],
 "city":["la ville","la ciudad","a cidade","la città","die Stadt","город","مدينة","城市"],
 "ask":["demander","preguntar","perguntar","chiedere","fragen","спрашивать","يسأل","问"],
 "open":["ouvrir","abrir","abrir","aprire","öffnen","открывать","يفتح","打开"],
 "glass":["le verre","el vidrio","o vidro","il vetro","das Glas","стекло","زجاج","玻璃"],
 "bus":["le bus","el autobús","o autocarro","l'autobus","der Bus","автобус","حافلة","公交车"],
 "good":["bon","bueno","bom","buono","gut","хороший","جيد","好"],
 "something":["quelque chose","algo","algo","qualcosa","etwas","что-то","شيء ما","某物"],
 "time":["le temps","el tiempo","o tempo","il tempo","die Zeit","время","وقت","时间"],
 "nothing":["rien","nada","nada","niente","nichts","ничего","لا شيء","没什么"],
 "empty":["vide","vacío","vazio","vuoto","leer","пустой","فارغ","空的"],
 "stand":["se tenir debout","estar de pie","ficar de pé","stare in piedi","stehen","стоять","يقف","站"],
 "small":["petit","pequeño","pequeno","piccolo","klein","маленький","صغير","小的"],
 "see":["voir","ver","ver","vedere","sehen","видеть","يرى","看见"],
 "address":["l'adresse","la dirección","o endereço","l'indirizzo","die Adresse","адрес","عنوان","地址"],
 "stop":["arrêter","parar","parar","fermare","anhalten","останавливаться","يتوقف","停"],
 "coffee":["le café","el café","o café","il caffè","der Kaffee","кофе","قهوة","咖啡"],
 "people":["les gens","la gente","as pessoas","la gente","die Leute","люди","الناس","人们"],
 "water":["l'eau","el agua","a água","l'acqua","das Wasser","вода","ماء","水"],
 "turn":["tourner","girar","virar","girare","drehen","поворачивать","يدور","转"],
 "outside":["dehors","fuera","fora","fuori","draußen","снаружи","في الخارج","外面"],
 "move":["bouger","mover","mover","muovere","bewegen","двигать","يتحرك","移动"],
 "come":["venir","venir","vir","venire","kommen","приходить","يأتي","来"],
 "tell":["dire","decir","dizer","dire","erzählen","рассказывать","يخبر","告诉"],
 "hour":["l'heure","la hora","a hora","l'ora","die Stunde","час","ساعة","小时"],
 "warm":["chaud","cálido","quente","caldo","warm","тёплый","دافئ","温暖的"],
 "watch":["observer","observar","observar","osservare","beobachten","наблюдать","يراقب","观察"],
 "feel":["sentir","sentir","sentir","sentire","fühlen","чувствовать","يشعر","感觉"],
 "dark":["sombre","oscuro","escuro","buio","dunkel","тёмный","مظلم","黑暗的"],
 "old":["vieux","viejo","velho","vecchio","alt","старый","قديم","旧的"],
 "gone":["parti","ido","ido","andato","weg","ушёл","ذهب","走了"],
 "new":["nouveau","nuevo","novo","nuovo","neu","новый","جديد","新的"],
 "today":["aujourd'hui","hoy","hoje","oggi","heute","сегодня","اليوم","今天"],
 "grey":["gris","gris","cinzento","grigio","grau","серый","رمادي","灰色的"],
 "inside":["à l'intérieur","dentro","dentro","dentro","drinnen","внутри","في الداخل","里面"],
 "clean":["propre","limpio","limpo","pulito","sauber","чистый","نظيف","干净的"],
 "kind":["gentil","amable","gentil","gentile","freundlich","добрый","لطيف","善良的"],
 "station":["la gare","la estación","a estação","la stazione","der Bahnhof","вокзал","محطة","车站"],
 "paper":["le papier","el papel","o papel","la carta","das Papier","бумага","ورق","纸"],
 "nobody":["personne","nadie","ninguém","nessuno","niemand","никто","لا أحد","没有人"],
 "want":["vouloir","querer","querer","volere","wollen","хотеть","يريد","想要"],
 "find":["trouver","encontrar","encontrar","trovare","finden","находить","يجد","找到"],
 "job":["l'emploi","el empleo","o emprego","il lavoro","der Job","работа","وظيفة","工作"],
 "word":["le mot","la palabra","a palavra","la parola","das Wort","слово","كلمة","词"],
 "take":["prendre","tomar","pegar","prendere","nehmen","брать","يأخذ","拿"],
 "tired":["fatigué","cansado","cansado","stanco","müde","усталый","متعب","累的"],
 "building":["le bâtiment","el edificio","o edifício","l'edificio","das Gebäude","здание","مبنى","建筑"],
 "somewhere":["quelque part","en algún lugar","algures","da qualche parte","irgendwo","где-то","في مكان ما","某处"],
 "yellow":["jaune","amarillo","amarelo","giallo","gelb","жёлтый","أصفر","黄色的"],
 "moment":["le moment","el momento","o momento","il momento","der Moment","момент","لحظة","时刻"],
 "driver":["le chauffeur","el conductor","o motorista","l'autista","der Fahrer","водитель","سائق","司机"],
 "close":["fermer","cerrar","fechar","chiudere","schließen","закрывать","يغلق","关闭"],
 "corner":["le coin","la esquina","a esquina","l'angolo","die Ecke","угол","زاوية","角落"],
 "train":["le train","el tren","o comboio","il treno","der Zug","поезд","قطار","火车"],
 "arrive":["arriver","llegar","chegar","arrivare","ankommen","прибывать","يصل","到达"],
 "start":["commencer","empezar","começar","cominciare","anfangen","начинать","يبدأ","开始"],
 "office":["le bureau","la oficina","o escritório","l'ufficio","das Büro","офис","مكتب","办公室"],
 "early":["tôt","temprano","cedo","presto","früh","рано","مبكرا","早"],
 "sign":["le panneau","el letrero","o letreiro","l'insegna","das Schild","вывеска","لافتة","招牌"],
 "wrong":["faux","incorrecto","errado","sbagliato","falsch","неправильный","خطأ","错误的"],
 "enough":["assez","suficiente","suficiente","abbastanza","genug","достаточно","كافٍ","足够"],
 "call":["appeler","llamar","chamar","chiamare","anrufen","звонить","يتصل","打电话"],
 "cost":["coûter","costar","custar","costare","kosten","стоить","يكلف","花费"],
 "suit":["le costume","el traje","o fato","l'abito","der Anzug","костюм","بدلة","西装"],
 "cup":["la tasse","la taza","a chávena","la tazza","die Tasse","чашка","كوب","杯子"],
 "twice":["deux fois","dos veces","duas vezes","due volte","zweimal","дважды","مرتين","两次"],
 "hold":["tenir","sostener","segurar","tenere","halten","держать","يمسك","握住"],
 "somebody":["quelqu'un","alguien","alguém","qualcuno","jemand","кто-то","شخص ما","某人"],
 "key":["la clé","la llave","a chave","la chiave","der Schlüssel","ключ","مفتاح","钥匙"],
 "quietly":["doucement","en voz baja","baixinho","silenziosamente","leise","тихо","بهدوء","安静地"],
 "bag":["le sac","la bolsa","o saco","la borsa","die Tasche","сумка","حقيبة","包"],
 "mean":["vouloir dire","significar","significar","significare","bedeuten","значить","يعني","意思是"],
 "minute":["la minute","el minuto","o minuto","il minuto","die Minute","минута","دقيقة","分钟"],
 "thing":["la chose","la cosa","a coisa","la cosa","das Ding","вещь","شيء","东西"],
 "everyone":["tout le monde","todos","todos","tutti","jeder","все","الجميع","每个人"],
 "hundred":["cent","cien","cem","cento","hundert","сто","مئة","一百"],
 "map":["la carte","el mapa","o mapa","la mappa","die Karte","карта","خريطة","地图"],
 "taxi":["le taxi","el taxi","o táxi","il taxi","das Taxi","такси","سيارة أجرة","出租车"],
 "everything":["tout","todo","tudo","tutto","alles","всё","كل شيء","一切"],
 "chair":["la chaise","la silla","a cadeira","la sedia","der Stuhl","стул","كرسي","椅子"],
 "place":["l'endroit","el lugar","o lugar","il posto","der Ort","место","مكان","地方"],
 "think":["penser","pensar","pensar","pensare","denken","думать","يفكر","想"],
 "road":["la route","la carretera","a estrada","la strada","die Straße","дорога","طريق","路"],
 "shut":["fermer","cerrar","fechar","chiudere","schließen","закрывать","يغلق","关"],
 "home":["la maison","la casa","casa","casa","das Zuhause","дом","بيت","家"],
 "write":["écrire","escribir","escrever","scrivere","schreiben","писать","يكتب","写"],
 "person":["la personne","la persona","a pessoa","la persona","die Person","человек","شخص","人"],
 "wet":["mouillé","mojado","molhado","bagnato","nass","мокрый","مبلل","湿的"],
 "whole":["entier","entero","inteiro","intero","ganz","целый","كامل","整个的"],
 "eye":["l'œil","el ojo","o olho","l'occhio","das Auge","глаз","عين","眼睛"],
 "reach":["atteindre","alcanzar","alcançar","raggiungere","erreichen","достигать","يصل إلى","到达"],
 "sorry":["désolé","lo siento","desculpe","scusa","Entschuldigung","извините","آسف","对不起"],
 "bridge":["le pont","el puente","a ponte","il ponte","die Brücke","мост","جسر","桥"],
 "front":["le devant","el frente","a frente","il davanti","die Vorderseite","перёд","أمام","前面"],
 "head":["la tête","la cabeza","a cabeça","la testa","der Kopf","голова","رأس","头"],
 "side":["le côté","el lado","o lado","il lato","die Seite","сторона","جانب","边"],
 "pay":["payer","pagar","pagar","pagare","bezahlen","платить","يدفع","付款"],
 "face":["le visage","la cara","o rosto","il viso","das Gesicht","лицо","وجه","脸"],
 "hurry":["se dépêcher","apurarse","apressar-se","affrettarsi","sich beeilen","спешить","يسرع","匆忙"],
 "phone":["le téléphone","el teléfono","o telefone","il telefono","das Telefon","телефон","هاتف","电话"],
 "room":["la chambre","la habitación","o quarto","la stanza","das Zimmer","комната","غرفة","房间"],
 "decide":["décider","decidir","decidir","decidere","entscheiden","решать","يقرر","决定"],
 "stay":["rester","quedarse","ficar","restare","bleiben","оставаться","يبقى","停留"],
 "alone":["seul","solo","sozinho","solo","allein","один","وحيد","独自"],
 "last":["dernier","último","último","ultimo","letzte","последний","أخير","最后的"],
 "first":["premier","primero","primeiro","primo","erste","первый","أول","第一"],
 "long":["long","largo","longo","lungo","lang","длинный","طويل","长的"],
 "behind":["derrière","detrás","atrás","dietro","hinter","позади","خلف","后面"],
 "leave":["partir","salir","sair","partire","verlassen","уходить","يغادر","离开"],
 "give":["donner","dar","dar","dare","geben","давать","يعطي","给"],
}

for i, code in enumerate(L):
    data = {lemma: tr[i] for lemma, tr in M.items()}
    json.dump(data, open(os.path.join(OUT, f"{code}.json"), "w", encoding="utf-8"),
              ensure_ascii=False, separators=(",", ":"), sort_keys=True)
print(f"Coverage dict: {len(M)} words × {len(L)} languages → content/dict/<lang>.json")
