#!/usr/bin/env python3
"""Phase 4: build 'The Cool of Evening's embedded lexicon.

Words shared with books 1 and 3 reuse their reviewed-draft glosses (kept only where the sense
matches here); new subject words (heat, sun, the desert, water and the body, the road and the
crisis) get fresh draft glosses in English + 8 languages. Machine-drafted; native review
(phase 5) finalises them.

Writes the merged lexicon into content/episode-04.json's `lexicon.entries`.
Run: python3 scripts/build_ep04_lexicon.py
"""
import json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
EP1 = os.path.join(ROOT, "content", "episode-01.json")
EP3 = os.path.join(ROOT, "content", "episode-03.json")
EP4 = os.path.join(ROOT, "content", "episode-04.json")

# General words already glossed for book 1 or book 3, reused here for a consistent learner gloss.
REUSE = [
    "child", "worst", "dust", "refuse", "breath", "steady", "scared", "cash", "frightened",
    "weigh", "breathe", "breathing", "heavy", "somehow", "torn", "signpost", "doubt", "trick",
    "relief", "shallow", "scrap", "feet", "thread", "manage", "gather", "fetch", "cruel",
    "anyway", "aisle", "chest", "nod", "path", "proud", "steam", "truth", "lean", "luggage",
    "spare", "collar", "settle", "brave", "advice", "rally", "blame", "robbery", "realise",
    "crawl", "pale", "kneel", "glance", "wave", "decent", "vehicle", "clever", "faded",
]

def e(pos, en, fr, es, pt, it, de, ru, ar, zh):
    return {"pos": pos, "en": en, "fr": fr, "es": es, "pt": pt, "it": it,
            "de": de, "ru": ru, "ar": ar, "zh": zh}

NEW = {
 # --- heat, sun, the desert ---
 "heat": e("noun", "the quality of being very hot; hot weather",
   "la chaleur", "el calor", "o calor", "il caldo", "die Hitze", "жара", "الحَرّ", "炎热"),
 "sun": e("noun", "the star that gives the earth light and heat",
   "le soleil", "el sol", "o sol", "il sole", "die Sonne", "солнце", "الشمس", "太阳"),
 "shade": e("noun", "a cool, darker place out of the sun",
   "l'ombre", "la sombra", "a sombra", "l'ombra", "der Schatten", "тень", "ظِلّ", "阴凉处"),
 "shadow": e("noun", "the dark shape made when something blocks the light",
   "l'ombre", "la sombra", "a sombra", "l'ombra", "der Schatten", "тень", "ظِلّ", "影子"),
 "glare": e("noun", "very strong, harsh light that hurts the eyes",
   "l'éblouissement", "el resplandor", "o clarão", "il bagliore", "das grelle Licht",
   "слепящий свет", "وهج", "刺眼的强光"),
 "shimmer": e("noun", "a wavering, trembling look that heat gives the air",
   "le miroitement", "el rielar", "a cintilação", "il tremolio", "das Flimmern",
   "марево", "تلألؤ", "热浪的闪动"),
 "haze": e("noun", "a thin mist of heat or dust that blurs what is far away",
   "la brume", "la calina", "a bruma", "la foschia", "der Dunst", "дымка", "ضبابٌ خفيف", "薄雾"),
 "hot": e("adjective", "having a high temperature",
   "chaud", "caliente", "quente", "caldo", "heiß", "горячий", "حارّ", "热的"),
 "dry": e("adjective", "having no water or moisture",
   "sec", "seco", "seco", "secco", "trocken", "сухой", "جافّ", "干的"),
 "cool": e("adjective", "pleasantly cold; not hot",
   "frais", "fresco", "fresco", "fresco", "kühl", "прохладный", "بارد قليلاً", "凉爽的"),
 "warm": e("adjective", "a little hot, in a pleasant way",
   "chaud", "cálido", "morno", "caldo", "warm", "тёплый", "دافئ", "温暖的"),
 "burn": e("verb", "to hurt or damage with heat or fire",
   "brûler", "quemar", "queimar", "bruciare", "brennen", "жечь", "يحرق", "灼烧"),
 "sweat": e("noun", "the water that comes from your skin when you are hot",
   "la sueur", "el sudor", "o suor", "il sudore", "der Schweiß", "пот", "عَرَق", "汗"),
 "noon": e("noun", "the middle of the day, twelve o'clock",
   "midi", "el mediodía", "o meio-dia", "mezzogiorno", "der Mittag", "полдень", "الظهيرة", "正午"),
 "evening": e("noun", "the time at the end of the day, before night",
   "le soir", "la tarde", "o entardecer", "la sera", "der Abend", "вечер", "المساء", "傍晚"),
 "hour": e("noun", "a period of sixty minutes",
   "l'heure", "la hora", "a hora", "l'ora", "die Stunde", "час", "ساعة", "小时"),
 "desert": e("noun", "a dry, sandy land with very little water",
   "le désert", "el desierto", "o deserto", "il deserto", "die Wüste", "пустыня", "صحراء", "沙漠"),
 "sand": e("noun", "the fine, loose grains that cover a desert or beach",
   "le sable", "la arena", "a areia", "la sabbia", "der Sand", "песок", "رمل", "沙子"),
 "ridge": e("noun", "a long, high line of rock or hills",
   "la crête", "la cresta", "a cordilheira", "il crinale", "der Bergrücken",
   "гребень", "حَيد", "山脊"),
 "flats": e("noun", "a wide area of flat, open ground",
   "la plaine", "el llano", "a planície", "la piana", "die Ebene", "равнина", "سهل منبسط", "平地"),
 "plain": e("noun", "a large area of flat land",
   "la plaine", "la llanura", "a planície", "la pianura", "die Ebene", "равнина", "سهل", "平原"),
 "horizon": e("noun", "the line far away where the land meets the sky",
   "l'horizon", "el horizonte", "o horizonte", "l'orizzonte", "der Horizont",
   "горизонт", "الأفق", "地平线"),
 "gully": e("noun", "a narrow channel cut in the ground by water",
   "le ravin", "el barranco", "a ravina", "il fosso", "die Rinne", "овраг", "أخدود", "沟壑"),
 "ground": e("noun", "the solid surface of the earth under your feet",
   "le sol", "el suelo", "o chão", "il terreno", "der Boden", "земля", "الأرض", "地面"),
 "tarmac": e("noun", "the hard black surface of a road",
   "le bitume", "el asfalto", "o asfalto", "l'asfalto", "der Asphalt", "асфальт", "الإسفلت", "柏油路面"),
 "mirage": e("noun", "water you seem to see in the heat that is not really there",
   "le mirage", "el espejismo", "a miragem", "il miraggio", "die Fata Morgana",
   "мираж", "سراب", "海市蜃楼"),
 "wind": e("noun", "moving air",
   "le vent", "el viento", "o vento", "il vento", "der Wind", "ветер", "ريح", "风"),
 "dune": e("noun", "a hill of sand made by the wind",
   "la dune", "la duna", "a duna", "la duna", "die Düne", "дюна", "كثيب", "沙丘"),

 # --- water and the body ---
 "water": e("noun", "the clear liquid that people and animals must drink to live",
   "l'eau", "el agua", "a água", "l'acqua", "das Wasser", "вода", "ماء", "水"),
 "bottle": e("noun", "a container for liquid, usually of glass or plastic",
   "la bouteille", "la botella", "a garrafa", "la bottiglia", "die Flasche", "бутылка", "زجاجة", "瓶子"),
 "crate": e("noun", "a large box for carrying goods",
   "la caisse", "la caja", "o caixote", "la cassa", "die Kiste", "ящик", "صندوق", "板条箱"),
 "sip": e("verb", "to drink a very small amount at a time",
   "siroter", "sorber", "beber aos golinhos", "sorseggiare", "nippen",
   "потягивать", "يرتشف", "小口喝"),
 "drink": e("verb", "to take liquid into your mouth and swallow it",
   "boire", "beber", "beber", "bere", "trinken", "пить", "يشرب", "喝"),
 "ration": e("verb", "to share out a small, fixed amount so it lasts",
   "rationner", "racionar", "racionar", "razionare", "rationieren", "нормировать", "يقنّن", "定量分配"),
 "thirst": e("noun", "the feeling of needing to drink",
   "la soif", "la sed", "a sede", "la sete", "der Durst", "жажда", "عطش", "口渴"),
 "thirsty": e("adjective", "feeling that you need to drink",
   "assoiffé", "sediento", "sedento", "assetato", "durstig", "испытывающий жажду", "عطشان", "口渴的"),
 "parched": e("adjective", "very dry, especially in the mouth from thirst",
   "assoiffé", "reseco", "ressequido", "riarso", "ausgedörrt", "пересохший", "متيبّس عطشًا", "焦渴的"),
 "mouth": e("noun", "the part of the face used for eating and speaking",
   "la bouche", "la boca", "a boca", "la bocca", "der Mund", "рот", "فم", "嘴"),
 "mouthful": e("noun", "the amount you can hold in your mouth at once",
   "une gorgée", "un bocado", "um gole", "un sorso", "ein Schluck", "глоток", "جرعة", "一口"),
 "throat": e("noun", "the passage at the back of the mouth for food and air",
   "la gorge", "la garganta", "a garganta", "la gola", "die Kehle", "горло", "حلق", "喉咙"),
 "lips": e("noun", "the soft edges of the mouth",
   "les lèvres", "los labios", "os lábios", "le labbra", "die Lippen", "губы", "شفتان", "嘴唇"),
 "cracked": e("adjective", "split with thin lines, as dry skin",
   "gercé", "agrietado", "rachado", "screpolato", "rissig", "потрескавшийся", "متشقّق", "干裂的"),
 "dizzy": e("adjective", "feeling that everything is spinning",
   "étourdi", "mareado", "tonto", "stordito", "schwindlig", "головокружительный", "دائخ", "头晕的"),
 "faint": e("verb", "to lose consciousness for a short time",
   "s'évanouir", "desmayarse", "desmaiar", "svenire", "ohnmächtig werden",
   "падать в обморок", "يُغمى عليه", "昏倒"),
 "dazed": e("adjective", "unable to think clearly, as if stunned",
   "hébété", "aturdido", "atordoado", "frastornato", "benommen", "оглушённый", "مذهول", "恍惚的"),
 "spent": e("adjective", "completely without energy; exhausted",
   "épuisé", "agotado", "esgotado", "sfinito", "erschöpft", "измождённый", "منهك", "精疲力竭的"),
 "stagger": e("verb", "to walk unsteadily, as if about to fall",
   "tituber", "tambalearse", "cambalear", "barcollare", "taumeln", "шататься", "يترنّح", "踉跄"),
 "stumble": e("verb", "to trip or walk unsteadily",
   "trébucher", "tropezar", "tropeçar", "inciampare", "stolpern", "спотыкаться", "يتعثّر", "绊倒"),
 "skin": e("noun", "the outer covering of the body",
   "la peau", "la piel", "a pele", "la pelle", "die Haut", "кожа", "جلد", "皮肤"),
 "neck": e("noun", "the part of the body joining the head to the shoulders",
   "le cou", "el cuello", "o pescoço", "il collo", "der Hals", "шея", "رقبة", "脖子"),
 "wrists": e("noun", "the joints between the hands and the arms",
   "les poignets", "las muñecas", "os pulsos", "i polsi", "die Handgelenke",
   "запястья", "معصمان", "手腕"),
 "legs": e("noun", "the parts of the body used for standing and walking",
   "les jambes", "las piernas", "as pernas", "le gambe", "die Beine", "ноги", "ساقان", "腿"),
 "cloth": e("noun", "a piece of fabric, used for cleaning or wiping",
   "le chiffon", "el paño", "o pano", "il panno", "das Tuch", "тряпка", "قطعة قماش", "布"),
 "fever": e("noun", "a body temperature that is too high",
   "la fièvre", "la fiebre", "a febre", "la febbre", "das Fieber", "жар", "حُمّى", "发烧"),
 "wet": e("verb", "to make something covered with water",
   "mouiller", "mojar", "molhar", "bagnare", "nass machen", "мочить", "يبلّل", "弄湿"),

 # --- the road and the crisis ---
 "bus": e("noun", "a large road vehicle that carries many passengers",
   "le bus", "el autobús", "o autocarro", "l'autobus", "der Bus", "автобус", "حافلة", "公共汽车"),
 "road": e("noun", "a wide, hard way built for vehicles to travel on",
   "la route", "la carretera", "a estrada", "la strada", "die Straße", "дорога", "طريق", "路"),
 "engine": e("noun", "the machine that makes a vehicle move",
   "le moteur", "el motor", "o motor", "il motore", "der Motor", "двигатель", "محرّك", "发动机"),
 "driver": e("noun", "the person who controls a vehicle",
   "le chauffeur", "el conductor", "o motorista", "l'autista", "der Fahrer",
   "водитель", "سائق", "司机"),
 "passenger": e("noun", "a person who travels in a vehicle but does not drive",
   "le passager", "el pasajero", "o passageiro", "il passeggero", "der Fahrgast",
   "пассажир", "راكب", "乘客"),
 "seat": e("noun", "a thing made for sitting on",
   "le siège", "el asiento", "o assento", "il sedile", "der Sitz", "сиденье", "مقعد", "座位"),
 "wheel": e("noun", "a round part that turns to move a vehicle; the steering wheel",
   "la roue", "la rueda", "a roda", "la ruota", "das Rad", "колесо", "عجلة", "车轮"),
 "radio": e("noun", "a device that sends and receives messages or sound",
   "la radio", "la radio", "o rádio", "la radio", "das Funkgerät", "рация", "جهاز لاسلكي", "无线电"),
 "signal": e("noun", "the reception that lets a phone connect",
   "le signal", "la señal", "o sinal", "il segnale", "das Signal", "сигнал", "إشارة", "信号"),
 "breakdown": e("noun", "the failure of a machine or vehicle to keep working",
   "la panne", "la avería", "a avaria", "il guasto", "die Panne", "поломка", "عطل", "故障"),
 "stall": e("verb", "(of an engine) to stop running suddenly",
   "caler", "calarse", "morrer", "spegnersi", "abwürgen", "глохнуть", "يتوقّف فجأة", "熄火"),
 "stuck": e("adjective", "unable to move or get free",
   "coincé", "atascado", "preso", "bloccato", "festgefahren", "застрявший", "عالق", "卡住的"),
 "stores": e("noun", "a supply of goods kept for use",
   "les provisions", "las provisiones", "os mantimentos", "le provviste", "die Vorräte",
   "запасы", "مؤن", "储备物资"),
 "supplies": e("noun", "the things needed for a task, kept ready",
   "les fournitures", "los suministros", "os suprimentos", "le scorte", "der Nachschub",
   "припасы", "إمدادات", "补给"),
 "tarp": e("noun", "a large sheet of strong cloth used as a cover",
   "la bâche", "la lona", "a lona", "il telone", "die Plane", "брезент", "مشمّع", "防水布"),
 "rags": e("noun", "old, torn pieces of cloth",
   "les chiffons", "los trapos", "os trapos", "gli stracci", "die Lumpen",
   "тряпьё", "خِرَق", "破布"),
 "canvas": e("noun", "a strong, heavy cloth",
   "la toile", "la lona", "a lona", "la tela", "das Segeltuch", "холст", "قماش خشن", "帆布"),
 "sheet": e("noun", "a large, flat piece of cloth or material",
   "la toile", "la lámina", "a folha", "il telo", "das Tuch", "полотнище", "غطاء", "布单"),
 "siding": e("noun", "a short side track by a railway; here, an old rail-stop",
   "la voie de garage", "el apartadero", "o desvio", "il binario di raccordo",
   "das Abstellgleis", "запасный путь", "مسار جانبي", "铁路侧线"),
 "windmill": e("noun", "a machine with turning blades driven by the wind",
   "le moulin à vent", "el molino de viento", "o moinho de vento", "il mulino a vento",
   "die Windmühle", "ветряк", "طاحونة هواء", "风车"),
 "well": e("noun", "a deep hole dug to reach water underground",
   "le puits", "el pozo", "o poço", "il pozzo", "der Brunnen", "колодец", "بئر", "井"),
 "pickup": e("noun", "a small truck with an open back",
   "le pick-up", "la camioneta", "a camioneta", "il pick-up", "der Pick-up",
   "пикап", "شاحنة صغيرة", "皮卡车"),
 "truck": e("noun", "a large road vehicle for carrying heavy loads",
   "le camion", "el camión", "o caminhão", "il camion", "der Lastwagen",
   "грузовик", "شاحنة", "卡车"),
 "plume": e("noun", "a tall, rising cloud of smoke or dust",
   "le panache", "la columna", "a coluna", "il pennacchio", "die Fahne",
   "шлейф", "عمود", "一缕"),
 "wheels": e("noun", "the round parts a vehicle rolls on; here, a vehicle",
   "les roues", "las ruedas", "as rodas", "le ruote", "die Räder", "колёса", "عجلات", "车轮"),
 "headlights": e("noun", "the bright lamps at the front of a vehicle",
   "les phares", "los faros", "os faróis", "i fari", "die Scheinwerfer", "фары", "مصابيح أمامية", "车头灯"),
 "roadside": e("noun", "the edge or side of a road",
   "le bord de la route", "el borde de la carretera", "a beira da estrada",
   "il ciglio della strada", "der Straßenrand", "обочина", "جانب الطريق", "路边"),
 "shoulder": e("noun", "the strip of ground at the edge of a road",
   "l'accotement", "el arcén", "o acostamento", "la banchina", "der Seitenstreifen",
   "обочина", "كتف الطريق", "路肩"),
 "smoke": e("noun", "the grey cloud that rises from a fire",
   "la fumée", "el humo", "o fumo", "il fumo", "der Rauch", "дым", "دخان", "烟"),
 "fire": e("noun", "the flames, heat and light of something burning",
   "le feu", "el fuego", "o fogo", "il fuoco", "das Feuer", "огонь", "نار", "火"),

 # --- people, feeling, and the con ---
 "stranger": e("noun", "a person you do not know",
   "l'inconnu", "el desconocido", "o estranho", "lo sconosciuto", "der Fremde",
   "незнакомец", "غريب", "陌生人"),
 "crowd": e("noun", "a large group of people together",
   "la foule", "la multitud", "a multidão", "la folla", "die Menge", "толпа", "حشد", "人群"),
 "family": e("noun", "a group of people related to one another",
   "la famille", "la familia", "a família", "la famiglia", "die Familie", "семья", "عائلة", "家庭"),
 "fear": e("noun", "the feeling of being afraid",
   "la peur", "el miedo", "o medo", "la paura", "die Angst", "страх", "خوف", "恐惧"),
 "calm": e("adjective", "quiet and not upset or excited",
   "calme", "tranquilo", "calmo", "calmo", "ruhig", "спокойный", "هادئ", "平静的"),
 "confused": e("adjective", "unable to think clearly or understand",
   "désorienté", "confundido", "confuso", "confuso", "verwirrt", "растерянный", "مرتبك", "困惑的"),
 "weak": e("adjective", "having little strength",
   "faible", "débil", "fraco", "debole", "schwach", "слабый", "ضعيف", "虚弱的"),
 "limp": e("adjective", "soft and without strength; not stiff",
   "mou", "lánguido", "mole", "floscio", "schlaff", "обмякший", "مرتخٍ", "软弱无力的"),
 "grey": e("adjective", "of a dull colour between black and white; pale and ill",
   "gris", "gris", "cinzento", "grigio", "grau", "серый", "رمادي", "灰色的"),
 "tired": e("adjective", "needing rest or sleep",
   "fatigué", "cansado", "cansado", "stanco", "müde", "усталый", "متعب", "疲倦的"),
 "kind": e("adjective", "gentle and caring toward others",
   "gentil", "amable", "gentil", "gentile", "freundlich", "добрый", "لطيف", "善良的"),
 "honest": e("adjective", "truthful; not lying or cheating",
   "honnête", "honesto", "honesto", "onesto", "ehrlich", "честный", "أمين", "诚实的"),
 "con": e("noun", "a dishonest trick to take someone's money",
   "l'arnaque", "la estafa", "o golpe", "la truffa", "der Betrug", "афёра", "احتيال", "骗局"),
 "fleeced": e("adjective", "cheated out of your money",
   "arnaqué", "estafado", "roubado", "spennato", "übers Ohr gehauen",
   "обманутый", "مغبون", "被敲竹杠的"),
 "cheated": e("adjective", "tricked in a dishonest way",
   "trompé", "engañado", "enganado", "imbrogliato", "betrogen", "обманутый", "مخدوع", "被骗的"),
 "money": e("noun", "coins and notes used to buy things",
   "l'argent", "el dinero", "o dinheiro", "il denaro", "das Geld", "деньги", "مال", "钱"),
 "price": e("noun", "the amount of money something costs",
   "le prix", "el precio", "o preço", "il prezzo", "der Preis", "цена", "سعر", "价格"),
 "pay": e("verb", "to give money for something",
   "payer", "pagar", "pagar", "pagare", "bezahlen", "платить", "يدفع", "支付"),
 "buy": e("verb", "to get something by paying money",
   "acheter", "comprar", "comprar", "comprare", "kaufen", "покупать", "يشتري", "买"),
 "offer": e("noun", "something you say you will give or do for someone",
   "l'offre", "la oferta", "a oferta", "l'offerta", "das Angebot", "предложение", "عرض", "提议"),
 "lift": e("noun", "a free ride in someone's vehicle",
   "le trajet", "el aventón", "a boleia", "il passaggio", "die Mitfahrt",
   "подвозка", "توصيلة", "搭车"),
 "ride": e("noun", "a journey in a vehicle",
   "le trajet", "el viaje", "a viagem", "la corsa", "die Fahrt", "поездка", "رحلة قصيرة", "乘车"),
 "brackish": e("adjective", "(of water) slightly salty and unpleasant",
   "saumâtre", "salobre", "salobra", "salmastro", "brackig", "солоноватый", "أُجاج", "微咸的"),
 "foul": e("adjective", "very unpleasant to taste or smell",
   "infect", "asqueroso", "nojento", "disgustoso", "widerlich", "отвратительный", "كريه", "恶臭的"),

 # --- common verbs & adjectives across the book ---
 "help": e("verb", "to make it easier for someone to do something",
   "aider", "ayudar", "ajudar", "aiutare", "helfen", "помогать", "يساعد", "帮助"),
 "share": e("verb", "to give a part of what you have to others",
   "partager", "compartir", "partilhar", "condividere", "teilen", "делиться", "يتشارك", "分享"),
 "hold": e("verb", "to keep or carry in your hands or arms; to keep steady",
   "tenir", "sostener", "segurar", "tenere", "halten", "держать", "يمسك", "握住"),
 "rig": e("verb", "to set up or fix something for use",
   "installer", "montar", "montar", "montare", "aufbauen", "сооружать", "ينصب", "搭起"),
 "knock": e("verb", "to hit a door to be let in",
   "frapper", "llamar", "bater", "bussare", "klopfen", "стучать", "يطرق", "敲"),
 "press": e("verb", "to push steadily; to urge",
   "appuyer", "presionar", "pressionar", "premere", "drücken", "давить", "يضغط", "按压"),
 "promise": e("verb", "to say firmly that you will do something",
   "promettre", "prometer", "prometer", "promettere", "versprechen", "обещать", "يعِد", "承诺"),
 "warn": e("verb", "to tell someone of a danger or problem ahead",
   "avertir", "advertir", "avisar", "avvertire", "warnen", "предупреждать", "يحذّر", "警告"),
 "guess": e("verb", "to give an answer you are not sure of",
   "deviner", "adivinar", "adivinhar", "indovinare", "raten", "угадывать", "يخمّن", "猜"),
 "save": e("verb", "to keep someone from harm or death",
   "sauver", "salvar", "salvar", "salvare", "retten", "спасать", "ينقذ", "拯救"),
 "hide": e("verb", "to keep something from being seen or known",
   "cacher", "ocultar", "esconder", "nascondere", "verbergen", "прятать", "يخفي", "隐藏"),
 "shove": e("verb", "to push roughly",
   "pousser", "empujar", "empurrar", "spingere", "stoßen", "толкать", "يدفع بعنف", "猛推"),
 "beg": e("verb", "to ask for something very anxiously",
   "supplier", "suplicar", "implorar", "supplicare", "flehen", "умолять", "يتوسّل", "乞求"),
 "slump": e("verb", "to fall or sit heavily, without strength",
   "s'affaisser", "desplomarse", "desabar", "accasciarsi", "sacken",
   "оседать", "ينهار", "瘫倒"),
 "rise": e("verb", "to go upward",
   "s'élever", "elevarse", "subir", "salire", "aufsteigen", "подниматься", "يرتفع", "上升"),
 "drop": e("verb", "to go down; to fall",
   "baisser", "bajar", "baixar", "calare", "sinken", "падать", "ينخفض", "下降"),
 "reach": e("verb", "to arrive at a place",
   "atteindre", "alcanzar", "alcançar", "raggiungere", "erreichen", "достигать", "يصل إلى", "到达"),
 "drift": e("verb", "to move slowly and gently, carried by air or water",
   "flotter", "flotar", "flutuar", "fluttuare", "treiben", "плыть", "ينساب", "飘"),
 "nag": e("verb", "to keep bothering you in the mind",
   "tarauder", "reconcomer", "atormentar", "assillare", "nagen", "не давать покоя", "يلحّ", "萦绕"),
 "spill": e("verb", "to let liquid fall or run out by accident",
   "renverser", "derramar", "derramar", "versare", "verschütten", "проливать", "يسكب", "洒"),
 "fan": e("verb", "to move air onto someone to cool them",
   "éventer", "abanicar", "abanar", "sventolare", "fächeln", "обмахивать", "يروّح", "扇风"),

 "real": e("adjective", "true; actually existing, not false",
   "réel", "real", "real", "reale", "echt", "настоящий", "حقيقي", "真实的"),
 "quiet": e("adjective", "making little or no noise; still",
   "calme", "silencioso", "quieto", "silenzioso", "still", "тихий", "هادئ", "安静的"),
 "thick": e("adjective", "dense; hard to see or move through",
   "épais", "espeso", "espesso", "denso", "dicht", "густой", "كثيف", "浓密的"),
 "thin": e("adjective", "narrow; not thick or dense",
   "mince", "fino", "fino", "sottile", "dünn", "тонкий", "رقيق", "细的"),
 "soft": e("adjective", "not hard; easy to press or shape",
   "mou", "blando", "macio", "morbido", "weich", "мягкий", "طريّ", "软的"),
 "deep": e("adjective", "going far down from the top",
   "profond", "profundo", "profundo", "profondo", "tief", "глубокий", "عميق", "深的"),
 "low": e("adjective", "close to the ground; not high",
   "bas", "bajo", "baixo", "basso", "niedrig", "низкий", "منخفض", "低的"),
 "dim": e("adjective", "not bright; hard to see in",
   "sombre", "tenue", "sombrio", "fioco", "schummrig", "тусклый", "خافت", "昏暗的"),
 "stifling": e("adjective", "so hot and airless it is hard to breathe",
   "étouffant", "sofocante", "sufocante", "soffocante", "stickig",
   "удушливый", "خانق", "闷热的"),
 "empty": e("adjective", "having nothing inside",
   "vide", "vacío", "vazio", "vuoto", "leer", "пустой", "فارغ", "空的"),
 "whole": e("adjective", "complete; all of a thing",
   "entier", "entero", "inteiro", "intero", "ganz", "весь", "كامل", "整个的"),
 "patient": e("adjective", "able to wait calmly for a long time",
   "patient", "paciente", "paciente", "paziente", "geduldig", "терпеливый", "صبور", "有耐心的"),
 "careful": e("adjective", "giving attention to avoid harm or mistakes",
   "prudent", "cuidadoso", "cuidadoso", "attento", "vorsichtig", "осторожный", "حذِر", "小心的"),
 "gentle": e("adjective", "soft and mild; not rough",
   "doux", "suave", "gentil", "delicato", "sanft", "нежный", "لطيف", "温柔的"),
 "strange": e("adjective", "unusual or hard to explain",
   "étrange", "extraño", "estranho", "strano", "seltsam", "странный", "غريب", "奇怪的"),
 "wrong": e("adjective", "not right; not as it should be",
   "faux", "equivocado", "errado", "sbagliato", "falsch", "неправильный", "خاطئ", "错误的"),
 "clean": e("adjective", "free of dirt; honest and fair",
   "propre", "limpio", "limpo", "pulito", "sauber", "чистый", "نظيف", "干净的"),
 "worn": e("adjective", "damaged or made weak by long use",
   "usé", "gastado", "gasto", "logoro", "abgenutzt", "изношенный", "بالٍ", "磨损的"),
 "curled": e("adjective", "bent or rolled into a curved shape",
   "recourbé", "rizado", "enrolado", "arricciato", "gewellt", "закрученный", "ملتوٍ", "卷曲的"),
 "silence": e("noun", "complete quiet; no sound",
   "le silence", "el silencio", "o silêncio", "il silenzio", "die Stille",
   "тишина", "صمت", "寂静"),
 "trouble": e("noun", "difficulty or danger",
   "les ennuis", "el problema", "o apuro", "i guai", "die Not", "беда", "ورطة", "麻烦"),

 # --- coverage top-up (words the prose leans on) ---
 "aboard": e("adverb", "on or onto a bus, boat or plane",
   "à bord", "a bordo", "a bordo", "a bordo", "an Bord", "на борту", "على متن", "在车上"),
 "ashamed": e("adjective", "feeling bad about something you have done",
   "honteux", "avergonzado", "envergonhado", "vergognoso", "beschämt",
   "пристыжённый", "خجلان", "羞愧的"),
 "kindness": e("noun", "the quality of being caring and helpful",
   "la gentillesse", "la amabilidad", "a bondade", "la gentilezza", "die Freundlichkeit",
   "доброта", "لطف", "善意"),
 "grab": e("verb", "to take hold of something suddenly and roughly",
   "saisir", "agarrar", "agarrar", "afferrare", "packen", "хватать", "يخطف", "抓住"),
 "rail": e("noun", "the metal track a train runs on",
   "le rail", "el riel", "o trilho", "la rotaia", "die Schiene", "рельс", "سكة", "铁轨"),
 "underfoot": e("adverb", "under your feet; on the ground you walk on",
   "sous les pieds", "bajo los pies", "sob os pés", "sotto i piedi", "unter den Füßen",
   "под ногами", "تحت القدمين", "脚下"),
 "fade": e("verb", "to slowly grow fainter and disappear",
   "s'estomper", "desvanecerse", "esvair-se", "svanire", "verblassen",
   "тускнеть", "يتلاشى", "渐渐消失"),
 "spread": e("verb", "to reach or move over a wider area",
   "se répandre", "extenderse", "espalhar-se", "diffondersi", "sich ausbreiten",
   "распространяться", "ينتشر", "蔓延"),
 "ache": e("verb", "to hurt with a dull, steady pain",
   "faire mal", "doler", "doer", "dolere", "schmerzen", "ныть", "يؤلم", "隐隐作痛"),
 "beat": e("verb", "to hit again and again; (of the sun) to shine down hard",
   "battre", "golpear", "bater", "battere", "schlagen", "бить", "يضرب", "拍打"),
 "bend": e("verb", "to make or become curved; to warp",
   "courber", "doblar", "dobrar", "piegare", "biegen", "гнуть", "يحني", "弯曲"),
 "hang": e("verb", "to hold or be held from above; to droop",
   "pendre", "colgar", "pendurar", "pendere", "hängen", "висеть", "يتدلّى", "悬挂"),
 "toward": e("preposition", "in the direction of",
   "vers", "hacia", "em direção a", "verso", "auf ... zu", "к", "نحو", "朝向"),
 "ahead": e("adverb", "in front; further on",
   "devant", "adelante", "à frente", "avanti", "voraus", "впереди", "أمام", "前方"),
 "barely": e("adverb", "only just; almost not",
   "à peine", "apenas", "mal", "appena", "kaum", "едва", "بالكاد", "勉强"),
 "aside": e("adverb", "to one side; out of the way",
   "de côté", "a un lado", "de lado", "da parte", "beiseite", "в сторону", "جانبًا", "在一旁"),
 "fairly": e("adverb", "in a just and even way",
   "équitablement", "con justicia", "de forma justa", "in modo equo", "gerecht",
   "справедливо", "بإنصاف", "公平地"),
 "whatever": e("pronoun", "anything or everything of a kind; no matter what",
   "quoi que ce soit", "lo que sea", "o que quer que seja", "qualunque cosa", "was auch immer",
   "что бы ни", "مهما كان", "无论什么"),
}


def main():
    ep1 = json.load(open(EP1, encoding="utf-8"))["lexicon"]["entries"]
    ep3 = json.load(open(EP3, encoding="utf-8"))["lexicon"]["entries"]
    book = json.load(open(EP4, encoding="utf-8"))
    src = {**ep1, **ep3}  # book-3 gloss wins where both have it (same house draft)
    entries, missing = {}, []
    for w in REUSE:
        if w in src:
            entries[w] = src[w]
        else:
            missing.append(w)
    for w, v in NEW.items():
        entries[w.strip()] = v
    book["lexicon"]["entries"] = dict(sorted(entries.items()))
    json.dump(book, open(EP4, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    print(f"Lexicon written: {len(entries)} entries "
          f"({len([w for w in REUSE if w in src])} reused, {len(NEW)} new).")
    if missing:
        print("WARNING reuse words not in book 1/3:", ", ".join(missing))


if __name__ == "__main__":
    main()
