#!/usr/bin/env python3
"""Per-passage clue text (gist) for book 6, The Orchard.
Scoped per book: content/gist/the-orchard/<lang>.json. "Where needed": opening, the fuel store,
a neighbour, rallying the village, the frozen-pond shortcut, the giving, the buyer's con, the
mystery (Wren), and all 12 endings. fr/es/it/de/pt vouched; ru/ar/zh draft PENDING NATIVE REVIEW.
Run: python3 scripts/build_gists_ep06.py
"""
import json, os
LANGS = ["fr", "es", "it", "de", "pt", "ru", "ar", "zh"]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "the-orchard")
os.makedirs(OUT, exist_ok=True)
G = {
 1: {
  "fr": "C'est la nuit la plus froide du printemps. Les arbres sont en fleur, et toute la récolte de l'année tient à quelques degrés. La vieille Edith Marsh tombe sur les marches et ne peut se relever. Les feux entre les rangs sont éteints, le gel descend déjà, et aucune aide ne viendra avant le matin. Sauver les fleurs dépend de vous.",
  "es": "Es la noche más fría de la primavera. Los árboles están en flor, y toda la cosecha del año pende de unos pocos grados. La vieja Edith Marsh cae en los escalones y no puede levantarse. Las hogueras de los surcos están apagadas, la helada ya baja y no vendrá ayuda antes del amanecer. Salvar la flor depende de ti.",
  "it": "È la notte più fredda della primavera. Gli alberi sono in fiore, e tutto il raccolto dell'anno è appeso a pochi gradi. La vecchia Edith Marsh cade sui gradini e non riesce a rialzarsi. I fuochi lungo i filari sono spenti, il gelo sta già scendendo e nessuno arriverà prima del mattino. Salvare i fiori tocca a te.",
  "de": "Es ist die kälteste Frühlingsnacht. Die Bäume stehen in Blüte, und die ganze Jahresernte hängt an wenigen Graden. Die alte Edith Marsh stürzt auf den Stufen und kann nicht mehr aufstehen. Die Feuer zwischen den Reihen sind aus, der Frost sinkt schon, und vor dem Morgen kommt keine Hilfe. Die Blüte zu retten liegt an dir.",
  "pt": "É a noite mais fria da primavera. As árvores estão em flor, e toda a colheita do ano depende de uns poucos graus. A velha Edith Marsh cai nos degraus e não consegue levantar-se. As fogueiras das fileiras estão apagadas, a geada já desce, e não virá ajuda antes de manhã. Salvar a flor depende de ti.",
  "ru": "Самая холодная ночь весны. Деревья в цвету, и весь урожай года висит на нескольких градусах. Старая Эдит Марш падает на ступенях и не может встать. Костры между рядами погасли, иней уже ложится, и до утра помощи не будет. Спасти цвет теперь на тебе.",
  "ar": "إنها أبرد ليالي الربيع. الأشجار في إزهار، ومحصول العام كلّه معلّق على بضع درجات. تسقط العجوز إديث مارش على الدرجات ولا تقوى على النهوض. نيران الصفوف مُطفأة، والصقيع ينزل بالفعل، ولن يأتي عون قبل الصباح. إنقاذ الزهر صار عليك.",
  "zh": "这是春天最冷的一夜。果树正开着花，一整年的收成就系在这几度之差上。老伊迪丝·马什在后阶上摔倒，起不来了。一排排之间的火堆没有点着，霜已经落下，天亮前不会有人来。保住这些花，就落在你身上。",
 },
 9: {
  "fr": "Tom ouvre la réserve et lève la lanterne : un bidon d'huile, des allumettes, des bottes de paille, de la toile sèche. « Prends ce qu'il te faut. Je reste au téléphone pour appeler du monde. » Un homme solide, et ça compte par une nuit pareille.",
  "es": "Tom abre el almacén y levanta el farol: un bidón de aceite, cerillas, haces de paja, arpillera seca. «Toma lo que necesites. Yo me quedo al teléfono para avisar a quien pueda». Un hombre firme, y en una noche así se nota.",
  "it": "Tom apre il deposito e alza la lanterna: un bidone d'olio, fiammiferi, balle di paglia, tela asciutta. «Prendi ciò che ti serve. Io resto al telefono a chiamare chi posso». Un uomo saldo, e in una notte così si vede.",
  "de": "Tom reißt das Lager auf und hebt die Laterne: ein Kanister Öl, Streichhölzer, Bunde Stroh, trockenes Sackleinen. „Nimm, was du brauchst. Ich bleibe am Telefon und rufe zusammen, wen ich kann.“ Ein verlässlicher Mann, und in einer solchen Nacht zeigt sich das.",
  "pt": "O Tom abre o armazém e ergue a lanterna: um bidão de óleo, fósforos, molhos de palha, serapilheira seca. «Leva o que precisares. Eu fico ao telefone a chamar quem puder». Um homem firme, e numa noite destas isso nota-se.",
  "ru": "Том распахивает склад и поднимает фонарь: канистра масла, спички, вязанки соломы, сухая мешковина. «Бери что нужно. Я останусь у телефона, созову кого смогу». Надёжный человек — в такую ночь это видно.",
  "ar": "يفتح توم المخزن ويرفع الفانوس: صفيحة زيت، أعواد ثقاب، حُزم قشّ، خيش جاف. «خذ ما تحتاج. سأبقى عند الهاتف أستدعي من أستطيع». رجلٌ ثابت، وفي ليلةٍ كهذه يظهر ذلك.",
  "zh": "汤姆拉开库房，举起灯：一桶油、火柴、一捆捆干草、干麻袋。“需要什么尽管拿。我守着电话，能叫来谁就叫谁。”他是个靠得住的人，这种夜里尤见真章。",
 },
 10: {
  "fr": "Le vieux M. Hollis ouvre, pâle de froid : son poêle est éteint, plus d'allumettes, les mains trop tremblantes pour en gratter une. « Je n'arrive pas à l'allumer. » La nuit sera longue — mais il est là, il a peur, et c'est vous qu'il appelle.",
  "es": "El viejo señor Hollis abre, pálido de frío: su estufa apagada, sin cerillas, las manos demasiado temblorosas para encender una. «No consigo prenderla». La noche será larga, pero él está ahí, tiene miedo y es a ti a quien pide ayuda.",
  "it": "Il vecchio signor Hollis apre, pallido dal freddo: la stufa spenta, niente fiammiferi, le mani troppo tremanti per accenderne uno. «Non riesco ad accenderla». La notte sarà lunga — ma lui è lì, ha paura, ed è te che sta chiamando.",
  "de": "Der alte Mr Hollis öffnet, bleich vor Kälte: der Ofen aus, keine Streichhölzer, die Hände zu zittrig, um eines anzureißen. „Ich bekomme ihn nicht an.“ Die Nacht wird lang – aber er ist hier, hat Angst, und dich bittet er.",
  "pt": "O velho Sr. Hollis abre, pálido de frio: o fogão apagado, sem fósforos, as mãos a tremer demais para riscar um. «Não consigo acendê-lo». A noite vai ser longa — mas ele está ali, tem medo, e é a ti que pede.",
  "ru": "Старый мистер Холлис открывает, бледный от холода: печь погасла, спички кончились, руки слишком дрожат, чтобы чиркнуть. «Не могу разжечь». Ночь будет долгой — но он здесь, ему страшно, и просит он тебя.",
  "ar": "يفتح العجوز السيد هولِس، شاحباً من البرد: مِدفأته خامدة، ولا ثقاب، ويداه ترتجفان أكثر من أن تُشعلا عوداً. «لا أستطيع إشعالها». الليلة ستطول — لكنه هنا، وهو خائف، ويطلب منك أنت.",
  "zh": "老霍利斯先生开了门，冻得脸色发白：炉子灭了，火柴用完了，手抖得划不着。“我点不着。”今夜漫长难熬——可他就在这儿，他害怕，向你求助的正是他。",
 },
 12: {
  "fr": "Vous allez de maison en maison demander la même chose : de la paille pour les feux, un coup de main aux brasiers, de l'aide pour tenir la lumière le long des rangs. Certains ferment leur porte. Mais quelques-uns enfilent leur manteau et sortent dans le froid — et quelques-uns suffisent pour commencer.",
  "es": "Vas de casa en casa pidiendo lo mismo: paja para las hogueras, una mano en los braseros, ayuda para sostener la luz por los surcos. Algunos cierran la puerta. Pero unos pocos se abrigan y salen al frío, y con unos pocos basta para empezar.",
  "it": "Vai di casa in casa chiedendo la stessa cosa: paglia per i fuochi, una mano ai bracieri, aiuto per tenere la luce lungo i filari. Alcuni chiudono la porta. Ma alcuni si infilano il cappotto ed escono nel freddo — e bastano pochi per cominciare.",
  "de": "Du gehst von Haus zu Haus und bittest um dasselbe: Stroh für die Feuer, eine Hand an den Öfen, Hilfe, das Licht entlang der Reihen zu halten. Manche schließen die Tür. Aber einige ziehen den Mantel an und treten hinaus in die Kälte – und ein paar genügen für den Anfang.",
  "pt": "Vais de casa em casa a pedir o mesmo: palha para as fogueiras, uma mão nos braseiros, ajuda para segurar a luz ao longo das fileiras. Alguns fecham a porta. Mas alguns vestem o casaco e saem para o frio — e bastam alguns para começar.",
  "ru": "Ты ходишь от дома к дому с одной просьбой: соломы для костров, рук у жаровен, помощи удержать свет вдоль рядов. Кто-то закрывает дверь. Но несколько человек надевают пальто и выходят на холод — а чтобы начать, хватит и нескольких.",
  "ar": "تذهب من بيتٍ إلى بيت طالباً الشيء نفسه: قشّاً للنيران، ويداً عند المواقد، وعوناً لإبقاء الضوء على امتداد الصفوف. يُغلق بعضهم الباب. لكن قلّةً يرتدون معاطفهم ويخرجون إلى البرد — ويكفي القليل للبدء.",
  "zh": "你挨家挨户地说着同一件事：拿草来生火、到火盆边搭把手、帮我守住一排排间的光。有人关上了门。但也有几个人披上外套、走进寒夜——今夜，几个人就够开头了。",
 },
 27: {
  "fr": "L'étang gelé couperait la route de moitié, et les rangs du fond sont juste au-delà. Mais la glace est mince, noire et traîtresse au-dessus d'une eau profonde. Jack Hale vous a dit de ne pas y aller — et il ne plaisantait pas.",
  "es": "El estanque helado acortaría el camino a la mitad, y los surcos del fondo quedan justo al otro lado. Pero el hielo es fino, negro y traicionero sobre aguas profundas. Jack Hale te dijo que no lo cruzaras, y no bromeaba.",
  "it": "Lo stagno gelato dimezzerebbe il cammino, e i filari in fondo sono proprio al di là. Ma il ghiaccio è sottile, nero e infido sopra acque profonde. Jack Hale ti ha detto di starne lontano — e non scherzava.",
  "de": "Der zugefrorene Teich würde den Weg halbieren, und die hinteren Reihen liegen gleich dahinter. Aber das Eis ist dünn, schwarz und tückisch über tiefem Wasser. Jack Hale hat dir gesagt, es zu meiden – und er hat nicht gescherzt.",
  "pt": "O lago gelado cortaria o caminho a meio, e as fileiras do fundo ficam logo do outro lado. Mas o gelo é fino, negro e traiçoeiro sobre água funda. O Jack Hale disse-te para não o atravessares — e não estava a brincar.",
  "ru": "Замёрзший пруд сократил бы путь вдвое, а дальние ряды сразу за ним. Но лёд тонкий, чёрный и коварный над глубокой водой. Джек Хейл велел туда не соваться — и не шутил.",
  "ar": "البركة المتجمّدة تختصر الطريق إلى النصف، والصفوف البعيدة خلفها مباشرة. لكن الجليد رقيق، أسود، غدّار فوق ماءٍ عميق. قال لك جاك هيل أن تتجنّبها — ولم يكن يمزح.",
  "zh": "结冰的池塘能把路缩短一半，尽头的那几排就在对岸。可那层冰又薄又黑，深水之上极其危险。杰克·黑尔叫你别走——他不是开玩笑。",
 },
 32: {
  "fr": "Une famille est enfermée dans une maison glacée — pas de feu, pas de lampe, un enfant qui pleure dans le noir. Les parents vous regardent, épuisés et sans espoir. Vous avez une lampe et un manteau. Peu de chose, mais plus qu'eux.",
  "es": "Una familia está encerrada en una casa helada — sin fuego, sin lámpara, un niño que llora en la oscuridad. Los padres te miran, agotados y sin esperanza. Tienes una lámpara y un abrigo. Poco, pero más que ellos.",
  "it": "Una famiglia è chiusa in una casa gelata — niente fuoco, niente lampada, un bambino che piange nel buio. I genitori ti guardano, sfiniti e senza speranza. Hai una lampada e un cappotto. Poco, ma più di loro.",
  "de": "Eine Familie sitzt in einem eiskalten Haus fest – kein Feuer, keine Lampe, ein Kind weint im Dunkeln. Die Eltern sehen dich erschöpft und hoffnungslos an. Du hast eine Lampe und einen Mantel. Wenig, aber mehr als sie.",
  "pt": "Uma família está fechada numa casa gelada — sem lume, sem lâmpada, uma criança a chorar no escuro. Os pais olham para ti, exaustos e sem esperança. Tens uma lâmpada e um casaco. Pouco, mas mais do que eles.",
  "ru": "Семья заперта в промёрзшем доме — ни огня, ни лампы, ребёнок плачет в темноте. Родители смотрят на тебя устало и безнадёжно. У тебя есть лампа и пальто. Немного, но больше, чем у них.",
  "ar": "عائلةٌ محبوسة في بيتٍ متجمّد — لا نار، لا مصباح، وطفلٌ يبكي في الظلام. ينظر إليك الوالدان بإرهاقٍ ويأس. معك مصباح ومعطف. قليلٌ، لكنه أكثر ممّا لديهم.",
  "zh": "一家人被困在冰冷的屋里——没有火，没有灯，一个孩子在黑暗中啼哭。父母疲惫而绝望地望着你。你有一盏灯、一件外套。不多，却比他们多。",
 },
 40: {
  "fr": "L'acheteur vous adresse son large sourire facile. « Dur travail, ça, dit-il. J'ai de l'huile à vendre et des bras à prêter — et le verger, ce n'est pas vraiment votre affaire ce soir, l'ami. » Sa lanterne se balance. Son sourire n'atteint jamais ses yeux.",
  "es": "El comprador te dirige su amplia sonrisa fácil. «Duro trabajo, este —dice—. Tengo aceite que vender y brazos que prestar, y el huerto no es realmente asunto tuyo esta noche, amigo». Su farol se balancea. Su sonrisa nunca llega a los ojos.",
  "it": "Il compratore ti rivolge il suo ampio sorriso facile. «Lavoro duro, questo», dice. «Ho olio da vendere e braccia da prestare — e il frutteto non è davvero affar tuo stanotte, amico». La sua lanterna dondola. Il sorriso non gli arriva mai agli occhi.",
  "de": "Der Aufkäufer schenkt dir sein breites, leichtes Lächeln. „Harte Arbeit, das“, sagt er. „Ich habe Öl zu verkaufen und starke Arme zu leihen – und der Obstgarten ist heute Nacht nicht wirklich deine Sache, Freund.“ Seine Laterne schwingt. Sein Lächeln erreicht nie die Augen.",
  "pt": "O comprador vira-te o seu largo sorriso fácil. «Trabalho duro, este», diz. «Tenho óleo para vender e braços para emprestar — e o pomar não é bem problema teu esta noite, amigo». A lanterna baloiça. O sorriso nunca lhe chega aos olhos.",
  "ru": "Скупщик обращает к тебе широкую лёгкую улыбку. «Тяжёлая работа, — говорит он. — У меня есть масло на продажу и крепкие руки внаём, а сад тебе сегодня, друг, вообще-то не забота». Его фонарь покачивается. Улыбка никогда не доходит до глаз.",
  "ar": "يوجّه إليك المشتري ابتسامته العريضة السهلة. «عملٌ شاقّ، هذا»، يقول. «عندي زيتٌ للبيع وساعدٌ أعيره — والبستان ليس حقاً شأنك الليلة يا صديق». يتأرجح فانوسه. وابتسامته لا تبلغ عينيه أبداً.",
  "zh": "买家朝你咧开那副轻松的笑。“这活儿苦啊，”他说，“我有油卖，也能搭把力气——再说，果园今晚本不算你的事，朋友。”他的灯晃着。那笑意从不抵达眼睛。",
 },
 41: {
  "fr": "L'offre est un hameçon, et vous le sentez s'enfoncer. Il se penche. « Ce verger est déjà perdu, dit-il tout bas. Laisse le gel l'emporter — et il y aura une part pour toi. » Une parole cruelle. Et faite pour jouer sur votre peur.",
  "es": "La oferta es un anzuelo, y lo sientes clavarse. Se inclina. «Ese huerto ya está perdido —dice en voz baja—. Deja que la helada se lo lleve, y habrá una parte para ti». Algo cruel de decir. Y pensado para jugar con tu miedo.",
  "it": "L'offerta è un amo, e lo senti affondare. Si china. «Quel frutteto è già perduto», dice piano. «Lascia che il gelo se lo prenda — e ci sarà una parte per te». Una cosa crudele da dire. E fatta apposta per far leva sulla tua paura.",
  "de": "Das Angebot ist ein Haken, und du spürst, wie er fasst. Er beugt sich vor. „Der Obstgarten ist ohnehin verloren“, sagt er leise. „Lass den Frost ihn holen – und es springt ein Anteil für dich heraus.“ Grausam gesagt. Und darauf gemünzt, deine Angst zu nutzen.",
  "pt": "A oferta é um anzol, e sente-lo fisgar. Ele inclina-se. «Esse pomar já está perdido», diz baixo. «Deixa a geada levá-lo — e há uma parte para ti». Uma coisa cruel de dizer. E feita para jogar com o teu medo.",
  "ru": "Предложение — это крючок, и ты чувствуешь, как он входит. Он наклоняется. «Сад и так уже потерян, — говорит тихо. — Пусть мороз его возьмёт — а тебе будет доля». Жестоко сказано. И рассчитано на твой страх.",
  "ar": "العرض خُطّاف، وتشعر به يعلَق. ينحني مقترباً. «ذلك البستان ضائعٌ أصلاً»، يقول بصوتٍ خافت. «دع الصقيع يأخذه — ولك نصيبٌ فيه». كلامٌ قاسٍ. ومقصودٌ به اللعب على خوفك.",
  "zh": "这提议是个钩子，你能感到它扎了进来。他凑近低声说：“那片果园反正已经完了。让霜把它收了去——你也有一份。”这话狠毒，专为撬动你的恐惧而说。",
 },
 69: {
  "fr": "Une maison fermée vous enserre — poussière, silence, vieux froid, un endroit où plus rien ne semble vivant. Puis vous l'entendez : une respiration, faible et proche, dans la pièce du fond. Quelqu'un est vivant ici, après tout.",
  "es": "Una casa cerrada te rodea — polvo, silencio, frío viejo, un lugar donde nada parece vivo. Entonces lo oyes: una respiración, débil y cercana, en el cuarto del fondo. Alguien está vivo aquí, después de todo.",
  "it": "Una casa chiusa ti stringe intorno — polvere, silenzio, freddo vecchio, un luogo dove nulla sembra vivo. Poi lo senti: un respiro, debole e vicino, dalla stanza in fondo. Qualcuno è vivo qui, dopotutto.",
  "de": "Ein verschlossenes Haus umfängt dich – Staub, Stille, alte Kälte, ein Ort, an dem nichts mehr lebendig scheint. Dann hörst du es: ein Atmen, schwach und nah, aus dem hinteren Zimmer. Hier lebt doch jemand.",
  "pt": "Uma casa fechada aperta-se à tua volta — pó, silêncio, frio antigo, um lugar onde nada parece vivo. Então ouve-lo: uma respiração, fraca e próxima, vinda do quarto do fundo. Afinal, há alguém vivo aqui.",
  "ru": "Запертый дом смыкается вокруг — пыль, тишина, застарелый холод, место, где ничто не кажется живым. И тут ты слышишь: дыхание, слабое и близкое, из дальней комнаты. Здесь всё-таки кто-то жив.",
  "ar": "يُطبق عليك بيتٌ مغلق — غبار، صمت، بردٌ قديم، مكانٌ لا يبدو فيه شيءٌ حيّاً. ثم تسمعه: أنفاسٌ خافتة قريبة، من الغرفة الخلفية. هناك من هو حيٌّ هنا، رغم كلّ شيء.",
  "zh": "一座封闭的屋子把你围住——尘土、寂静、陈年的寒意，一个仿佛毫无生气的地方。然后你听见了：微弱而很近的呼吸，从里屋传来。原来这里还有人活着。",
 },
 120: {
  "fr": "Vous avez tenu les feux toute la nuit le long des rangs. Au petit jour, le soleil passe la crête, le gel se lève, et les fleurs — toute une récolte — sont sauvées. Tout a tenu parce que vous êtes resté dans le froid à ne pas laisser mourir les feux. C'est toute l'histoire.",
  "es": "Mantuviste las hogueras toda la noche por los surcos. Al amanecer el sol asoma sobre la loma, la helada se levanta, y la flor —toda una cosecha— se salva. Todo salió adelante porque te quedaste en el frío y no dejaste morir el fuego. Eso es todo.",
  "it": "Hai tenuto i fuochi tutta la notte lungo i filari. All'alba il sole valica il crinale, il gelo si leva, e i fiori — un intero raccolto — ce la fanno. Tutto ha retto perché sei rimasto al freddo a non lasciar morire i fuochi. È tutto qui.",
  "de": "Du hast die Feuer die ganze Nacht entlang der Reihen gehalten. Im Morgenlicht steigt die Sonne über den Kamm, der Frost hebt sich, und die Blüte – eine ganze Ernte – kommt durch. Alles kam durch, weil du in der Kälte bliebst und die Feuer nicht sterben ließt. Das ist das Ganze.",
  "pt": "Mantiveste as fogueiras toda a noite ao longo das fileiras. Ao amanhecer o sol passa o cume, a geada levanta, e a flor — toda uma colheita — resiste. Tudo resistiu porque ficaste no frio e não deixaste morrer o fogo. É tudo.",
  "ru": "Ты держал костры всю ночь вдоль рядов. На рассвете солнце выходит из-за гребня, иней отступает, и цвет — весь урожай года — выживает. Всё уцелело потому, что ты остался на холоде и не дал кострам погаснуть. Вот и всё.",
  "ar": "أبقيت النيران مشتعلة طوال الليل على امتداد الصفوف. عند أول الضوء تطلع الشمس فوق الحافة، ويرتفع الصقيع، ويصمد الزهر — محصول عامٍ كامل. صمد كلّ شيء لأنك بقيت في البرد ولم تدع النيران تموت. هذا كلّ شيء.",
  "zh": "你守着火堆，沿着一排排烧了整整一夜。天一亮，太阳越过山脊，霜退了，花——整整一年的收成——保住了。一切都挺了过来，只因你守在寒夜里，不让火熄。这就是全部。",
 },
 121: {
  "fr": "Vous avez répondu à la lumière que nul ne s'expliquait. Vous avez trouvé Wren, perdu et gelé dans les rangs du fond, et l'avez réchauffé juste à temps. Et ce n'est pas qu'une vie sauvée : Wren est le petit-enfant d'Edith. Une porte fermée depuis des années se rouvre, là, dans l'aube grise.",
  "es": "Respondiste a la luz que nadie sabía explicar. Encontraste a Wren, perdido y helado entre los surcos del fondo, y lo calentaste justo a tiempo. Y no fue solo una vida salvada: Wren es el nieto de Edith. Una puerta cerrada durante años vuelve a abrirse, allí, en el alba gris.",
  "it": "Hai risposto alla luce che nessuno sapeva spiegare. Hai trovato Wren, perduto e gelato tra i filari in fondo, e l'hai riscaldato appena in tempo. E non è solo una vita salvata: Wren è il nipote di Edith. Una porta chiusa da anni si riapre, lì, nell'alba grigia.",
  "de": "Du hast dem Licht geantwortet, das sich niemand erklären konnte. Du fandest Wren, verloren und durchfroren in den hinteren Reihen, und wärmtest es gerade noch rechtzeitig. Und es war mehr als ein gerettetes Leben: Wren ist Ediths Enkelkind. Eine seit Jahren verschlossene Tür geht wieder auf, dort im grauen Morgen.",
  "pt": "Respondeste à luz que ninguém sabia explicar. Encontraste Wren, perdido e gelado entre as fileiras do fundo, e aqueceste-o mesmo a tempo. E não foi só uma vida salva: Wren é o neto de Edith. Uma porta fechada há anos volta a abrir-se, ali, na madrugada cinzenta.",
  "ru": "Ты откликнулся на свет, который никто не мог объяснить. Ты нашёл Рена, заблудившегося и замёрзшего в дальних рядах, и согрел его как раз вовремя. И это не одна спасённая жизнь: Рен — внук Эдит. Дверь, затворённая годами, снова открывается там, в сером рассвете.",
  "ar": "استجبت للضوء الذي لم يستطع أحدٌ تفسيره. وجدت رِن ضائعاً متجمّداً بين الصفوف البعيدة، ودفّأته في الوقت المناسب تماماً. ولم تكن حياةً واحدة فحسب: رِن حفيد إديث. بابٌ أُغلق سنين يُفتح من جديد، هناك في الفجر الرمادي.",
  "zh": "你回应了那道谁也说不清的光。你在尽头的果行间找到了迷路冻僵的雷恩，赶在最后关头把他暖了过来。而且救下的不止一条命：雷恩是伊迪丝的孙辈。一扇关了多年的门，正在灰蒙蒙的黎明里重新打开。",
 },
 122: {
  "fr": "Il n'y a pas eu d'acte héroïque isolé — il y a eu mieux. Vous avez transformé un village endormi en gens munis de torches dans chaque rang, et ensemble ils ont traversé la nuit. Personne n'y a été laissé seul. Voilà, au fond, ce que peut être un village.",
  "es": "No hubo un único acto heroico: hubo algo mejor. Convertiste un pueblo dormido en gente con antorchas en cada surco, y juntos sacaron la noche adelante. Nadie quedó solo en ella. Eso, al final, es lo que puede ser un pueblo.",
  "it": "Non c'è stato un singolo gesto eroico — c'è stato qualcosa di meglio. Hai trasformato un villaggio addormentato in gente con le torce lungo ogni filare, e insieme hanno portato a termine la notte. Nessuno è stato lasciato solo. Questo, in fondo, è ciò che un villaggio può essere.",
  "de": "Es gab keine einzelne Heldentat – es gab etwas Besseres. Du hast aus einem schlafenden Dorf Menschen mit Fackeln in jeder Reihe gemacht, und gemeinsam brachten sie die Nacht durch. Niemand blieb allein darin. Das ist am Ende, was ein Dorf sein kann.",
  "pt": "Não houve um único ato heroico — houve algo melhor. Transformaste uma aldeia adormecida em gente com archotes em cada fileira, e juntos levaram a noite até ao fim. Ninguém ficou sozinho nela. Isso, no fundo, é o que uma aldeia pode ser.",
  "ru": "Не было одного геройского поступка — было кое-что получше. Ты превратил спящую деревню в людей с факелами в каждом ряду, и вместе они одолели ночь. Никто не остался в ней один. Вот чем, в конце концов, может быть деревня.",
  "ar": "لم يكن هناك فعلٌ بطوليٌّ واحد — بل ما هو أفضل. حوّلت قريةً نائمة إلى أناسٍ بمشاعل في كلّ صفّ، وعبروا الليل معاً. لم يُترك أحدٌ وحده فيه. هذا، في النهاية، ما يمكن أن تكونه قرية.",
  "zh": "没有哪一桩孤身的壮举——有的是更好的东西。你把一个沉睡的村子，变成了每一排都举着火把的人，他们一起把这一夜挺了过来。没有谁被丢下独自面对。说到底，这就是一个村子可以成为的样子。",
 },
 123: {
  "fr": "Vous avez refusé l'arnaque — vu la combine de l'acheteur pour ce qu'elle était et tourné le dos. Vous avez gardé la tête froide et sauvé ce que vous pouviez par des moyens honnêtes. La nuit ne fut pas parfaite ; vous n'avez pas tout sauvé. Mais c'était propre, et propre, ça suffit.",
  "es": "Rechazaste el timo: viste la treta del comprador tal como era y le diste la espalda. Mantuviste la cabeza y salvaste lo que pudiste por medios decentes y honrados. No fue una noche perfecta; no lo salvaste todo. Pero lo hiciste limpio, y limpio basta.",
  "it": "Hai rifiutato la truffa — hai visto l'inganno del compratore per quello che era e gli hai voltato le spalle. Hai tenuto la testa e salvato ciò che potevi con mezzi onesti. Non è stata una notte perfetta; non hai salvato tutto. Ma l'hai fatto pulito, e pulito basta.",
  "de": "Du hast den Betrug abgelehnt – den Trick des Aufkäufers durchschaut und ihm den Rücken gekehrt. Du hast einen klaren Kopf behalten und mit anständigen Mitteln gerettet, was du konntest. Keine perfekte Nacht; du hast nicht alles gerettet. Aber du hast es sauber gemacht, und sauber genügt.",
  "pt": "Recusaste a vigarice — viste o truque do comprador tal como era e viraste-lhe as costas. Mantiveste a cabeça e salvaste o que pudeste por meios decentes e honestos. Não foi uma noite perfeita; não salvaste tudo. Mas fizeste-o limpo, e limpo chega.",
  "ru": "Ты отказался от аферы — распознал уловку скупщика и отвернулся от неё. Ты сохранил голову и спас, что смог, честными средствами. Ночь вышла не идеальной; ты спас не всё. Но сделал это чисто — а чистого достаточно.",
  "ar": "رفضت الخديعة — رأيت حيلة المشتري على حقيقتها وأدرت له ظهرك. حفظت رأسك وأنقذت ما استطعت بوسائل نزيهة شريفة. لم تكن ليلةً كاملة؛ لم تُنقذ الجميع. لكنك فعلتها نظيفة، والنظيف يكفي.",
  "zh": "你拒绝了这场骗局——看穿了买家的伎俩，转身走开。你稳住了心神，用正当、本分的办法尽力救下能救的。这一夜算不上圆满，你没能全保住。可你做得干净——干净，就够了。",
 },
 124: {
  "fr": "Vous n'avez pas sauvé tout le verger. Mais le voisin que vous aviez aidé plus tôt revient maintenant, et à vous deux vous sauvez les rangs proches et réchauffez Edith. Ce n'est pas la pleine victoire. Mais une bonté, on le voit, ne reste pas où on la laisse. Elle revient.",
  "es": "No salvaste todo el huerto. Pero el vecino al que ayudaste antes vuelve ahora, y entre los dos salváis los surcos cercanos y hacéis entrar en calor a Edith. No es la victoria entera. Pero una bondad, se ve, no se queda donde la dejas. Vuelve.",
  "it": "Non hai salvato tutto il frutteto. Ma il vicino che avevi aiutato prima torna ora, e insieme salvate i filari vicini e scaldate Edith. Non è la vittoria piena. Ma una gentilezza, si vede, non resta dove la lasci. Torna indietro.",
  "de": "Du hast nicht den ganzen Obstgarten gerettet. Aber der Nachbar, dem du vorhin geholfen hast, kommt jetzt zurück, und zu zweit rettet ihr die nahen Reihen und wärmt Edith. Nicht der volle Sieg. Aber eine Güte bleibt, wie man sieht, nicht, wo man sie lässt. Sie kommt zurück.",
  "pt": "Não salvaste o pomar inteiro. Mas o vizinho que ajudaste antes volta agora, e juntos salvam as fileiras próximas e aquecem a Edith. Não é a vitória completa. Mas uma bondade, vê-se, não fica onde a deixas. Volta.",
  "ru": "Ты спас не весь сад. Но сосед, которому ты помог раньше, теперь возвращается, и вдвоём вы спасаете ближние ряды и отогреваете Эдит. Это не полная победа. Но доброта, как видишь, не остаётся там, где её оставили. Она возвращается.",
  "ar": "لم تُنقذ البستان كلّه. لكن الجار الذي أعنته سابقاً يعود الآن، فتُنقذان معاً الصفوف القريبة وتُدفّئان إديث. ليس النصر الكامل. لكن المعروف، كما يتبيّن، لا يبقى حيث تتركه. إنه يعود.",
  "zh": "你没能保住整片果园。但先前你帮过的那位邻居此刻回来了，两人一起救下近处的几排，把伊迪丝暖了过来。这不是完完全全的胜利。可善意，原来并不停在你搁下它的地方。它会绕回来。",
 },
 125: {
  "fr": "Vous avez donné votre manteau et votre combustible à plus démuni que vous, et vous finissez la nuit transi. Vous n'avez pas tout sauvé. Mais vous n'êtes pas seul, ni personne de ceux que vous avez croisés. Quelque chose a changé en silence dans le village. C'est un début, pas un sauvetage.",
  "es": "Diste tu abrigo y tu combustible a quien tenía menos, y terminas la noche helado. No lo salvaste todo. Pero no estás solo, ni lo está nadie de los que encontraste. Algo ha cambiado en silencio en el pueblo. Es un comienzo, no un rescate.",
  "it": "Hai dato il tuo cappotto e il tuo combustibile a chi aveva meno, e finisci la notte intirizzito. Non hai salvato tutto. Ma non sei solo, né lo è nessuno di quelli che hai incontrato. Qualcosa è cambiato in silenzio nel villaggio. È un inizio, non un salvataggio.",
  "de": "Du hast deinen Mantel und deinen Brennstoff an Ärmere verschenkt und beendest die Nacht durchgefroren. Du hast nicht alles gerettet. Aber du bist nicht allein, und niemand, dem du begegnet bist, ist es. Etwas hat sich im Dorf still verschoben. Ein Anfang, keine Rettung.",
  "pt": "Deste o teu casaco e o teu combustível a quem tinha menos, e acabas a noite gelado. Não salvaste tudo. Mas não estás sozinho, nem ninguém que encontraste lá fora. Algo mudou em silêncio na aldeia. É um começo, não um salvamento.",
  "ru": "Ты отдал своё пальто и топливо тем, у кого было меньше, и заканчиваешь ночь продрогшим. Ты спас не всё. Но ты не один — и никто из тех, кого ты встретил. Что-то тихо сдвинулось в деревне. Это начало, а не спасение.",
  "ar": "أعطيت معطفك ووقودك لمن هم أقلّ منك، وتُنهي الليلة متجمّداً. لم تُنقذ كلّ شيء. لكنك لست وحدك، ولا أحدٌ ممّن لقيتهم في الخارج. شيءٌ ما تحوّل في القرية بهدوء. إنها بداية، لا إنقاذ.",
  "zh": "你把自己的外套和燃料给了比你更缺的人，自己冻了一整夜。你没能全保住。可你并不孤单，你在外头遇见的那些人也不孤单。村子里，有些东西悄悄挪动了。这是个开头，不是一次挽救。",
 },
 126: {
  "fr": "Vous passez de justesse le pire. L'air immobile tourne enfin, et une aube pâle sauve une partie des fleurs. Ce n'est pas un triomphe, et nul n'en fera une chanson. Mais vous avez traversé la nuit — et au fond, c'est un soulagement en soi.",
  "es": "Pasas a duras penas lo peor. El aire quieto cambia al fin, y un amanecer pálido salva parte de la flor. No es un triunfo, y nadie hará una canción de ello. Pero cruzaste la noche, y al final eso ya es un alivio en sí mismo.",
  "it": "Superi per un soffio il peggio. L'aria immobile gira infine, e un'alba pallida salva parte dei fiori. Non è un trionfo, e nessuno ne farà una canzone. Ma hai attraversato la notte — e in fondo è già un sollievo di per sé.",
  "de": "Du kommst mit knapper Not durch das Schlimmste. Die stille Luft dreht endlich, und ein blasser Morgen rettet einen Teil der Blüte. Kein Triumph, und niemand wird ein Lied daraus machen. Aber du bist durch die Nacht gekommen – und das ist am Ende schon eine Erleichterung für sich.",
  "pt": "Passas à justa o pior. O ar parado muda por fim, e uma madrugada pálida salva parte da flor. Não é um triunfo, e ninguém fará uma canção disso. Mas atravessaste a noite — e, no fim, isso já é um alívio por si só.",
  "ru": "Ты едва-едва проходишь худшее. Застывший воздух наконец сдвигается, и бледный рассвет спасает часть цвета. Это не триумф, и о нём не сложат песен. Но ты прошёл сквозь ночь — а это, в конце концов, уже само по себе облегчение.",
  "ar": "تتجاوز الأسوأ بالكاد. يتحرّك الهواء الساكن أخيراً، ويُنقذ فجرٌ شاحب جزءاً من الزهر. ليس انتصاراً، ولن يُنشد فيه أحد. لكنك عبرت الليل — وهذا، في النهاية، راحةٌ بحدّ ذاته.",
  "zh": "你堪堪熬过了最糟的时候。凝滞的空气终于转了，一抹苍白的黎明救下了一部分花。这算不上凯旋，没人会为它唱歌。但你撑过了这一夜——到头来，这本身就是一种宽慰。",
 },
 127: {
  "fr": "Vous n'avez pas tout sauvé. Mais le village vous a vu parmi les arbres quand d'autres restaient au lit — vous a vu essayer, la pire nuit de l'année. À partir de ce soir, vous êtes quelqu'un que ce lieu connaît. Et ce n'est pas rien.",
  "es": "No lo salvaste todo. Pero el pueblo te vio entre los árboles cuando otros se quedaban en la cama — te vio intentarlo, en la peor noche del año. Desde esta noche, eres alguien que este lugar conoce. Y eso no es nada poco.",
  "it": "Non hai salvato tutto. Ma il villaggio ti ha visto tra gli alberi quando altri restavano a letto — ti ha visto provarci, nella notte peggiore dell'anno. Da stanotte, sei qualcuno che questo posto conosce. E non è poco.",
  "de": "Du hast nicht alles gerettet. Aber das Dorf hat dich zwischen den Bäumen gesehen, als andere im Bett blieben – hat dich es versuchen sehen, in der schlimmsten Nacht des Jahres. Von heute an bist du jemand, den dieser Ort kennt. Und das ist nicht nichts.",
  "pt": "Não salvaste tudo. Mas a aldeia viu-te entre as árvores quando outros ficaram na cama — viu-te tentar, na pior noite do ano. A partir desta noite, és alguém que este lugar conhece. E isso não é nada pouco.",
  "ru": "Ты спас не всё. Но деревня видела тебя среди деревьев, когда другие остались в постели, — видела, как ты пытался, в худшую ночь года. С этой ночи ты — тот, кого здесь знают. И это не пустяк.",
  "ar": "لم تُنقذ كلّ شيء. لكن القرية رأتك بين الأشجار حين لزم غيرك الفراش — رأتك تحاول، في أسوأ ليالي العام. من هذه الليلة، صرت شخصاً يعرفه هذا المكان. وهذا ليس بالقليل.",
  "zh": "你没能全保住。可当别人还躺在床上时，村子看见了你在树间——看见你在一年里最糟的一夜里拼过。从今夜起，你成了这地方记得的人。这，并非微不足道。",
 },
 128: {
  "fr": "Vous avez accepté le marché de l'acheteur, et au matin le verger n'est plus à Edith pour être sauvé. Le gel a fait le reste. Le chèque dans votre poche est froid, et le sol aussi au petit jour. Vous n'oublierez pas de sitôt comment vous l'avez gagné.",
  "es": "Aceptaste el trato del comprador, y por la mañana el huerto ya no es de Edith para salvarlo. La helada hizo el resto. El cheque en tu bolsillo está frío, y también lo está la tierra al amanecer. No olvidarás pronto cómo llegaste a ganarlo.",
  "it": "Hai accettato il patto del compratore, e al mattino il frutteto non è più di Edith da salvare. Il gelo ha fatto il resto. L'assegno in tasca è freddo, e così è il terreno all'alba. Non dimenticherai presto come sei arrivato a guadagnarlo.",
  "de": "Du hast den Handel des Aufkäufers angenommen, und am Morgen gehört der Obstgarten nicht mehr Edith, um ihn zu retten. Den Rest hat der Frost getan. Der Scheck in deiner Tasche ist kalt, und der Boden am Morgen auch. Du wirst nicht so bald vergessen, wie du ihn verdient hast.",
  "pt": "Aceitaste o acordo do comprador, e de manhã o pomar já não é da Edith para salvar. A geada fez o resto. O cheque no teu bolso está frio, e o chão também ao amanhecer. Não esquecerás tão cedo como vieste a ganhá-lo.",
  "ru": "Ты принял сделку скупщика, и к утру сад уже не Эдит, чтобы его спасать. Остальное доделал мороз. Чек у тебя в кармане холоден, и земля к утру тоже. Ты не скоро забудешь, как его заработал.",
  "ar": "قبلت صفقة المشتري، وبحلول الصباح لم يعُد البستان مِلك إديث لتُنقذه. وأتمّ الصقيع الباقي. الشيك في جيبك بارد، والأرض كذلك عند الفجر. لن تنسى قريباً كيف كسبته.",
  "zh": "你接下了买家的交易，到早上，这片果园已不再是伊迪丝能去保的了。其余的，霜替你做完了。你口袋里的支票冰冷，天亮时的土地也一样冷。你不会很快忘记自己是怎么挣下它的。",
 },
 129: {
  "fr": "L'étang gelé était un piège, comme Jack Hale l'avait prévenu. Vous êtes passé au travers dans le noir, et cela a pris toute la nuit. Vous vous traînez dehors, gelé et tremblant, et atteignez les rangs du fond bien trop tard. La glace vous a coûté tout ce que le raccourci promettait de sauver.",
  "es": "El estanque helado era una trampa, tal como advirtió Jack Hale. Lo rompiste en la oscuridad, y eso se llevó toda la noche. Sales a rastras, helado y temblando, y llegas a los surcos del fondo demasiado tarde. El hielo te costó todo lo que el atajo prometía salvar.",
  "it": "Lo stagno gelato era una trappola, proprio come Jack Hale aveva avvertito. Ci sei sprofondato nel buio, e ci è voluta tutta la notte. Ti trascini fuori, gelato e tremante, e raggiungi i filari in fondo troppo tardi. Il ghiaccio ti è costato tutto ciò che la scorciatoia prometteva di salvare.",
  "de": "Der zugefrorene Teich war eine Falle, genau wie Jack Hale gewarnt hatte. Du bist im Dunkeln eingebrochen, und es hat die ganze Nacht gekostet. Du schleppst dich heraus, durchgefroren und zitternd, und erreichst die hinteren Reihen viel zu spät. Das Eis kostete dich alles, was die Abkürzung zu retten versprach.",
  "pt": "O lago gelado era uma armadilha, tal como o Jack Hale avisou. Caíste através dele no escuro, e isso levou a noite toda. Arrastas-te para fora, gelado e a tremer, e chegas às fileiras do fundo tarde demais. O gelo custou-te tudo o que o atalho prometia salvar.",
  "ru": "Замёрзший пруд был ловушкой, как и предупреждал Джек Хейл. Ты провалился под лёд в темноте, и это отняло всю ночь. Ты выползаешь, промёрзший и дрожащий, и добираешься до дальних рядов слишком поздно. Лёд стоил тебе всего, что обещал спасти короткий путь.",
  "ar": "كانت البركة المتجمّدة فخّاً، تماماً كما حذّر جاك هيل. سقطت من خلالها في الظلام، فابتلع ذلك الليل كلّه. تجرّ نفسك خارجاً، متجمّداً مرتجفاً، وتبلغ الصفوف البعيدة بعد فوات الأوان بكثير. كلّفك الجليد كلّ ما وعد به الطريق المختصر أن يُنقذه.",
  "zh": "那结冰的池塘是个陷阱，正如杰克·黑尔的警告。你在黑暗里踩穿了冰，这一下耗掉了整夜。你挣扎着爬出来，冻僵发抖，赶到尽头的果行时已太迟。这层冰，叫你赔上了抄近路本想保住的一切。",
 },
 130: {
  "fr": "Vous avez passé la nuit sur les mauvaises choses, et les feux sont restés éteints trop longtemps. À l'aube, la fleur est noire sur chaque arbre, et la récolte de l'année est perdue. Vous êtes bien sorti dans le froid. Mais vous n'avez pas tenu les feux quand cela comptait vraiment.",
  "es": "Pasaste la noche en lo que no debías, y los fuegos quedaron apagados demasiado tiempo. Al alba, la flor está negra en cada árbol, y la cosecha del año se pierde. Sí saliste al frío. Pero no sostuviste los fuegos cuando de verdad importaba.",
  "it": "Hai passato la notte sulle cose sbagliate, e i fuochi sono rimasti spenti troppo a lungo. All'alba il fiore è nero su ogni albero, e il raccolto dell'anno è perduto. Sei uscito, sì, nel freddo. Ma non hai tenuto i fuochi quando contava davvero.",
  "de": "Du hast die Nacht mit den falschen Dingen verbracht, und die Feuer blieben zu lange aus. Im Morgengrauen ist die Blüte an jedem Baum schwarz, und die Jahresernte ist verloren. Du bist zwar in die Kälte hinausgegangen. Aber du hast die Feuer nicht gehalten, als es wirklich zählte.",
  "pt": "Passaste a noite nas coisas erradas, e os fogos ficaram apagados demasiado tempo. Ao amanhecer, a flor está negra em cada árvore, e a colheita do ano perdeu-se. Saíste, sim, para o frio. Mas não seguraste os fogos quando realmente importava.",
  "ru": "Ты потратил ночь не на то, и костры слишком долго стояли погасшими. На рассвете цвет почернел на каждом дереве, и урожай года потерян. Ты ведь вышел на холод. Но не удержал костры тогда, когда это по-настоящему решало.",
  "ar": "أمضيت الليل في الأمور الخاطئة، وبقيت النيران مُطفأة وقتاً أطول من اللازم. عند الفجر، الزهر أسودُ على كلّ شجرة، ومحصول العام ضائع. لقد خرجت بالفعل إلى البرد. لكنك لم تُبقِ النيران حين كان ذلك يُهمّ حقّاً.",
  "zh": "你把一夜花在了不该花的地方，火堆熄得太久。天亮时，每棵树上的花都黑了，一年的收成没了。你确实走进了寒夜。可在真正要紧的时候，你没把火守住。",
 },
 131: {
  "fr": "Au bout du compte, vous êtes resté à l'intérieur, au chaud et en sûreté. Vous vous êtes dit que le gel était trop fort, que ce n'était pas votre affaire, que l'aide viendrait à l'aube. Tout cela était vrai. Et toute la nuit, dans les rangs, les feux sont restés éteints. Rien de mal ne vous est arrivé. Vous y penserez très, très longtemps.",
  "es": "Al final, te quedaste dentro, caliente y a salvo. Te dijiste que la helada era demasiado dura, que no era asunto tuyo, que la ayuda llegaría al alba. Todo eso era cierto. Y toda la noche, en los surcos, los fuegos quedaron apagados. No te pasó nada malo. Lo pensarás durante mucho, mucho tiempo.",
  "it": "Alla fine sei rimasto dentro, al caldo e al sicuro. Ti sei detto che il gelo era troppo duro, che non era affar tuo, che l'aiuto sarebbe arrivato all'alba. Tutto vero. E per tutta la notte, lungo i filari, i fuochi sono rimasti spenti. Non ti è successo nulla di male. Ci penserai per molto, molto tempo.",
  "de": "Am Ende bist du drinnen geblieben, warm und sicher. Du hast dir gesagt, der Frost sei zu hart, es sei nicht deine Sache, Hilfe komme im Morgengrauen. Das alles stimmte. Und die ganze Nacht blieben draußen in den Reihen die Feuer dunkel. Dir ist nichts Schlimmes geschehen. Du wirst sehr, sehr lange daran denken.",
  "pt": "No fim, ficaste lá dentro, quente e em segurança. Disseste a ti mesmo que a geada era dura demais, que não era problema teu, que a ajuda viria ao amanhecer. Tudo isso era verdade. E toda a noite, nas fileiras, os fogos ficaram apagados. Nada de mau te aconteceu. Vais pensar nisso durante muito, muito tempo.",
  "ru": "В конце концов ты остался внутри, в тепле и безопасности. Ты говорил себе, что мороз слишком силён, что это не твоё дело, что помощь придёт на рассвете. Всё это было правдой. И всю ночь там, в рядах, костры стояли тёмными. С тобой ничего плохого не случилось. Ты будешь думать об этом очень, очень долго.",
  "ar": "في النهاية بقيت في الداخل، دافئاً آمناً. قلت لنفسك إنّ الصقيع أقسى من أن يُقاوَم، وإنّ الأمر ليس شأنك، وإنّ العون سيأتي عند الفجر. كلّ ذلك كان صحيحاً. وطوال الليل، في الصفوف، بقيت النيران مُطفأة. لم يُصبك سوء. ستفكّر في ذلك وقتاً طويلاً، طويلاً.",
  "zh": "到最后，你留在了屋里，又暖又安全。你对自己说：霜太重了，这不是你的事，天亮自会有人来。这些话都没错。而整整一夜，外头一排排间，火堆一直是灭的。你毫发无伤。这件事，你会想上很久，很久。",
 },
}

def main():
    for lang in LANGS:
        data = {str(nid): G[nid][lang] for nid in G if lang in G[nid]}
        path = os.path.join(OUT, f"{lang}.json")
        json.dump(data, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
        print(f"wrote {path}: {len(data)} passages")


if __name__ == "__main__":
    main()
