#!/usr/bin/env python3
"""Per-passage clue text (the "See the meaning" gist) for book 3, First Light.

Scoped per book: content/gist/first-light/<lang>.json → {"<nodeId>": "meaning"}. Offered
"where needed" (the opening, the major forks, the con, the neighbour, the shortcut, the giving,
the mystery, and all 12 endings). fr/es/it/de/pt author-vouched; ru/ar/zh native review:
complete. Run: python3 scripts/build_gists_ep03.py
"""
import json, os
LANGS = ["fr", "es", "it", "de", "pt", "ru", "ar", "zh"]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "first-light")
os.makedirs(OUT, exist_ok=True)

G = {
 1: {
  "fr": "C'est la nuit la plus froide de l'hiver et toute la ville est coupée de courant. Vous pensez à la vieille Mme Ada, en haut de la colline : fragile, la poitrine faible, et son seul chauffage est électrique.",
  "es": "Es la noche más fría del invierno y toda la ciudad se queda sin electricidad. Piensas en la anciana Sra. Ada, colina arriba: frágil, con el pecho débil, y su única calefacción es eléctrica.",
  "it": "È la notte più fredda dell'inverno e tutta la città resta senza corrente. Pensi alla vecchia signora Ada, in cima alla collina: fragile, col petto debole, e il suo unico riscaldamento è elettrico.",
  "de": "Es ist die kälteste Nacht des Winters, und in der ganzen Stadt fällt der Strom aus. Du denkst an die alte Frau Ada oben am Hügel: gebrechlich, mit schwacher Brust, und ihre einzige Heizung läuft mit Strom.",
  "pt": "É a noite mais fria do inverno e toda a cidade fica sem energia. Pensas na velha Sra. Ada, no alto da colina: frágil, com o peito fraco, e o seu único aquecedor é elétrico.",
  "ru": "Самая холодная ночь зимы, и во всём городе гаснет электричество. Ты думаешь о старой миссис Аде на холме: она слаба, у неё больная грудь, а её единственный обогреватель — электрический.",
  "ar": "إنها أبرد ليالي الشتاء، وتنقطع الكهرباء عن المدينة كلّها. تتذكّر العجوز السيدة آدا أعلى التلّة: واهنة، صدرها ضعيف، ومدفأتها الوحيدة تعمل بالكهرباء.",
  "zh": "这是冬天最冷的一夜，全镇的电一下子全断了。你想起山上的老太太阿达：身子弱、胸口不好，而她唯一的取暖器是用电的。",
 },
 9: {
  "fr": "M. Okafor a ouvert sa boutique à la bougie et vous offre un poêle à pétrole, des couvertures, un thermos : « Paie-moi quand le courant reviendra. » Une vraie bonté.",
  "es": "El Sr. Okafor abrió su tienda a la luz de las velas y te ofrece una estufa de parafina, mantas, un termo: «Págame cuando vuelva la luz». Bondad de verdad.",
  "it": "Il signor Okafor ha aperto il negozio a lume di candela e ti offre una stufa a cherosene, coperte, un thermos: «Pagami quando torna la corrente». Vera gentilezza.",
  "de": "Herr Okafor hat seinen Laden bei Kerzenlicht geöffnet und bietet dir einen Petroleumofen, Decken, eine Thermoskanne an: „Zahl, wenn der Strom zurück ist.“ Echte Güte.",
  "pt": "O Sr. Okafor abriu a loja à luz das velas e oferece-te um aquecedor a petróleo, cobertores, um termo: «Paga-me quando a luz voltar». Bondade a sério.",
  "ru": "Мистер Окафор открыл лавку при свечах и предлагает тебе керосиновый обогреватель, одеяла, термос: «Заплатишь, когда дадут свет». Настоящая доброта.",
  "ar": "فتح السيد أوكافور دكّانه على ضوء الشموع ويعرض عليك مدفأة كيروسين وبطانيات وقارورة ساخنة: «ادفع لي حين تعود الكهرباء». لطفٌ حقيقي.",
  "zh": "奥卡福先生点着蜡烛开了店，给你煤油炉、毯子、热水瓶：“来电了再给我钱。”是真正的好心。",
 },
 10: {
  "fr": "Vous frappez chez une voisine : Mme Pratt, âgée, seule et visiblement effrayée. « Je n'arrive pas à me réchauffer, et je ne vois rien. » Vous avez loin à aller, mais c'est vous qu'elle appelle.",
  "es": "Llamas a casa de una vecina: la Sra. Pratt, anciana, sola y claramente asustada. «No consigo entrar en calor, y no veo nada». Tienes mucho camino, pero es a ti a quien pide ayuda.",
  "it": "Bussi da una vicina: la signora Pratt, anziana, sola e chiaramente spaventata. «Non riesco a scaldarmi, e non ci vedo nulla». Hai molta strada, ma è te che sta chiedendo.",
  "de": "Du klopfst bei einer Nachbarin: Frau Pratt, alt, allein und sichtlich verängstigt. „Mir wird nicht warm, und ich sehe nichts.“ Du hast noch weit zu gehen, aber dich bittet sie jetzt.",
  "pt": "Bates à porta de uma vizinha: a Sra. Pratt, idosa, sozinha e visivelmente assustada. «Não consigo aquecer-me, e não vejo nada». Tens muito caminho, mas é a ti que ela pede.",
  "ru": "Ты стучишь к соседке: миссис Пратт, старая, одинокая, явно напуганная. «Я не могу согреться и ничего не вижу». Тебе ещё далеко идти, но просит она — тебя.",
  "ar": "تطرق باب جارة: السيدة برات، مسنّة ووحيدة وخائفة بوضوح. «لا أستطيع أن أدفأ، ولا أرى شيئاً». أمامك طريق طويل، لكنها تطلب منك أنت.",
  "zh": "你敲开一位邻居的门：普拉特太太，年老、独居，明显受了惊。“我暖不起来，也什么都看不见。”你今晚还有很远的路，但此刻向你求助的是她。",
 },
 12: {
  "fr": "Vous allez de porte en porte parler d'Ada, du froid et de la longue nuit, en demandant de l'aide. Certains aideront, d'autres non — mais il faut demander quand même.",
  "es": "Vas de puerta en puerta hablando de Ada, del frío y de la larga noche, pidiendo ayuda. Algunos ayudarán, otros no, pero hay que pedir de todos modos.",
  "it": "Vai di porta in porta a parlare di Ada, del freddo e della lunga notte, chiedendo aiuto. Alcuni aiuteranno, altri no, ma bisogna chiedere lo stesso.",
  "de": "Du gehst von Tür zu Tür, erzählst von Ada, der Kälte und der langen Nacht und bittest um Hilfe. Manche helfen, manche nicht – aber fragen musst du trotzdem.",
  "pt": "Vais de porta em porta a falar da Ada, do frio e da longa noite, pedindo ajuda. Alguns ajudarão, outros não, mas tens de pedir à mesma.",
  "ru": "Ты ходишь от двери к двери, рассказываешь про Аду, про холод и долгую ночь, просишь помочь. Кто-то поможет, кто-то нет — но просить всё равно надо.",
  "ar": "تذهب من باب إلى باب تحدّث الناس عن آدا والبرد والليلة الطويلة، طالباً العون. بعضهم سيساعد وبعضهم لا، لكن عليك أن تطلب على أي حال.",
  "zh": "你挨家挨户地敲门，说起阿达、严寒和漫漫长夜，请人帮忙。有人会帮，有人不会——但你还是得开口。",
 },
 27: {
  "fr": "La rivière gelée, en bas de la colline, ferait gagner beaucoup de temps. Mais Okafor a prévenu : la glace semble solide et ne l'est pas — dessous coule une eau noire et glacée. Le temps ou la sécurité.",
  "es": "El río helado, al pie de la colina, ahorraría mucho tiempo. Pero Okafor avisó: el hielo parece firme y no lo es; debajo corre agua negra y helada. El tiempo o la seguridad.",
  "it": "Il fiume gelato, ai piedi della collina, farebbe risparmiare molto tempo. Ma Okafor ha avvertito: il ghiaccio sembra solido e non lo è — sotto scorre acqua nera e gelida. Il tempo o la sicurezza.",
  "de": "Der zugefrorene Fluss am Fuß des Hügels würde viel Zeit sparen. Aber Okafor hat gewarnt: Das Eis sieht fest aus und ist es nicht – darunter fließt schwarzes, eiskaltes Wasser. Zeit oder Sicherheit.",
  "pt": "O rio gelado, ao pé da colina, pouparia muito tempo. Mas o Okafor avisou: o gelo parece firme e não é — por baixo corre água negra e gelada. O tempo ou a segurança.",
  "ru": "Замёрзшая река у подножия холма сильно сократила бы путь. Но Окафор предупредил: лёд кажется крепким, а он не крепкий — под ним чёрная ледяная вода. Время или безопасность.",
  "ar": "النهر المتجمّد أسفل التلّة يوفّر وقتاً كثيراً. لكن أوكافور حذّر: الجليد يبدو صلباً وليس كذلك — تحته ماء أسود متجمّد. الوقت أو السلامة.",
  "zh": "山脚那条冻结的河能省下很多时间。但奥卡福警告过：冰看着结实，其实不然——底下是漆黑冰冷的河水。要么抢时间，要么保平安。",
 },
 32: {
  "fr": "Dans une maison froide et sombre, une famille se serre : un bébé pleure, une seule bougie, aucune chaleur. Vous n'avez qu'une couverture, destinée à Ada.",
  "es": "En una casa fría y oscura, una familia se acurruca: un bebé llora, una sola vela, nada de calor. Solo tienes una manta, que era para Ada.",
  "it": "In una casa fredda e buia, una famiglia è stretta insieme: un neonato piange, una sola candela, nessun calore. Hai una sola coperta, destinata ad Ada.",
  "de": "In einem kalten, dunklen Haus drängt sich eine Familie zusammen: ein Baby weint, eine einzige Kerze, keine Wärme. Du hast nur eine Decke, die für Ada gedacht war.",
  "pt": "Numa casa fria e escura, uma família aconchega-se: um bebé chora, uma única vela, nenhum calor. Só tens um cobertor, que era para a Ada.",
  "ru": "В холодном тёмном доме сгрудилась семья: плачет младенец, одна свеча, ни капли тепла. У тебя лишь одно одеяло — оно предназначалось Аде.",
  "ar": "في بيت بارد مظلم تتلاصق عائلة: رضيعٌ يبكي، شمعة واحدة، ولا دفء. ليس معك إلا بطانية واحدة، كانت لآدا.",
  "zh": "在一间又冷又黑的屋子里，一家人挤作一团：婴儿哭个不停，只有一支蜡烛，没有一丝暖气。你只有一条毯子，本是留给阿达的。",
 },
 40: {
  "fr": "L'homme de la camionnette vous sourit : il « peut aider » — poêles, carburant, un groupe électrogène, tout de suite. Voix chaleureuse, prix sûrement exorbitants.",
  "es": "El hombre de la furgoneta te sonríe: «puede ayudar» con estufas, combustible, un generador, ahora mismo. Voz cálida, precios seguramente abusivos.",
  "it": "L'uomo del furgone ti sorride: «può aiutare» con stufe, carburante, un generatore, subito. Voce calda, prezzi di sicuro esorbitanti.",
  "de": "Der Mann vom Lieferwagen lächelt dich an: Er „kann helfen“ – Öfen, Brennstoff, ein Generator, sofort. Warme Stimme, sicher Wucherpreise.",
  "pt": "O homem da carrinha sorri-te: «pode ajudar» com aquecedores, combustível, um gerador, já. Voz calorosa, preços de certeza exorbitantes.",
  "ru": "Мужчина из фургона улыбается: он «может помочь» — обогреватели, топливо, генератор, прямо сейчас. Голос тёплый, цены наверняка грабительские.",
  "ar": "يبتسم لك رجل الشاحنة: «يمكنه المساعدة» — مدافئ، وقود، مولّد، الآن. صوته دافئ، وأسعاره بلا شكّ فاحشة.",
  "zh": "货车男人朝你笑：他“能帮忙”——取暖器、燃料、发电机，马上就有。语气热络，价钱肯定是黑心价。",
 },
 41: {
  "fr": "Il annonce un prix cinq fois trop élevé, puis joue sur votre peur : « Ta Ada ne passera pas la nuit — combien vaut-elle pour toi ? » Un piège cruel et habile.",
  "es": "Dice un precio cinco veces más alto de lo justo y luego juega con tu miedo: «Tu Ada no pasará la noche, ¿cuánto vale para ti?». Una trampa cruel y astuta.",
  "it": "Dice un prezzo cinque volte troppo alto, poi gioca sulla tua paura: «La tua Ada non passerà la notte — quanto vale per te?». Una trappola crudele e astuta.",
  "de": "Er nennt einen fünffach überhöhten Preis und spielt dann mit deiner Angst: „Deine Ada übersteht die Nacht nicht – wie viel ist sie dir wert?“ Eine grausame, raffinierte Falle.",
  "pt": "Diz um preço cinco vezes acima do justo e depois joga com o teu medo: «A tua Ada não passa a noite — quanto vale ela para ti?». Uma armadilha cruel e astuta.",
  "ru": "Он называет цену впятеро выше справедливой, а потом играет на твоём страхе: «Твоя Ада не доживёт до утра — сколько она для тебя стоит?» Жестокая, хитрая ловушка.",
  "ar": "يطلب ثمناً أعلى بخمسة أضعاف، ثم يلعب على خوفك: «آدا لن تصمد الليلة — كم تساوي عندك؟». فخّ قاسٍ وماكر.",
  "zh": "他开出五倍的高价，又拿你的恐惧要挟：“你那位阿达熬不过今晚——她对你值多少钱？”一个残忍又狡猾的圈套。",
 },
 69: {
  "fr": "Cette maison glacée porte quarante ans de silence entre un frère et une sœur brouillés. Puis, de la pièce voisine, une respiration faible : quelqu'un de vivant, là, maintenant, qui a besoin de vous.",
  "es": "Esta casa helada guarda cuarenta años de silencio entre un hermano y una hermana enemistados. Entonces, del cuarto de al lado, una respiración débil: alguien vivo, ahí, ahora, que te necesita.",
  "it": "Questa casa gelata porta quarant'anni di silenzio tra un fratello e una sorella in rotta. Poi, dalla stanza accanto, un respiro debole: qualcuno di vivo, lì, ora, che ha bisogno di te.",
  "de": "Dieses eiskalte Haus trägt vierzig Jahre Schweigen zwischen einem zerstrittenen Bruder und einer Schwester. Dann, aus dem Nebenzimmer, ein schwacher Atem: jemand Lebendiges, dort, jetzt, der dich braucht.",
  "pt": "Esta casa gelada carrega quarenta anos de silêncio entre um irmão e uma irmã zangados. Então, do quarto ao lado, uma respiração fraca: alguém vivo, ali, agora, que precisa de ti.",
  "ru": "В этом ледяном доме — сорок лет молчания между поссорившимися братом и сестрой. И вдруг из соседней комнаты слабое дыхание: кто-то живой, здесь, сейчас, нуждается в тебе.",
  "ar": "هذا البيت المتجمّد يحمل أربعين عاماً من الصمت بين أخٍ وأختٍ تخاصما. ثم من الغرفة المجاورة يأتي نفَسٌ ضعيف: شخصٌ حيّ، هنا، الآن، يحتاج إليك.",
  "zh": "这间冰冷的屋子里，压着一对反目兄妹四十年的沉默。忽然，隔壁房间传来微弱的呼吸声：有个活生生的人，就在此刻，需要你。",
 },
 120: {
  "fr": "FIN (bonne) — Le chauffage a tenu toute la nuit, et Ada avec lui. À l'aube elle est au chaud, respire bien et vous gronde pour tant d'inquiétude. Elle est en vie parce que vous êtes sorti dans le froid.",
  "es": "FINAL (bueno) — La calefacción aguantó toda la noche, y Ada con ella. Al amanecer está caliente, respira bien y te riñe en broma por preocuparte. Está viva porque saliste al frío.",
  "it": "FINALE (buono) — Il riscaldamento ha tenuto tutta la notte, e Ada con esso. All'alba è al caldo, respira bene e ti rimprovera per esserti preoccupato. È viva perché sei uscito nel freddo.",
  "de": "ENDE (gut) — Die Heizung hielt die ganze Nacht, und Ada mit ihr. Im Morgengrauen ist sie warm, atmet leicht und schimpft scherzhaft über deine Sorge. Sie lebt, weil du hinaus in die Kälte gegangen bist.",
  "pt": "FIM (bom) — O aquecedor aguentou a noite toda, e a Ada com ele. Ao amanhecer está quente, respira bem e ralha contigo por teres ficado preocupado. Está viva porque saíste para o frio.",
  "ru": "КОНЦОВКА (хорошая) — Обогреватель продержался всю ночь, и Ада вместе с ним. На рассвете ей тепло, дышит легко и в шутку ворчит, что ты зря волновался. Она жива, потому что ты вышел в холод.",
  "ar": "النهاية (جيدة) — صمدت المدفأة الليل كله، وصمدت آدا معها. عند الفجر هي دافئة، تتنفّس بسهولة، وتعاتبك مازحةً على قلقك. هي حيّة لأنك خرجت إلى البرد.",
  "zh": "结局（好）——取暖器撑了一整夜，阿达也撑住了。天亮时她暖暖的，呼吸顺畅，还假装生气怪你瞎操心。她还活着，是因为你走进了寒夜。",
 },
 121: {
  "fr": "FIN (bonne, secrète) — Parce que vous avez suivi une lumière inexpliquée, M. Harrow est vivant ; à l'aube, vous l'amenez chez Ada. Un frère et une sœur, séparés depuis quarante ans, se retrouvent. Vous avez rendu deux personnes l'une à l'autre.",
  "es": "FINAL (bueno, secreto) — Porque seguiste una luz inexplicable, el Sr. Harrow está vivo; al amanecer lo llevas a casa de Ada. Un hermano y una hermana, cuarenta años separados, se reencuentran. Devolviste dos personas la una a la otra.",
  "it": "FINALE (buono, segreto) — Perché hai seguito una luce inspiegabile, il signor Harrow è vivo; all'alba lo porti da Ada. Un fratello e una sorella, divisi da quarant'anni, si ritrovano. Hai ridato due persone l'una all'altra.",
  "de": "ENDE (gut, geheim) — Weil du einem unerklärlichen Licht gefolgt bist, lebt Herr Harrow; im Morgengrauen bringst du ihn zu Ada. Ein Bruder und eine Schwester, vierzig Jahre getrennt, finden wieder zueinander. Du hast zwei Menschen einander zurückgegeben.",
  "pt": "FIM (bom, secreto) — Porque seguiste uma luz inexplicável, o Sr. Harrow está vivo; ao amanhecer levas-lo a casa da Ada. Um irmão e uma irmã, quarenta anos separados, reencontram-se. Devolveste duas pessoas uma à outra.",
  "ru": "КОНЦОВКА (хорошая, тайная) — Оттого что ты пошёл на необъяснимый свет, мистер Хэрроу жив; на рассвете ты приводишь его к дверям Ады. Брат и сестра, разлучённые сорок лет, встречаются вновь. Ты вернул двух людей друг другу.",
  "ar": "النهاية (جيدة، سرّية) — لأنك تبِعت ضوءاً لا يُفسَّر، السيد هارو حيّ؛ وعند الفجر تأخذه إلى باب آدا. أخٌ وأخت، فرّقهما أربعون عاماً، يلتقيان من جديد. أعدتَ شخصين أحدهما إلى الآخر.",
  "zh": "结局（好·隐藏）——因为你追着那道无法解释的光走去，哈罗先生得救了；灰蒙蒙的黎明里，你把他带到阿达门前。分离四十年的兄妹重逢。是你，把两个人重新交还给了彼此。",
 },
 122: {
  "fr": "FIN (bonne) — Vous n'avez jamais agi seul : au matin, la moitié de la rue est réveillée, des pièces chaudes s'allument sur toute la colline. Ada, Mme Pratt, la famille au bébé — tous au chaud, parce que vous avez frappé à la première porte.",
  "es": "FINAL (bueno) — Nunca lo hiciste solo: al amanecer, media calle está despierta y se encienden cuartos cálidos por toda la colina. Ada, la Sra. Pratt, la familia del bebé: todos calientes, porque llamaste a la primera puerta.",
  "it": "FINALE (buono) — Non l'hai mai fatto da solo: al mattino metà strada è sveglia, stanze calde si accendono lungo la collina. Ada, la signora Pratt, la famiglia col neonato: tutti al caldo, perché hai bussato alla prima porta.",
  "de": "ENDE (gut) — Du hast es nie allein getan: Am Morgen ist die halbe Straße wach, warme Zimmer leuchten den Hügel hinab. Ada, Frau Pratt, die Familie mit dem Baby – alle warm, weil du an die erste Tür geklopft hast.",
  "pt": "FIM (bom) — Nunca o fizeste sozinho: de manhã, meia rua está acordada, quartos quentes acendem-se pela colina abaixo. A Ada, a Sra. Pratt, a família do bebé: todos quentes, porque bateste à primeira porta.",
  "ru": "КОНЦОВКА (хорошая) — Ты справился не один: к утру полулица на ногах, по всему холму загораются тёплые комнаты. Ада, миссис Пратт, семья с младенцем — всем тепло, потому что ты постучал в первую дверь.",
  "ar": "النهاية (جيدة) — لم تفعلها وحدك قط: مع الصباح نصف الشارع مستيقظ، وغرفٌ دافئة تُضيء على امتداد التلّة. آدا، والسيدة برات، والعائلة ذات الرضيع — كلّهم دافئون، لأنك طرقت الباب الأول.",
  "zh": "结局（好）——你从不是一个人在做：天亮时半条街都醒了，暖和的房间沿着山坡一间间亮起。阿达、普拉特太太、有婴儿的那家人——都暖了，只因你敲响了第一扇门。",
 },
 123: {
  "fr": "FIN (bonne) — Vous avez refusé le marchand de peur, sans raccourcis ni compromis, et obtenu honnêtement ce qu'il fallait pour Ada. Plus dur, plus lent — mais propre, suffisant, et vous pouvez regarder chacun en face au matin.",
  "es": "FINAL (bueno) — Rechazaste al vendedor de miedo, sin atajos ni trampas, y conseguiste con honradez lo que Ada necesitaba. Más duro, más lento, pero limpio, suficiente, y por la mañana puedes mirar a cualquiera a los ojos.",
  "it": "FINALE (buono) — Hai rifiutato il venditore di paura, senza scorciatoie né compromessi, e hai ottenuto onestamente ciò che serviva ad Ada. Più dura, più lenta, ma pulita, sufficiente, e al mattino puoi guardare tutti negli occhi.",
  "de": "ENDE (gut) — Du hast den Angstverkäufer abgewiesen, ohne Abkürzungen, ohne faule Kompromisse, und ehrlich besorgt, was Ada brauchte. Härter, langsamer – aber sauber, genug, und am Morgen kannst du jedem in die Augen sehen.",
  "pt": "FIM (bom) — Recusaste o vendedor do medo, sem atalhos nem compromissos, e conseguiste honestamente o que a Ada precisava. Mais difícil, mais lento, mas limpo, suficiente, e de manhã podes olhar qualquer um nos olhos.",
  "ru": "КОНЦОВКА (хорошая) — Ты отказал торговцу страхом, без срезанных углов и сделок, и честно добыл то, что нужно Аде. Труднее и дольше — но чисто, достаточно, и утром можешь любому смотреть в глаза.",
  "ar": "النهاية (جيدة) — رفضتَ بائع الخوف، دون طرق مختصرة ولا مساومات، وحصلتَ بنزاهة على ما تحتاجه آدا. أصعب وأبطأ، لكنه نظيف وكافٍ، وفي الصباح تستطيع أن تنظر في عين أي أحد.",
  "zh": "结局（好）——你拒绝了那个贩卖恐惧的人，不走捷径、不打折扣，靠正道弄到了阿达需要的东西。更难、更慢，却干净、足够，天亮后你能坦然面对任何人。",
 },
 124: {
  "fr": "FIN (mitigée) — Vous n'avez pas tout réussi, mais parce que vous vous étiez arrêté plus tôt pour un inconnu, une porte s'ouvre : un voisin vous accueille, Ada et vous, près d'un vrai feu. Pas la victoire entière, mais réel.",
  "es": "FINAL (agridulce) — No lo lograste todo, pero por haberte parado antes por un desconocido, ahora se abre una puerta: un vecino os acoge, a Ada y a ti, junto a un fuego de verdad. No es la victoria completa, pero es real.",
  "it": "FINALE (agrodolce) — Non è andato tutto bene, ma poiché prima ti eri fermato per uno sconosciuto, ora una porta si apre: un vicino accoglie te e Ada accanto a un vero fuoco. Non la vittoria piena, ma reale.",
  "de": "ENDE (zwiespältig) — Nicht alles ist gelungen, aber weil du vorhin für einen Fremden stehen geblieben bist, öffnet sich nun eine Tür: Ein Nachbar nimmt dich und Ada an einem echten Feuer auf. Nicht der ganze Sieg, aber echt.",
  "pt": "FIM (agridoce) — Não acertaste em tudo, mas porque paraste antes por um estranho, abre-se agora uma porta: um vizinho acolhe-vos, a ti e à Ada, junto a um fogo a sério. Não é a vitória inteira, mas é real.",
  "ru": "КОНЦОВКА (неоднозначная) — Не всё вышло, но оттого что раньше ты задержался ради незнакомца, теперь открывается дверь: сосед принимает тебя и Аду у настоящего огня. Не полная победа, но настоящее.",
  "ar": "النهاية (مُرّة حلوة) — لم يُصب كل شيء، لكن لأنك توقّفت سابقاً من أجل غريب، ينفتح الآن باب: جارٌ يأويك أنت وآدا إلى نار حقيقية. ليس النصر الكامل، لكنه حقيقي.",
  "zh": "结局（苦乐参半）——你并没有事事做对，但因为先前你为一个陌生人停下了脚步，此刻一扇门为你敞开：一位邻居把你和阿达都请进屋，围着真正的炉火。不是完胜，却是实实在在的温暖。",
 },
 125: {
  "fr": "FIN (mitigée) — Vous avez donné votre propre chaleur — couverture, manteau, thermos — à ceux qui avaient moins. À l'aube vous avez froid et n'avez pas tout sauvé, mais personne n'est seul : quelque chose de bon s'est répandu dans la ville gelée.",
  "es": "FINAL (agridulce) — Diste tu propio calor —manta, abrigo, termo— a quienes tenían menos. Al amanecer tienes frío y no lo salvaste todo, pero nadie está solo: algo bueno se extendió por la ciudad helada.",
  "it": "FINALE (agrodolce) — Hai dato il tuo calore — coperta, cappotto, thermos — a chi aveva meno. All'alba hai freddo e non hai salvato tutto, ma nessuno è solo: qualcosa di buono si è diffuso nella città gelata.",
  "de": "ENDE (zwiespältig) — Du hast deine eigene Wärme – Decke, Mantel, Thermoskanne – an die mit weniger verschenkt. Im Morgengrauen frierst du und hast nicht alles gerettet, aber niemand ist allein: Etwas Gutes hat sich durch die gefrorene Stadt verbreitet.",
  "pt": "FIM (agridoce) — Deste o teu próprio calor — cobertor, casaco, termo — a quem tinha menos. Ao amanhecer tens frio e não salvaste tudo, mas ninguém está sozinho: algo de bom espalhou-se pela cidade gelada.",
  "ru": "КОНЦОВКА (неоднозначная) — Ты отдал своё тепло — одеяло, пальто, термос — тем, у кого было меньше. На рассвете тебе холодно и спас ты не всё, но никто не одинок: что-то доброе разошлось по замёрзшему городу.",
  "ar": "النهاية (مُرّة حلوة) — أعطيت دفأك — بطانيتك ومعطفك وقارورتك — لمن هم أقلّ منك. عند الفجر أنت باردٌ ولم تُنقذ كلّ شيء، لكن لا أحد وحده: شيءٌ طيّب انتشر في المدينة المتجمّدة.",
  "zh": "结局（苦乐参半）——你把自己的暖意——毯子、外套、热水瓶——都给了比你更缺的人。天亮时你冷着，也没能救下一切，但没有谁是孤单的：一份小小的善意，在冰封的小镇里一手传一手地散开了。",
 },
 126: {
  "fr": "FIN (mitigée) — Ça s'est joué de justesse, mais le courant revient enfin, tard et à contrecœur, et le pire du froid se lève. Ada va bien, vous allez bien. Ni habile ni net — mais vous avez passé la nuit, et au matin c'est ce qui compte.",
  "es": "FINAL (agridulce) — Fue por los pelos, pero la luz vuelve al fin, tarde y a regañadientes, y lo peor del frío se levanta. Ada está bien, tú estás bien. Ni astuto ni limpio, pero pasaste la noche, y por la mañana eso es lo que cuenta.",
  "it": "FINALE (agrodolce) — È stata dura, ma la corrente torna infine, tardi e a malincuore, e il peggio del freddo passa. Ada sta bene, tu stai bene. Né astuto né pulito, ma hai passato la notte, e al mattino è questo che conta.",
  "de": "ENDE (zwiespältig) — Es war knapp, aber der Strom kommt endlich zurück, spät und widerwillig, und das Schlimmste der Kälte lässt nach. Ada ist in Ordnung, du bist in Ordnung. Nicht clever, nicht sauber – aber du bist durch die Nacht gekommen, und am Morgen zählt das.",
  "pt": "FIM (agridoce) — Foi por pouco, mas a energia volta enfim, tarde e a contragosto, e o pior do frio passa. A Ada está bem, tu estás bem. Nem esperto nem limpo, mas passaste a noite, e de manhã é isso que conta.",
  "ru": "КОНЦОВКА (неоднозначная) — Было впритык, но свет наконец возвращается, поздно и нехотя, и худший холод отступает. С Адой всё хорошо, с тобой тоже. Не ловко и не чисто — но ты прошёл ночь, а утром это и важно.",
  "ar": "النهاية (مُرّة حلوة) — كان الأمر على حافة الهاوية، لكن الكهرباء تعود أخيراً، متأخرةً على مضض، ويخفّ أسوأ البرد. آدا بخير، وأنت بخير. لا ذكاء ولا نظافة، لكنك اجتزت الليل، وفي الصباح هذا ما يهمّ.",
  "zh": "结局（苦乐参半）——险之又险，但电终究来了，姗姗来迟又极不情愿，最冷的那阵总算过去。阿达没事，你也没事。谈不上高明或干净，可你熬过了这一夜——到了早上，这就够了。",
 },
 127: {
  "fr": "FIN (mitigée) — Vous n'avez pas tout réussi, mais quand la ville a sombré dans le noir, vous êtes sorti. Les gens ont vu un jeune grimper la colline dans le froid, pour une vieille dame, la pire nuit de l'année. Désormais, la ville vous connaît.",
  "es": "FINAL (agridulce) — No lo lograste todo, pero cuando la ciudad se hundió en la oscuridad, saliste. La gente vio a un joven subir la colina en el frío, por una anciana, la peor noche del año. Desde hoy, la ciudad te conoce.",
  "it": "FINALE (agrodolce) — Non è andato tutto bene, ma quando la città è sprofondata nel buio, sei uscito. La gente ha visto un giovane salire la collina nel freddo, per una vecchia signora, nella notte peggiore dell'anno. Da oggi, la città ti conosce.",
  "de": "ENDE (zwiespältig) — Nicht alles ist gelungen, aber als die Stadt im Dunkeln versank, bist du hinaus. Die Leute sahen einen jungen Menschen in der Kälte den Hügel hinaufsteigen, für eine alte Frau, in der schlimmsten Nacht des Jahres. Von heute an kennt dich die Stadt.",
  "pt": "FIM (agridoce) — Não acertaste em tudo, mas quando a cidade mergulhou no escuro, saíste. As pessoas viram um jovem subir a colina no frio, por uma velha senhora, na pior noite do ano. A partir de hoje, a cidade conhece-te.",
  "ru": "КОНЦОВКА (неоднозначная) — Не всё удалось, но когда город погрузился во тьму, ты вышел наружу. Люди видели, как молодой человек в стужу поднимается на холм ради старой женщины в худшую ночь года. С сегодняшнего дня город тебя знает.",
  "ar": "النهاية (مُرّة حلوة) — لم يُصب كل شيء، لكن حين غرقت المدينة في الظلام، خرجتَ أنت. رأى الناس شابّاً يصعد التلّة في البرد، من أجل عجوز، في أسوأ ليالي العام. من الليلة، صرتَ معروفاً في المدينة.",
  "zh": "结局（苦乐参半）——你并非事事如愿，但当全镇陷入黑暗，你走了出去。人们看见一个年轻人在严寒里为一位老太太爬上山坡，在一年中最糟的夜里。从今夜起，这个镇子记住了你。",
 },
 128: {
  "fr": "FIN (mauvaise) — Le groupe électrogène ne démarre jamais, le carburant ne brûle pas. Vous avez donné presque tout à l'homme de la camionnette pour un bloc de métal froid et inutile. L'argent est parti, le froid intact. Vous saviez que c'était un piège — et dans la peur, vous l'avez pris.",
  "es": "FINAL (malo) — El generador nunca arranca, el combustible no prende. Diste casi todo al hombre de la furgoneta por un bloque de metal frío e inútil. El dinero se fue, el frío sigue igual. Sabías que era un anzuelo, y aun así, por miedo, lo tomaste.",
  "it": "FINALE (cattivo) — Il generatore non parte mai, il carburante non brucia. Hai dato quasi tutto all'uomo del furgone per un blocco di metallo freddo e inutile. I soldi sono spariti, il freddo è intatto. Sapevi che era un amo, eppure, per paura, l'hai preso.",
  "de": "ENDE (schlecht) — Der Generator springt nie an, der Brennstoff brennt nicht. Du hast dem Mann vom Lieferwagen fast alles gegeben für einen kalten, nutzlosen Klumpen Metall. Das Geld ist weg, die Kälte unverändert. Du wusstest, es war ein Köder – und hast ihn aus Angst doch geschluckt.",
  "pt": "FIM (mau) — O gerador nunca arranca, o combustível não arde. Deste quase tudo ao homem da carrinha por um bloco de metal frio e inútil. O dinheiro foi-se, o frio ficou igual. Sabias que era um anzol — e, com medo, mordeste-o na mesma.",
  "ru": "КОНЦОВКА (плохая) — Генератор так и не заводится, топливо не горит. Ты отдал мужчине из фургона почти всё за холодную, бесполезную железяку. Деньги пропали, холод не отступил. Ты знал, что это крючок, — и со страху всё равно попался.",
  "ar": "النهاية (سيّئة) — المولّد لا يبدأ أبداً، والوقود لا يشتعل. أعطيتَ رجل الشاحنة كل ما تملك تقريباً مقابل كتلة معدنٍ باردة عديمة النفع. ذهب المال، وبقي البرد كما هو. كنتَ تعلم أنه فخّ — ومع ذلك، في خوفك، وقعتَ فيه.",
  "zh": "结局（坏）——发电机始终发动不起来，燃料也点不着。你几乎把所有钱都给了货车男人，换来一坨又冷又没用的铁疙瘩。钱没了，寒冷纹丝未动。你心里其实知道那是个钩子——可还是在恐惧里咬了上去。",
 },
 129: {
  "fr": "FIN (mauvaise) — La glace a menti, comme Okafor l'avait dit. Elle cède, l'eau noire vous happe. Vous vous en sortez — trempé, grelottant, à demi gelé — mais la nuit est perdue : vous atteignez la colline bien trop tard. La rivière a coûté tout ce que le raccourci promettait.",
  "es": "FINAL (malo) — El hielo mintió, como avisó Okafor. Cede, y el agua negra te atrapa. Sales a duras penas —empapado, temblando, medio congelado—, pero la noche se perdió: llegas a la colina demasiado tarde. El río costó todo lo que el atajo prometía.",
  "it": "FINALE (cattivo) — Il ghiaccio ha mentito, come aveva detto Okafor. Cede, e l'acqua nera ti afferra. Ne esci a fatica — fradicio, tremante, mezzo congelato — ma la notte è persa: raggiungi la collina troppo tardi. Il fiume è costato tutto ciò che la scorciatoia prometteva.",
  "de": "ENDE (schlecht) — Das Eis hat gelogen, wie Okafor warnte. Es bricht, das schwarze Wasser packt dich. Du ziehst dich heraus – durchnässt, zitternd, halb erfroren –, aber die Nacht ist verloren: Du erreichst den Hügel viel zu spät. Der Fluss kostete alles, was die Abkürzung versprach.",
  "pt": "FIM (mau) — O gelo mentiu, como o Okafor avisou. Cede, e a água negra agarra-te. Sais a custo — encharcado, a tremer, meio gelado —, mas a noite perdeu-se: chegas à colina tarde demais. O rio custou tudo o que o atalho prometia.",
  "ru": "КОНЦОВКА (плохая) — Лёд солгал, как и предупреждал Окафор. Он проваливается, чёрная вода хватает тебя. Ты кое-как выбираешься — промокший, дрожащий, полузамёрзший, — но ночь потеряна: ты добираешься до холма слишком поздно. Река отняла всё, что обещал сократить путь.",
  "ar": "النهاية (سيّئة) — كذب الجليد، كما حذّر أوكافور. ينهار، ويمسكك الماء الأسود. تنتشل نفسك بالكاد — مبلّلاً مرتجفاً نصف متجمّد — لكن الليلة ضاعت: تصل إلى التلّة متأخراً جداً. كلّفك النهر كلّ ما وعد به الطريق المختصر.",
  "zh": "结局（坏）——冰果然是假的，正如奥卡福所警告。它塌了，漆黑的河水一把攫住你。你好不容易爬上来——浑身湿透、发抖、半冻僵——可这一夜已经毁了：你赶到山上时早已太迟。那条河，夺走了捷径许诺要省下的一切。",
 },
 130: {
  "fr": "FIN (mauvaise) — Vous avez passé la nuit sur de mauvaises choses — un mauvais marché, un détour, une pièce chaude où rester. Quand vous arrivez enfin chez Ada, le froid est entré depuis trop longtemps. À l'aube, les secours l'emmènent, grise et immobile. Vous êtes sorti, mais pas arrivé à temps.",
  "es": "FINAL (malo) — Pasaste la noche en cosas equivocadas: un mal trato, un desvío, un cuarto caliente donde quedarte. Cuando por fin llegas a casa de Ada, el frío lleva demasiado tiempo dentro. Al amanecer, los servicios se la llevan, gris e inmóvil. Saliste, pero no llegaste a tiempo.",
  "it": "FINALE (cattivo) — Hai passato la notte sulle cose sbagliate: un cattivo affare, una deviazione, una stanza calda in cui restare. Quando arrivi da Ada, il freddo è dentro da troppo tempo. All'alba i soccorsi la portano via, grigia e immobile. Sei uscito, ma non sei arrivato in tempo.",
  "de": "ENDE (schlecht) — Du hast die Nacht mit den falschen Dingen verbracht – einem schlechten Geschäft, einem Umweg, einem warmen Zimmer zum Bleiben. Als du endlich zu Ada kommst, ist die Kälte zu lange im Haus. Im Morgengrauen tragen die Helfer sie hinaus, grau und reglos. Du bist hinausgegangen, aber nicht rechtzeitig angekommen.",
  "pt": "FIM (mau) — Passaste a noite nas coisas erradas: um mau negócio, um desvio, um quarto quente onde ficar. Quando chegas enfim a casa da Ada, o frio já entrou há tempo demais. Ao amanhecer, os socorros levam-na, cinzenta e imóvel. Saíste, mas não chegaste a tempo.",
  "ru": "КОНЦОВКА (плохая) — Ты потратил ночь не на то — плохая сделка, не туда свернул, тёплая комната, где задержался. Когда ты наконец добираешься до Ады, холод уже слишком долго в доме. На рассвете спасатели выносят её, серую и неподвижную. Ты вышел — но не успел.",
  "ar": "النهاية (سيّئة) — أمضيتَ الليل في أمور خاطئة: صفقة سيّئة، منعطف غلط، غرفة دافئة بقيتَ فيها. وحين تصل أخيراً إلى بيت آدا، يكون البرد قد سكن البيت وقتاً أطول من اللازم. عند الفجر يحملها المسعفون، شاحبةً ساكنة. خرجتَ، لكنك لم تصل في الوقت.",
  "zh": "结局（坏）——你把一夜花在了不该花的事上——一桩坏交易、一个错弯、一间不该多待的暖房。等你终于赶到阿达家，寒气早已在屋里待得太久。天亮时，救护人员把她抬下山，脸色灰白，一动不动。你是走出去了，却没能及时赶到。",
 },
 131: {
  "fr": "FIN (mauvaise) — Au bout du compte, vous êtes resté derrière votre porte, au chaud et en sécurité, en vous disant que ce n'était pas votre affaire. Toute la nuit, là-haut, une petite lumière est restée éteinte. Rien ne vous est arrivé. Vous y penserez très longtemps.",
  "es": "FINAL (malo) — Al final te quedaste tras tu puerta, caliente y a salvo, diciéndote que no era asunto tuyo. Toda la noche, colina arriba, una lucecita siguió apagada. A ti no te pasó nada. Pensarás en eso mucho, mucho tiempo.",
  "it": "FINALE (cattivo) — Alla fine sei rimasto dietro la tua porta, al caldo e al sicuro, dicendoti che non erano affari tuoi. Tutta la notte, lassù, una piccola luce è rimasta spenta. A te non è successo nulla. Ci penserai a lungo, a lungo.",
  "de": "ENDE (schlecht) — Am Ende bist du hinter deiner Tür geblieben, warm und sicher, und hast dir gesagt, es sei nicht deine Sache. Die ganze Nacht blieb oben am Hügel ein kleines Licht dunkel. Dir ist nichts passiert. Du wirst noch lange, lange daran denken.",
  "pt": "FIM (mau) — No fim, ficaste atrás da tua porta, quente e em segurança, a dizer-te que não era contigo. A noite toda, lá no alto, uma luzinha ficou apagada. A ti não aconteceu nada. Vais pensar nisso durante muito, muito tempo.",
  "ru": "КОНЦОВКА (плохая) — В итоге ты остался за своей дверью, в тепле и безопасности, твердя себе, что это не твоё дело. Всю ночь там, на холме, маленький огонёк оставался тёмным. С тобой ничего не случилось. Ты будешь думать об этом очень, очень долго.",
  "ar": "النهاية (سيّئة) — في النهاية بقيتَ خلف بابك، دافئاً آمناً، تُقنع نفسك أن الأمر لا يعنيك. وطوال الليل، في الأعلى، بقي ضوءٌ صغير مُطفأً. لم يصبك مكروه. ستفكّر في ذلك وقتاً طويلاً طويلاً.",
  "zh": "结局（坏）——到头来，你留在自家门后，又暖又安全，告诉自己这不关你的事。整整一夜，山上那一点小小的灯，一直没有亮起。你毫发无伤。而这件事，你会想很久，很久。",
 },
}
for lg in LANGS:
    json.dump({str(n): G[n][lg] for n in sorted(G)},
              open(os.path.join(OUT, lg + ".json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("Wrote %d gist files (%d passages each) to content/gist/first-light/" % (len(LANGS), len(G)))
