#!/usr/bin/env python3
"""Build the per-passage gist files — the on-demand "meaning in your language" fallback.

A concise 1–2 sentence meaning per passage, offered only where a learner is likely to get
stuck (the pivotal/dense beats and every ending — "where needed"), not on every passage.
Emits content/gist/<lang>.json → { "<nodeId>": "gist" }, lazy-loaded per language.

Authored here in the five languages Claude can vouch for (fr, es, it, de, pt). Russian,
Arabic and Mandarin are left for native translators — the reader simply shows no meaning
control for a language that has no gist for that node.
"""
import json, os

L = ["fr", "es", "it", "de", "pt"]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist")
os.makedirs(OUT, exist_ok=True)

# nodeId : [fr, es, it, de, pt]
G = {
 1: [
  "Vous arrivez de nuit dans une ville inconnue avec une lettre : un entretien d'embauche chez Kessler & Rowe, 14 Rosewater Street, mardi à neuf heures. La gare est vide et froide.",
  "Llegas de noche a una ciudad desconocida con una carta: una entrevista de trabajo en Kessler & Rowe, 14 Rosewater Street, el martes a las nueve. La estación está vacía y fría.",
  "Arrivi di notte in una città sconosciuta con una lettera: un colloquio di lavoro da Kessler & Rowe, 14 Rosewater Street, martedì alle nove. La stazione è vuota e fredda.",
  "Sie kommen nachts in einer fremden Stadt an, mit einem Brief: ein Vorstellungsgespräch bei Kessler & Rowe, Rosewater Street 14, Dienstag um neun. Der Bahnhof ist leer und kalt.",
  "Chegas de noite a uma cidade desconhecida com uma carta: uma entrevista de emprego na Kessler & Rowe, Rosewater Street 14, terça-feira às nove. A estação está vazia e fria.",
 ],
 7: [
  "Rosewater Street est sombre et à moitié en travaux. Le numéro 14 est un immeuble gris et poussiéreux, à l'abandon : la société est manifestement partie depuis longtemps.",
  "Rosewater Street está oscura y medio en obras. El número 14 es un edificio gris y polvoriento, abandonado: la empresa se marchó hace tiempo.",
  "Rosewater Street è buia e mezza in cantiere. Il numero 14 è un palazzo grigio e polveroso, abbandonato: l'azienda se n'è andata da tempo.",
  "Die Rosewater Street ist dunkel und halb Baustelle. Nummer 14 ist ein graues, staubiges, verlassenes Gebäude: die Firma ist längst weg.",
  "A Rosewater Street está escura e meio em obras. O número 14 é um prédio cinzento e poeirento, abandonado: a empresa foi-se há muito.",
 ],
 24: [
  "Une agence pour l'emploi, trop neuve et trop souriante, propose du travail — mais réclame d'abord 200 d'« inscription ». C'est le piège de l'histoire.",
  "Una agencia de empleo, demasiado nueva y sonriente, ofrece trabajo, pero pide primero 200 de «inscripción». Es la trampa de la historia.",
  "Un'agenzia per il lavoro, troppo nuova e sorridente, offre lavoro ma chiede prima 200 di «iscrizione». È la trappola della storia.",
  "Eine Arbeitsagentur, zu neu und zu freundlich, bietet Arbeit an — verlangt aber erst 200 „Anmeldegebühr“. Das ist die Falle der Geschichte.",
  "Uma agência de emprego, nova e sorridente demais, oferece trabalho mas pede primeiro 200 de «inscrição». É a armadilha da história.",
 ],
 32: [
  "Vous payez les 200. On vous donne un reçu sans adresse ni nom, juste un numéro. Votre argent est parti.",
  "Pagas los 200. Te dan un recibo sin dirección ni nombre, solo un número. Tu dinero se ha ido.",
  "Paghi i 200. Ti danno una ricevuta senza indirizzo né nome, solo un numero. I tuoi soldi sono spariti.",
  "Sie zahlen die 200. Man gibt Ihnen eine Quittung ohne Adresse und Namen, nur eine Nummer. Ihr Geld ist weg.",
  "Pagas os 200. Dão-te um recibo sem morada nem nome, só um número. O teu dinheiro desapareceu.",
 ],
 33: [
  "Vous refusez de payer. Le sourire de l'homme disparaît aussitôt : vous aviez raison, c'était une arnaque. Vous gardez votre argent.",
  "Te niegas a pagar. La sonrisa del hombre desaparece al instante: tenías razón, era una estafa. Conservas tu dinero.",
  "Ti rifiuti di pagare. Il sorriso dell'uomo sparisce subito: avevi ragione, era una truffa. Tieni i tuoi soldi.",
  "Sie weigern sich zu zahlen. Das Lächeln des Mannes verschwindet sofort: Sie hatten recht, es war Betrug. Ihr Geld bleibt Ihnen.",
  "Recusas-te a pagar. O sorriso do homem desaparece logo: tinhas razão, era uma fraude. Ficas com o teu dinheiro.",
 ],
 35: [
  "Mme Rowe lit votre lettre et comprend l'erreur : la société a déménagé il y a deux ans, mais quelqu'un envoie encore l'ancienne adresse. Elle vous invite à vous asseoir.",
  "La Sra. Rowe lee tu carta y comprende el error: la empresa se mudó hace dos años, pero alguien sigue enviando la dirección antigua. Te invita a sentarte.",
  "La signora Rowe legge la lettera e capisce l'errore: l'azienda ha traslocato due anni fa, ma qualcuno manda ancora il vecchio indirizzo. Ti invita a sederti.",
  "Frau Rowe liest Ihren Brief und versteht den Fehler: die Firma ist vor zwei Jahren umgezogen, aber jemand verschickt noch die alte Adresse. Sie bittet Sie, sich zu setzen.",
  "A Sra. Rowe lê a tua carta e percebe o erro: a empresa mudou-se há dois anos, mas alguém ainda envia a morada antiga. Convida-te a sentar.",
 ],
 36: [
  "Vous lui racontez toute votre nuit. Touchée que vous ne soyez pas rentré chez vous, elle vous embauche : votre première tâche sera de corriger les lettres. (Bonne fin.)",
  "Le cuentas toda tu noche. Conmovida de que no te hayas ido a casa, te contrata: tu primera tarea será corregir las cartas. (Final bueno.)",
  "Le racconti tutta la notte. Colpita dal fatto che non sei tornato a casa, ti assume: il tuo primo compito sarà correggere le lettere. (Finale buono.)",
  "Sie erzählen ihr die ganze Nacht. Gerührt, dass Sie nicht heimgefahren sind, stellt sie Sie ein: Ihre erste Aufgabe wird sein, die Briefe zu korrigieren. (Gutes Ende.)",
  "Contas-lhe toda a noite. Comovida por não teres ido para casa, contrata-te: a tua primeira tarefa será corrigir as cartas. (Final bom.)",
 ],
 37: [
  "Pas de poste aujourd'hui, mais elle note votre nom sur du vrai papier et vous dit de rappeler au printemps. Vous êtes dans la ville, et on s'y souvient de vous. (Fin neutre.)",
  "Hoy no hay puesto, pero anota tu nombre en papel de verdad y te dice que llames en primavera. Estás en la ciudad, y alguien te recuerda. (Final neutro.)",
  "Oggi niente posto, ma annota il tuo nome su carta vera e ti dice di richiamare in primavera. Sei in città, e qualcuno ti ricorda. (Finale neutro.)",
  "Heute keine Stelle, aber sie notiert Ihren Namen auf echtem Papier und sagt, Sie sollen im Frühling anrufen. Sie sind in der Stadt, und man kennt Sie. (Neutrales Ende.)",
  "Hoje não há vaga, mas ela anota o teu nome em papel a sério e diz para ligares na primavera. Estás na cidade, e alguém se lembra de ti. (Final neutro.)",
 ],
 38: [
  "Vous appelez Mme Rowe par son nom avant qu'elle ne se présente : elle comprend que vous êtes allé jusqu'à Rosewater Street. Elle vous embauche. (Fin secrète, bonne.)",
  "Llamas a la Sra. Rowe por su nombre antes de que se presente: entiende que llegaste hasta Rosewater Street. Te contrata. (Final secreto, bueno.)",
  "Chiami la signora Rowe per nome prima che si presenti: capisce che sei arrivato fino a Rosewater Street. Ti assume. (Finale segreto, buono.)",
  "Sie nennen Frau Rowe beim Namen, bevor sie sich vorstellt: sie versteht, dass Sie bis zur Rosewater Street gegangen sind. Sie stellt Sie ein. (Geheimes, gutes Ende.)",
  "Chamas a Sra. Rowe pelo nome antes de ela se apresentar: percebe que foste até Rosewater Street. Contrata-te. (Final secreto, bom.)",
 ],
 39: [
  "Le numéro de l'agence ne répond plus. Le bureau est vide, sans meubles. Vous n'avez ni argent ni travail : vous avez été escroqué. (Mauvaise fin.)",
  "El número de la agencia ya no responde. La oficina está vacía, sin muebles. No tienes ni dinero ni trabajo: te han estafado. (Final malo.)",
  "Il numero dell'agenzia non risponde più. L'ufficio è vuoto, senza mobili. Non hai né soldi né lavoro: sei stato truffato. (Finale cattivo.)",
  "Die Nummer der Agentur antwortet nicht mehr. Das Büro ist leer, ohne Möbel. Sie haben weder Geld noch Arbeit: Sie wurden betrogen. (Schlechtes Ende.)",
  "O número da agência já não atende. O escritório está vazio, sem móveis. Não tens dinheiro nem trabalho: foste enganado. (Final mau.)",
 ],
 40: [
  "Vous abandonnez et regardez le tableau des départs : un train à deux heures vous ramène d'où vous venez. (Mauvaise fin.)",
  "Te rindes y miras el panel de salidas: un tren a las dos te lleva de vuelta a casa. (Final malo.)",
  "Ti arrendi e guardi il tabellone delle partenze: un treno alle due ti riporta da dove sei venuto. (Finale cattivo.)",
  "Sie geben auf und schauen auf die Abfahrtstafel: ein Zug um zwei bringt Sie zurück, woher Sie kamen. (Schlechtes Ende.)",
  "Desistes e olhas para o painel das partidas: um comboio às duas leva-te de volta de onde vieste. (Final mau.)",
 ],
 44: [
  "L'homme du kiosque explique : la société a déménagé vers le fleuve il y a des années, mais les lettres partent toujours avec l'ancienne adresse. Ce détail est au cœur de l'histoire.",
  "El hombre del quiosco explica: la empresa se mudó al río hace años, pero las cartas siguen saliendo con la dirección antigua. Ese detalle es el centro de la historia.",
  "L'uomo dell'edicola spiega: l'azienda si è trasferita al fiume anni fa, ma le lettere partono ancora col vecchio indirizzo. Questo dettaglio è il cuore della storia.",
  "Der Mann am Kiosk erklärt: die Firma zog vor Jahren an den Fluss, aber die Briefe gehen noch mit der alten Adresse raus. Dieses Detail ist der Kern der Geschichte.",
  "O homem do quiosque explica: a empresa mudou-se para o rio há anos, mas as cartas ainda saem com a morada antiga. Esse detalhe é o centro da história.",
 ],
 63: [
  "À l'accueil, un plateau de courrier renvoyé : de vieilles lettres avec l'adresse de Rosewater Street barrée. L'une d'elles est la vôtre — celle qui vous a mené à la mauvaise porte.",
  "En recepción, una bandeja de correo devuelto: cartas viejas con la dirección de Rosewater Street tachada. Una es la tuya, la que te llevó a la puerta equivocada.",
  "Alla reception, un vassoio di posta rispedita: vecchie lettere con l'indirizzo di Rosewater Street cancellato. Una è la tua, quella che ti ha portato alla porta sbagliata.",
  "Am Empfang ein Tablett mit zurückgeschickter Post: alte Briefe mit durchgestrichener Rosewater-Street-Adresse. Einer ist Ihrer — der, der Sie zur falschen Tür führte.",
  "Na receção, um tabuleiro de correio devolvido: cartas velhas com a morada de Rosewater Street riscada. Uma é a tua, a que te levou à porta errada.",
 ],
 85: [
  "Le bureau de Mme Rowe donne sur l'eau. Sur la table, votre propre lettre, revenue à l'expéditeur. Elle voit que vous l'avez remarquée.",
  "El despacho de la Sra. Rowe da al agua. Sobre la mesa, tu propia carta, devuelta al remitente. Ella ve que te has dado cuenta.",
  "L'ufficio della signora Rowe dà sull'acqua. Sul tavolo, la tua stessa lettera, tornata al mittente. Lei vede che l'hai notata.",
  "Frau Rowes Büro liegt am Wasser. Auf dem Tisch Ihr eigener Brief, zurückgeschickt. Sie sieht, dass Sie ihn bemerkt haben.",
  "O gabinete da Sra. Rowe dá para a água. Na mesa, a tua própria carta, devolvida ao remetente. Ela vê que reparaste.",
 ],
 86: [
  "Elle explique que quelqu'un envoie l'ancienne adresse depuis deux ans ; vous n'êtes pas le premier égaré, mais le premier à être quand même venu.",
  "Explica que alguien lleva dos años enviando la dirección antigua; no eres el primero al que despistó, pero sí el primero en venir de todos modos.",
  "Spiega che qualcuno manda il vecchio indirizzo da due anni; non sei il primo a essere sviato, ma il primo a venire lo stesso.",
  "Sie erklärt, dass jemand seit zwei Jahren die alte Adresse verschickt; Sie sind nicht der erste Fehlgeleitete, aber der erste, der trotzdem kam.",
  "Explica que alguém envia a morada antiga há dois anos; não és o primeiro a ser desencaminhado, mas o primeiro a vir na mesma.",
 ],
 96: [
  "Dans la cour, un plateau d'enveloppes prêtes à poster — toutes adressées à Rosewater Street, c'est-à-dire à personne. Vous découvrez d'où vient l'erreur.",
  "En el patio, una bandeja de sobres listos para enviar, todos a Rosewater Street, es decir, a nadie. Descubres de dónde viene el error.",
  "Nel cortile, un vassoio di buste pronte da spedire, tutte indirizzate a Rosewater Street, cioè a nessuno. Scopri da dove nasce l'errore.",
  "Im Hof ein Tablett mit versandfertigen Umschlägen — alle an die Rosewater Street, also an niemanden. Sie entdecken, woher der Fehler kommt.",
  "No pátio, um tabuleiro de envelopes prontos a enviar, todos para Rosewater Street, ou seja, para ninguém. Descobres de onde vem o erro.",
 ],
 106: [
  "L'adresse donnée par l'agence n'est qu'un terrain vague derrière une clôture. Il n'y a jamais eu de travail : seulement les 200 envolés.",
  "La dirección que dio la agencia es solo un solar tras una valla. Nunca hubo trabajo: solo los 200 desaparecidos.",
  "L'indirizzo dato dall'agenzia è solo un terreno abbandonato dietro una recinzione. Non c'è mai stato lavoro: solo i 200 spariti.",
  "Die Adresse der Agentur ist nur ein leeres Grundstück hinter einem Zaun. Es gab nie Arbeit — nur die verschwundenen 200.",
  "A morada dada pela agência é só um terreno baldio atrás de uma vedação. Nunca houve trabalho: apenas os 200 desaparecidos.",
 ],
 120: [
  "Mme Rowe vous demande pourquoi elle devrait embaucher un inconnu arrivé presque par hasard. Elle attend votre réponse.",
  "La Sra. Rowe te pregunta por qué debería contratar a un desconocido que llegó casi por casualidad. Espera tu respuesta.",
  "La signora Rowe ti chiede perché dovrebbe assumere uno sconosciuto arrivato quasi per caso. Aspetta la tua risposta.",
  "Frau Rowe fragt, warum sie einen Fremden einstellen sollte, der fast zufällig kam. Sie wartet auf Ihre Antwort.",
  "A Sra. Rowe pergunta por que deveria contratar um desconhecido que chegou quase por acaso. Espera a tua resposta.",
 ],
 121: [
  "Vous lui parlez de l'agence qui a failli vous prendre 200. Elle vous dit que vous avez eu raison de partir.",
  "Le hablas de la agencia que casi te quita 200. Te dice que hiciste bien en marcharte.",
  "Le parli dell'agenzia che stava per prenderti 200. Ti dice che hai fatto bene ad andartene.",
  "Sie erzählen ihr von der Agentur, die Ihnen fast 200 abgenommen hätte. Sie sagt, Sie hätten richtig gehandelt, zu gehen.",
  "Falas-lhe da agência que quase te tirou 200. Ela diz que fizeste bem em ir embora.",
 ],
 141: [
  "Vous répondez simplement, sans faire semblant. Cela suffit : « Commencez lundi. » Un travail honnêtement gagné. (Bonne fin.)",
  "Respondes con sencillez, sin fingir. Basta con eso: «Empieza el lunes». Un trabajo ganado con honestidad. (Final bueno.)",
  "Rispondi con semplicità, senza fingere. Basta così: «Inizi lunedì». Un lavoro guadagnato onestamente. (Finale buono.)",
  "Sie antworten schlicht, ohne sich zu verstellen. Das genügt: „Fangen Sie Montag an.“ Ehrlich verdiente Arbeit. (Gutes Ende.)",
  "Respondes com simplicidade, sem fingir. Basta: «Começa segunda-feira». Um trabalho ganho com honestidade. (Final bom.)",
 ],
 142: [
  "Vous entrez reposé et sans rien devoir à ceux qui voulaient vous vendre de l'espoir — et cela se voit. Elle vous embauche. (Bonne fin, secrète.)",
  "Entras descansado y sin deberle nada a quienes querían venderte esperanza, y se nota. Te contrata. (Final bueno, secreto.)",
  "Entri riposato e senza dover nulla a chi voleva venderti speranza, e si vede. Ti assume. (Finale buono, segreto.)",
  "Sie treten ausgeruht ein und schulden niemandem etwas, der Ihnen Hoffnung verkaufen wollte — man sieht es. Sie stellt Sie ein. (Gutes, geheimes Ende.)",
  "Entras descansado e sem dever nada a quem queria vender-te esperança, e nota-se. Contrata-te. (Final bom, secreto.)",
 ],
 143: [
  "Pas de travail, mais elle écrit votre nom à la main. Vous êtes dans la ville, et on s'y souvient de vous. (Fin neutre.)",
  "No hay trabajo, pero anota tu nombre a mano. Estás en la ciudad, y alguien te recuerda. (Final neutro.)",
  "Niente lavoro, ma scrive il tuo nome a mano. Sei in città, e qualcuno ti ricorda. (Finale neutro.)",
  "Keine Arbeit, aber sie schreibt Ihren Namen von Hand auf. Sie sind in der Stadt, und man erinnert sich an Sie. (Neutrales Ende.)",
  "Não há trabalho, mas ela escreve o teu nome à mão. Estás na cidade, e alguém se lembra de ti. (Final neutro.)",
 ],
 144: [
  "Tout se passe vite, on vous embauche avant midi — mais personne ne demande ce que la nuit vous a coûté, et vous ne ressentez rien. (Fin neutre, amère.)",
  "Todo va rápido, te contratan antes del mediodía, pero nadie pregunta qué te costó la noche, y no sientes nada. (Final neutro, amargo.)",
  "Tutto va veloce, ti assumono prima di mezzogiorno, ma nessuno chiede cosa ti è costata la notte, e non provi nulla. (Finale neutro, amaro.)",
  "Alles geht schnell, man stellt Sie vor Mittag ein — aber niemand fragt, was die Nacht Sie gekostet hat, und Sie fühlen nichts. (Neutrales, bitteres Ende.)",
  "Tudo corre depressa, contratam-te antes do meio-dia, mas ninguém pergunta o que a noite te custou, e não sentes nada. (Final neutro, amargo.)",
 ],
 145: [
  "Pas de travail, mais l'homme du banc, que vous avez aidé, vous offre une chambre et une clé. Vous n'êtes pas embauché, mais plus seul. (Fin neutre.)",
  "No hay trabajo, pero el hombre del banco, al que ayudaste, te ofrece un cuarto y una llave. No te contratan, pero ya no estás solo. (Final neutro.)",
  "Niente lavoro, ma l'uomo della panchina, che hai aiutato, ti offre una stanza e una chiave. Non sei assunto, ma non più solo. (Finale neutro.)",
  "Keine Arbeit, aber der Mann von der Bank, dem Sie geholfen haben, bietet Ihnen ein Zimmer und einen Schlüssel. Nicht eingestellt, aber nicht mehr allein. (Neutrales Ende.)",
  "Não há trabalho, mas o homem do banco, que ajudaste, oferece-te um quarto e uma chave. Não és contratado, mas já não estás sozinho. (Final neutro.)",
 ],
 146: [
  "Vous arrivez à neuf heures vingt : le carnet de rendez-vous est fermé, les chaises pleines. On vous dit gentiment non. (Mauvaise fin.)",
  "Llegas a las nueve y veinte: la agenda está cerrada, las sillas llenas. Te dicen que no con amabilidad. (Final malo.)",
  "Arrivi alle nove e venti: l'agenda è chiusa, le sedie piene. Ti dicono gentilmente di no. (Finale cattivo.)",
  "Sie kommen um zwanzig nach neun: der Terminkalender ist zu, die Stühle besetzt. Man sagt freundlich Nein. (Schlechtes Ende.)",
  "Chegas às nove e vinte: a agenda está fechada, as cadeiras cheias. Dizem-te que não com gentileza. (Final mau.)",
 ],
 147: [
  "Le matin se lève sur le banc et vous ne bougez pas. Quand vous reprenez vos esprits, neuf heures sont passées — et la raison de votre venue aussi. (Mauvaise fin.)",
  "Amanece sobre el banco y no te mueves. Cuando reaccionas, ya han pasado las nueve, y con ellas el motivo de tu viaje. (Final malo.)",
  "Sorge il mattino sulla panchina e non ti muovi. Quando ti riprendi, le nove sono passate, e con esse il motivo del tuo viaggio. (Finale cattivo.)",
  "Der Morgen graut über der Bank, und Sie rühren sich nicht. Als Sie zu sich kommen, ist neun Uhr vorbei — und damit der Grund Ihrer Reise. (Schlechtes Ende.)",
  "O dia nasce sobre o banco e não te mexes. Quando dás por ti, passaram das nove — e com elas a razão da tua viagem. (Final mau.)",
 ],
}

# French is being taken to whole-book coverage first (primary audience); the other four
# languages stay at the 26 pivotal/ending gists above until extended.
FR_ONLY = {
 2: "Au guichet d'information, un homme fatigué lit votre lettre : Rosewater Street est en travaux depuis deux ans ; le bus 9 y va, mais il est presque minuit. Il vous glisse un petit plan.",
 3: "Dehors, l'air est froid et sent le fleuve. Trois chauffeurs de taxi vous observent ; il y a aussi un arrêt de bus. Le bus ne coûte presque rien, le taxi presque tout ce que vous avez.",
 4: "Le bus est chaud et presque vide. Vous relisez la lettre : Kessler & Rowe, mardi à neuf heures. On est lundi : vous avez toute la nuit devant vous.",
 5: "Vous marchez, mais après vingt minutes vous êtes perdu. Une femme baisse le rideau d'un kiosque au coin de la rue — la seule personne alentour.",
 6: "Le chauffeur de taxi rit : « Rosewater Street ? Il n'y a plus rien, les bureaux ont déménagé, il y a deux ou trois ans. » Il démarre quand même.",
 8: "Vous vous réveillez au terminus : le chauffeur vous regarde. Vous êtes du mauvais côté de la ville, il est une heure du matin, et il n'y a plus de bus.",
 9: "La femme du kiosque lit la lettre : Kessler & Rowe sont partis depuis longtemps. Elle indique un café au coin, le Blue Kettle : demandez-y le matin, ils savent tout.",
 10: "L'hôtel est petit, propre et un peu cher. L'homme de la réception mentionne une agence pour l'emploi juste en face, qui trouve du travail aux nouveaux arrivants.",
 11: "Vous essuyez la vitre poussiéreuse : des bureaux vides, une chaise renversée, un calendrier arrêté il y a deux ans — mais tout au fond, derrière une porte vitrée, une petite lumière est allumée.",
 12: "Au numéro 16, un homme en robe de chambre, mécontent de l'heure : « Ils ont déménagé près du fleuve. Mme Rowe revient le vendredi, pour le courrier. » Puis il referme la porte.",
 13: "Vous dormez sur un banc de la gare. À six heures, une agente d'entretien vous réveille. Vous avez mal au dos, au cou, et presque plus d'argent.",
 14: "Vous marchez près de deux heures dans des rues vides et vous vous retrouvez près de la gare. Il est trois heures du matin ; vous n'avez rien appris, sinon que la ville est immense.",
 15: "Le café est fermé, mais une carte est collée à la vitre : KESSLER & ROWE — MAINTENANT AU 3 MILL QUAY. Vous la photographiez deux fois, les mains gelées.",
 16: "La chambre est petite mais le lit est bon. Au matin, l'agence est bien là, en face : une grande enseigne jaune, TRAVAIL POUR TOUS — AUJOURD'HUI.",
 17: "Mardi, huit heures : vous êtes de nouveau devant l'immeuble vide de Rosewater Street. L'entretien est dans une heure et vous ignorez toujours où il a lieu.",
 18: "Une femme de ménage entrouvre la porte intérieure : « Il n'y a personne, ils ont déménagé. » Elle vous envoie demander au café du coin, puis referme.",
 19: "Vous marchez vers le fleuve, en devinant le chemin. Il est presque deux heures ; tout est fermé. De l'autre côté de l'eau, des bureaux neufs, tout en verre, éteints.",
 20: "C'est le matin ; vous êtes fatigué, gelé, presque sans argent. Il reste une heure avant l'entretien, et vous êtes devant un immeuble vide.",
 21: "Le café est cher mais chaud. Vous réfléchissez : une adresse périmée, presque pas d'argent, une heure. Mais quelqu'un a écrit cette lettre, et quelqu'un vous attend.",
 22: "À huit heures, vous ne sentez plus vos pieds. Vous avez marché toute la nuit pour rien. Sur un banc, un instant, vous songez sérieusement à rentrer chez vous.",
 23: "Mill Quay longe l'eau. Le numéro 3 est neuf ; sur la liste des sociétés, le quatrième nom est KESSLER & ROWE, deuxième étage.",
 25: "Vous arrivez à Mill Quay à huit heures et demie. Le fleuve est gris, il y a des mouettes. Vous êtes en avance, à peu près propre, et pour la première fois vous savez où vous allez.",
 26: "Cette fois, une jeune femme ouvre au 16 : « Le fleuve, 3 Mill Quay. Prenez le bus 4 au coin, c'est plus rapide. » Elle vous regarde une seconde de trop : « Bonne chance. »",
 27: "Vous attendez devant le 14. À neuf heures cinq, une femme arrive, clé en main : « Vous attendez Kessler & Rowe ? Moi aussi, en quelque sorte : c'est moi, Kessler & Rowe. »",
 28: "Dans le noir, tous les immeubles du quai se ressemblent. Le numéro 3 que vous trouvez n'est qu'un parking. Vous vous asseyez près de l'eau pour attendre le jour.",
 29: "Derrière le comptoir : « Kessler & Rowe ? Partis au fleuve depuis des années. » Il écrit une adresse sur une serviette : 3 Mill Quay. « Vous êtes le troisième à me le demander cette année. »",
 30: "L'accueil est chaud et sent le café. La réceptionniste tape votre nom, deux fois : « Désolée, aucun entretien n'est prévu aujourd'hui. Vous êtes sûr de la date ? »",
 31: "Vous surveillez la porte. À neuf heures moins dix, une femme d'environ soixante ans approche, un café à la main ; sur son sac, une petite étiquette jaune : R. ROWE.",
 34: "Il est neuf heures et quart. L'heure de l'entretien est passée. Vous êtes dans une ville inconnue, une lettre désormais inutile à la main, presque rien en poche.",
 41: "Le quai se vide. Parmi les voyageurs, un jeune au gros sac à dos relit un bout de papier, comme vous relisez votre lettre. Il a l'air aussi perdu que vous.",
 42: "Elle s'appelle Mara, venue par le même train, elle aussi pour du travail. Un instant, vous n'êtes pas seuls. Son adresse est de l'autre côté du fleuve ; la vôtre, une rue qu'elle ne connaît pas.",
 43: "L'homme du kiosque à journaux lit votre lettre : « Rosewater Street ? Le troisième que j'y envoie ce mois-ci. Là-haut, quelqu'un met encore la vieille adresse sur les lettres. »",
 45: "Rosewater Street est cachée par une palissade de chantier. Sur une vieille affiche déchirée au nom de la société, quelqu'un a écrit un mot au marqueur, avec une flèche vers l'est : DÉMÉNAGÉ.",
 46: "Vous remarquez une porte latérale étroite, un filet de lumière en dessous. Quelqu'un est là, malgré l'heure. Vous restez un instant à fixer cette petite ligne jaune.",
 47: "Une femme sort, enfilant son manteau : « Plus personne ne travaille ici, ils sont au fleuve. Si vous ne pouvez pas attendre le matin, demandez au café du coin. »",
 48: "Sur le banc voisin, un homme sans sac ni manteau, juste un gobelet. Il ne demande rien. Il a raté le dernier train, comme vous — mais il a connu bien plus de nuits pareilles.",
 49: "Vous vous trompez de chemin, encore et encore ; la même boutique fermée repasse deux fois. Le plan ne veut plus rien dire. La ville, à une heure du matin, n'est à personne.",
 50: "La lumière vient d'une laverie ouverte toute la nuit, vide, un employé qui plie des serviettes. Content d'avoir de la compagnie, il vous dessine le chemin d'une main sûre.",
 51: "Sur une porte vitrée au fond, un nom à moitié gratté : on lit encore ROWE. Quelqu'un est parti en hâte, ou a voulu effacer ce nom. Dans le noir, difficile de dire ce qui est pire.",
 52: "Une fenêtre éclairée au 16 : une fillette d'une dizaine d'années vous observe, très calme, habituée aux inconnus aux heures étranges. Elle ne salue pas ; elle attend de voir ce que vous ferez.",
 53: "Un bus de nuit surgit, ses vitres jaunes et chaudes, filant vers ce que vous croyez être le fleuve. Il ne ralentit pas : quelques secondes pour décider, et vos pieds sont fatigués de décider.",
 54: "Un pont enjambe l'eau noire. En face, les bureaux neufs sont sombres, tout en verre — sauf une fenêtre éclairée, tout en haut. Vous la regardez, et elle ne s'éteint pas.",
 55: "Un gardien de nuit se penche de sa guérite : « Kessler & Rowe ? Deuxième étage. Mais personne avant neuf heures. » Gentiment, il vous invite à vous réchauffer.",
 56: "Le Blue Kettle est fermé, mais une lumière au fond, quelqu'un qui range des chaises. La carte est toujours collée à la vitre. Vous soufflez sur le verre et attendez qu'on vous voie.",
 57: "La femme à l'intérieur vous répond par l'entrebâillement : « Kessler & Rowe ? Ada Rowe, vous voulez dire. Elle est au fleuve. Elle vient ici prendre son café chaque matin. »",
 58: "L'agente d'entretien qui vous a réveillé vous verse la moitié d'une tasse de son thermos et demande, sans grande curiosité, d'où vous venez.",
 59: "Au petit-déjeuner, Mara est là aussi : « Il y a une agence en face. Ils ont voulu me prendre de l'argent hier soir. N'y allez pas. Quoi qu'ils disent. »",
 60: "Une file s'est déjà formée devant TRAVAIL POUR TOUS avant l'ouverture. Visages fatigués, souffle visible dans le froid. Devant, une femme recompte ses derniers billets.",
 61: "L'homme en beau costume glisse un formulaire : « Deux cents pour l'inscription, et on vous place aujourd'hui. Tout le monde paie. » Il tend déjà la main vers votre argent.",
 62: "Dehors, un homme s'appuie au mur, un reçu comme le vôtre à la main : « Payé la semaine dernière. Ils n'ont jamais rappelé. Vous n'avez pas payé, dites-moi ? »",
 65: "Le chauffeur raconte : tous ont déménagé au fleuve, dans des bureaux de verre. « Et méfiez-vous des agences près de la gare. Elles ne sont pas ce qu'elles paraissent. »",
 67: "L'aube grise se lève sur Mill Quay : un chariot à café ouvre, des camionnettes passent. Vous êtes en avance et propre ; pour la première fois, vous savez où vous allez.",
 68: "En surveillant les portes du quai, vous le voyez : l'homme en beau costume de l'agence entre dans un immeuble deux portes plus loin, sans nom ni enseigne. Sa façon de regarder autour dit tout.",
 69: "Dans votre sac : la lettre, un peu d'argent qui ne durera pas, et une photo que vous ne sortez pas. Vous relisez la lettre, comme si les mots avaient pu changer pendant votre sommeil.",
 72: "Votre téléphone n'a plus qu'une barre de batterie. La chercher maintenant, ou la garder pour pire ? La nuit, dans une ville inconnue, un téléphone qui meurt est une sorte de compte à rebours.",
 73: "Une vieille page se charge : l'adresse n'est pas Rosewater Street, mais quelque part au bord du fleuve. Puis l'écran s'éteint pour de bon, et vous restez seul avec une lettre en papier.",
 75: "Mara a plus de bon sens que d'argent, vous un peu plus d'argent que de bon sens. À deux, il y a peut-être de quoi bien faire, au lieu de marcher la nuit dans le mauvais sens.",
 77: "Un agent éteint les lumières de la gare, banc par banc : « On ferme, vous ne pouvez pas rester. » Sans méchanceté, mais il le pense. Le grand hall s'assombrit, et le froid entre.",
 79: "Par la fenêtre du bus, la ville défile, sombre et mouillée. Descendre plus tôt et vous débrouiller, ou rester jusqu'au bon arrêt en faisant confiance au chauffeur ?",
 84: "L'accueil est chaud, sentant le café. La réceptionniste, aimable, vous regarde une seconde de trop : la nuit se lit sur vous — manteau froissé, yeux fatigués — mais elle ne dit rien.",
 88: "Elle arrive sur le pas de la porte, un café et des clés en main, et vous voit attendre, sans surprise : « Vous avez l'air d'avoir passé la nuit dehors. Entrez, avant qu'on gèle tous les deux. »",
 89: "Le quai s'éveille : mouettes sur l'eau grise, un chariot à café, des camionnettes. Vous avez le temps, pour une fois, et les mains propres. Après une telle nuit, être simplement en avance est étrange.",
 90: "L'homme en beau costume de l'agence vous voit le regarder. Un instant, personne ne bouge. Puis il entre dans l'immeuble sans nom et disparaît : vous comprenez quel genre d'endroit vous avez quitté.",
 91: "« Ils ont voulu me prendre de l'argent à moi aussi, pour l'inscription. J'ai failli payer », dit l'autre candidate. Vous n'êtes donc pas le seul — c'est un maigre réconfort.",
 92: "Par la fenêtre, vous voyez le pont franchi dans le noir, l'eau désormais grise et ordinaire. De jour, il n'a plus rien d'effrayant. La plupart des choses, apprenez-vous, à la lumière du jour.",
 94: "Elle appelle un jeune collègue, qui rougit jusqu'aux oreilles : « Le vieux papier à en-tête. On va régler ça. » Puis, à vous : « Et vous pouvez nous aider — vous connaissez le chemin mieux que nous. »",
 95: "La femme du kiosque vous lance : « Il y a un passage à l'arrière du 14, par la cour. La porte de devant ne s'ouvre plus depuis des années. » Elle repart chez elle.",
 97: "La fenêtre du haut s'ouvre, la fillette se penche : « Ils sont au fleuve maintenant. Ada Rowe. Mon père travaillait pour elle, avant tout ça. »",
 98: "« Trois Mill Quay, prenez le bus 4 le matin, il s'arrête juste devant. » Puis la voix de son père la rappelle, la fenêtre se referme, et la rue est de nouveau à vous.",
 99: "Au bord de l'eau, vous perdez le fil des rues. Mais un hangar à bateaux est éclairé : on porte de longues rames vers le fleuve, des voix basses — des gens qui savent où ils vont.",
 100: "« Mill Quay ? Tout droit, après le deuxième pont. Dix minutes. » Le rameur ralentit à peine, une rame sur l'épaule : « Vous y êtes presque, quoi que vous cherchiez. »",
 101: "Le nouvel ensemble a un hall de verre éclairé et vide, une casquette de gardien sur un bureau abandonné. Tout ici a deux ans de moins que votre lettre — et vous les sentez, en habits de la veille.",
 102: "Vous attendez l'ouverture du café. Le ciel passe du noir à la couleur de l'eau de vaisselle. Vos pieds ont cessé de faire mal, ce qui est peut-être pire. Enfin, une lumière s'allume.",
 103: "Un habitué lève les yeux de son thé : « Kessler & Rowe ? J'ai tenu leurs comptes autrefois. De braves gens. Nuls avec le courrier, cela dit. Demandez à qui a attendu une de leurs lettres. »",
 104: "Le patron de l'hôtel : « Un conseil : l'agence en face, l'enseigne jaune ? N'y allez pas. Ils ont pris à un gars son dernier argent mardi ; il est encore dans mon hall, trop honteux pour rentrer. »",
 105: "Le premier bus du jour arrive, chaud et presque vide. Il va vers Rosewater, ou vous pouvez changer pour le fleuve. Dans les deux cas, il avance — c'est déjà plus que vous cette nuit.",
 107: "Une femme dans la file lit le formulaire, le plie et le rend : « C'est une escroquerie. Venez. Tous. » Et quelques-uns, n'osant y croire, la suivent dehors.",
 108: "Le taxi traverse des rues désertes : boutiques closes, un café de nuit jetant sa lumière jaune sur la chaussée mouillée, un renard. Le chauffeur fredonne. Un instant, se laisser porter est presque reposant.",
 109: "L'homme du guichet vous dessine un meilleur plan au dos d'un reçu, marquant le fleuve d'un petit carré : « C'est là que sont allés les malins. Allez-y. Et faites attention à vous. »",
 110: "Vous marchez vers le quai dans la lumière montante, parmi des gens qui savent où ils vont. Pour la première fois, vous aussi — et cela change votre façon de marcher.",
 111: "La jeune femme du 16 va dans la même direction : « Le bus 4, je vous montrerai où descendre. » Elle le dit simplement, comme si aider un inconnu à trouver du travail allait de soi. Ici, peut-être.",
 112: "Vous montez vous expliquer, en retard et essoufflé, répétant vos mots dans l'escalier. Aucun ne sonne juste ; tous commencent par « désolé ». Et vous sentez que « désolé » ne suffira pas ce matin.",
 113: "La femme du chariot à café vous regarde et ajoute une dose, offerte : « Longue nuit. » Ce n'est pas une question. Vous tenez la tasse chaude à deux mains, et la chaleur gagne enfin tout votre corps.",
 114: "Devant le café froid, vous décidez enfin de faire confiance à la lettre — ou du moins à celui qui l'a écrite ; quelqu'un a voulu que vous veniez. Cela compte. Vous rangez la lettre et vous levez.",
 115: "Vous traversez une place de marché déserte, les étals repliés, les pavés luisants sous un réverbère. Un renard trotte dans le caniveau comme s'il était chez lui, vous jette un regard, et vous ignore.",
 116: "Un taxi attend au bord du trottoir, moteur au ralenti, le chauffeur lisant son journal. Cela coûterait plus que vous ne voulez. Mais cela mettrait fin à la marche — qui commence à ressembler à toute votre vie.",
 117: "L'agente d'entretien soupire et cale la porte du pied : « Laissez un mot si vous voulez, je le mettrai sur le bureau d'Ada. Pas de promesse. » Elle tend la main, déjà ailleurs.",
 118: "Vous photographiez le nom à moitié gratté, deux fois, au cas où. Une preuve, en somme, que vous êtes venu et avez regardé, sans abandonner. Pour qui ? Pour vous-même, sans doute. Ça ira.",
 119: "Vous attendez dehors l'ouverture du café, tapant des pieds dans le froid, fixant la carte à la vitre comme si elle pouvait changer d'avis. Elle ne change pas — mais c'est quelque chose à regarder, et vous n'avez plus d'orgueil.",
 122: "La travailleuse de nuit va dans votre direction et partage un taxi : « Vous ne trouverez jamais à pied dans le noir, et vous avez l'air épuisé. » Vous montez, reconnaissant : dix minutes où quelqu'un d'autre connaît le chemin.",
 123: "Le gardien vous fait entrer dans sa guérite chaude et verse quelque chose d'un thermos dans un gobelet en fer : « Neuf heures. Pas avant. Autant attendre au chaud. » Vous serrez la tasse et restez.",
 124: "Dans la file du café, vous entendez le nom avant de voir personne : « …Ada Rowe veut les chiffres de jeudi… » Deux employés du deuxième étage. Vous êtes tout près — vous entendez le matin ordinaire de l'endroit tant cherché.",
 125: "Mara, au petit-déjeuner, a la même idée : « Le fleuve. On pourrait y aller ensemble ; c'est plus sûr, et je déteste arriver seule. » Vous la comprenez, car c'est pareil pour vous. Vous partez ensemble.",
 126: "L'agente d'entretien travaille là depuis vingt ans : « Kessler & Rowe ont bien agi envers ma sœur, quand personne d'autre. Allez les trouver. Ne gâchez pas votre chance sur mon banc. »",
 127: "Vous laissez votre nom et votre numéro à l'homme du comptoir, au cas où. Il les note au dos d'un bon et hoche la tête, comme s'il l'avait entendu bien des fois. Ici, tout le monde cherche quelqu'un.",
 128: "L'aube sur le banc. Le dos en compote, presque plus d'argent — mais vous n'êtes pas prêt à renoncer. Pas encore. Vous vous redressez : le matin est gris, plein de bus, et l'un d'eux va dans votre direction.",
 129: "Vous ne pouvez pas payer la chambre ; l'homme le voit, et quelque chose cède en lui : « Restez dans le hall jusqu'au jour. Il y a un radiateur près de la fenêtre. Je ne vous ai pas vu. » Vous auriez pu pleurer, mais vous restez.",
}

for i, code in enumerate(L):
    data = {str(nid): tr[i] for nid, tr in G.items()}
    if code == "fr":
        data.update({str(k): v for k, v in FR_ONLY.items()})
    json.dump(data, open(os.path.join(OUT, f"{code}.json"), "w", encoding="utf-8"),
              ensure_ascii=False, separators=(",", ":"), sort_keys=True)
print(f"Gists: fr={len(G)+len(FR_ONLY)} (whole book), "
      f"es/it/de/pt={len(G)} each; ru/ar/zh left for native translators")
