#!/usr/bin/env python3
"""Build the coverage-tier dictionary: the book's high-frequency everyday words, so a
learner can tap ANY common word and get a translation (not only the curated hard words).

Emits one compact file per language at content/dict/<lang>.json → { lemma: translation }.
The reader lazy-loads the file for the selected language. Keyed by base form; the reader's
suffix rules catch inflections. This is the "coverage" tier — quick, everyday translations,
distinct from the hand-reviewed curated lexicon; it still flows through the review pipeline.
"""
import json, os

L = ["fr", "es", "pt", "it", "de", "ru", "ar", "zh"]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "dict")
os.makedirs(OUT, exist_ok=True)

# lemma : [fr, es, pt, it, de, ru, ar, zh]  — story-appropriate common sense
M = {
 "say":["dire","decir","dizer","dire","sagen","сказать","يقول","说"],
 "look":["regarder","mirar","olhar","guardare","schauen","смотреть","ينظر","看"],
 "letter":["la lettre","la carta","a carta","la lettera","der Brief","письмо","رسالة","信"],
 "street":["la rue","la calle","a rua","la strada","die Straße","улица","شارع","街道"],
 "door":["la porte","la puerta","a porta","la porta","die Tür","дверь","باب","门"],
 "night":["la nuit","la noche","a noite","la notte","die Nacht","ночь","ليل","夜晚"],
 "know":["savoir","saber","saber","sapere","wissen","знать","يعرف","知道"],
 "number":["le numéro","el número","o número","il numero","die Nummer","номер","رقم","号码"],
 "man":["l'homme","el hombre","o homem","l'uomo","der Mann","мужчина","رجل","男人"],
 "way":["le chemin","el camino","o caminho","la via","der Weg","путь","طريق","路"],
 "river":["la rivière","el río","o rio","il fiume","der Fluss","река","نهر","河"],
 "name":["le nom","el nombre","o nome","il nome","der Name","имя","اسم","名字"],
 "window":["la fenêtre","la ventana","a janela","la finestra","das Fenster","окно","نافذة","窗户"],
 "woman":["la femme","la mujer","a mulher","la donna","die Frau","женщина","امرأة","女人"],
 "hand":["la main","la mano","a mão","la mano","die Hand","рука","يد","手"],
 "someone":["quelqu'un","alguien","alguém","qualcuno","jemand","кто-то","شخص ما","某人"],
 "morning":["le matin","la mañana","a manhã","la mattina","der Morgen","утро","صباح","早晨"],
 "work":["le travail","el trabajo","o trabalho","il lavoro","die Arbeit","работа","عمل","工作"],
 "light":["la lumière","la luz","a luz","la luce","das Licht","свет","ضوء","光"],
 "sit":["s'asseoir","sentarse","sentar-se","sedersi","sitzen","сидеть","يجلس","坐"],
 "wait":["attendre","esperar","esperar","aspettare","warten","ждать","ينتظر","等待"],
 "read":["lire","leer","ler","leggere","lesen","читать","يقرأ","读"],
 "year":["l'année","el año","o ano","l'anno","das Jahr","год","سنة","年"],
 "money":["l'argent","el dinero","o dinheiro","il denaro","das Geld","деньги","مال","钱"],
 "desk":["le bureau","el escritorio","a secretária","la scrivania","der Schreibtisch","стол","مكتب","书桌"],
 "walk":["marcher","caminar","caminhar","camminare","gehen","идти","يمشي","走"],
 "cold":["froid","frío","frio","freddo","kalt","холодный","بارد","冷"],
 "city":["la ville","la ciudad","a cidade","la città","die Stadt","город","مدينة","城市"],
 "ask":["demander","preguntar","perguntar","chiedere","fragen","спрашивать","يسأل","问"],
 "open":["ouvrir","abrir","abrir","aprire","öffnen","открывать","يفتح","打开"],
 "glass":["le verre","el vidrio","o vidro","il vetro","das Glas","стекло","زجاج","玻璃"],
 "bus":["le bus","el autobús","o autocarro","l'autobus","der Bus","автобус","حافلة","公交车"],
 "good":["bon","bueno","bom","buono","gut","хороший","جيد","好"],
 "something":["quelque chose","algo","algo","qualcosa","etwas","что-то","شيء ما","某物"],
 "time":["le temps","el tiempo","o tempo","il tempo","die Zeit","время","وقت","时间"],
 "nothing":["rien","nada","nada","niente","nichts","ничего","لا شيء","没什么"],
 "empty":["vide","vacío","vazio","vuoto","leer","пустой","فارغ","空的"],
 "stand":["se tenir debout","estar de pie","ficar de pé","stare in piedi","stehen","стоять","يقف","站"],
 "small":["petit","pequeño","pequeno","piccolo","klein","маленький","صغير","小的"],
 "see":["voir","ver","ver","vedere","sehen","видеть","يرى","看见"],
 "address":["l'adresse","la dirección","o endereço","l'indirizzo","die Adresse","адрес","عنوان","地址"],
 "stop":["arrêter","parar","parar","fermare","anhalten","останавливаться","يتوقف","停"],
 "coffee":["le café","el café","o café","il caffè","der Kaffee","кофе","قهوة","咖啡"],
 "people":["les gens","la gente","as pessoas","la gente","die Leute","люди","الناس","人们"],
 "water":["l'eau","el agua","a água","l'acqua","das Wasser","вода","ماء","水"],
 "turn":["tourner","girar","virar","girare","drehen","поворачивать","يدور","转"],
 "outside":["dehors","fuera","fora","fuori","draußen","снаружи","في الخارج","外面"],
 "move":["bouger","mover","mover","muovere","bewegen","двигать","يتحرك","移动"],
 "come":["venir","venir","vir","venire","kommen","приходить","يأتي","来"],
 "tell":["dire","decir","dizer","dire","erzählen","рассказывать","يخبر","告诉"],
 "hour":["l'heure","la hora","a hora","l'ora","die Stunde","час","ساعة","小时"],
 "warm":["chaud","cálido","quente","caldo","warm","тёплый","دافئ","温暖的"],
 "watch":["observer","observar","observar","osservare","beobachten","наблюдать","يراقب","观察"],
 "feel":["sentir","sentir","sentir","sentire","fühlen","чувствовать","يشعر","感觉"],
 "dark":["sombre","oscuro","escuro","buio","dunkel","тёмный","مظلم","黑暗的"],
 "old":["vieux","viejo","velho","vecchio","alt","старый","قديم","旧的"],
 "gone":["parti","ido","ido","andato","weg","ушёл","ذهب","走了"],
 "new":["nouveau","nuevo","novo","nuovo","neu","новый","جديد","新的"],
 "today":["aujourd'hui","hoy","hoje","oggi","heute","сегодня","اليوم","今天"],
 "grey":["gris","gris","cinzento","grigio","grau","серый","رمادي","灰色的"],
 "inside":["à l'intérieur","dentro","dentro","dentro","drinnen","внутри","في الداخل","里面"],
 "clean":["propre","limpio","limpo","pulito","sauber","чистый","نظيف","干净的"],
 "kind":["gentil","amable","gentil","gentile","freundlich","добрый","لطيف","善良的"],
 "station":["la gare","la estación","a estação","la stazione","der Bahnhof","вокзал","محطة","车站"],
 "paper":["le papier","el papel","o papel","la carta","das Papier","бумага","ورق","纸"],
 "nobody":["personne","nadie","ninguém","nessuno","niemand","никто","لا أحد","没有人"],
 "want":["vouloir","querer","querer","volere","wollen","хотеть","يريد","想要"],
 "find":["trouver","encontrar","encontrar","trovare","finden","находить","يجد","找到"],
 "job":["l'emploi","el empleo","o emprego","il lavoro","der Job","работа","وظيفة","工作"],
 "word":["le mot","la palabra","a palavra","la parola","das Wort","слово","كلمة","词"],
 "take":["prendre","tomar","pegar","prendere","nehmen","брать","يأخذ","拿"],
 "tired":["fatigué","cansado","cansado","stanco","müde","усталый","متعب","累的"],
 "building":["le bâtiment","el edificio","o edifício","l'edificio","das Gebäude","здание","مبنى","建筑"],
 "somewhere":["quelque part","en algún lugar","algures","da qualche parte","irgendwo","где-то","في مكان ما","某处"],
 "yellow":["jaune","amarillo","amarelo","giallo","gelb","жёлтый","أصفر","黄色的"],
 "moment":["le moment","el momento","o momento","il momento","der Moment","момент","لحظة","时刻"],
 "driver":["le chauffeur","el conductor","o motorista","l'autista","der Fahrer","водитель","سائق","司机"],
 "close":["fermer","cerrar","fechar","chiudere","schließen","закрывать","يغلق","关闭"],
 "corner":["le coin","la esquina","a esquina","l'angolo","die Ecke","угол","زاوية","角落"],
 "train":["le train","el tren","o comboio","il treno","der Zug","поезд","قطار","火车"],
 "arrive":["arriver","llegar","chegar","arrivare","ankommen","прибывать","يصل","到达"],
 "start":["commencer","empezar","começar","cominciare","anfangen","начинать","يبدأ","开始"],
 "office":["le bureau","la oficina","o escritório","l'ufficio","das Büro","офис","مكتب","办公室"],
 "early":["tôt","temprano","cedo","presto","früh","рано","مبكرا","早"],
 "sign":["le panneau","el letrero","o letreiro","l'insegna","das Schild","вывеска","لافتة","招牌"],
 "wrong":["faux","incorrecto","errado","sbagliato","falsch","неправильный","خطأ","错误的"],
 "enough":["assez","suficiente","suficiente","abbastanza","genug","достаточно","كافٍ","足够"],
 "call":["appeler","llamar","chamar","chiamare","anrufen","звонить","يتصل","打电话"],
 "cost":["coûter","costar","custar","costare","kosten","стоить","يكلف","花费"],
 "suit":["le costume","el traje","o fato","l'abito","der Anzug","костюм","بدلة","西装"],
 "cup":["la tasse","la taza","a chávena","la tazza","die Tasse","чашка","كوب","杯子"],
 "twice":["deux fois","dos veces","duas vezes","due volte","zweimal","дважды","مرتين","两次"],
 "hold":["tenir","sostener","segurar","tenere","halten","держать","يمسك","握住"],
 "somebody":["quelqu'un","alguien","alguém","qualcuno","jemand","кто-то","شخص ما","某人"],
 "key":["la clé","la llave","a chave","la chiave","der Schlüssel","ключ","مفتاح","钥匙"],
 "quietly":["doucement","en voz baja","baixinho","silenziosamente","leise","тихо","بهدوء","安静地"],
 "bag":["le sac","la bolsa","o saco","la borsa","die Tasche","сумка","حقيبة","包"],
 "mean":["vouloir dire","significar","significar","significare","bedeuten","значить","يعني","意思是"],
 "minute":["la minute","el minuto","o minuto","il minuto","die Minute","минута","دقيقة","分钟"],
 "thing":["la chose","la cosa","a coisa","la cosa","das Ding","вещь","شيء","东西"],
 "everyone":["tout le monde","todos","todos","tutti","jeder","все","الجميع","每个人"],
 "hundred":["cent","cien","cem","cento","hundert","сто","مئة","一百"],
 "map":["la carte","el mapa","o mapa","la mappa","die Karte","карта","خريطة","地图"],
 "taxi":["le taxi","el taxi","o táxi","il taxi","das Taxi","такси","سيارة أجرة","出租车"],
 "everything":["tout","todo","tudo","tutto","alles","всё","كل شيء","一切"],
 "chair":["la chaise","la silla","a cadeira","la sedia","der Stuhl","стул","كرسي","椅子"],
 "place":["l'endroit","el lugar","o lugar","il posto","der Ort","место","مكان","地方"],
 "think":["penser","pensar","pensar","pensare","denken","думать","يفكر","想"],
 "road":["la route","la carretera","a estrada","la strada","die Straße","дорога","طريق","路"],
 "shut":["fermer","cerrar","fechar","chiudere","schließen","закрывать","يغلق","关"],
 "home":["la maison","la casa","casa","casa","das Zuhause","дом","بيت","家"],
 "write":["écrire","escribir","escrever","scrivere","schreiben","писать","يكتب","写"],
 "person":["la personne","la persona","a pessoa","la persona","die Person","человек","شخص","人"],
 "wet":["mouillé","mojado","molhado","bagnato","nass","мокрый","مبلل","湿的"],
 "whole":["entier","entero","inteiro","intero","ganz","целый","كامل","整个的"],
 "eye":["l'œil","el ojo","o olho","l'occhio","das Auge","глаз","عين","眼睛"],
 "reach":["atteindre","alcanzar","alcançar","raggiungere","erreichen","достигать","يصل إلى","到达"],
 "sorry":["désolé","lo siento","desculpe","scusa","Entschuldigung","извините","آسف","对不起"],
 "bridge":["le pont","el puente","a ponte","il ponte","die Brücke","мост","جسر","桥"],
 "front":["le devant","el frente","a frente","il davanti","die Vorderseite","перёд","أمام","前面"],
 "head":["la tête","la cabeza","a cabeça","la testa","der Kopf","голова","رأس","头"],
 "side":["le côté","el lado","o lado","il lato","die Seite","сторона","جانب","边"],
 "pay":["payer","pagar","pagar","pagare","bezahlen","платить","يدفع","付款"],
 "face":["le visage","la cara","o rosto","il viso","das Gesicht","лицо","وجه","脸"],
 "hurry":["se dépêcher","apurarse","apressar-se","affrettarsi","sich beeilen","спешить","يسرع","匆忙"],
 "phone":["le téléphone","el teléfono","o telefone","il telefono","das Telefon","телефон","هاتف","电话"],
 "room":["la chambre","la habitación","o quarto","la stanza","das Zimmer","комната","غرفة","房间"],
 "decide":["décider","decidir","decidir","decidere","entscheiden","решать","يقرر","决定"],
 "stay":["rester","quedarse","ficar","restare","bleiben","оставаться","يبقى","停留"],
 "alone":["seul","solo","sozinho","solo","allein","один","وحيد","独自"],
 "last":["dernier","último","último","ultimo","letzte","последний","أخير","最后的"],
 "first":["premier","primero","primeiro","primo","erste","первый","أول","第一"],
 "long":["long","largo","longo","lungo","lang","длинный","طويل","长的"],
 "behind":["derrière","detrás","atrás","dietro","hinter","позади","خلف","后面"],
 "leave":["partir","salir","sair","partire","verlassen","уходить","يغادر","离开"],
 "give":["donner","dar","dar","dare","geben","давать","يعطي","给"],
}

# --- batch 2: numbers, more everyday words, and common irregular past forms ---
M.update({
 "two":["deux","dos","dois","due","zwei","два","اثنان","二"],
 "three":["trois","tres","três","tre","drei","три","ثلاثة","三"],
 "four":["quatre","cuatro","quatro","quattro","vier","четыре","أربعة","四"],
 "five":["cinq","cinco","cinco","cinque","fünf","пять","خمسة","五"],
 "six":["six","seis","seis","sei","sechs","шесть","ستة","六"],
 "seven":["sept","siete","sete","sette","sieben","семь","سبعة","七"],
 "eight":["huit","ocho","oito","otto","acht","восемь","ثمانية","八"],
 "nine":["neuf","nueve","nove","nove","neun","девять","تسعة","九"],
 "ten":["dix","diez","dez","dieci","zehn","десять","عشرة","十"],
 "eleven":["onze","once","onze","undici","elf","одиннадцать","أحد عشر","十一"],
 "twelve":["douze","doce","doze","dodici","zwölf","двенадцать","اثنا عشر","十二"],
 "twenty":["vingt","veinte","vinte","venti","zwanzig","двадцать","عشرون","二十"],
 "second":["deuxième","segundo","segundo","secondo","zweite","второй","ثانٍ","第二"],
 "third":["troisième","tercero","terceiro","terzo","dritte","третий","ثالث","第三"],
 "back":["en arrière","atrás","de volta","indietro","zurück","назад","إلى الخلف","回"],
 "near":["près de","cerca de","perto de","vicino a","nahe","рядом","قريب","靠近"],
 "still":["encore","todavía","ainda","ancora","noch","всё ещё","لا يزال","仍然"],
 "now":["maintenant","ahora","agora","adesso","jetzt","сейчас","الآن","现在"],
 "about":["à propos de","sobre","sobre","riguardo a","über","о","حول","关于"],
 "past":["passé","pasado","passado","passato","vorbei","мимо","ماضٍ","过去"],
 "half":["la moitié","la mitad","a metade","la metà","die Hälfte","половина","نصف","一半"],
 "almost":["presque","casi","quase","quasi","fast","почти","تقريبا","几乎"],
 "through":["à travers","a través de","através de","attraverso","durch","через","عبر","穿过"],
 "along":["le long de","a lo largo de","ao longo de","lungo","entlang","вдоль","على طول","沿着"],
 "exactly":["exactement","exactamente","exatamente","esattamente","genau","точно","بالضبط","确切地"],
 "never":["jamais","nunca","nunca","mai","nie","никогда","أبدا","从不"],
 "without":["sans","sin","sem","senza","ohne","без","بدون","没有"],
 "other":["autre","otro","outro","altro","andere","другой","آخر","其他"],
 "little":["petit","poco","pouco","poco","wenig","маленький","قليل","少"],
 "same":["même","mismo","mesmo","stesso","gleich","тот же","نفس","相同"],
 "black":["noir","negro","preto","nero","schwarz","чёрный","أسود","黑色的"],
 "away":["loin","lejos","longe","via","weg","прочь","بعيدا","离开"],
 "better":["meilleur","mejor","melhor","migliore","besser","лучше","أفضل","更好"],
 "ago":["il y a","hace","atrás","fa","vor","назад","منذ","以前"],
 "right":["droite/juste","derecha/correcto","direita/certo","destra/giusto","rechts/richtig","правильно","صحيح","对"],
 "already":["déjà","ya","já","già","schon","уже","بالفعل","已经"],
 "own":["propre","propio","próprio","proprio","eigen","собственный","خاص","自己的"],
 "both":["les deux","ambos","ambos","entrambi","beide","оба","كلاهما","两者"],
 "toward":["vers","hacia","em direção a","verso","zu","к","نحو","朝向"],
 "left":["gauche","izquierda","esquerda","sinistra","links","левый","يسار","左"],
 "since":["depuis","desde","desde","da","seit","с тех пор","منذ","自从"],
 "far":["loin","lejos","longe","lontano","weit","далеко","بعيد","远"],
 "else":["autre","más","mais","altro","sonst","ещё","آخر","别的"],
 "yourself":["toi-même","tú mismo","você mesmo","te stesso","selbst","сам","نفسك","你自己"],
 "cafe":["le café","el café","o café","il caffè","das Café","кафе","مقهى","咖啡馆"],
 "quite":["assez","bastante","bastante","piuttosto","ziemlich","довольно","تماما","相当"],
 "cannot":["ne peut pas","no puede","não pode","non può","kann nicht","не может","لا يستطيع","不能"],
 "whatever":["quoi que ce soit","lo que sea","seja o que for","qualunque","was auch immer","что бы ни","مهما","无论什么"],
 "single":["seul","único","único","singolo","einzeln","единственный","واحد","单一的"],
 "slow":["lent","lento","lento","lento","langsam","медленный","بطيء","慢的"],
 "put":["mettre","poner","pôr","mettere","setzen","класть","يضع","放"],
 "carry":["porter","llevar","carregar","portare","tragen","нести","يحمل","携带"],
 "coat":["le manteau","el abrigo","o casaco","il cappotto","der Mantel","пальто","معطف","外套"],
 "complete":["complet","completo","completo","completo","vollständig","полный","كامل","完整的"],
 "late":["tard","tarde","tarde","tardi","spät","поздно","متأخر","晚"],
 "smell":["l'odeur","el olor","o cheiro","l'odore","der Geruch","запах","رائحة","气味"],
 "worse":["pire","peor","pior","peggio","schlimmer","хуже","أسوأ","更糟"],
 "until":["jusqu'à","hasta","até","fino a","bis","до","حتى","直到"],
 "sleep":["dormir","dormir","dormir","dormire","schlafen","спать","ينام","睡觉"],
 "business":["l'affaire","el negocio","o negócio","l'affare","das Geschäft","дело","عمل","事务"],
 "trust":["faire confiance","confiar","confiar","fidarsi","vertrauen","доверять","يثق","信任"],
 "floor":["le sol/l'étage","el suelo/piso","o chão/andar","il pavimento/piano","der Boden/Stock","пол/этаж","أرضية/طابق","地板/楼层"],
 "real":["vrai","real","real","reale","echt","настоящий","حقيقي","真实的"],
 "question":["la question","la pregunta","a pergunta","la domanda","die Frage","вопрос","سؤال","问题"],
 "show":["montrer","mostrar","mostrar","mostrare","zeigen","показывать","يظهر","展示"],
 "anyone":["n'importe qui","cualquiera","qualquer um","chiunque","irgendjemand","кто-нибудь","أي شخص","任何人"],
 "stranger":["l'inconnu","el desconocido","o estranho","lo sconosciuto","der Fremde","незнакомец","غريب","陌生人"],
 "let":["laisser","dejar","deixar","lasciare","lassen","позволять","يترك","让"],
 "count":["compter","contar","contar","contare","zählen","считать","يعد","数"],
 "car":["la voiture","el coche","o carro","l'auto","das Auto","машина","سيارة","汽车"],
 "yet":["encore","todavía","ainda","ancora","noch","ещё","بعد","还"],
 "card":["la carte","la tarjeta","o cartão","la carta","die Karte","карточка","بطاقة","卡片"],
 "smile":["sourire","sonreír","sorrir","sorridere","lächeln","улыбаться","يبتسم","微笑"],
 "everybody":["tout le monde","todos","todos","tutti","jeder","все","الجميع","每个人"],
 "young":["jeune","joven","jovem","giovane","jung","молодой","شاب","年轻的"],
 "help":["aider","ayudar","ajudar","aiutare","helfen","помогать","يساعد","帮助"],
 "spring":["le printemps","la primavera","a primavera","la primavera","der Frühling","весна","الربيع","春天"],
 "round":["rond/autour","redondo/alrededor","redondo/à volta","rotondo/intorno","rund/herum","круглый","حول","圆/周围"],
 "story":["l'histoire","la historia","a história","la storia","die Geschichte","история","قصة","故事"],
 "full":["plein","lleno","cheio","pieno","voll","полный","ممتلئ","满的"],
 "strange":["étrange","extraño","estranho","strano","seltsam","странный","غريب","奇怪的"],
 "understand":["comprendre","entender","entender","capire","verstehen","понимать","يفهم","理解"],
 "square":["la place","la plaza","a praça","la piazza","der Platz","площадь","ساحة","广场"],
 "mind":["l'esprit","la mente","a mente","la mente","der Verstand","ум","عقل","头脑"],
 "lost":["perdu","perdido","perdido","perso","verloren","потерянный","ضائع","迷路的"],
 "hear":["entendre","oír","ouvir","sentire","hören","слышать","يسمع","听见"],
 "hurt":["faire mal","doler","doer","far male","wehtun","болеть","يؤلم","疼"],
 "final":["final","final","final","finale","endgültig","окончательный","نهائي","最后的"],
 "bright":["lumineux","brillante","brilhante","luminoso","hell","яркий","ساطع","明亮的"],
 "anything":["n'importe quoi","cualquier cosa","qualquer coisa","qualsiasi cosa","irgendetwas","что-нибудь","أي شيء","任何东西"],
 "quiet":["calme","tranquilo","quieto","tranquillo","ruhig","тихий","هادئ","安静的"],
 "answer":["répondre","responder","responder","rispondere","antworten","отвечать","يجيب","回答"],
 "use":["utiliser","usar","usar","usare","benutzen","использовать","يستخدم","使用"],
 "send":["envoyer","enviar","enviar","inviare","senden","отправлять","يرسل","发送"],
 "line":["la ligne","la línea","a linha","la linea","die Linie","линия","خط","线"],
 "shop":["le magasin","la tienda","a loja","il negozio","der Laden","магазин","متجر","商店"],
 "hut":["la cabane","la caseta","a cabana","la capanna","die Hütte","хижина","كوخ","小屋"],
 "sense":["le sens","el sentido","o sentido","il senso","der Sinn","смысл","معنى","意义"],
 "change":["changer","cambiar","mudar","cambiare","ändern","менять","يغير","改变"],
 "big":["grand","grande","grande","grande","groß","большой","كبير","大的"],
 "reason":["la raison","la razón","a razão","la ragione","der Grund","причина","سبب","原因"],
 "air":["l'air","el aire","o ar","l'aria","die Luft","воздух","هواء","空气"],
 "clear":["clair","claro","claro","chiaro","klar","ясный","واضح","清楚的"],
 "point":["le point","el punto","o ponto","il punto","der Punkt","точка","نقطة","点"],
 "wall":["le mur","la pared","a parede","il muro","die Wand","стена","جدار","墙"],
 "machine":["la machine","la máquina","a máquina","la macchina","die Maschine","машина","آلة","机器"],
 "great":["formidable","genial","ótimo","grande","großartig","отличный","عظيم","很棒的"],
 "luck":["la chance","la suerte","a sorte","la fortuna","das Glück","удача","حظ","运气"],
 "counter":["le comptoir","el mostrador","o balcão","il bancone","die Theke","прилавок","منضدة","柜台"],
 "fix":["réparer","arreglar","consertar","riparare","reparieren","чинить","يصلح","修理"],
 "piece":["le morceau","el trozo","o pedaço","il pezzo","das Stück","кусок","قطعة","一块"],
 "miss":["manquer","perder","perder","perdere","verpassen","пропустить","يفوت","错过"],
 "simple":["simple","simple","simples","semplice","einfach","простой","بسيط","简单的"],
 "plain":["simple","sencillo","simples","semplice","schlicht","простой","بسيط","朴素的"],
 "cross":["traverser","cruzar","atravessar","attraversare","überqueren","пересекать","يعبر","穿过"],
 "low":["bas","bajo","baixo","basso","niedrig","низкий","منخفض","低的"],
 "form":["le formulaire","el formulario","o formulário","il modulo","das Formular","бланк","استمارة","表格"],
 "catch":["attraper","atrapar","apanhar","prendere","fangen","ловить","يمسك","抓住"],
 "foot":["le pied","el pie","o pé","il piede","der Fuß","нога","قدم","脚"],
 "sure":["sûr","seguro","certo","sicuro","sicher","уверенный","متأكد","确定的"],
 "expect":["s'attendre à","esperar","esperar","aspettarsi","erwarten","ожидать","يتوقع","期待"],
 "idea":["l'idée","la idea","a ideia","l'idea","die Idee","идея","فكرة","主意"],
 "laugh":["rire","reír","rir","ridere","lachen","смеяться","يضحك","笑"],
 "careful":["prudent","cuidadoso","cuidadoso","attento","vorsichtig","осторожный","حذر","小心的"],
 "hotel":["l'hôtel","el hotel","o hotel","l'hotel","das Hotel","отель","فندق","酒店"],
 "wake":["se réveiller","despertar","acordar","svegliarsi","aufwachen","просыпаться","يستيقظ","醒来"],
 "finish":["finir","terminar","terminar","finire","beenden","заканчивать","ينهي","完成"],
 "hot":["chaud","caliente","quente","caldo","heiß","горячий","حار","热的"],
 "stone":["la pierre","la piedra","a pedra","la pietra","der Stein","камень","حجر","石头"],
 "type":["le type","el tipo","o tipo","il tipo","die Art","тип","نوع","类型"],
 "listen":["écouter","escuchar","ouvir","ascoltare","zuhören","слушать","يستمع","听"],
 "print":["imprimer","imprimir","imprimir","stampare","drucken","печать","طباعة","印刷"],
 "ring":["sonner","sonar","tocar","suonare","klingeln","звонить","يرن","响"],
 "together":["ensemble","juntos","juntos","insieme","zusammen","вместе","معا","一起"],
 "book":["le livre","el libro","o livro","il libro","das Buch","книга","كتاب","书"],
 "upstairs":["à l'étage","arriba","lá em cima","di sopra","oben","наверху","في الطابق العلوي","楼上"],
 "girl":["la fille","la niña","a menina","la ragazza","das Mädchen","девочка","فتاة","女孩"],
 "breakfast":["le petit-déjeuner","el desayuno","o café da manhã","la colazione","das Frühstück","завтрак","فطور","早餐"],
 "return":["revenir","volver","voltar","tornare","zurückkehren","возвращаться","يعود","返回"],
 "smart":["élégant","elegante","elegante","elegante","schick","элегантный","أنيق","时髦的"],
 "yard":["la cour","el patio","o pátio","il cortile","der Hof","двор","فناء","院子"],
 "stamp":["le timbre","el sello","o selo","il francobollo","die Briefmarke","марка","طابع","邮票"],
 "ready":["prêt","listo","pronto","pronto","bereit","готовый","جاهز","准备好的"],
 "push":["pousser","empujar","empurrar","spingere","drücken","толкать","يدفع","推"],
 "beside":["à côté de","al lado de","ao lado de","accanto a","neben","рядом с","بجانب","旁边"],
 "against":["contre","contra","contra","contro","gegen","против","ضد","靠着"],
 "pocket":["la poche","el bolsillo","o bolso","la tasca","die Tasche","карман","جيب","口袋"],
 "heart":["le cœur","el corazón","o coração","il cuore","das Herz","сердце","قلب","心"],
 "pull":["tirer","tirar","puxar","tirare","ziehen","тянуть","يسحب","拉"],
 "need":["avoir besoin de","necesitar","precisar","avere bisogno","brauchen","нуждаться","يحتاج","需要"],
 "shake":["secouer","sacudir","sacudir","scuotere","schütteln","трясти","يهز","摇"],
 "happen":["se passer","pasar","acontecer","succedere","passieren","случаться","يحدث","发生"],
 "dress":["la robe","el vestido","o vestido","il vestito","das Kleid","платье","فستان","连衣裙"],
 "thank":["remercier","agradecer","agradecer","ringraziare","danken","благодарить","يشكر","感谢"],
 "part":["la partie","la parte","a parte","la parte","der Teil","часть","جزء","部分"],
 "deal":["l'accord","el trato","o acordo","l'accordo","der Deal","сделка","صفقة","交易"],
 "next":["prochain","próximo","próximo","prossimo","nächste","следующий","التالي","下一个"],
 "date":["la date","la fecha","a data","la data","das Datum","дата","تاريخ","日期"],
 "run":["courir","correr","correr","correre","laufen","бежать","يجري","跑"],
 "top":["le haut","la parte de arriba","o topo","la cima","die Spitze","верх","أعلى","顶部"],
 "sound":["le son","el sonido","o som","il suono","der Klang","звук","صوت","声音"],
 "company":["l'entreprise","la empresa","a empresa","l'azienda","die Firma","компания","شركة","公司"],
 "lock":["verrouiller","cerrar con llave","trancar","chiudere a chiave","abschließen","запирать","يقفل","锁"],
 "day":["le jour","el día","o dia","il giorno","der Tag","день","يوم","天"],
 "around":["autour","alrededor","à volta","intorno","herum","вокруг","حول","周围"],
 "beneath":["sous","debajo de","sob","sotto","unter","под","تحت","下面"],
 "perhaps":["peut-être","quizás","talvez","forse","vielleicht","возможно","ربما","也许"],
 "step":["le pas/la marche","el paso/escalón","o passo/degrau","il passo/gradino","der Schritt/die Stufe","шаг/ступенька","خطوة/درجة","脚步/台阶"],
 "try":["essayer","intentar","tentar","provare","versuchen","пытаться","يحاول","尝试"],
 "draw":["dessiner","dibujar","desenhar","disegnare","zeichnen","рисовать","يرسم","画"],
 "mark":["la marque","la marca","a marca","il segno","die Marke","метка","علامة","标记"],
 "hall":["le hall","el vestíbulo","o hall","l'atrio","die Halle","зал","قاعة","大厅"],
 "case":["le cas","el caso","o caso","il caso","der Fall","случай","حالة","情况"],
 "worth":["valoir","valer","valer","valere","wert","стоящий","يستحق","值得"],
 "list":["la liste","la lista","a lista","la lista","die Liste","список","قائمة","清单"],
 "father":["le père","el padre","o pai","il padre","der Vater","отец","أب","父亲"],
 "speak":["parler","hablar","falar","parlare","sprechen","говорить","يتحدث","说话"],
 "end":["la fin","el final","o fim","la fine","das Ende","конец","نهاية","结束"],
 "figure":["la silhouette","la figura","a figura","la figura","die Gestalt","фигура","شخص","身影"],
 "either":["l'un ou l'autre","cualquiera","qualquer","l'uno o l'altro","entweder","любой","أي","任一"],
 "hard":["dur","duro","duro","duro","hart","трудный","صعب","难的"],
 "thin":["mince","delgado","fino","sottile","dünn","тонкий","رفيع","薄的"],
 "hope":["espérer","esperar","esperar","sperare","hoffen","надеяться","يأمل","希望"],
 "spare":["de rechange","de repuesto","sobressalente","di scorta","Ersatz-","запасной","احتياطي","备用的"],
 "always":["toujours","siempre","sempre","sempre","immer","всегда","دائما","总是"],
 "talk":["parler","hablar","falar","parlare","reden","говорить","يتكلم","谈话"],
 "paint":["la peinture","la pintura","a tinta","la vernice","die Farbe","краска","طلاء","油漆"],
 "finger":["le doigt","el dedo","o dedo","il dito","der Finger","палец","إصبع","手指"],
 "sort":["la sorte","el tipo","o tipo","il tipo","die Sorte","вид","نوع","种类"],
 "proof":["la preuve","la prueba","a prova","la prova","der Beweis","доказательство","دليل","证据"],
 "chance":["la chance","la oportunidad","a chance","la possibilità","die Chance","шанс","فرصة","机会"],
 "seem":["sembler","parecer","parecer","sembrare","scheinen","казаться","يبدو","似乎"],
 "grow":["grandir","crecer","crescer","crescere","wachsen","расти","ينمو","生长"],
 "white":["blanc","blanco","branco","bianco","weiß","белый","أبيض","白色的"],
 "above":["au-dessus","encima","acima","sopra","über","над","فوق","上面"],
 "probably":["probablement","probablemente","provavelmente","probabilmente","wahrscheinlich","вероятно","على الأرجح","大概"],
 "comfortable":["confortable","cómodo","confortável","comodo","bequem","удобный","مريح","舒适的"],
 "free":["libre/gratuit","libre/gratis","livre/grátis","libero/gratis","frei/kostenlos","свободный/бесплатный","حر/مجاني","自由的/免费的"],
 "photo":["la photo","la foto","a foto","la foto","das Foto","фото","صورة","照片"],
 "gap":["l'écart","el hueco","a fenda","lo spazio","die Lücke","щель","فجوة","缝隙"],
 "brother":["le frère","el hermano","o irmão","il fratello","der Bruder","брат","أخ","兄弟"],
 "mother":["la mère","la madre","a mãe","la madre","die Mutter","мать","أم","母亲"],
 "morning":["le matin","la mañana","a manhã","la mattina","der Morgen","утро","صباح","早晨"],
 # common irregular past forms (won't resolve to their base via the suffix rules)
 "said":["dit","dijo","disse","detto","sagte","сказал","قال","说过"],
 "came":["est venu","vino","veio","è venuto","kam","пришёл","جاء","来了"],
 "went":["est allé","fue","foi","è andato","ging","пошёл","ذهب","去了"],
 "got":["a obtenu","obtuvo","obteve","ha ottenuto","bekam","получил","حصل","得到了"],
 "took":["a pris","tomó","pegou","ha preso","nahm","взял","أخذ","拿了"],
 "wrote":["a écrit","escribió","escreveu","ha scritto","schrieb","написал","كتب","写了"],
 "told":["a dit","dijo","disse","ha detto","erzählte","сказал","أخبر","告诉了"],
 "found":["a trouvé","encontró","encontrou","ha trovato","fand","нашёл","وجد","找到了"],
 "heard":["a entendu","oyó","ouviu","ha sentito","hörte","услышал","سمع","听到了"],
 "meant":["voulait dire","significaba","significava","significava","meinte","имел в виду","قصد","意思是"],
 "learnt":["a appris","aprendió","aprendeu","ha imparato","lernte","узнал","تعلم","学到了"],
})

# --- batch 3: the next tier of common vocabulary + a few more irregular pasts ---
M.update({
 "across":["à travers","a través","através","attraverso","über","через","عبر","穿过"],
 "go":["aller","ir","ir","andare","gehen","идти","يذهب","去"],
 "like":["aimer/comme","gustar/como","gostar/como","piacere/come","mögen/wie","нравиться/как","مثل","像/喜欢"],
 "off":["éteint/hors","apagado/fuera","desligado/fora","spento/via","aus","выключенный","مطفأ","关/离"],
 "get":["obtenir","conseguir","obter","ottenere","bekommen","получать","يحصل","得到"],
 "post":["le courrier","el correo","o correio","la posta","die Post","почта","بريد","邮件"],
 "even":["même","incluso","até","perfino","sogar","даже","حتى","甚至"],
 "till":["jusqu'à","hasta","até","fino a","bis","до","حتى","直到"],
 "maybe":["peut-être","quizás","talvez","forse","vielleicht","может быть","ربما","也许"],
 "lot":["beaucoup","mucho","muito","molto","viel","много","كثير","很多"],
 "another":["un autre","otro","outro","un altro","noch ein","ещё один","آخر","另一个"],
 "bank":["la banque/la berge","el banco/la orilla","o banco/a margem","la banca/la riva","die Bank/das Ufer","банк/берег","بنك/ضفة","银行/岸"],
 "delivery":["la livraison","la entrega","a entrega","la consegna","die Lieferung","доставка","توصيل","送货"],
 "anywhere":["n'importe où","en cualquier lugar","em qualquer lugar","dovunque","irgendwo","где угодно","في أي مكان","任何地方"],
 "tonight":["ce soir","esta noche","esta noite","stasera","heute Abend","сегодня вечером","الليلة","今晚"],
 "except":["sauf","excepto","exceto","tranne","außer","кроме","إلا","除了"],
 "surprise":["la surprise","la sorpresa","a surpresa","la sorpresa","die Überraschung","сюрприз","مفاجأة","惊讶"],
 "keep":["garder","guardar","guardar","tenere","behalten","держать","يحتفظ","保持"],
 "joke":["la blague","el chiste","a piada","lo scherzo","der Witz","шутка","نكتة","玩笑"],
 "honest":["honnête","honesto","honesto","onesto","ehrlich","честный","صادق","诚实的"],
 "green":["vert","verde","verde","verde","grün","зелёный","أخضر","绿色的"],
 "plant":["la plante","la planta","a planta","la pianta","die Pflanze","растение","نبات","植物"],
 "kitchen":["la cuisine","la cocina","a cozinha","la cucina","die Küche","кухня","مطبخ","厨房"],
 "park":["le parc","el parque","o parque","il parco","der Park","парк","حديقة","公园"],
 "believe":["croire","creer","acreditar","credere","glauben","верить","يصدق","相信"],
 "certain":["certain","cierto","certo","certo","sicher","определённый","مؤكد","确定的"],
 "sixty":["soixante","sesenta","sessenta","sessanta","sechzig","шестьдесят","ستون","六十"],
 "set":["poser","poner","pôr","posare","stellen","ставить","يضع","放置"],
 "quarter":["le quart","el cuarto","o quarto","il quarto","das Viertel","четверть","ربع","四分之一"],
 "begin":["commencer","empezar","começar","cominciare","beginnen","начинать","يبدأ","开始"],
 "ticket":["le billet","el billete","o bilhete","il biglietto","die Fahrkarte","билет","تذكرة","票"],
 "platform":["le quai","el andén","a plataforma","il binario","der Bahnsteig","платформа","رصيف","站台"],
 "exit":["la sortie","la salida","a saída","l'uscita","der Ausgang","выход","مخرج","出口"],
 "traveller":["le voyageur","el viajero","o viajante","il viaggiatore","der Reisende","путешественник","مسافر","旅客"],
 "lie":["mentir/s'allonger","mentir/tumbarse","mentir/deitar","mentire/sdraiarsi","lügen/liegen","лгать/лежать","يكذب/يستلقي","撒谎/躺"],
 "month":["le mois","el mes","o mês","il mese","der Monat","месяц","شهر","月"],
 "matter":["importer","importar","importar","importare","wichtig sein","иметь значение","يهم","要紧"],
 "problem":["le problème","el problema","o problema","il problema","das Problem","проблема","مشكلة","问题"],
 "notice":["remarquer","notar","notar","notare","bemerken","замечать","يلاحظ","注意"],
 "thick":["épais","grueso","grosso","spesso","dick","толстый","سميك","厚的"],
 "accident":["l'accident","el accidente","o acidente","l'incidente","der Unfall","несчастный случай","حادث","事故"],
 "rest":["le repos/le reste","el descanso/el resto","o descanso/o resto","il riposo/il resto","die Ruhe/der Rest","отдых/остаток","راحة/بقية","休息/其余"],
 "sell":["vendre","vender","vender","vendere","verkaufen","продавать","يبيع","卖"],
 "share":["partager","compartir","partilhar","condividere","teilen","делить","يشارك","分享"],
 "pair":["la paire","el par","o par","la coppia","das Paar","пара","زوج","一对"],
 "perfect":["parfait","perfecto","perfeito","perfetto","perfekt","идеальный","مثالي","完美的"],
 "belong":["appartenir","pertenecer","pertencer","appartenere","gehören","принадлежать","ينتمي","属于"],
 "towel":["la serviette","la toalla","a toalha","l'asciugamano","das Handtuch","полотенце","منشفة","毛巾"],
 "odd":["étrange","raro","estranho","strano","seltsam","странный","غريب","奇怪的"],
 "high":["haut","alto","alto","alto","hoch","высокий","عالٍ","高的"],
 "save":["sauver/économiser","salvar/ahorrar","salvar/poupar","salvare/risparmiare","retten/sparen","спасать/копить","يوفر","节省/救"],
 "table":["la table","la mesa","a mesa","il tavolo","der Tisch","стол","طاولة","桌子"],
 "voice":["la voix","la voz","a voz","la voce","die Stimme","голос","صوت","声音"],
 "register":["s'inscrire","registrarse","registar","registrarsi","registrieren","регистрироваться","يسجل","登记"],
 "week":["la semaine","la semana","a semana","la settimana","die Woche","неделя","أسبوع","星期"],
 "mirror":["le miroir","el espejo","o espelho","lo specchio","der Spiegel","зеркало","مرآة","镜子"],
 "bar":["le bar","el bar","o bar","il bar","die Bar","бар","حانة","酒吧"],
 "dying":["mourant","muriendo","morrendo","morente","sterbend","умирающий","يحتضر","垂死的"],
 "clock":["l'horloge","el reloj","o relógio","l'orologio","die Uhr","часы","ساعة","钟"],
 "page":["la page","la página","a página","la pagina","die Seite","страница","صفحة","页"],
 "load":["charger","cargar","carregar","caricare","laden","загружать","يحمّل","加载"],
 "guard":["le gardien","el guardia","o guarda","la guardia","der Wächter","охранник","حارس","警卫"],
 "least":["le moins","el menos","o menos","il meno","am wenigsten","меньше всего","الأقل","最少"],
 "fact":["le fait","el hecho","o facto","il fatto","die Tatsache","факт","حقيقة","事实"],
 "colour":["la couleur","el color","a cor","il colore","die Farbe","цвет","لون","颜色"],
 "dad":["le papa","el papá","o pai","il papà","der Papa","папа","أبي","爸爸"],
 "lose":["perdre","perder","perder","perdere","verlieren","терять","يخسر","丢失"],
 "straight":["droit","recto","direto","dritto","gerade","прямо","مستقيم","直"],
 "rower":["le rameur","el remero","o remador","il rematore","der Ruderer","гребец","مجدف","划船者"],
 "shoulder":["l'épaule","el hombro","o ombro","la spalla","die Schulter","плечо","كتف","肩膀"],
 "add":["ajouter","añadir","adicionar","aggiungere","hinzufügen","добавлять","يضيف","添加"],
 "cap":["la casquette","la gorra","o boné","il berretto","die Mütze","кепка","قبعة","帽子"],
 "cloth":["le tissu","la tela","o pano","la stoffa","der Stoff","ткань","قماش","布"],
 "sky":["le ciel","el cielo","o céu","il cielo","der Himmel","небо","سماء","天空"],
 "tea":["le thé","el té","o chá","il tè","der Tee","чай","شاي","茶"],
 "advice":["le conseil","el consejo","o conselho","il consiglio","der Rat","совет","نصيحة","建议"],
 "loud":["fort","alto","alto","forte","laut","громкий","عالٍ","大声的"],
 "follow":["suivre","seguir","seguir","seguire","folgen","следовать","يتبع","跟随"],
 "throw":["jeter","lanzar","atirar","lanciare","werfen","бросать","يرمي","扔"],
 "radio":["la radio","la radio","o rádio","la radio","das Radio","радио","راديو","收音机"],
 "explain":["expliquer","explicar","explicar","spiegare","erklären","объяснять","يشرح","解释"],
 "stairs":["l'escalier","las escaleras","as escadas","le scale","die Treppe","лестница","درج","楼梯"],
 "climb":["grimper","subir","subir","salire","klettern","взбираться","يتسلق","爬"],
 "extra":["supplémentaire","extra","extra","extra","zusätzlich","дополнительный","إضافي","额外的"],
 "shot":["le coup/le shot","el chorro","a dose","lo shot","der Schuss","порция","جرعة","一份"],
 "everywhere":["partout","en todas partes","em todo lado","dovunque","überall","везде","في كل مكان","到处"],
 "market":["le marché","el mercado","o mercado","il mercato","der Markt","рынок","سوق","市场"],
 "lamp":["la lampe","la lámpara","o candeeiro","la lampada","die Lampe","лампа","مصباح","灯"],
 "life":["la vie","la vida","a vida","la vita","das Leben","жизнь","حياة","生活"],
 "note":["la note","la nota","a nota","la nota","die Notiz","записка","ملاحظة","便条"],
 "cab":["le taxi","el taxi","o táxi","il taxi","das Taxi","такси","سيارة أجرة","出租车"],
 "heater":["le chauffage","la calefacción","o aquecedor","il riscaldamento","die Heizung","обогреватель","مدفأة","暖气"],
 "tin":["la boîte/l'étain","la lata","a lata","la latta","die Dose","жестянка","علبة","锡"],
 "hate":["détester","odiar","odiar","odiare","hassen","ненавидеть","يكره","讨厌"],
 "sister":["la sœur","la hermana","a irmã","la sorella","die Schwester","сестра","أخت","姐妹"],
 "dawn":["l'aube","el amanecer","o amanhecer","l'alba","die Morgendämmerung","рассвет","فجر","黎明"],
 "metal":["le métal","el metal","o metal","il metallo","das Metall","металл","معدن","金属"],
 "below":["en dessous","debajo","abaixo","sotto","unten","ниже","أسفل","下面"],
 "engine":["le moteur","el motor","o motor","il motore","der Motor","двигатель","محرك","发动机"],
 "care":["le soin/se soucier","el cuidado","o cuidado","la cura","die Sorge","забота","رعاية","关心"],
 "direction":["la direction","la dirección","a direção","la direzione","die Richtung","направление","اتجاه","方向"],
 "rub":["frotter","frotar","esfregar","strofinare","reiben","тереть","يفرك","擦"],
 "circle":["le cercle","el círculo","o círculo","il cerchio","der Kreis","круг","دائرة","圆圈"],
 "edge":["le bord","el borde","a borda","il bordo","der Rand","край","حافة","边缘"],
 "neck":["le cou","el cuello","o pescoço","il collo","der Hals","шея","رقبة","脖子"],
 "best":["le meilleur","el mejor","o melhor","il migliore","am besten","лучший","الأفضل","最好的"],
 "course":["le cours","el curso","o curso","il corso","der Kurs","курс","دورة","课程"],
 "bed":["le lit","la cama","a cama","il letto","das Bett","кровать","سرير","床"],
 "large":["grand","grande","grande","grande","groß","большой","كبير","大的"],
 "guess":["deviner","adivinar","adivinhar","indovinare","raten","угадывать","يخمن","猜"],
 "meet":["rencontrer","conocer","encontrar","incontrare","treffen","встречать","يقابل","见面"],
 "able":["capable","capaz","capaz","capace","fähig","способный","قادر","能够的"],
 "normal":["normal","normal","normal","normale","normal","нормальный","عادي","正常的"],
 "strong":["fort","fuerte","forte","forte","stark","сильный","قوي","强壮的"],
 "short":["court","corto","curto","corto","kurz","короткий","قصير","短的"],
 "mobile":["le portable","el móvil","o telemóvel","il cellulare","das Handy","мобильный","محمول","手机"],
 "telephone":["le téléphone","el teléfono","o telefone","il telefono","das Telefon","телефон","هاتف","电话"],
 "fast":["rapide","rápido","rápido","veloce","schnell","быстрый","سريع","快的"],
 "pass":["passer","pasar","passar","passare","vorbeigehen","проходить","يمر","经过"],
 "mistake":["l'erreur","el error","o erro","l'errore","der Fehler","ошибка","خطأ","错误"],
 "dead":["mort","muerto","morto","morto","tot","мёртвый","ميت","死的"],
 "board":["le tableau","el tablero","o quadro","il tabellone","die Tafel","табло","لوحة","板"],
 "collar":["le col","el cuello","a gola","il colletto","der Kragen","воротник","ياقة","衣领"],
 "flat":["l'appartement/plat","el piso/plano","o apartamento/plano","l'appartamento/piatto","die Wohnung/flach","квартира/плоский","شقة/مسطح","公寓/平的"],
 "tomorrow":["demain","mañana","amanhã","domani","morgen","завтра","غدا","明天"],
 "hidden":["caché","escondido","escondido","nascosto","versteckt","скрытый","مخفي","隐藏的"],
 "narrow":["étroit","estrecho","estreito","stretto","eng","узкий","ضيق","窄的"],
 "bottom":["le bas","el fondo","o fundo","il fondo","der Boden","дно","قاع","底部"],
 "nowhere":["nulle part","en ningún lugar","em lugar nenhum","da nessuna parte","nirgendwo","нигде","لا مكان","无处"],
 "sheet":["la feuille","la hoja","a folha","il foglio","das Blatt","лист","ورقة","一张"],
 "smooth":["lisse","suave","liso","liscio","glatt","гладкий","أملس","光滑的"],
 "silence":["le silence","el silencio","o silêncio","il silenzio","die Stille","тишина","صمت","沉默"],
 "calm":["calme","tranquilo","calmo","calmo","ruhig","спокойный","هادئ","平静的"],
 "swing":["balancer","balancear","balançar","dondolare","schwingen","качать","يتأرجح","摆动"],
 "gate":["le portail","la puerta","o portão","il cancello","das Tor","ворота","بوابة","大门"],
 "love":["aimer","amar","amar","amare","lieben","любить","يحب","爱"],
 "tip":["le pourboire/le bout","la propina/la punta","a gorjeta/a ponta","la mancia/la punta","das Trinkgeld/die Spitze","чаевые/кончик","بقشيش/طرف","小费/尖端"],
 "shape":["la forme","la forma","a forma","la forma","die Form","форма","شكل","形状"],
 "burn":["brûler","quemar","queimar","bruciare","brennen","гореть","يحرق","燃烧"],
 "onto":["sur","sobre","sobre","su","auf","на","على","到…上"],
 "soften":["adoucir","suavizar","suavizar","ammorbidire","weich werden","смягчать","يلين","软化"],
 "gather":["rassembler","reunir","reunir","radunare","sammeln","собирать","يجمع","聚集"],
 "total":["le total","el total","o total","il totale","die Summe","итог","مجموع","总数"],
 "country":["le pays","el país","o país","il paese","das Land","страна","بلد","国家"],
 "length":["la longueur","la longitud","o comprimento","la lunghezza","die Länge","длина","طول","长度"],
 "please":["s'il vous plaît","por favor","por favor","per favore","bitte","пожалуйста","من فضلك","请"],
 "prove":["prouver","probar","provar","provare","beweisen","доказывать","يثبت","证明"],
 "force":["la force/forcer","la fuerza/forzar","a força/forçar","la forza/forzare","die Kraft/zwingen","сила/заставлять","قوة/يجبر","力量/强迫"],
 "degree":["le degré","el grado","o grau","il grado","der Grad","градус","درجة","度"],
 "easy":["facile","fácil","fácil","facile","einfach","лёгкий","سهل","容易的"],
 "drive":["conduire","conducir","conduzir","guidare","fahren","водить","يقود","开车"],
 "hire":["embaucher","contratar","contratar","assumere","einstellen","нанимать","يوظف","雇用"],
 "manage":["gérer/réussir","lograr/gestionar","conseguir/gerir","riuscire/gestire","schaffen","справляться","يدير","设法"],
 "less":["moins","menos","menos","meno","weniger","меньше","أقل","更少"],
 "fourth":["quatrième","cuarto","quarto","quarto","vierte","четвёртый","رابع","第四"],
 # more irregular pasts
 "saw":["a vu","vio","viu","ha visto","sah","увидел","رأى","看见了"],
 "met":["a rencontré","conoció","conheceu","ha incontrato","traf","встретил","قابل","遇见了"],
 "sat":["s'est assis","se sentó","sentou-se","si è seduto","saß","сел","جلس","坐下了"],
 "sent":["a envoyé","envió","enviou","ha inviato","schickte","отправил","أرسل","发送了"],
 "paid":["a payé","pagó","pagou","ha pagato","bezahlte","заплатил","دفع","付了"],
 "brought":["a apporté","trajo","trouxe","ha portato","brachte","принёс","أحضر","带来了"],
 "spent":["a passé/dépensé","pasó/gastó","passou/gastou","ha passato/speso","verbrachte","провёл/потратил","قضى/أنفق","花了"],
 "woke":["s'est réveillé","despertó","acordou","si è svegliato","wachte auf","проснулся","استيقظ","醒了"],
 "known":["connu","conocido","conhecido","conosciuto","bekannt","известный","معروف","已知的"],
 "begun":["commencé","empezado","começado","cominciato","begonnen","начатый","بدأ","开始了"],
 "written":["écrit","escrito","escrito","scritto","geschrieben","написанный","مكتوب","写的"],
 "forgotten":["oublié","olvidado","esquecido","dimenticato","vergessen","забытый","منسي","忘记的"],
})

for i, code in enumerate(L):
    data = {lemma: tr[i] for lemma, tr in M.items()}
    json.dump(data, open(os.path.join(OUT, f"{code}.json"), "w", encoding="utf-8"),
              ensure_ascii=False, separators=(",", ":"), sort_keys=True)
print(f"Coverage dict: {len(M)} words × {len(L)} languages → content/dict/<lang>.json")
