#!/usr/bin/env python3
"""Phase 4: build The Night Market's embedded lexicon.

Two sources, per the playbook:
  1. Words shared with book 1 reuse book 1's exact reviewed-draft glosses, so a word a
     learner already met reads identically. (Only words whose *sense* matches this book;
     steel/pointed/handle are excluded because their book-2 use differs.)
  2. New subject words (cooking, the market, money, the night) get fresh draft glosses in
     English + 8 languages. Machine-drafted; the native review (phase 5) finalises them.

Writes the merged lexicon into content/episode-02.json's `lexicon.entries`.
Run: python3 scripts/build_ep02_lexicon.py
"""
import json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
EP1 = os.path.join(ROOT, "content", "episode-01.json")
EP2 = os.path.join(ROOT, "content", "episode-02.json")

REUSE = [
    "anyway", "apologise", "bother", "breath", "breathe", "brief", "builder", "ceremony",
    "cleaner", "entire", "fair", "feet", "further", "glad", "glance", "glow", "heavy",
    "kerb", "lean", "lone", "midnight", "murmur", "neither", "nerve", "patience", "pause",
    "photograph", "pity", "pour", "proper", "proud", "queue", "realise", "refuse",
    "regular", "scrap", "settle", "shutter", "slide", "somehow", "stall", "steady",
    "steam", "survive", "tiny", "truth", "unkind", "vanish", "warmth", "waste", "wave",
    "whoever", "wrap",
]

def e(pos, en, fr, es, pt, it, de, ru, ar, zh):
    return {"pos": pos, "en": en, "fr": fr, "es": es, "pt": pt, "it": it,
            "de": de, "ru": ru, "ar": ar, "zh": zh}

NEW = {
 # --- food & cooking ---
 "broth": e("noun", "a thin soup made by boiling meat, bones or vegetables",
   "le bouillon", "el caldo", "o caldo", "il brodo", "die Brühe", "бульон", "مرق", "高汤"),
 "dumpling": e("noun", "a small ball of dough, often filled with meat, cooked in water or steam",
   "la boulette de pâte", "la empanadilla", "o bolinho", "il raviolo", "die Teigtasche",
   "пельмень", "فطيرة محشوة", "饺子"),
 "pork": e("noun", "meat from a pig",
   "le porc", "el cerdo", "a carne de porco", "il maiale", "das Schweinefleisch",
   "свинина", "لحم خنزير", "猪肉"),
 "ginger": e("noun", "a hot, spicy root used in cooking",
   "le gingembre", "el jengibre", "o gengibre", "lo zenzero", "der Ingwer",
   "имбирь", "زنجبيل", "姜"),
 "garlic": e("noun", "a strong-smelling bulb used to flavour food",
   "l'ail", "el ajo", "o alho", "l'aglio", "der Knoblauch", "чеснок", "ثوم", "大蒜"),
 "spice": e("noun", "a strong flavouring from a plant, used in cooking",
   "l'épice", "la especia", "a especiaria", "la spezia", "das Gewürz", "специя", "بهار", "香料"),
 "ladle": e("noun", "a big deep spoon for serving soup",
   "la louche", "el cucharón", "a concha", "il mestolo", "die Kelle", "половник", "مغرفة", "汤勺"),
 "burner": e("noun", "the ring on a stove that makes heat",
   "le brûleur", "el quemador", "o queimador", "il fornello", "der Brenner", "горелка", "موقد", "灶头"),
 "flame": e("noun", "the bright hot part of a fire",
   "la flamme", "la llama", "a chama", "la fiamma", "die Flamme", "пламя", "لهب", "火焰"),
 "pot": e("noun", "a deep round container for cooking",
   "la marmite", "la olla", "a panela", "la pentola", "der Topf", "кастрюля", "قدر", "锅"),
 "steamer": e("noun", "a stacked basket for cooking food with steam",
   "le panier vapeur", "la vaporera", "a vaporeira", "la vaporiera", "der Dämpfkorb",
   "пароварка", "سلة بخار", "蒸笼"),
 "fry": e("verb", "to cook something in hot oil",
   "frire", "freír", "fritar", "friggere", "braten", "жарить", "يقلي", "煎炸"),
 "refill": e("verb", "to fill something again",
   "recharger", "rellenar", "reabastecer", "riempire di nuovo", "nachfüllen",
   "наполнять снова", "يعيد ملء", "再装满"),
 "cloth": e("noun", "a piece of fabric used for cleaning or wiping",
   "le chiffon", "el paño", "o pano", "lo straccio", "das Tuch", "тряпка", "قطعة قماش", "抹布"),

 # --- the market ---
 "pitch": e("noun", "the spot where a trader sets up a stall in a market",
   "l'emplacement", "el puesto", "o lugar de banca", "la piazzola", "der Standplatz",
   "торговое место", "موقع البسطة", "摊位"),
 "awning": e("noun", "a cloth roof that sticks out over a stall or window",
   "l'auvent", "el toldo", "o toldo", "la tenda", "die Markise", "навес", "مظلة", "遮篷"),
 "lantern": e("noun", "a light with a cover, often made of paper",
   "la lanterne", "el farol", "a lanterna", "la lanterna", "die Laterne", "фонарь", "فانوس", "灯笼"),
 "arcade": e("noun", "a covered walkway with shops or stalls along it",
   "la galerie marchande", "la galería", "a galeria", "la galleria", "die Passage",
   "пассаж", "ممر مسقوف", "拱廊"),
 "master": e("noun", "the person in charge of the market",
   "le régisseur", "el encargado", "o administrador", "il responsabile", "der Marktmeister",
   "управляющий рынком", "مدير السوق", "市场管理员"),
 "stallholder": e("noun", "a person who runs a stall in a market",
   "le marchand", "el vendedor", "o feirante", "il bancarellista", "der Standbetreiber",
   "торговец", "صاحب كشك", "摊主"),
 "supplier": e("noun", "a person or company that provides goods to sell",
   "le fournisseur", "el proveedor", "o fornecedor", "il fornitore", "der Lieferant",
   "поставщик", "مورّد", "供货商"),
 "fee": e("noun", "money you must pay for something",
   "la redevance", "la cuota", "a taxa", "la quota", "die Gebühr", "плата", "رسوم", "费用"),
 "takings": e("noun", "the money a shop or stall makes in a day",
   "la recette", "la recaudación", "a receita", "l'incasso", "die Einnahmen",
   "выручка", "الإيرادات", "营业额"),
 "till": e("noun", "the box or drawer where a shop keeps its money",
   "la caisse", "la caja", "a caixa", "la cassa", "die Kasse", "касса", "صندوق النقود", "钱箱"),
 "stock": e("noun", "the food or goods a shop has ready to sell",
   "le stock", "las existencias", "o estoque", "la merce", "der Warenbestand",
   "запас товара", "بضاعة", "存货"),
 "rival": e("noun", "a person who competes with you",
   "le rival", "el rival", "o rival", "il rivale", "der Konkurrent", "соперник", "منافس", "对手"),
 "trade": e("noun", "the business of buying and selling",
   "le commerce", "el comercio", "o comércio", "il commercio", "das Geschäft",
   "торговля", "تجارة", "生意"),
 "roof": e("noun", "the cover on top of a building",
   "le toit", "el tejado", "o telhado", "il tetto", "das Dach", "крыша", "سقف", "屋顶"),
 "arch": e("noun", "a curved structure, often a gateway",
   "l'arche", "el arco", "o arco", "l'arco", "der Bogen", "арка", "قوس", "拱门"),
 "crew": e("noun", "a group of people who go about together",
   "la bande", "la panda", "o grupo", "la banda", "die Truppe", "компания", "جماعة", "一伙人"),

 # --- money ---
 "loan": e("noun", "money that is lent and must be paid back",
   "le prêt", "el préstamo", "o empréstimo", "il prestito", "das Darlehen", "заём", "قرض", "贷款"),
 "debt": e("noun", "money that you owe to someone",
   "la dette", "la deuda", "a dívida", "il debito", "die Schuld", "долг", "دين", "债务"),
 "penny": e("noun", "a coin of very little value",
   "le centime", "el centavo", "o cêntimo", "il centesimo", "der Pfennig", "грош", "فلس", "一分钱"),
 "charge": e("verb", "to ask a certain price for something",
   "faire payer", "cobrar", "cobrar", "far pagare", "verlangen", "брать плату", "يتقاضى", "收费"),
 "earn": e("verb", "to get money by working",
   "gagner", "ganar", "ganhar", "guadagnare", "verdienen", "зарабатывать", "يكسب", "赚"),
 "owe": e("verb", "to have to pay money back to someone",
   "devoir", "deber", "dever", "dovere", "schulden", "быть должным", "يدين", "欠"),

 # --- people & time ---
 "customer": e("noun", "a person who buys something from a shop or stall",
   "le client", "el cliente", "o cliente", "il cliente", "der Kunde", "покупатель", "زبون", "顾客"),
 "dawn": e("noun", "the first light of the morning",
   "l'aube", "el amanecer", "o amanhecer", "l'alba", "die Morgendämmerung", "рассвет", "الفجر", "黎明"),
 "dusk": e("noun", "the time when the light goes and night begins",
   "le crépuscule", "el anochecer", "o anoitecer", "il crepuscolo", "die Dämmerung",
   "сумерки", "الغسق", "黄昏"),
 "rush": e("noun", "a busy time when many people come at once",
   "le coup de feu", "la hora punta", "o pico", "la calca", "der Ansturm",
   "наплыв", "ذروة الزحام", "高峰"),
 "lull": e("noun", "a quiet time between busy times",
   "l'accalmie", "la calma", "a pausa", "la pausa", "die Flaute", "затишье", "فترة هدوء", "间歇"),
 "trickle": e("noun", "a thin, slow flow",
   "le filet", "el goteo", "o fio", "il rivolo", "das Rinnsal", "струйка", "تدفق ضئيل", "细流"),
 "cousin": e("noun", "the child of your aunt or uncle",
   "le cousin", "el primo", "o primo", "il cugino", "der Cousin", "двоюродный брат", "ابن العم", "表亲"),
 "habit": e("noun", "something you do often, without thinking",
   "l'habitude", "el hábito", "o hábito", "l'abitudine", "die Gewohnheit", "привычка", "عادة", "习惯"),

 # --- verbs ---
 "stretch": e("verb", "to make something last longer than it should",
   "faire durer", "estirar", "esticar", "far bastare", "strecken", "растягивать", "يمدد", "使够用"),
 "wipe": e("verb", "to clean something by rubbing it",
   "essuyer", "limpiar", "limpar", "pulire", "wischen", "вытирать", "يمسح", "擦"),
 "restock": e("verb", "to fill up your supplies again",
   "réapprovisionner", "reponer", "repor", "rifornire", "auffüllen",
   "пополнять запас", "يعيد التخزين", "补货"),
 "weigh": e("verb", "to think carefully about something before deciding",
   "peser", "sopesar", "ponderar", "soppesare", "abwägen", "взвешивать", "يزن", "权衡"),
 "coax": e("verb", "to gently persuade something or someone",
   "amadouer", "engatusar", "persuadir", "convincere", "überreden", "уговаривать", "يستدرج", "哄"),
 "gasp": e("verb", "to breathe in suddenly and sharply, from shock or pain",
   "haleter", "jadear", "arquejar", "ansimare", "nach Luft schnappen", "ахнуть", "يلهث", "倒吸气"),
 "grumble": e("verb", "to complain in a low voice",
   "ronchonner", "refunfuñar", "resmungar", "brontolare", "murren", "ворчать", "يتذمر", "抱怨"),
 "argue": e("verb", "to disagree with someone in words",
   "se disputer", "discutir", "discutir", "litigare", "streiten", "спорить", "يجادل", "争论"),
 "warn": e("verb", "to tell someone about a danger or problem",
   "avertir", "advertir", "avisar", "avvertire", "warnen", "предупреждать", "يحذّر", "警告"),
 "cheat": e("verb", "to trick someone, especially to take their money",
   "escroquer", "engañar", "enganar", "imbrogliare", "betrügen", "обманывать", "يغش", "欺骗"),
 "spill": e("verb", "to make a liquid flow out by accident",
   "renverser", "derramar", "derramar", "rovesciare", "verschütten", "проливать", "يسكب", "洒"),
 "splash": e("verb", "to make liquid fly about in drops",
   "éclabousser", "salpicar", "salpicar", "schizzare", "spritzen", "брызгать", "يرشّ", "溅"),
 "scald": e("verb", "to burn with very hot liquid or steam",
   "ébouillanter", "escaldar", "escaldar", "scottare", "verbrühen", "обварить", "يسلق", "烫伤"),
 "sweep": e("verb", "to clean a floor with a brush",
   "balayer", "barrer", "varrer", "spazzare", "fegen", "подметать", "يكنس", "扫"),
 "hang": e("verb", "to fix something at the top so it drops down",
   "accrocher", "colgar", "pendurar", "appendere", "hängen", "вешать", "يعلّق", "挂"),
 "pack": e("verb", "to put things into boxes or bags to carry away",
   "emballer", "empacar", "embalar", "impacchettare", "einpacken", "упаковывать", "يحزم", "打包"),
 "soften": e("verb", "to become gentler or kinder",
   "s'adoucir", "ablandarse", "abrandar", "addolcirsi", "weicher werden", "смягчаться", "يلين", "变温和"),
 "straighten": e("verb", "to make something tidy or not crooked",
   "redresser", "enderezar", "endireitar", "raddrizzare", "gerade richten", "поправлять", "يعدّل", "弄整齐"),
 "harden": e("verb", "to become firm or unfriendly",
   "durcir", "endurecerse", "endurecer", "indurirsi", "sich verhärten", "твердеть", "يقسو", "变硬"),
 "undercut": e("verb", "to sell more cheaply than someone else, to take their trade",
   "casser les prix", "vender más barato", "vender mais barato", "vendere sottocosto",
   "unterbieten", "сбивать цену", "يبيع بأرخص", "压价"),
 "fret": e("verb", "to worry, often about small things",
   "se tracasser", "inquietarse", "preocupar-se", "agitarsi", "sich sorgen", "тревожиться", "يقلق", "焦虑"),
 "reassure": e("verb", "to make someone feel calmer and less worried",
   "rassurer", "tranquilizar", "tranquilizar", "rassicurare", "beruhigen", "успокаивать", "يطمئن", "安慰"),
 "manage": e("verb", "to cope, or to succeed in doing something hard",
   "se débrouiller", "arreglárselas", "arranjar-se", "cavarsela", "zurechtkommen",
   "справляться", "يتدبّر", "应付"),
 "duck": e("verb", "to move your head or body down quickly",
   "se baisser", "agacharse", "baixar-se", "abbassarsi", "sich ducken", "пригнуться", "ينحني", "低头躲"),
 "fetch": e("verb", "to go and bring something back",
   "aller chercher", "traer", "ir buscar", "andare a prendere", "holen", "приносить", "يحضر", "去拿"),
 "sway": e("verb", "to move slowly from side to side",
   "se balancer", "balancearse", "balançar", "dondolare", "schwanken", "покачиваться", "يتمايل", "摇晃"),
 "sting": e("verb", "to cause a sharp, sudden pain",
   "piquer", "escocer", "arder", "bruciare", "brennen", "жечь", "يلسع", "刺痛"),
 "ache": e("verb", "to hurt with a dull, steady pain",
   "faire mal", "doler", "doer", "dolere", "schmerzen", "ныть", "يؤلم", "疼痛"),
 "praise": e("verb", "to say good things about someone or something",
   "faire l'éloge", "elogiar", "elogiar", "lodare", "loben", "хвалить", "يمدح", "称赞"),
 "shoo": e("verb", "to send someone away with words or a wave",
   "chasser", "espantar", "enxotar", "scacciare", "verscheuchen", "прогонять", "يهشّ", "赶走"),

 # --- adjectives ---
 "generous": e("adjective", "glad to give more than is needed",
   "généreux", "generoso", "generoso", "generoso", "großzügig", "щедрый", "كريم", "慷慨的"),
 "greedy": e("adjective", "wanting more money or things than you need",
   "avide", "codicioso", "ganancioso", "avido", "gierig", "жадный", "جشع", "贪婪的"),
 "grateful": e("adjective", "feeling thankful for something",
   "reconnaissant", "agradecido", "grato", "grato", "dankbar", "благодарный", "ممتن", "感激的"),
 "nervous": e("adjective", "worried and a little afraid",
   "nerveux", "nervioso", "nervoso", "nervoso", "nervös", "нервный", "متوتر", "紧张的"),
 "breathless": e("adjective", "unable to breathe easily, after effort",
   "essoufflé", "sin aliento", "sem fôlego", "senza fiato", "außer Atem", "запыхавшийся", "لاهث", "喘不过气的"),
 "patient": e("adjective", "able to wait calmly without getting cross",
   "patient", "paciente", "paciente", "paziente", "geduldig", "терпеливый", "صبور", "耐心的"),
 "stubborn": e("adjective", "not willing to change or give way",
   "têtu", "terco", "teimoso", "testardo", "stur", "упрямый", "عنيد", "固执的"),
 "bland": e("adjective", "having little taste or flavour",
   "fade", "soso", "insosso", "insipido", "fade", "пресный", "بلا نكهة", "淡而无味的"),
 "crisp": e("adjective", "firm and fresh, not soft",
   "croquant", "crujiente", "crocante", "croccante", "knackig", "хрустящий", "مقرمش", "爽脆的"),
 "soaked": e("adjective", "completely wet",
   "trempé", "empapado", "encharcado", "fradicio", "durchnässt", "промокший", "مبلل تمامًا", "湿透的"),
 "ragged": e("adjective", "old, torn and worn out",
   "en haillons", "harapiento", "esfarrapado", "stracciato", "zerlumpt", "оборванный", "رثّ", "破烂的"),
 "tempting": e("adjective", "making you want it, even if it may be unwise",
   "tentant", "tentador", "tentador", "allettante", "verlockend", "заманчивый", "مغرٍ", "诱人的"),
 "modest": e("adjective", "small and plain, not grand",
   "modeste", "modesto", "modesto", "modesto", "bescheiden", "скромный", "متواضع", "简朴的"),
 "bare": e("adjective", "empty, with nothing on or in it",
   "nu", "desnudo", "nu", "spoglio", "kahl", "пустой", "عارٍ", "空荡的"),
 "tight": e("adjective", "held firmly and closely; hard to manage",
   "serré", "apretado", "apertado", "stretto", "knapp", "тугой", "محكم", "紧的"),
 "fierce": e("adjective", "very strong and forceful",
   "féroce", "feroz", "feroz", "feroce", "heftig", "яростный", "شرس", "强烈的"),
 "gentle": e("adjective", "soft, calm and kind",
   "doux", "suave", "suave", "gentile", "sanft", "нежный", "لطيف", "温柔的"),
 "noisy": e("adjective", "making a lot of noise",
   "bruyant", "ruidoso", "barulhento", "rumoroso", "laut", "шумный", "صاخب", "吵闹的"),
 "sleepy": e("adjective", "tired and ready to sleep",
   "somnolent", "soñoliento", "sonolento", "assonnato", "schläfrig", "сонный", "نعسان", "困倦的"),
 "swamped": e("adjective", "overwhelmed with too much to do",
   "débordé", "desbordado", "sobrecarregado", "sommerso", "überlastet",
   "заваленный работой", "غارق في العمل", "忙不过来的"),

 # --- other nouns ---
 "kindness": e("noun", "the quality of being kind; a kind act",
   "la gentillesse", "la amabilidad", "a bondade", "la gentilezza", "die Freundlichkeit",
   "доброта", "لطف", "善意"),
 "favour": e("noun", "a kind act you do to help someone",
   "le service", "el favor", "o favor", "il favore", "der Gefallen", "одолжение", "معروف", "帮忙"),
 "hook": e("noun", "a hidden trap in something that looks like help",
   "le piège", "el anzuelo", "o anzol", "l'amo", "der Haken", "крючок", "خطاف", "圈套"),
 "trick": e("noun", "a clever act meant to fool or cheat someone",
   "le tour", "el truco", "o truque", "il trucco", "der Trick", "уловка", "خدعة", "把戏"),
 "unease": e("noun", "a feeling that something is wrong",
   "le malaise", "la inquietud", "o desassossego", "il disagio", "das Unbehagen",
   "тревога", "قلق", "不安"),
 "balance": e("noun", "an even, well-judged mix of things",
   "l'équilibre", "el equilibrio", "o equilíbrio", "l'equilibrio", "das Gleichgewicht",
   "баланс", "توازن", "平衡"),
 "rhythm": e("noun", "a steady, repeating pattern of movement",
   "le rythme", "el ritmo", "o ritmo", "il ritmo", "der Rhythmus", "ритм", "إيقاع", "节奏"),
 "spark": e("noun", "a tiny flash of fire or feeling",
   "l'étincelle", "la chispa", "a faísca", "la scintilla", "der Funke", "искра", "شرارة", "火花"),
 "pride": e("noun", "a feeling of pleasure in what you have done",
   "la fierté", "el orgullo", "o orgulho", "l'orgoglio", "der Stolz", "гордость", "فخر", "自豪"),
 "anger": e("noun", "a strong feeling of being cross",
   "la colère", "la ira", "a raiva", "la rabbia", "der Zorn", "гнев", "غضب", "愤怒"),
 "loss": e("noun", "the fact of no longer having something",
   "la perte", "la pérdida", "a perda", "la perdita", "der Verlust", "потеря", "خسارة", "损失"),
 "terms": e("noun", "the conditions of an agreement or deal",
   "les conditions", "las condiciones", "as condições", "le condizioni", "die Bedingungen",
   "условия", "الشروط", "条款"),
 "warning": e("noun", "words that tell you about a danger",
   "l'avertissement", "la advertencia", "o aviso", "l'avvertimento", "die Warnung",
   "предупреждение", "تحذير", "警告"),
 "mouthful": e("noun", "the amount of food you put in your mouth at once",
   "la bouchée", "el bocado", "a garfada", "il boccone", "der Bissen", "кусок", "لقمة", "一口"),
 "spoonful": e("noun", "the amount a spoon holds",
   "la cuillerée", "la cucharada", "a colherada", "la cucchiaiata", "der Löffel voll",
   "ложка", "ملعقة", "一勺"),
 "handful": e("noun", "the amount a hand can hold; a small number",
   "la poignée", "el puñado", "o punhado", "la manciata", "die Handvoll", "горсть", "حفنة", "一把"),
 "errand": e("noun", "a short trip to do a small task for someone",
   "la course", "el recado", "o recado", "la commissione", "die Besorgung", "поручение", "مهمة", "跑腿"),
 "chaos": e("noun", "a state of complete disorder",
   "le chaos", "el caos", "o caos", "il caos", "das Chaos", "хаос", "فوضى", "混乱"),
 "crash": e("noun", "a sudden loud noise of something breaking or falling",
   "le fracas", "el estruendo", "o estrondo", "il fracasso", "der Krach", "грохот", "تحطّم", "哗啦声"),
 "sweat": e("noun", "the water your skin makes when you are hot",
   "la sueur", "el sudor", "o suor", "il sudore", "der Schweiß", "пот", "عرق", "汗"),
 "stomach": e("noun", "the part of the body where food goes",
   "l'estomac", "el estómago", "o estômago", "lo stomaco", "der Magen", "живот", "معدة", "胃"),
 "chest": e("noun", "the front part of your body between neck and stomach",
   "la poitrine", "el pecho", "o peito", "il petto", "die Brust", "грудь", "صدر", "胸口"),
 "rope": e("noun", "thick strong cord",
   "la corde", "la cuerda", "a corda", "la corda", "das Seil", "верёвка", "حبل", "绳子"),
 "lifetime": e("noun", "the whole length of a person's life",
   "la vie entière", "toda una vida", "uma vida inteira", "una vita intera", "das ganze Leben",
   "целая жизнь", "عمر كامل", "一辈子"),
 "decision": e("noun", "a choice you make after thinking",
   "la décision", "la decisión", "a decisão", "la decisione", "die Entscheidung",
   "решение", "قرار", "决定"),
 "instructions": e("noun", "words that tell you how to do something",
   "les instructions", "las instrucciones", "as instruções", "le istruzioni", "die Anweisungen",
   "инструкции", "تعليمات", "指示"),
 "path": e("noun", "a way to get through or forward",
   "le chemin", "el camino", "o caminho", "il percorso", "der Weg", "путь", "طريق", "路径"),
 "tip": e("noun", "a small piece of useful advice",
   "le conseil", "el consejo", "a dica", "il consiglio", "der Tipp", "совет", "نصيحة", "建议"),

 # --- high-frequency content words the coverage pass flagged ---
 "stool": e("noun", "a small seat with no back",
   "le tabouret", "el taburete", "o banco", "lo sgabello", "der Hocker", "табурет", "كرسي بلا ظهر", "凳子"),
 "child": e("noun", "a young person, not yet grown up",
   "l'enfant", "el niño", "a criança", "il bambino", "das Kind", "ребёнок", "طفل", "小孩"),
 "firm": e("adjective", "steady and strong; not giving way",
   "ferme", "firme", "firme", "fermo", "fest", "твёрдый", "حازم", "坚定的"),
 "sell": e("verb", "to give something in exchange for money",
   "vendre", "vender", "vender", "vendere", "verkaufen", "продавать", "يبيع", "卖"),
}


def main():
    ep1 = json.load(open(EP1, encoding="utf-8"))["lexicon"]["entries"]
    book = json.load(open(EP2, encoding="utf-8"))
    entries, missing = {}, []
    for w in REUSE:
        if w in ep1:
            entries[w] = ep1[w]
        else:
            missing.append(w)
    for w, v in NEW.items():
        entries[w.strip()] = v
    book["lexicon"]["entries"] = dict(sorted(entries.items()))
    json.dump(book, open(EP2, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    print(f"Lexicon written: {len(entries)} entries "
          f"({len([w for w in REUSE if w in ep1])} reused, {len(NEW)} new).")
    if missing:
        print("WARNING reuse words not in book 1:", ", ".join(missing))


if __name__ == "__main__":
    main()
