#!/usr/bin/env python3
"""Per-passage clue text (the "See the meaning" gist) for book 2, The Night Market.

Scoped per book: writes content/gist/the-night-market/<lang>.json → {"<nodeId>": "meaning"}.
Offered "where needed" (the opening, the major forks, the con, the neighbour, the saved bowl,
the kindness, and every one of the 12 endings), per the authoring playbook — not every passage.
fr/es/it/de/pt are author-vouched; ru/ar/zh native review: complete.

Run: python3 scripts/build_gists_ep02.py
"""
import json, os

LANGS = ["fr", "es", "it", "de", "pt", "ru", "ar", "zh"]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "the-night-market")
os.makedirs(OUT, exist_ok=True)

# nodeId: {lang: concise meaning}
G = {
 1: {
  "fr": "Ce soir, vous tenez seul le stand de Tatie (elle s'est brûlé la main). La taxe de la saison doit être payée au maître du marché avant l'aube, sinon la famille perd l'emplacement.",
  "es": "Esta noche llevas tú solo el puesto de la tía (se quemó la mano). La cuota de la temporada hay que pagarla al jefe del mercado antes del alba, o la familia pierde el puesto.",
  "it": "Stasera gestisci da solo la bancarella della zia (si è ustionata la mano). La quota della stagione va pagata al capo del mercato prima dell'alba, o la famiglia perde il posto.",
  "de": "Heute Nacht führst du allein den Stand der Tante (sie hat sich die Hand verbrüht). Die Saisongebühr muss bis zum Morgengrauen an den Marktmeister gezahlt werden, sonst verliert die Familie den Platz.",
  "pt": "Esta noite ficas sozinho com a banca da tia (queimou a mão). A taxa da época tem de ser paga ao mestre do mercado antes do amanhecer, ou a família perde o lugar.",
  "ru": "Сегодня ты один держишь лоток тёти (она обожгла руку). Плату за сезон нужно внести хозяину рынка до рассвета, иначе семья потеряет место.",
  "ar": "الليلة تدير وحدك كشك العمّة (حرقت يدها). على رسم الموسم أن يُدفع لمدير السوق قبل الفجر، وإلّا تفقد العائلة المكان.",
  "zh": "今晚你独自经营姑婆的摊子（她烫伤了手）。摊位的季费必须在天亮前交给市场管事，否则家里就会失去这个摊位。",
 },
 6: {
  "fr": "Choix du fournisseur : la marchandise du vieux Han est bonne mais chère ; la camionnette bon marché est à moitié prix, mais une partie est avariée. La bonne qualité coûte de l'argent ; la mauvaise coûtera votre réputation.",
  "es": "Elección de proveedor: la mercancía del viejo Han es buena pero cara; la furgoneta barata está a mitad de precio, pero parte está pasada. La calidad cuesta dinero ahora; lo malo costará tu reputación después.",
  "it": "Scelta del fornitore: la roba del vecchio Han è buona ma costa; il furgone economico è a metà prezzo, ma una parte è andata a male. La qualità costa soldi ora; la roba scadente costerà la tua reputazione poi.",
  "de": "Lieferanten-Wahl: Alter Hans Ware ist gut, aber teuer; der billige Wagen ist zum halben Preis, doch ein Teil ist verdorben. Gute Ware kostet jetzt Geld; schlechte kostet später deinen Ruf.",
  "pt": "Escolha do fornecedor: a mercadoria do velho Han é boa mas cara; a carrinha barata está a metade do preço, mas parte está estragada. A qualidade custa dinheiro agora; a má custará a tua reputação depois.",
  "ru": "Выбор поставщика: у старого Хана товар хороший, но дорогой; дешёвый фургон вдвое дешевле, но часть товара несвежая. Качество стоит денег сейчас; плохой товар будет стоить твоей репутации потом.",
  "ar": "اختيار المورّد: بضاعة هان العجوز جيّدة لكنها غالية؛ الشاحنة الرخيصة بنصف الثمن، لكن بعضها فسد. الجودة تكلّف مالاً الآن؛ والرديء سيكلّف سمعتك لاحقاً.",
  "zh": "选供货：老韩的货好但贵；便宜的货车半价，但有些已经不新鲜。好货现在要花钱，差货以后要赔上你的名声。",
 },
 13: {
  "fr": "Tatie garde toujours un bol sur l'étagère du fond pour M. Behn, qui ne vient plus. Garder cette habitude ne coûte qu'un bol, mais c'est ainsi qu'on reste dans la vie des autres.",
  "es": "La tía siempre guarda un cuenco en el estante del fondo para el Sr. Behn, que dejó de venir. Mantener esa costumbre cuesta solo un cuenco, pero así es como la gente sigue en la vida de los demás.",
  "it": "La zia tiene sempre una ciotola sulla mensola in fondo per il signor Behn, che non viene più. Mantenere questa abitudine costa solo una ciotola, ma è così che si resta nella vita degli altri.",
  "de": "Die Tante hält immer eine Schale im hinteren Regal für Herrn Behn bereit, der nicht mehr kommt. Diese Gewohnheit kostet nur eine Schale, aber so bleibt man im Leben der anderen.",
  "pt": "A tia guarda sempre uma tigela na prateleira do fundo para o Sr. Behn, que deixou de vir. Manter esse hábito custa só uma tigela, mas é assim que se continua na vida dos outros.",
  "ru": "Тётя всегда держит на дальней полке миску для господина Бена, который перестал приходить. Эта привычка стоит всего одной миски, но так люди остаются в жизни друг друга.",
  "ar": "تحتفظ العمّة دائماً بوعاء على الرفّ الخلفي للسيد بِن، الذي لم يعد يأتي. هذه العادة تكلّف وعاءً واحداً فقط، لكن هكذا يبقى الناس في حياة بعضهم.",
  "zh": "姑婆总在后架上为不再来的贝恩先生留一碗。保留这个习惯只花一碗的成本，但人与人正是这样留在彼此生命里。",
 },
 42: {
  "fr": "Le comptoir est débordé. Vous devez choisir : travailler posément en gardant la qualité, aller plus vite en bâclant, ou appeler de l'aide avant de couler.",
  "es": "El mostrador está desbordado. Debes elegir: trabajar con calma y mantener la calidad, ir más rápido haciendo las cosas peor, o pedir ayuda antes de hundirte.",
  "it": "Il bancone è preso d'assalto. Devi scegliere: lavorare con calma mantenendo la qualità, andare più veloce facendo le cose peggio, o chiedere aiuto prima di affondare.",
  "de": "Der Tresen ist überrannt. Du musst wählen: ruhig arbeiten und die Qualität halten, schneller werden und schludern, oder Hilfe rufen, bevor du untergehst.",
  "pt": "O balcão está cheio. Tens de escolher: trabalhar com calma mantendo a qualidade, ir mais depressa fazendo pior, ou pedir ajuda antes de afundar.",
  "ru": "У прилавка не протолкнуться. Нужно выбрать: работать спокойно, сохраняя качество; ускориться, делая хуже; или позвать на помощь, пока не захлебнулся.",
  "ar": "ازدحم المنضدة. عليك أن تختار: العمل بهدوء مع الحفاظ على الجودة، أو الإسراع مع التهاون، أو طلب المساعدة قبل أن تغرق.",
  "zh": "柜台前挤满了人。你必须选择：稳稳地做、保住质量，或者加快却偷工减料，或者在撑不住前叫人来帮忙。",
 },
 44: {
  "fr": "Vous trouvez votre rythme et séduisez la foule, en traitant chaque client comme un ami, comme le fait Tatie.",
  "es": "Encuentras tu ritmo y te ganas a la multitud, tratando a cada cliente como un amigo, igual que hace la tía.",
  "it": "Trovi il ritmo e conquisti la folla, trattando ogni cliente come un amico, come fa la zia.",
  "de": "Du findest deinen Rhythmus und gewinnst die Menge für dich, indem du jeden Kunden wie einen Freund behandelst, so wie die Tante.",
  "pt": "Encontras o teu ritmo e conquistas a multidão, tratando cada cliente como um amigo, tal como a tia faz.",
  "ru": "Ты входишь в ритм и покоряешь толпу, обращаясь с каждым покупателем как с другом, как делает тётя.",
  "ar": "تجد إيقاعك وتكسب الزبائن، معامِلاً كلّ واحد كصديق، كما تفعل العمّة.",
  "zh": "你找到了节奏，像姑婆那样把每位客人都当朋友，渐渐赢得了整群人的心。",
 },
 58: {
  "fr": "La grande bouilloire de la marchande de thé s'est renversée ; son stand est en plein chaos. Elle ne demandera jamais d'aide, mais elle vous a aidé toute la nuit. L'aidez-vous ?",
  "es": "Se ha volcado el gran caldero de té de la vendedora; su puesto es un caos. Ella nunca pediría ayuda, pero te ha ayudado toda la noche. ¿La ayudas?",
  "it": "Il grande bollitore della venditrice di tè si è rovesciato; la sua bancarella è nel caos. Non chiederebbe mai aiuto, ma ti ha aiutato tutta la notte. La aiuti?",
  "de": "Der große Teekessel der Teeverkäuferin ist umgekippt; ihr Stand ist im Chaos. Sie würde nie um Hilfe bitten, aber sie hat dir die ganze Nacht geholfen. Hilfst du ihr?",
  "pt": "O grande caldeirão de chá da vendedora virou-se; a banca dela é um caos. Ela nunca pediria ajuda, mas ajudou-te a noite toda. Ajudá-la?",
  "ru": "Большой чайный котёл у торговки опрокинулся; на её лотке хаос. Она никогда не попросит помощи, но всю ночь помогала тебе. Поможешь ей?",
  "ar": "انقلب مِرجل الشاي الكبير لبائعة الشاي؛ كشكها في فوضى. لن تطلب المساعدة أبداً، لكنها ساعدتك طوال الليل. هل تساعدها؟",
  "zh": "卖茶女人的大茶炉翻了，摊子一片狼藉。她绝不会开口求助，但她整晚都在帮你。你去帮她吗？",
 },
 61: {
  "fr": "M. Sould, le « fixeur », propose son aide : un prêt pour la taxe, ou un mot contre votre rival — pour ceux qui « s'occupent » de lui. C'est un piège.",
  "es": "El Sr. Sould, el «arreglador», ofrece ayuda: un préstamo para la cuota, o una palabra contra tu rival, para los que lo «cuidan». Es una trampa.",
  "it": "Il signor Sould, il «sistematutto», offre aiuto: un prestito per la quota, o una parola contro il tuo rivale, per chi «si prende cura» di lui. È una trappola.",
  "de": "Herr Sould, der „Macher“, bietet Hilfe an: ein Darlehen für die Gebühr oder ein Wort gegen deinen Rivalen – für die, die sich um ihn „kümmern“. Es ist eine Falle.",
  "pt": "O Sr. Sould, o «resolvedor», oferece ajuda: um empréstimo para a taxa, ou uma palavra contra o teu rival, para quem «cuida» dele. É uma armadilha.",
  "ru": "Господин Соулд, «решала», предлагает помощь: ссуду на оплату или словечко против твоего соперника — для тех, кто «заботится» о нём. Это ловушка.",
  "ar": "السيد سولد، «المُدبِّر»، يعرض المساعدة: قرضاً لدفع الرسم، أو كلمة ضدّ منافسك — لمن «يعتني» به. إنه فخّ.",
  "zh": "“摆平事儿”的苏尔德先生来帮忙：借钱交费，或替你压一压对手——专照顾“照顾”他的人。这是个圈套。",
 },
 62: {
  "fr": "Sould propose un prêt : payez la taxe maintenant, remboursez plus tard — mais il cache les intérêts et le vrai prix. Le prendre, demander ce qu'il coûte, ou s'en aller.",
  "es": "Sould ofrece un préstamo: paga la cuota ahora, devuélvelo luego, pero oculta los intereses y el precio real. Aceptarlo, preguntar cuánto cuesta, o marcharte.",
  "it": "Sould offre un prestito: paga la quota ora, restituisci dopo, ma nasconde gli interessi e il vero prezzo. Accettarlo, chiedere quanto costa, o andartene.",
  "de": "Sould bietet ein Darlehen: Zahl die Gebühr jetzt, zahl später zurück – doch er verschweigt die Zinsen und den wahren Preis. Annehmen, nach dem Preis fragen, oder weggehen.",
  "pt": "Sould oferece um empréstimo: paga a taxa agora, devolve depois, mas esconde os juros e o custo real. Aceitá-lo, perguntar quanto custa, ou ir-te embora.",
  "ru": "Соулд предлагает ссуду: заплати сейчас, вернёшь позже — но он скрывает проценты и настоящую цену. Взять, спросить о цене или уйти.",
  "ar": "يعرض سولد قرضاً: ادفع الرسم الآن وسدِّد لاحقاً — لكنه يُخفي الفائدة والثمن الحقيقي. أن تأخذه، أو تسأل عن كلفته، أو تنصرف.",
  "zh": "苏尔德提出借款：现在交费，以后再还——可他绝口不提利息和真正的代价。接受、追问代价，还是转身离开。",
 },
 73: {
  "fr": "Le gamin qui a rapporté vos provisions regarde la nourriture avec faim, sans rien demander. Vous tenez un bol dans une main et un choix dans l'autre.",
  "es": "El chico que trajo tus provisiones mira la comida con hambre, sin pedir nada. Tienes un cuenco en una mano y una decisión en la otra.",
  "it": "Il ragazzino che ha portato le provviste guarda il cibo con fame, senza chiedere nulla. Hai una ciotola in una mano e una scelta nell'altra.",
  "de": "Das Kind, das deine Vorräte geholt hat, sieht das Essen hungrig an, ohne etwas zu verlangen. Du hast eine Schale in der einen Hand und eine Entscheidung in der anderen.",
  "pt": "O miúdo que trouxe as tuas provisões olha a comida com fome, sem pedir nada. Tens uma tigela numa mão e uma decisão na outra.",
  "ru": "Мальчишка, что принёс твои припасы, голодно смотрит на еду, но ничего не просит. В одной руке у тебя миска, в другой — выбор.",
  "ar": "الفتى الذي أحضر مؤونتك ينظر إلى الطعام بجوع، دون أن يطلب شيئاً. في يدٍ وعاء وفي الأخرى قرار.",
  "zh": "替你跑腿拿货的孩子饿饿地望着食物，却什么也不要。你一手端着一碗，一手握着一个选择。",
 },
 120: {
  "fr": "FIN (bonne) — Vous avez vendu une bonne cuisine honnête jusqu'au dernier bol et payé la taxe de reste : l'emplacement est sauvé pour une saison de plus. Tatie en pleure, puis rit.",
  "es": "FINAL (bueno) — Vendiste comida buena y honrada hasta el último cuenco y pagaste la cuota de sobra: el puesto se salva una temporada más. La tía llora, y luego ríe.",
  "it": "FINALE (buono) — Hai venduto cibo buono e onesto fino all'ultima ciotola e pagato la quota con l'avanzo: il posto è salvo per un'altra stagione. La zia piange, poi ride.",
  "de": "ENDE (gut) — Du hast gutes, ehrliches Essen bis zur letzten Schale verkauft und die Gebühr mit Überschuss gezahlt: Der Platz ist für eine weitere Saison gerettet. Die Tante weint, dann lacht sie.",
  "pt": "FIM (bom) — Vendeste comida boa e honesta até à última tigela e pagaste a taxa de sobra: o lugar está salvo por mais uma época. A tia chora e depois ri.",
  "ru": "КОНЦОВКА (хорошая) — Ты честно распродал хорошую еду до последней миски и с лихвой внёс плату: место спасено ещё на сезон. Тётя плачет, потом смеётся.",
  "ar": "النهاية (جيدة) — بِعتَ طعاماً جيّداً وصادقاً حتى آخر وعاء ودفعت الرسم وزيادة: المكان آمن لموسم آخر. تبكي العمّة ثم تضحك.",
  "zh": "结局（好）——你把诚实的好饭卖到最后一碗，交费还有余：摊位又保住了一季。姑婆先哭，后又笑了。",
 },
 121: {
  "fr": "FIN (bonne, secrète) — M. Behn mange le bol que vous aviez gardé ; quand l'argent manque, il se lève et paie le reste « pour les vieux amis ». L'emplacement est sauvé, et une amitié ancienne renouée. Dites à Tatie que Behn est revenu.",
  "es": "FINAL (bueno, secreto) — El Sr. Behn se come el cuenco que guardaste; cuando falta dinero, se levanta y paga el resto «por los viejos amigos». El puesto se salva, y una vieja amistad se recompone. Dile a la tía que Behn volvió.",
  "it": "FINALE (buono, segreto) — Il signor Behn mangia la ciotola che avevi tenuto; quando mancano i soldi, si alza e paga il resto «per i vecchi amici». Il posto è salvo, e una vecchia amicizia ricucita. Di' alla zia che Behn è tornato.",
  "de": "ENDE (gut, geheim) — Herr Behn isst die aufgehobene Schale; als das Geld fehlt, steht er auf und zahlt den Rest „für alte Freunde“. Der Platz ist gerettet, und eine alte Freundschaft wieder gekittet. Sag der Tante, Behn ist zurückgekommen.",
  "pt": "FIM (bom, secreto) — O Sr. Behn come a tigela que guardaste; quando falta dinheiro, levanta-se e paga o resto «pelos velhos amigos». O lugar está salvo, e uma velha amizade reatada. Diz à tia que o Behn voltou.",
  "ru": "КОНЦОВКА (хорошая, тайная) — Господин Бен съедает отложенную миску; когда денег не хватает, он встаёт и доплачивает «ради старых друзей». Место спасено, а старая дружба восстановлена. Скажи тёте, что Бен вернулся.",
  "ar": "النهاية (جيدة، سرّية) — يأكل السيد بِن الوعاء الذي احتفظتَ به؛ وحين ينقص المال ينهض ويدفع الباقي «إكراماً للأصدقاء القدامى». المكان آمن، وصداقة قديمة تُرمَّم. أخبر العمّة أن بِن قد عاد.",
  "zh": "结局（好·隐藏）——贝恩先生慢慢吃下你留的那碗；当钱不够时，他站起来，替你补齐，“为了老朋友”。摊位保住了，一段旧情也重新接上。告诉姑婆，贝恩回来了。",
 },
 122: {
  "fr": "FIN (bonne) — Vous avez réuni la taxe seul : sans prêt, sans faveur, sans compromis. Épuisé et fier, vous avez porté le stand par vos propres forces.",
  "es": "FINAL (bueno) — Reuniste la cuota tú solo: sin préstamo, sin favores, sin atajos. Agotado y orgulloso, sostuviste el puesto con tus propias fuerzas.",
  "it": "FINALE (buono) — Hai messo insieme la quota da solo: senza prestito, senza favori, senza scorciatoie. Sfinito e fiero, hai retto la bancarella con le tue forze.",
  "de": "ENDE (gut) — Du hast die Gebühr allein zusammenbekommen: ohne Darlehen, ohne Gefallen, ohne Abkürzung. Erschöpft und stolz hast du den Stand aus eigener Kraft getragen.",
  "pt": "FIM (bom) — Juntaste a taxa sozinho: sem empréstimo, sem favores, sem atalhos. Exausto e orgulhoso, seguraste a banca com as tuas próprias forças.",
  "ru": "КОНЦОВКА (хорошая) — Ты собрал плату сам: без ссуды, без одолжений, без срезанных углов. Вымотанный и гордый, ты вытянул лоток своими силами.",
  "ar": "النهاية (جيدة) — جمعتَ الرسم وحدك: دون قرض ولا معروف ولا طريق مختصر. منهكاً وفخوراً، حملتَ الكشك بقوّتك.",
  "zh": "结局（好）——你靠自己凑齐了摊费：没借钱、没求人、没走捷径。筋疲力尽却自豪，你用自己的双手撑住了这个摊子。",
 },
 123: {
  "fr": "FIN (bonne) — L'argent manque un peu, mais vos habitués prennent votre défense ; sur votre bon nom, le maître garde l'emplacement.",
  "es": "FINAL (bueno) — Falta un poco de dinero, pero tus clientes de siempre te defienden; por tu buen nombre, el jefe conserva el puesto.",
  "it": "FINALE (buono) — Mancano un po' di soldi, ma i tuoi clienti abituali ti difendono; per il tuo buon nome, il capo tiene il posto.",
  "de": "ENDE (gut) — Es fehlt etwas Geld, aber deine Stammkunden legen ein gutes Wort ein; um deines guten Namens willen behält der Meister den Platz.",
  "pt": "FIM (bom) — Falta um pouco de dinheiro, mas os teus clientes do costume defendem-te; pelo teu bom nome, o mestre mantém o lugar.",
  "ru": "КОНЦОВКА (хорошая) — Денег чуть не хватает, но твои завсегдатаи вступаются за тебя; за доброе имя хозяин оставляет место.",
  "ar": "النهاية (جيدة) — ينقص بعض المال، لكن زبائنك الدائمين يشهدون لك؛ بفضل سمعتك الطيّبة يُبقي المدير المكان لك.",
  "zh": "结局（好）——钱差了一点，但你的老主顾们替你说话；凭你的好名声，管事保住了你的摊位。",
 },
 124: {
  "fr": "FIN (mitigée) — Vous avez tout juste réuni la taxe, mais en bâclant : bols à moitié cuits, monnaie courte, quelques habitués perdus. L'emplacement est sauvé, le nom un peu terni.",
  "es": "FINAL (agridulce) — Reuniste la cuota justa, pero a base de atajos: cuencos a medio hacer, cambio corto, algún cliente perdido. El puesto se salva, el nombre algo manchado.",
  "it": "FINALE (agrodolce) — Hai raggiunto a malapena la quota, ma tagliando angoli: ciotole a metà, resto corto, qualche cliente perso. Il posto è salvo, il nome un po' sciupato.",
  "de": "ENDE (zwiespältig) — Du hast die Gebühr knapp geschafft, aber mit Pfusch: halbgare Schalen, zu wenig Wechselgeld, ein paar verlorene Stammkunden. Der Platz ist gerettet, der Name etwas ramponiert.",
  "pt": "FIM (agridoce) — Juntaste a taxa à justa, mas cortando caminho: tigelas meio cruas, troco a menos, alguns clientes perdidos. O lugar está salvo, o nome um pouco manchado.",
  "ru": "КОНЦОВКА (неоднозначная) — Ты впритык собрал плату, но срезая углы: недоваренные миски, недосдача, пара потерянных завсегдатаев. Место спасено, доброе имя слегка подпорчено.",
  "ar": "النهاية (مُرّة حلوة) — جمعتَ الرسم بالكاد، لكن بالتهاون: أوعية نصف مطهوّة، وباقٍ ناقص، وبعض الزبائن لن يعودوا. المكان آمن، والسمعة أقلّ قليلاً.",
  "zh": "结局（苦乐参半）——你勉强凑足了费，却是靠偷工：半生的碗、少找的钱、几个不会再来的熟客。摊位保住了，名声却折了一些。",
 },
 125: {
  "fr": "FIN (mitigée) — L'argent manque, mais la marchande de thé pose ses propres pièces pour combler l'écart : « Tu m'as aidée, je t'aide. » L'emplacement est sauvé par une gentillesse rendue.",
  "es": "FINAL (agridulce) — Falta dinero, pero la vendedora de té pone sus propias monedas para cubrir la diferencia: «Me ayudaste, ahora te ayudo». El puesto se salva por una amabilidad devuelta.",
  "it": "FINALE (agrodolce) — Mancano soldi, ma la venditrice di tè mette le sue monete per colmare il divario: «Mi hai aiutato, ora ti aiuto». Il posto è salvo per una gentilezza ricambiata.",
  "de": "ENDE (zwiespältig) — Es fehlt Geld, aber die Teeverkäuferin legt ihre eigenen Münzen dazu, um die Lücke zu schließen: „Du hast mir geholfen, jetzt helfe ich dir.“ Der Platz ist durch eine erwiderte Freundlichkeit gerettet.",
  "pt": "FIM (agridoce) — Falta dinheiro, mas a vendedora de chá põe as suas próprias moedas para cobrir a diferença: «Ajudaste-me, agora ajudo-te». O lugar salva-se por uma gentileza retribuída.",
  "ru": "КОНЦОВКА (неоднозначная) — Денег не хватает, но торговка чаем добавляет свои монеты, чтобы покрыть разницу: «Ты мне помог — теперь я тебе». Место спасено ответной добротой.",
  "ar": "النهاية (مُرّة حلوة) — ينقص المال، لكن بائعة الشاي تضع نقودها لتسدّ الفرق: «ساعدتني، والآن أساعدك». يُنقَذ المكان بمعروفٍ رُدّ.",
  "zh": "结局（苦乐参半）——钱不够，但卖茶女人掏出自己的钱补上缺口：“你帮了我，这回我帮你。”摊位靠一份回报的善意保住了。",
 },
 126: {
  "fr": "FIN (mitigée) — L'emplacement est perdu pour ce soir, mais le gamin revient avec toute une bande d'affamés et des pièces pour vos derniers bols. Pas assez pour sauver la place, mais le début de quelque chose.",
  "es": "FINAL (agridulce) — El puesto se pierde por esta noche, pero el chico vuelve con toda una pandilla hambrienta y monedas para tus últimos cuencos. No basta para salvar la plaza, pero es el comienzo de algo.",
  "it": "FINALE (agrodolce) — Il posto è perso per stanotte, ma il ragazzino torna con un'intera banda affamata e monete per le tue ultime ciotole. Non basta a salvare la piazzola, ma è l'inizio di qualcosa.",
  "de": "ENDE (zwiespältig) — Der Platz ist für heute Nacht verloren, aber das Kind kommt mit einer ganzen hungrigen Bande und Münzen für deine letzten Schalen zurück. Nicht genug, um den Stand zu retten, aber der Anfang von etwas.",
  "pt": "FIM (agridoce) — O lugar perde-se por esta noite, mas o miúdo volta com um bando faminto e moedas para as tuas últimas tigelas. Não chega para salvar a banca, mas é o início de algo.",
  "ru": "КОНЦОВКА (неоднозначная) — Место на эту ночь потеряно, но мальчишка возвращается с целой голодной ватагой и монетами за твои последние миски. Спасти лоток не хватит, но это начало чего-то.",
  "ar": "النهاية (مُرّة حلوة) — يضيع المكان هذه الليلة، لكن الفتى يعود ومعه عصبة جائعة ونقود لآخر أوعيتك. لا يكفي لإنقاذ المكان، لكنه بداية شيء ما.",
  "zh": "结局（苦乐参半）——今晚摊位是保不住了，但那孩子带着一群饿着肚子的伙伴回来，手里攥着买你最后几碗的钱。救不了摊位，却是某种开始。",
 },
 127: {
  "fr": "FIN (mitigée) — L'argent manque, mais le maître vous accorde un jour de marché de plus, au nom des trente ans de Tatie. Ni victoire ni défaite : une nouvelle chance.",
  "es": "FINAL (agridulce) — Falta dinero, pero el jefe te concede un día de mercado más, por los treinta años de la tía. Ni victoria ni derrota: otra oportunidad.",
  "it": "FINALE (agrodolce) — Mancano soldi, ma il capo ti concede un altro giorno di mercato, in nome dei trent'anni della zia. Né vittoria né sconfitta: un'altra occasione.",
  "de": "ENDE (zwiespältig) — Es fehlt Geld, aber der Meister gewährt dir im Namen der dreißig Jahre der Tante einen weiteren Markttag. Kein Sieg, keine Niederlage: eine neue Chance.",
  "pt": "FIM (agridoce) — Falta dinheiro, mas o mestre concede-te mais um dia de mercado, em nome dos trinta anos da tia. Nem vitória nem derrota: outra oportunidade.",
  "ru": "КОНЦОВКА (неоднозначная) — Денег не хватает, но хозяин даёт тебе ещё один базарный день — ради тридцати лет тёти. Не победа и не поражение: ещё один шанс.",
  "ar": "النهاية (مُرّة حلوة) — ينقص المال، لكن المدير يمنحك يوم سوقٍ آخر، إكراماً لثلاثين عاماً من العمّة. لا فوز ولا خسارة: فرصة أخرى.",
  "zh": "结局（苦乐参半）——钱不够，但管事看在姑婆三十年的份上，再给你一个赶集日。不算赢，也不算输：又一次机会。",
 },
 128: {
  "fr": "FIN (mauvaise) — La taxe est payée avec l'argent de Sould : l'emplacement est à lui en tout sauf le nom. Demain il sourira, vous appellera « ami », et commencera à fixer son prix.",
  "es": "FINAL (malo) — La cuota se paga con el dinero de Sould: el puesto es suyo en todo menos en el nombre. Mañana sonreirá, te llamará «amigo» y empezará a poner su precio.",
  "it": "FINALE (cattivo) — La quota è pagata coi soldi di Sould: il posto è suo in tutto tranne che nel nome. Domani sorriderà, ti chiamerà «amico» e comincerà a fare il suo prezzo.",
  "de": "ENDE (schlecht) — Die Gebühr ist mit Soulds Geld bezahlt: Der Platz gehört ihm in allem außer dem Namen. Morgen wird er lächeln, dich „Freund“ nennen und anfangen, seinen Preis zu nennen.",
  "pt": "FIM (mau) — A taxa é paga com o dinheiro de Sould: o lugar é dele em tudo menos no nome. Amanhã vai sorrir, chamar-te «amigo» e começar a impor o seu preço.",
  "ru": "КОНЦОВКА (плохая) — Плата внесена деньгами Соулда: место его во всём, кроме названия. Завтра он улыбнётся, назовёт тебя «другом» и начнёт назначать свою цену.",
  "ar": "النهاية (سيّئة) — دُفِع الرسم بمال سولد: المكان له في كلّ شيء إلّا الاسم. غداً سيبتسم ويناديك «يا صديق»، ويبدأ في فرض ثمنه.",
  "zh": "结局（坏）——摊费是用苏尔德的钱交的：摊位除了名义之外都成了他的。明天他会笑着喊你“朋友”，然后慢慢开出他的价码。",
 },
 129: {
  "fr": "FIN (mauvaise) — L'argent reste en dessous de la taxe. Le maître compte deux fois, mais le chiffre ne change pas : l'emplacement passe sur la liste du matin. Trente ans finis en une nuit — sans faute de votre part.",
  "es": "FINAL (malo) — El dinero no llega a la cuota. El jefe cuenta dos veces, pero la cifra no cambia: el puesto pasa a la lista de la mañana. Treinta años terminados en una noche, sin culpa tuya.",
  "it": "FINALE (cattivo) — I soldi restano sotto la quota. Il capo conta due volte, ma la cifra non cambia: il posto va sulla lista del mattino. Trent'anni finiti in una notte, senza colpa tua.",
  "de": "ENDE (schlecht) — Das Geld bleibt unter der Gebühr. Der Meister zählt zweimal, doch die Zahl ändert sich nicht: Der Platz kommt auf die Morgenliste. Dreißig Jahre in einer Nacht zu Ende, ohne deine Schuld.",
  "pt": "FIM (mau) — O dinheiro fica abaixo da taxa. O mestre conta duas vezes, mas o número não muda: o lugar vai para a lista da manhã. Trinta anos acabados numa noite, sem culpa tua.",
  "ru": "КОНЦОВКА (плохая) — Денег не хватает до платы. Хозяин пересчитывает дважды, но число не меняется: место уходит в утренний список. Тридцать лет кончились за одну ночь — не по твоей вине.",
  "ar": "النهاية (سيّئة) — يبقى المال دون الرسم. يعدّه المدير مرّتين، لكن الرقم لا يتغيّر: يذهب المكان إلى قائمة الصباح. ثلاثون عاماً تنتهي في ليلة، دون ذنبٍ منك.",
  "zh": "结局（坏）——钱始终不够交费。管事数了两遍，数字没变：摊位被列入早晨的名单。三十年，在你当家的这一夜终结——并不是你的错。",
 },
 130: {
  "fr": "FIN (mauvaise) — Vous êtes tombé en rupture bien trop tôt : des heures avant l'aube, la marmite était vide. Ce n'est pas la malchance, mais une mauvaise organisation. Loin du compte.",
  "es": "FINAL (malo) — Te quedaste sin existencias demasiado pronto: horas antes del alba, la olla estaba vacía. No fue mala suerte, sino mala planificación. Muy lejos de la cuota.",
  "it": "FINALE (cattivo) — Sei rimasto senza scorte troppo presto: ore prima dell'alba la pentola era vuota. Non è stata sfortuna, ma cattiva organizzazione. Molto sotto la quota.",
  "de": "ENDE (schlecht) — Dir ging viel zu früh die Ware aus: Stunden vor dem Morgengrauen war der Topf leer. Es war kein Pech, sondern schlechte Planung. Weit unter der Gebühr.",
  "pt": "FIM (mau) — Ficaste sem stock cedo demais: horas antes do amanhecer, a panela estava vazia. Não foi azar, foi má organização. Muito longe da taxa.",
  "ru": "КОНЦОВКА (плохая) — Товар кончился слишком рано: за часы до рассвета котёл опустел. Это не невезение, а плохое планирование. До платы далеко.",
  "ar": "النهاية (سيّئة) — نفدت بضاعتك مبكراً جداً: قبل الفجر بساعات كانت القِدر فارغة. لم يكن سوء حظّ، بل سوء تدبير. وأنت بعيد عن الرسم.",
  "zh": "结局（坏）——你太早就断了货：离天亮还有好几个钟头，锅就空了。这不是运气差，而是没安排好。离摊费还差得远。",
 },
 131: {
  "fr": "FIN (mauvaise) — La taxe est hors de portée et quelque chose cède en vous. Épuisé, vous songez un instant à abandonner le stand. Vous ne le dites pas tout haut — mais cette nuit, pour la première fois, vous y pensez.",
  "es": "FINAL (malo) — La cuota queda fuera de alcance y algo en ti se rinde. Agotado, por un momento piensas en dejar el puesto. No lo dices en voz alta, pero esta noche, por primera vez, lo piensas.",
  "it": "FINALE (cattivo) — La quota è irraggiungibile e qualcosa dentro di te cede. Sfinito, per un attimo pensi di lasciare la bancarella. Non lo dici ad alta voce, ma stanotte, per la prima volta, ci pensi.",
  "de": "ENDE (schlecht) — Die Gebühr ist unerreichbar, und etwas in dir gibt auf. Erschöpft denkst du einen Moment daran, den Stand aufzugeben. Du sagst es nicht laut – aber heute Nacht denkst du es zum ersten Mal.",
  "pt": "FIM (mau) — A taxa está fora de alcance e algo em ti cede. Exausto, por um momento pensas em desistir da banca. Não o dizes em voz alta, mas esta noite, pela primeira vez, pensa-lo.",
  "ru": "КОНЦОВКА (плохая) — Плата недостижима, и что-то в тебе сдаётся. Измотанный, ты на миг думаешь бросить лоток. Вслух не говоришь — но этой ночью впервые об этом думаешь.",
  "ar": "النهاية (سيّئة) — الرسم بعيد المنال وشيءٌ فيك يستسلم. منهكاً، تفكّر للحظة في ترك الكشك. لا تقولها بصوتٍ عالٍ، لكنك الليلة، لأول مرّة، تفكّر فيها.",
  "zh": "结局（坏）——摊费遥不可及，你心里某处悄悄塌了。疲惫至极，你有一瞬想到干脆放弃这个摊子。你没有说出口——但今夜，你第一次动了这个念头。",
 },
}

for lg in LANGS:
    data = {str(nid): G[nid][lg] for nid in sorted(G)}
    json.dump(data, open(os.path.join(OUT, lg + ".json"), "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)
print("Wrote %d gist files (%d passages each) to content/gist/the-night-market/" % (len(LANGS), len(G)))
