#!/usr/bin/env python3
"""Extend The Night Market's French gist to full per-passage coverage.
Merges these French summaries into content/gist/the-night-market/fr.json, keeping the existing
(vouched) entries and adding one for every remaining passage. French-first; other languages later.
Native review: complete. Run: python3 scripts/build_gist_fr_full_ep02.py
"""
import json, os
SLUG = "the-night-market"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", SLUG, "fr.json")

FR = {
 2: "Vous levez le rideau, allumez les brûleurs sous la grande marmite, accrochez les deux lanternes rouges et nettoyez le comptoir. Sur l'étagère du fond, une place reste vide. Autour de vous, le marché s'éveille — voix, fumée, odeur d'huile chaude et d'ail.",
 3: "Vous appelez Tatie. Sa voix est fatiguée mais claire : « Goûte le bouillon avant de le vendre. Achète chez le vieux Han, pas à la camionnette. Et mets un bol de côté pour M. Behn. » Elle raccroche, souffrante, avant que vous puissiez en demander plus.",
 4: "Dans la caisse, une carte de la main de Tatie indique la somme à atteindre avant l'aube. Le chiffre est gros, et un bol ne rapporte que quelques pièces : il faudra une nuit entière, bien remplie, pour y arriver.",
 5: "La marchande de thé du stand 25, là depuis des années, se penche gentiment : « C'est donc toi ce soir. La main de ta tante, c'est grave ? » Elle voit ton comptoir vide et tes mains nerveuses, et sourit : « Ne t'en fais pas, je garde un œil sur toi. »",
 7: "Vous demandez qui est M. Behn. Un silence. « Un vieil ami, dit enfin Tatie. Il venait chaque soir, puis il a cessé. Garde-lui son bol, c'est tout. S'il te plaît. » Il y a dans sa voix quelque chose que vous ne savez pas lire.",
 8: "Vous faites le calcul : un bol ne vaut que quelques pièces, et la somme en exigera des centaines — toute une nuit sans pause, sans rien gâcher. C'est faisable ; Tatie le fait chaque saison. Mais elle est rapide et sûre, et vous ne l'êtes pas encore.",
 9: "La marchande de thé vous explique la nuit : « Du monde vers neuf heures, encore à minuit. Prix juste, sois rapide, ne gâche rien. » Puis, plus bas : « M. Sould passera. Il offrira son aide — un prêt, un mot à un rival. Dis non. Son aide est un hameçon. »",
 10: "Le porc du vieux Han est rose et frais, ses légumes croquants. Vous les rangez dans la glacière. Cela coûte plus cher que voulu — mais la différence se goûtera, et les clients le sentiront. La bonne nourriture, c'est ainsi que Tatie tient ce coin depuis trente ans.",
 11: "La marchandise bon marché coûte moitié prix, alors vous la rapportez. Mais le porc sent mauvais et les légumes ramollissent déjà. Vous avez économisé — peut-être du mauvais côté. Un mauvais bol coûte cher : un client perdu, et tous ceux à qui il le dira.",
 12: "Vous achetez un peu de bon et un peu de bon marché, pour assurer. Cela paraît prudent. Mais la moitié de vos bols seront en deçà du meilleur de Tatie, et un seul bol faible, au mauvais moment, peut faire fuir une foule. Il faudra surveiller quel stock va dans quel bol.",
 14: "Vous la remerciez. « On se serre les coudes sur ce coin, dit-elle. Ta tante l'a fait pour moi plus de fois que je peux compter. » Savoir qu'on n'est pas seul cette nuit fait du bien : un visage ami vaut beaucoup, une fois la foule arrivée.",
 15: "Un homme en manteau propre s'arrête, souriant comme un vieil ami : « Tu dois être la famille de Sim. Quelle histoire, sa main. Ne t'inquiète pas — je veille sur ce marché. Le moindre besoin ce soir, tu viens voir M. Sould. » Son sourire est chaud. Ses yeux, non.",
 16: "Le stand est enfin prêt : lanternes rouges, bouillon fumant, bols empilés. Dans la galerie, la foule coule déjà, dense, dans la fumée, le bruit et l'odeur de cent cuisines. Certains ont faim. Certains s'arrêteront ici — si vous êtes rapide et si c'est bon.",
 17: "Vous jetez le pire du stock bon marché. Cela fait mal de jeter de l'argent déjà dépensé — mais un mauvais bol coûterait bien plus. Vous gardez ce qui semble encore bon, le reste part. Mieux vaut une nuit plus petite qu'un nom taché. Tatie aurait fait pareil.",
 18: "Un bol attend maintenant sur l'étagère du fond, plein et chaud, pour un homme qui ne viendra peut-être jamais. Il a l'air petit là-haut, un peu triste — mais aussi juste. C'est le stand de Tatie, et c'est ainsi qu'il a toujours été. Vous gardez vivant plus qu'un commerce.",
 19: "Le grand brûleur claque et claque sans s'allumer — le gaz siffle, pas de flamme. Sans lui, le bouillon reste froid, et le bouillon froid ne se vend pas. Vos mains tremblent un peu ; ce n'est pas le début rêvé. Mais tout cuisinier a déjà lutté contre un brûleur têtu.",
 20: "Vous goûtez le bouillon : le sel d'abord, puis le gingembre, puis une note chaude et profonde que vous ne savez nommer. C'est le goût pour lequel on traverse le marché — trente ans de soin dans une cuillerée. Faites-le comme elle vous l'a appris, et le bouillon vendra pour vous.",
 21: "Tatie revient sans cesse sur la somme : « Ne perds pas le coin. Ma mère l'avait avant moi — trente ans. » La peur court sous ses mots. Vous la rassurez, sans en être sûr vous-même. Mais elle doit reposer sa main, et s'inquiéter au téléphone n'aide ni l'un ni l'autre.",
 22: "Les habitués connaissent le bol de Tatie par cœur — la taille, la chaleur, le prix, l'équilibre exact. Si le vôtre diffère, ils le sentiront dès la première gorgée. Vous ne pouvez pas être Tatie ce soir. Mais vous pouvez faire son bol à sa façon et le laisser parler pour elle.",
 23: "Votre toute première grosse commande : une famille de six, parlant tous en même temps. Six bols, avec des variantes pour les enfants. Beaucoup à retenir en une heure. Bien fait, ils reviendront toute la saison ; raté, votre première histoire de la nuit sera mauvaise.",
 24: "Un petit enfant compte ses pièces en une pile soignée. Il lui manque une pièce pour un bol. Il vous regarde, puis les pièces, puis vous, sans un mot. Un tout petit moment — mais votre réponse est exactement ce dont un marché se souvient d'un stand.",
 26: "Les commandes fusent de partout : « Deux bols ! » « Plus de raviolis ! » « C'est long l'attente ? » Impossible de tout retenir. Il faut un système, vite : prendre dans l'ordre, répéter chacune, garder la file qui avance. La panique perd des bols, le calme les garde. Vous choisissez le calme.",
 27: "« Où est Sim ? » demande un habitué, cherchant son visage. « Elle va bien ? » Vous pouvez dire la vérité — sa main, la brûlure, vous ce soir — ou sourire, servir, rester léger. On vient pour la nourriture, mais aussi pour elle. Votre réponse dit quel stand c'est ce soir.",
 28: "Le bouillon brûlant éclabousse votre main et vous gémissez. Ça brûle, vif et soudain — comme Tatie s'est blessée, pensez-vous follement. Un instant, la douleur emplit tout. Puis vous respirez et l'enveloppez d'un linge mouillé. Le stand ne s'arrête pas pour une brûlure.",
 29: "Le cuit-vapeur siffle puis se tait — à sec, les raviolis à moitié cuits. Vous le rattrapez de justesse : une minute de plus et ça brûlait, et l'odeur de brûlé vide un comptoir plus vite que tout. Vous le remplissez vite et avec soin. Une petite victoire — mais elles s'additionnent.",
 30: "Un moment plus calme. Vous essuyez, réapprovisionnez les bols, rangez le comptoir. Dans le calme, l'esprit dérive — la somme, le tabouret vide, la voix inquiète de Tatie. Puis un client paraît et vous revoilà dedans. Mais c'est dans les accalmies qu'on pense, et penser fait tenir la nuit.",
 31: "Les premiers vrais clients arrivent, affamés et prêts à payer. Alors, quel prix ? Tatie a un tarif juste et stable, que tous ses habitués connaissent. Vous pouvez l'égaler, monter pour les touristes, ou baisser pour vendre plus. Le chiffre choisi ce soir est une sorte de promesse.",
 32: "Vous fixez un prix juste — ni trop haut, ni trop bas. C'est honnête, et l'honnête est facile à assumer. Les clients paient sans broncher ; personne ne discute le juste. Vous ne gagnerez pas le plus par bol, mais les gens reviendront, et un stand plein vaut toujours mieux qu'un stand avide.",
 33: "Vous gonflez le prix. Les touristes n'y verront rien, et plus par bol veut dire moins de bols pour atteindre la somme — tentant. Mais la rumeur court vite : si les habitués vous surprennent à doubler, ils se sentiront floués, et un stand qui triche ne tient pas un coin trente ans.",
 34: "Vous appliquez le prix habituel de Tatie, au centime près. Le premier habitué le remarque, et quelque chose s'apaise sur son visage : « Comme toujours », dit-il, content. Cela leur dit, à sa manière, qu'elle est toujours là. Parfois le choix le plus sûr est aussi, simplement, le bon.",
 35: "Vous versez le bouillon, ajoutez les raviolis, tendez les premiers bols. La vapeur monte dans la nuit froide ; des mains prennent les bols ; les pièces tombent dans la caisse. Ça marche — vous y arrivez vraiment. Et un instant, par-dessus le bruit, vous sentez une petite fierté féroce.",
 36: "Quelqu'un ronchonne, fort, que c'est trop cher. Des têtes se tournent. Un ronchonnement peut se répandre ou mourir sur place, selon ce que vous faites. Vous pouvez revenir au juste prix pour garder la paix, ou tenir bon et laisser la nourriture parler plus fort qu'une voix.",
 37: "Un client prend une bouchée et s'arrête net : « C'est la vraie, dit-il, surpris. Comme la sienne. » Il le dit assez fort pour qu'on entende, et quelques personnes s'approchent. La bonne nourriture est sa meilleure publicité — une bouche heureuse attire toute une file.",
 38: "Un client fronce les sourcils : « C'est un peu fade. Pas comme d'habitude. » Peut-être le stock bon marché, peut-être votre main avec le gingembre. Dur à entendre le premier soir. Vous pouvez corriger l'assaisonnement maintenant, avant le prochain bol, ou laisser filer en espérant que la foule couvre ça.",
 39: "Entre deux commandes, vous jetez un œil à la caisse. Il y a des pièces dedans — des vraies, gagnées de vos mains. Loin de la somme, pas encore, mais c'est un début, et un début vaut bien plus que rien il y a une heure. Vous refermez et retournez à la vapeur et à la foule.",
 40: "Vous comptez vite, sous le comptoir. C'est un début — mais rien qu'un début. À ce rythme, la somme ne sera pas atteinte à l'aube ; il vous faut le coup de feu, et un bon. La grande foule de minuit, affamée et prompte à dépenser, fait ou défait une nuit pareille.",
 41: "Et la foule arrive — non plus un filet mais une vague. Employés, familles, travailleurs de nuit, déferlant d'un coup dans la galerie, et le bruit double. Dix visages à votre comptoir, puis vingt. Les commandes fusent. C'est le coup de feu. C'est la nuit. La voilà.",
 43: "La galerie est bondée, les gens se bousculent avec des sacs et des enfants endormis. L'air est épais et chaud de vapeur et d'huile. Votre petit stand est une île dans le bruit. Plus le temps de penser, seulement d'agir — alors vous respirez un coup et vous vous lancez.",
 45: "Vous accélérez trop. Un bol sort à moitié cuit ; vous rendez la monnaie en moins, par accident ou non. Vous vous dites que c'est le coup de feu, que tout le monde fait ça. Mais rogner, c'est un trou dans le seau — ça fait fuir votre bon nom, une petite coupe à la fois.",
 46: "Vous appelez à l'aide, la voix se brisant dans le bruit. Mais qui peut venir ? Le gamin du marché est près — vif, toujours affamé, toujours prêt à courir pour une pièce. Ou la marchande de thé d'à côté, quoiqu'un coup d'œil montre qu'elle est aussi débordée que vous. Une seconde pour choisir.",
 47: "Le coup de feu continue. Vos bras, votre dos vous font mal — mais la caisse s'alourdit, et ce son, les pièces sur les pièces, vous tient debout. Bol après bol, visage après visage. Vous êtes en plein dedans, et vous tenez. Vous ne pensiez pas y arriver. Et pourtant vous y êtes.",
 48: "« Hé — ce n'est pas le compte. » Le client tend la main, paume ouverte : la monnaie est en moins. Des têtes se tournent. Votre visage chauffe. C'est le moment : vous pouvez vous excuser et corriger tout de suite, ou discuter en espérant qu'il cède avant que d'autres entendent.",
 49: "Vous regardez le stock et le cœur vous tombe : le porc presque fini, les légumes à une dernière poignée. La nuit n'est pas à moitié passée et vous manquez déjà. Vous pouvez faire des bols plus petits pour étirer, envoyer chercher du renfort, ou laisser le cuit-vapeur se vider et décider pour vous.",
 50: "Un instant la foule s'éclaircit et vous respirez. Vous essuyez la sueur et le comptoir. Les lanternes se balancent au vent. Ça ne durera pas — le vrai coup de feu de minuit est à venir — mais une accalmie est un cadeau. Utilisez-la bien, et soyez prêt quand la vague revient.",
 51: "« Vous avez raison — pardon. » Vous recomptez, lentement cette fois, et glissez la pièce manquante dans sa main. « Longue nuit. Merci de votre patience. » Le client s'adoucit ; les têtes se détournent. Une erreur réparée vite et avec douceur n'est pas une tache — bien gérée, elle peut même jouer en votre faveur.",
 52: "Vous vous appuyez au comptoir et respirez une seconde. La caisse est lourde maintenant — plus que vous n'osiez l'espérer. Vous pourriez vous arrêter pour compter et voir où vous en êtes. Ou garder le compte pour plus tard et replonger tant que la foule est là et dépense.",
 54: "« La monnaie était juste », dites-vous, en tenant son regard jusqu'à ce qu'il cède. Il hausse les épaules et s'en va en maugréant. Vous avez gagné — sauf que non. Il en parlera, et un nom court plus vite qu'un client. Vous avez sauvé une pièce ce soir, et dépensé bien plus précieux.",
 55: "Vous glissez des pièces au gamin et l'envoyez chercher du porc et des légumes. Il connaît chaque ruelle et file avant que vous ayez fini la phrase. Il faut tenir le stand seul jusqu'à son retour. Vous espérez que le stock tiendra, et que le gamin est aussi rapide et honnête que vous le pensez.",
 56: "Vous faites les bols un peu plus petits — plus de bouillon, moins de raviolis, un peu moins de porc. Peu le remarqueront une nuit si chargée. Ça étire le stock et gagne du temps. Ce n'est pas tricher ; le bol reste bon, honnête et chaud. Juste une cuisinière prudente avec ce qu'elle a — Tatie approuverait.",
 57: "Le coup de feu continue et vous perdez le fil du temps dedans. Rien que vapeur, visages, bols, pièces, et la chaleur des brûleurs sur les bras. Dehors il se fait tard ; quelque part la somme attend encore. Mais pour l'instant il n'y a que le prochain bol, et le suivant, et le suivant.",
 59: "Dans un creux, votre œil tombe sur l'étagère du fond. Le bol réservé y refroidit lentement. En dessous, le tabouret du bout reste vide, comme toute la nuit — celui de M. Behn. Qui est-il ? Pourquoi Tatie garde-t-elle son bol ? Le coup de feu tire, mais le tabouret vide tire aussi, plus doucement.",
 60: "Enfin le coup de feu culmine et retombe. La foule passe de la vague au filet, et vous relevez les yeux en clignant, comme en remontant des profondeurs. Vous tenez encore ; le stand est toujours à vous. Mais la nuit n'en a pas fini — il vient toujours quelque chose dans le calme après la vague.",
 63: "« Non merci, dites-vous. On se débrouillera. » Le sourire de Sould tient, mais ses yeux se refroidissent d'un cran. « Comme tu voudras », et il passe au stand suivant. Vous vous sentez plus léger dès qu'il est parti. Quoi qu'il arrive, ce sera à vous — la victoire ou la perte, mais sans son hameçon en vous.",
 64: "Vous prenez l'argent de Sould. La somme est couverte, quoi que fasse la nuit. Un instant le poids s'envole et vous respirez. Puis le malaise monte : vous n'avez lu aucune condition, vous ignorez ce que « plus tard » veut dire. Vous avez troqué un souci pour un autre — et celui-là sourit, et sait où vous trouver.",
 65: "« Ça coûte combien ? » demandez-vous. Sould sourit plus large : « Ne t'en fais pas pour ça maintenant. On réglera plus tard. Entre amis, toujours. » Il refuse de donner un chiffre, et c'est tout le piège. Un vrai prix se pèse ; un prix sans chiffre est une corde sans bout. Vous le voyez clairement.",
 66: "Vous observez la file des marchands qui attendent de payer Sould. Certains ont l'air calme ; d'autres fatigués, un peu effrayés. Une vieille femme recompte ses pièces avant de les tendre. Voilà comment marche vraiment le marché, sous les lanternes : un homme tranquille, une longue file, et l'argent qui coule vers lui toute la nuit.",
 67: "La marchande d'à côté se penche : « Quoi qu'il offre, dis non, murmure-t-elle. Sould n'oublie jamais une dette. Mon cousin a emprunté une fois. Trois ans à rembourser. Trois ans. » Elle se redresse quand Sould regarde. « Sois... prudent », dit-elle, et se retourne. L'avertissement vous glace.",
 68: "Vers la fermeture, Sould repasse : « Tu as fait la somme ? demande-t-il, doux, comme s'il tenait à vous. Parce que l'offre tient toujours. Dernière chance ce soir. » Il sait exactement comment la nuit s'est passée — il sait toujours. Son prêt finirait la peur tout de suite. Mais son prêt ne finit jamais vraiment.",
 74: "Vous tendez un bol plein au gamin : « Mange. Tu l'as mérité. » Son visage tout entier change. Il mange vite, dans un coin, comme s'il craignait que ça disparaisse. Un seul bol ; cela ne vous coûte presque rien. Mais pour le gamin, c'est le monde entier un instant — et il n'oubliera pas qui le lui a donné.",
 75: "Vous payez le gamin en pièces, comme convenu, rien de plus. Il empoche et hoche la tête — il comprend, les pièces sont le marché, et le marché est juste. Mais il a encore faim, et son regard glisse vers les bols en partant. Vous avez été juste. Juste, c'est bien. Mais juste n'est pas tout à fait gentil.",
 76: "Le gamin ne part pas. Il traîne au bord du stand — observe, apprend, tend un linge ou une cuillère avant même qu'on demande. Sa présence allège toute la nuit. Un marché est plein de gens qui passent entre les mailles, et parfois un stand est le seul endroit chaud qui les laisse rester.",
 77: "Entre deux bols, le gamin vous dit son nom. Et où il dort — un coin sec derrière l'arche aux poissons, le plus souvent. Il le dit simplement, sans quêter la pitié. Vous écoutez, et vous retenez. Un nom est petit à donner et grand à garder, et le marché semble un peu moins fait d'étrangers.",
 78: "Vous laissez le gamin surveiller le stand pendant que vous filez chercher du stock. Petite confiance, qu'il prend au sérieux — droit, faisant patienter les clients, gardant la caisse des deux yeux. À votre retour, rien ne manque. Confiance donnée, confiance tenue — et cela compte, dans un endroit pareil.",
 79: "La pluie balaie la galerie, soudaine et dure, tambourinant sur les toits. La foule se disperse à l'abri et votre comptoir se vide en quelques secondes. La pluie peut tuer une nuit de ventes. Ou, bien prise, remplir votre stand de gens trempés qui veulent soudain du chaud. Cela dépend de vous.",
 80: "Vous vérifiez les pots : le bouillon est bas, le stock presque fini — de quoi tenir un moment, pas toute la nuit. Il faut choisir comment dépenser ce qui reste. De petits bols prudents, pour tirer jusqu'à l'aube. Ou de pleins bols généreux maintenant, au risque d'être à sec des heures trop tôt.",
 81: "Vous baissez l'auvent et attendez. La pluie coule en une longue ligne d'argent. Un moment, presque personne ne vient, alors vous en profitez — essuyer, réapprovisionner, reposer vos pieds, goûter le bouillon. La pluie finit toujours par passer. Et alors le marché ressort, froid et affamé, et vous serez prêt et au chaud.",
 82: "Vous lancez dans la pluie : « Bols chauds ! Sortez du mouillé ! » Quelques transis se glissent sous l'auvent, reconnaissants. Vous leur vendez des bols plus petits, moins chers, vite et chauds. Moins d'argent par bol. Mais un stand plein attire plus qu'un stand vide, et la chaleur se vend seule par nuit froide et humide.",
 83: "La grande marmite est presque vide — on en voit le fond sous le dernier bouillon. C'est le vrai point de danger de la nuit. À sec trop tôt, vous resterez planté devant un stand froid et fermé pendant que le marché tourne encore. Vous pouvez étirer le tout dernier, ou accepter que la marmite est finie et compter.",
 84: "Vous étirez le dernier bouillon — un peu plus d'eau, une main prudente sur l'épice, petits bols à petits prix. C'est plus clair que le meilleur de Tatie, vous le savez. Mais c'est encore chaud, honnête, et sien dans la forme. Mieux vaut un petit bol vrai que pas de bol — alors vous gardez la lanterne et le pot encore un peu.",
 85: "La nuit tourne. La foule s'éclaircit, le bruit s'adoucit, et le marché glisse lentement vers l'aube. Plus loin, des stands tirent déjà leurs rideaux. Bientôt le maître passera pour les redevances. Vous sentez toute la longue nuit dans vos bras et votre dos — mais c'est presque fini, et vous y êtes presque, d'une façon ou d'une autre.",
 86: "Un nouveau stand s'ouvre juste en face, à moitié prix. Le patron crie fort, fait signe, et une partie de votre file dérive vers lui. Pas cher et bruyant attire vite une foule, une nuit pareille. Vous pouvez baisser pour vous aligner et vous battre — ou tenir votre prix, et compter sur votre nourriture pour garder vos gens.",
 87: "Vous baissez pour vous aligner, et vous voilà dans une guerre des prix. Les bols partent, mais chacun ne rapporte presque rien. Débordé, vous n'avancez pas. C'est une course vers le bas, et le bas est là où les stands ferment pour de bon. On ne gagne pas une nuit sur le prix seul — il vous faut un autre moyen, et vite.",
 88: "Vous quittez votre comptoir et allez droit vers elle. Ensemble, vous redressez l'urne, épongez le thé brûlant, calmez ses clients fâchés et la remettez en route. Cela coûte quelques minutes et quelques ventes. Elle vous agrippe le bras, hors d'haleine : « Je n'oublierai pas ça. » Et sur ce coin, ce ne sont pas que des mots.",
 89: "Vous tenez votre prix et laissez le stand bon marché s'époumoner. Certains dérivent vers lui, oui. Mais vos habitués restent. « Le sien, c'est de l'eau, dit l'un en désignant votre pot. Le tien, c'est le vrai. » La bonne nourriture est plus lente à gagner une nuit, mais plus sûre. Pas le moins cher — celui pour qui on fait la queue.",
 90: "Au petit matin, le stand bon marché d'en face s'éteint. Il a tout vendu bien trop bas, n'a presque rien gagné, et s'est retrouvé à court de stock et de cœur en même temps. Le patron remballe, fatigué et aigre. Votre lanterne brûle encore, votre pot est encore chaud. Lent, régulier et honnête dure plus que fort et bon marché.",
 91: "La fermeture approche. La foule est mince, le bruit bas. Sur l'étagère, le bol réservé attend encore — froid maintenant, mais là. En dessous, le tabouret du bout est toujours vide. D'un instant à l'autre le maître passera. Mais vos yeux glissent sans cesse vers ce tabouret, le bol froid, et la question restée sans réponse.",
 92: "Sould paraît à votre comptoir, pile à l'heure : « Alors ? La somme est faite ? Ou il te faut ce petit prêt, finalement ? » Si vous êtes court, c'est la sortie facile : prendre son argent, payer le maître, garder le coin ce soir. Mais vous connaissez le vrai prix de son aide. Il faut lui répondre.",
 93: "Un vieil homme s'avance lentement dans la foule clairsemée — maigre, gris, las. Il s'arrête au tabouret vide du bout, y pose une main, comme s'il le connaissait bien. Il vous regarde, puis l'étagère, puis détourne les yeux. Il ne s'assoit pas, ne commande pas. Il reste là, attendant quelque chose que vous ne savez nommer.",
 94: "Vous descendez le bol réservé et le posez devant lui : « Celui-ci est à vous. Il l'a toujours été. » Le vieil homme regarde le bol, puis vous, et ses yeux s'emplissent. « Elle l'a gardé, dit-il tout bas. Tout ce temps. Elle l'a gardé. » Vous ne comprenez pas encore tout — mais vous savez avoir fait quelque chose de juste.",
 95: "Vous le servez, et enfin il s'assoit. En mangeant, il parle un peu. Lui et Tatie étaient proches, autrefois — puis une brouille, petite et bête, de celles qui durcissent avec les années. Il a cessé de venir. Mais il n'a jamais cessé d'en avoir envie. « Dis-lui, souffle-t-il. Dis-lui que Behn est revenu. »",
 96: "Le tabouret du bout est resté vide toute la nuit, quand toutes les autres places se remplissaient et se vidaient. Un tabouret vide, un bol froid réservé sur l'étagère au-dessus. C'est la chose la plus silencieuse d'un marché bruyant — et, si on y prête l'oreille, la plus bruyante. Tatie le garde pour une raison. Vous aimeriez savoir laquelle.",
 97: "Vous repensez au visage de Tatie au téléphone — sa voix qui change au nom de Behn. Pas de la colère. Quelque chose de plus doux et de plus triste. Qui qu'il soit, il compte encore pour elle, après toutes ces années. Le bol sur l'étagère n'est pas qu'une habitude. C'est une porte qu'elle garde ouverte, au cas où. Vous le comprenez, au moins.",
 98: "Près de la caisse, à demi cachée, une vieille photo. Vous êtes passé devant toute la nuit sans la voir. Maintenant si : Tatie, bien plus jeune, riant. À côté d'elle, un jeune homme qui rit aussi. Au dos, de sa main, deux mots : moi et Behn. Le tabouret vide et le bol froid prennent soudain un sens.",
 100: "Tandis que Behn mange, vous comprenez ce qu'est vraiment devenue cette nuit. Il n'a jamais été question que de la somme. Tatie vous a envoyé tenir le stand — mais aussi, sans le dire, garder sa porte ouverte. Et ça a marché : il est revenu. Quoi qu'il advienne de l'argent, cette part de la nuit est déjà une victoire.",
 101: "Fermeture. Vous sortez la caisse et comptez, pièce par pièce, à la lueur basse des lanternes. Le cœur bat fort. Est-ce assez ? Le chiffre monte à mesure, et vous recomptez pour en être sûr. Au loin, le maître approche — de stand en stand, prenant les redevances, une porte après l'autre. Votre tour est proche.",
 102: "Le maître descend la rangée, lent et sûr. Vieux, juste, il a vu en trente ans toutes les ruses d'un stand. À chaque emplacement il s'arrête, prend la redevance, marque son livre, repart. Certains paient sans peine ; d'autres ne peuvent pas. Vous le regardez approcher et serrez un peu plus votre caisse.",
 103: "Vous voyez un stand, plus loin, rester court. Le maître secoue la tête, ferme mais sans dureté. Le marchand commence, lentement, à remballer — assiettes, pots, toute une vie de nuits, rangée en cartons. Pas de cris, juste une fin tranquille. Ce pourrait être vous dans une heure. La pensée vous raidit : pas ce soir, pas le coin de Tatie.",
 104: "Une à une, tout le long de la rangée, les lanternes descendent. Le marché se met au lit. Le monde vif et bruyant d'il y a quelques heures se replie en cartons et en ombres. Vos deux lanternes rouges brillent encore, pour l'instant. Qu'elles pendent ici la saison prochaine se joue dans les prochaines minutes — et dans les pièces de votre caisse.",
 105: "Une lumière grise rampe sur les toits du marché : l'aube, la fin de la nuit et la fin de la saison. Quelque part un oiseau solitaire s'éveille. L'air sent la cendre froide et la vieille vapeur. Vous êtes debout depuis toute la nuit, et vous en sentez chaque heure. Mais vous êtes encore là, et le stand est encore à vous — pour l'instant.",
 110: "Le maître s'arrête au stand 24. Il vous regarde, puis le stand, puis la place vide de Tatie. « C'est donc toi ce soir, dit-il. On a fait combien ? » Voilà — toute la nuit ramenée à un instant et un chiffre. Vous respirez et ouvrez la caisse. Tout ce que vous avez fait cette nuit est là-dedans.",
 111: "Vous comptez devant lui, pièce par pièce. Toute la nuit est là, dans l'argent — les bons bols, les choix durs, les coins gardés ou rognés. Le maître regarde, patient, sans un mot. Vous êtes près de la somme. Près. Mais « près » peut tomber des deux côtés à l'aube, et tout tient à ce dernier compte.",
 112: "Le compte s'arrête juste en deçà. De peu — mais court reste court, et le livre du maître n'arrondit pour personne. Le coin s'en va, pièce manquante après pièce manquante. À moins que — il reste peut-être une carte ou deux à jouer, si vous avez bien mené le reste de la nuit. Vous réfléchissez vite : qu'avez-vous que l'argent seul ne montre pas ?",
 113: "Vous en êtes au tout dernier recours. L'argent manque, le passeur a refusé, la marchande de thé est déjà au bout. Reste le plus petit, le plus discret — une gentillesse faite plus tôt, peut-être, qui revient. Ou rien du tout. Parfois une nuit ne tombe pas juste, malgré tout le travail. Vous attendez de voir quelle nuit ce sera.",
 114: "Il ne reste rien à opposer à la redevance. Pas assez d'argent, aucune faveur due, aucune gentillesse qui revienne. Juste vous, une boîte froide de pièces, et un chiffre que vous n'avez pu atteindre. Le maître attend votre réponse, sans méchanceté. Quoi qu'il arrive, vous y avez travaillé toute la nuit — et ça doit compter, même si ce n'est pas ce soir.",
}


def main():
    data = json.load(open(OUT, encoding="utf-8"))
    added = 0
    for nid, text in FR.items():
        k = str(nid)
        if k not in data:
            data[k] = text
            added += 1
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"{SLUG}/fr.json: {len(data)} passages total (+{added} added)")


if __name__ == "__main__":
    main()
