#!/usr/bin/env python3
"""Extend First Light's French gist to full per-passage coverage.
Merges into content/gist/first-light/fr.json, keeping existing entries and adding the rest.
French-first. Run: python3 scripts/build_gist_fr_full_ep03.py
"""
import json, os
SLUG = "first-light"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", SLUG, "fr.json")

FR = {
 2: "Vous trouvez une bougie et l'allumez de mains tremblantes, puis une torche, votre gros manteau, vos bottes. La petite flamme rend la pièce dorée et minuscule. Dehors, la rue est toute noire, et le froid s'infiltre déjà sous les portes. Il faut décider quoi faire, et vite.",
 3: "Vous essayez le téléphone. Le signal va et vient, puis un message passe enfin de la mairie : les routes sont bloquées par la neige, aucun secours avant l'aube, chacun doit rester au chaud chez soi. Mais Mme Ada ne peut pas se réchauffer — pas sans chauffage, pas par une nuit pareille.",
 4: "Vous sortez en courant, les mains vides, et le froid vous frappe comme un mur. Il coupe le souffle ; vos doigts font mal aussitôt. Vous vous arrêtez dans la rue noire et comprenez : on n'aide pas Ada les mains vides. Il faut des choses chaudes — et réfléchir avant de courir.",
 5: "Vous sortez. La rue est noire et parfaitement immobile, la neige sur tout, les maisons réduites à des formes sombres. À une fenêtre, une seule bougie brûle. Votre souffle fait de la buée ; le froid est féroce. Un chien aboie au loin. Et l'épicerie du coin, remarquez-vous, montre encore une petite lumière.",
 6: "Vous restez dans le froid et vous forcez à réfléchir. Aller d'abord à l'épicerie, pour un chauffage et des couvertures. Monter droit chez Ada en espérant. Ou frapper aux portes pour rassembler de l'aide. Chaque choix coûte du temps — et cette nuit, le temps, c'est du froid.",
 8: "Le froid s'installe dans vos os. Vous pensez à Ada, seule dans une maison sans chauffage, la poitrine serrée à chaque souffle. Une nuit pareille pourrait la tuer. Ce n'est pas une peur, c'est un fait. Personne d'autre ne montera cette colline cette nuit. Alors ce sera vous.",
 11: "Vous partez vers la colline avec ce que vous avez. C'est raide, la neige est profonde, et vos jambes brûlent vite. Le froid entre dans la poitrine, chaque souffle fait mal. Vous n'êtes pas sûr de porter quoi que ce soit d'utile. Mais vous continuez de grimper, car Ada est là-haut.",
 13: "Vous prenez le poêle à pétrole. Lourd et encombrant, mais c'est de la vraie chaleur — ce dont Ada a le plus besoin. Vous remerciez M. Okafor, qui hoche la tête : « Fais attention en le portant. Et méfie-toi de la glace. » Le poêle dans les bras, vous sentez pour la première fois que vous avez une chance.",
 14: "Vous prenez des bougies et des piles. Elles donneront de la lumière à Ada, et la lumière aide — mais la lumière n'est pas de la chaleur. Le froid entrera quand même, sa poitrine se serrera quand même. Vous avez choisi quelque chose, mais peut-être pas assez. Vous jetez un œil au poêle resté sur l'étagère.",
 15: "« Écoute, dit M. Okafor. Trois choses. » Il les compte : « Évite l'homme à la camionnette — il vend de la peur. Ne traverse pas la glace de la rivière ; elle paraît solide, elle ne l'est pas. Et prends la route, même si c'est plus long. » Les bons conseils sont rares cette nuit. Vous vous y accrochez.",
 16: "Vous allumez les bougies de Mme Pratt, l'enveloppez d'une couverture et lui montrez comment fermer les portes pour garder le peu de chaleur. Ses mains cessent de trembler. « Tu es quelqu'un de bien, dit-elle. Va — d'autres ont plus besoin de toi. » Vous promettez de revenir. Quelques minutes perdues, et bien employées.",
 17: "Vous dites à Mme Pratt que vous devez atteindre Ada, et que vous êtes désolé. Elle hoche la tête et referme sa porte. Partir vous pèse. Mais le besoin d'Ada est plus grand, et la nuit ne fait que se refroidir. Vous repartez, plus vite, dans le noir.",
 18: "Vous êtes près du pied de la colline, mais transi et mal préparé — mains vides et gourdes, rien de chaud à offrir à Ada. Devant, à travers la neige qui tombe, des phares brillent : une camionnette, une petite foule autour. On vend quelque chose.",
 19: "La rue commence à se réveiller. Des portes s'ouvrent ; des gens sortent avec bougies et torches. Quelqu'un a un réchaud de camping, quelqu'un une marmite de soupe, et un plan se forme presque tout seul. Soudain vous n'êtes plus seul dans le noir. Vous faites partie de quelque chose — et c'est chaud.",
 20: "Vous frappez, encore et encore, mais personne ne répond. Ils dorment peut-être ; ou ils ont trop froid et trop peur pour ouvrir. La rue reste noire et muette, et vous vous sentez très seul. Mais être seul ne change rien à ce qu'il faut à Ada. Vous irez seul.",
 21: "Maintenant, la route vers Ada. Deux chemins montent la colline : la longue route, solide sous la neige, ou la rivière gelée, qui couperait le trajet de moitié. Mais la glace peut mentir. En bas, près de l'eau, vous voyez aussi les phares de l'homme à la camionnette, et une foule autour.",
 22: "Vous décidez d'être prudent cette nuit : pas de raccourcis, pas de marchés dans le noir. Vous prendrez la longue route et ferez confiance aux gens que vous connaissez. Ce sera plus lent. Mais lent et sûr vaut mieux que rapide et imprudent, par la nuit la plus froide de l'année.",
 23: "Vous repartez, un peu réchauffé au-dedans par ce bon geste. C'est étrange : la nuit est tout aussi froide, mais vous vous sentez plus fort. Aider fait cela. Maintenant, pourtant, il faut repenser à Ada. La colline est toujours devant, et il fait toujours noir.",
 24: "La camionnette est garée dans la neige, phares aveuglants, un homme à côté qui hèle. Une foule de gens transis et effrayés se presse. Sur la camionnette : des chauffages, des générateurs, des bidons de carburant. « Ce soir seulement ! crie-t-il. En liquide ! » Tout le monde ici a peur, et il semble le savoir.",
 25: "Vous menez un petit groupe vers la colline, des bougies dansant dans le noir derrière vous — l'un portant le réchaud, l'autre la soupe. Vous vous sentez à la tête de quelque chose de bon. Puis vous la voyez : une lumière chaude là-haut, dans la vieille maison Harrow. Mais cette maison est vide depuis des années.",
 26: "Vous prenez la route. Elle est longue, serpentant dans le noir, mais le sol est ferme sous la neige, et cette nuit cela compte plus que la vitesse. Vos pas crissent, votre souffle fume. Toute la ville est silencieuse autour de vous, retenant son souffle glacé, attendant le retour de la lumière.",
 28: "Vous posez le pied sur la glace, et elle tient. Un pas, puis un autre. L'eau noire attend quelque part dessous. Chaque pas est un petit pari avec votre vie. L'autre rive n'est plus loin — mais la glace fait de petits bruits sous vos bottes, et ces bruits ne vous plaisent pas du tout.",
 29: "Vous cliquez la torche — rien. Les piles sont mortes. Il ne vous reste que la bougie, et une bougie ne survit pas au vent du dehors. Il vous faut plus de lumière avant d'aller loin. L'épicerie a peut-être des piles, ou vous pouvez vous débrouiller, prudemment, avec ce que vous avez.",
 30: "Vous grimpez la route dans le noir épais, et le froid durcit d'heure en heure, jusqu'à vous faire mal au visage. Devant, à une fenêtre noire, une famille grelotte, enveloppée de tous ses manteaux. Et la colline monte encore, toujours plus haut, vers Ada.",
 31: "Une voiture est coincée dans la neige, les roues patinant en vain. Un vieil homme est au volant, seul, le visage gris de froid. Il ne peut ni avancer ni reculer. Vous arrêter pour pousser, c'est perdre un temps précieux ; le laisser, c'est le laisser peut-être passer la nuit dans le froid.",
 33: "Vous continuez, vers la colline. Le noir est épais, et votre torche jette un seul petit cercle de lumière sur la neige. De côté, la camionnette de l'homme. Tout là-haut brûle cette lumière étrange dans la vieille maison. Et devant s'étend la dernière montée dure jusqu'à la porte d'Ada.",
 34: "Vous mettez l'épaule à la voiture et poussez. Vos bottes glissent ; puis, lentement, les roues accrochent et la voiture se dégage. Le vieil homme baisse sa vitre : « Que Dieu te bénisse, dit-il en vous pressant un thermos chaud dans les mains. File maintenant, et vite. »",
 35: "Vous promettez à la famille d'envoyer de l'aide, et vous le pensez. Mais une promesse n'est pas de la chaleur, et le bébé pleure encore quand vous refermez la porte. Vous en sentez le poids en repartant. On ne peut être qu'à un endroit à la fois, cette nuit entre toutes.",
 36: "Les voisins rassemblent tout dans une maison avec un poêle : une pièce chaude, pleine de bougies, de soupe et de gens. Des enfants dorment sur des manteaux empilés ; les vieux sont au plus près du feu. C'est bondé, bruyant et chaud. Pour la première fois cette nuit, le froid semble loin.",
 37: "Vous ressortez frapper à d'autres portes. Une à une, des bougies paraissent à d'autres fenêtres, et la rue noire devient lentement une rue éclairée. Les gens s'entraident maintenant, sans qu'on le demande. C'est vous qui avez lancé ça — et maintenant ça vous dépasse.",
 38: "Le froid vous travaille la tête autant que les os. Une petite voix dit : rentre, assieds-toi près d'une bougie, personne ne t'en voudra. Ce serait si facile. Puis vous pensez au visage d'Ada, et la voix se tait. Vous ne rentrerez pas cette nuit.",
 39: "Un panneau se dresse, à moitié enfoui dans la neige. Vous le dégagez pour le lire. Une flèche indique la route ; l'autre un sentier vers la colline, et la vieille maison Harrow, où cette lumière brûle toujours. Quel chemin, dans le noir ?",
 42: "Vous lui tournez le dos et vous éloignez. Derrière vous, la foule effrayée continue de lui fourrer de l'argent dans les mains. Vous en sentez l'attrait — la peur, l'espoir d'une réponse facile. Mais il n'y a pas de réponse facile cette nuit, seulement du travail dur et de braves gens. Vous continuez, votre argent toujours à vous.",
 43: "La peur l'emporte. Vous comptez l'argent — presque tout ce que vous avez — et le tendez. Il vous donne un générateur et un bidon de carburant, et un large sourire rapide. « Bon choix, l'ami. » L'argent n'est plus dans votre poche. Et, allez savoir, vous avez plus froid qu'avant.",
 44: "« Est-ce que ça marche ? demandez-vous. Par ce froid ? À coup sûr ? » Son sourire vacille, une seconde. « Ils marchent tous, dit-il, trop vite. Mais rien n'est garanti. Pas de remboursement. » Rien de garanti. Voilà votre réponse, si vous voulez l'entendre — une bonne chose n'a pas besoin de « rien de garanti ».",
 45: "Le générateur est lourd — un poids mort dans vos bras douloureux. Vous le hissez sur la colline, soufflant fort. En haut, vous le posez et tentez de le démarrer. Il tousse. Il crachote. Par ce froid, il ne prend tout simplement pas. Vous commencez à comprendre ce que vous avez vraiment acheté.",
 46: "Vous ouvrez le bidon et le sentez. C'est louche — mince et aqueux, plus d'eau que de carburant. Il vous a vendu un bidon de presque rien pour presque tout votre argent. Le doute en vous devient dur et froid. Vous avez été dupé, et la nuit n'est qu'à moitié passée.",
 47: "Vous tirez sur le cordon, encore et encore. Le générateur tousse, prend une seconde, puis meurt. Le carburant est mauvais, la machine bonne à rien. Vous avez payé presque tout pour un bloc de métal lourd et inutile dans la neige. Rien à faire que de l'abandonner et d'aller chez Ada les mains vides.",
 48: "Vous vous retournez pour trouver la camionnette, mais elle a disparu — les phares, l'homme, la foule, tout fondu dans le noir. Il ne reste que le froid, vos poches vides, et la chose inutile dans la neige. Il savait. Il a toujours su. Et il est ailleurs, maintenant, à vendre de la peur à un autre.",
 49: "Vous regardez la foule autour de la camionnette. Ce ne sont pas des sots — ils ont peur, pour leurs enfants, leurs parents, eux-mêmes. La peur fait faire des sottises aux gens bien. Vous voyez tout le tour de passe-passe, clair : l'homme vend de la peur, et par une nuit pareille, la peur se vend toute seule.",
 50: "Vous êtes à mi-chemin sur la glace, et l'autre rive est proche — vous pourriez presque la toucher. Encore quelques pas prudents. L'eau noire est juste sous vos pieds, mais vous essayez de ne pas y penser. Lentement, sûrement. Presque là. Presque—",
 51: "Un bruit comme un coup de feu déchire la nuit. La glace s'ouvre sous vos pieds. En une seconde glacée, tout pourrait mal tourner. Votre cœur s'arrête. Plus le temps de penser maintenant — seulement de bouger, à l'instant, dans un sens ou dans l'autre.",
 52: "Vous vous jetez sur l'autre rive et vous y accrochez. Sauf — mais trempé jusqu'aux genoux et tremblant fort, l'eau de la rivière gelant déjà sur vos jambes. Vous avez gagné du temps, oui. Mais vous voilà mouillé et transi, haut sur une colline froide, la nuit la plus froide de l'année.",
 53: "Vous vous rejetez en arrière d'où vous veniez, et la glace tient — de justesse. Vous rampez sur la rive, sauf mais tremblant, le cœur affolé. La rivière vous a presque eu. Vous avez perdu du temps, et votre sang-froid avec — mais vous êtes vivant, et vous avez appris une chose : la glace ment.",
 54: "Vous tentez de réchauffer la pièce de la famille — fermer les portes, boucher les fentes dessous avec des manteaux roulés. Ça aide un peu, mais loin d'assez. Sans chauffage, une pièce aussi froide ne se sauve pas vraiment. Le bébé pleure encore. Il ne reste vraiment qu'une seule chose à donner.",
 55: "Vous sortez la couverture d'Ada et en enveloppez bien le bébé. Les pleurs s'apaisent, puis cessent. La mère vous agrippe le bras, sans pouvoir parler. Vous ressortez dans le froid avec moins qu'en arrivant — mais le bébé est au chaud. Certaines choses qu'on donne nous rendent plus riches, pas plus pauvres.",
 56: "Sans la couverture, le froid vous trouve vite — au col, aux poignets, au creux du dos. Vous marchez plus vite pour vous réchauffer. Vous avez donné votre chaleur, et vous en payez le prix. Mais vous recommenceriez. Devant, une porte luit de lumière de bougie, chaude et ouverte.",
 57: "Une inconnue se tient dans la porte éclairée : « Tu as l'air à moitié gelé. Entre, juste une minute — réchauffe-toi les mains. » C'est si tentant : une minute au chaud. Mais Ada attend, et une minute a vite fait d'en devenir dix. Il faut choisir.",
 58: "Vous la remerciez, mais vous ne vous arrêtez pas. Vous avancez dans le noir, les dents claquant comme un tambour. Le froid est une main refermée sur votre poitrine, à présent. Mais chaque pas vous rapproche d'Ada, et cette pensée est son propre petit feu. Vous continuez.",
 60: "Une petite silhouette passe en courant dans le noir : un enfant, Bex, du bas de la rue. « Tu as vu mon frère ? demande Bex en pleurant. Il est sorti après le chat, et il n'est pas revenu. » Un petit enfant, perdu dans la neige, par une nuit pareille. Vous regardez la colline, puis Bex.",
 61: "Vous et Bex fouillez les jardins noirs en appelant son nom. Enfin, un petit bruit vient d'un abri. Dedans, transi et effrayé, se tient le petit frère de Bex, serrant le chat. Vous l'enveloppez de votre écharpe. Il est sauf, et Bex le serre et ne le lâche plus.",
 62: "Vous dites à Bex de courir chercher un adulte — c'est l'aide la plus rapide, et Ada attend. Bex file dans le noir. Vous espérez qu'on retrouvera vite le frère. Vous repartez, mais l'inquiétude vous suit, petit poids dans le froid.",
 63: "Vous raccompagnez les deux enfants. Leur mère ouvre la porte et pleure de soulagement. Elle vous tire à l'intérieur un instant et vous met une boisson chaude dans les mains, à la lueur d'une bougie. « Merci », répète-t-elle. Chaleur pour chaleur. Puis il faut repartir.",
 64: "Vous vous arrêtez un instant pour regarder la ville en contrebas. Tout est noir — ni réverbères, ni fenêtres éclairées, seulement çà et là le petit or d'une bougie. C'est étrange, et beau, et un peu effrayant : toute une ville retenant son souffle dans le froid, attendant l'aube.",
 65: "Le froid descend plus profond encore. Le givre se forme sur votre manteau, blanc sur la laine sombre ; vos pieds semblent loin et étrangers. C'est le genre de froid qui tue, lentement et sans bruit, si on le laisse faire. Vous ne pouvez pas vous arrêter. Vous ne pouvez pas le laisser gagner. Vous continuez.",
 67: "M. Okafor vous met son propre thermos de thé chaud dans les mains. « Le dernier, dit-il. Pour Ada. » Puis il commence à fermer, soufflant ses bougies une à une, rentrant dans sa propre maison froide. Vous sentez le thermos chaud à travers vos gants — un petit cadeau, un bon.",
 68: "À l'épicerie, une rumeur court dans la file : « Il n'y a plus de chauffages ! crie quelqu'un. C'est chacun pour soi ! » Les gens se poussent. La peur se répand plus vite que le froid. Vous pourriez intervenir pour les calmer, ou simplement entrer de force et prendre ce que vous pouvez.",
 70: "La vieille maison Harrow se dresse haut sur la colline. Vide depuis des années — noire, froide, oubliée de tous. Mais ce soir, une fenêtre luit d'une lumière chaude et régulière. Personne n'y habite. Personne ne devrait y être. Et pourtant la lumière brûle, dorée dans le noir, comme si quelqu'un était là.",
 71: "Vous frappez à la vieille porte. Pas de réponse. Vous frappez encore et appelez ; toujours rien. Mais quand vous poussez, la porte s'ouvre — jamais fermée à clé. Dedans, il fait froid et noir, et ça sent la poussière et les années. Mais quelque part plus loin, cette lumière chaude brûle encore.",
 72: "Vous entrez, suivant la lumière. Dans une pièce du fond, près d'une bougie presque consumée, un vieil homme est étendu par terre. Maigre, gris, dangereusement froid. Il est tombé il y a des heures et n'a pu se relever. Ses yeux trouvent les vôtres. « Tu es venu, murmure-t-il. Personne ne vient jamais. »",
 73: "Vous appelez dans la maison noire. Un long moment, rien. Puis, d'une pièce du fond, une voix faible répond — mince, cassée, effrayée. Quelqu'un est là. Quelqu'un a besoin d'aide. Vous ne pouvez pas partir, pas cette nuit, pas jamais.",
 74: "Vous enveloppez le vieil homme de votre manteau, ranimez le petit feu, tenez ses mains froides dans les vôtres. Lentement, très lentement, les couleurs lui reviennent au visage. Il boit un peu à votre thermos. « Merci », dit-il, les yeux pleins. Vous êtes arrivé à temps — de justesse, mais à temps.",
 75: "Vous vous retournez pour courir chercher de l'aide — puis vous vous figez. Il n'y a pas de secours en chemin. Les routes sont bloquées, les téléphones muets. C'est vous ou personne, pour cet homme aussi. Vous ne pouvez pas sauver tout le monde cette nuit. Mais vous ne pouvez pas le laisser geler par terre non plus.",
 76: "Réchauffé, le vieil homme parle. « Je m'appelle Harrow, dit-il. Je suis revenu il y a des mois. Je ne l'ai dit à personne. » Il regarde le feu. « Ada est ma sœur. On s'est disputés, autrefois — une bêtise. Quarante ans sans se parler. Quarante ans. Et elle est juste en bas de la colline. »",
 77: "Quarante ans, c'est long pour rester fâché. Et une nuit froide est un cadeau étrange et dur : elle se moque des vieilles querelles. Deux vieilles personnes — un frère et une sœur — seules dans le noir, transies, à quelques pas l'une de l'autre. Vous allez les réunir cette nuit. C'est décidé.",
 78: "Dedans, la maison est un musée du froid. La poussière couvre tout ; des chaises dorment sous des draps blancs comme des fantômes. C'est entrer dans une horloge arrêtée. Mais la lumière chaude vous attire, pièce après pièce, plus profond. Quelqu'un a fait cette lumière. Quelqu'un est là.",
 79: "Au mur pend une vieille photo : deux jeunes gens, un garçon et une fille, riant ensemble dans la lumière d'été. Vous regardez de plus près — la fille, c'est Ada, jeune, mais c'est bien elle. Puis, de la pièce voisine, vient un petit bruit : une respiration lente et faible.",
 80: "L'homme à la camionnette a suivi la peur jusqu'en haut de la colline. « Toujours froid là-haut ? dit-il en souriant. Dernière chance, l'ami — un petit chauffage, et elle est au chaud au matin. » Il est à la porte même d'Ada, vous vendant par-dessus son toit glacé. C'est votre dernière chance de le refuser pour de bon.",
 90: "La dernière montée jusqu'à la porte d'Ada. Vos jambes sont de plomb, votre poitrine brûle de froid. Mais sa maison est là, sombre et silencieuse au sommet. Vous y êtes arrivé. Quoi que vous portiez, quoi que vous ayez fait en chemin, c'est le moment pour lequel tout cela comptait.",
 91: "Dedans, la maison d'Ada est noire et terriblement froide. Elle est couchée sous de minces couvertures, toute petite dans le grand lit, le souffle court et rapide. « C'est toi ? murmure-t-elle. Je savais que quelqu'un viendrait. » Vous l'avez trouvée à temps — de justesse. Tout dépend maintenant de ce que vous ferez.",
 92: "Derrière vous sur la colline montent des lumières et des voix. Les voisins que vous avez rassemblés arrivent enfin — portant le réchaud, la soupe, les couvertures, la chaleur de mains nombreuses. Vous n'êtes pas seul là-haut, finalement. Ensemble, vous vous entassez chez Ada et commencez à la remplir de vie.",
 93: "Maintenant, la chaleur — et ce que vous pouvez faire dépend de ce que vous avez monté. Si vous avez le poêle à pétrole, vous avez de la vraie chaleur, régulière. Sinon, vous avez des bougies, des couvertures, et la chaleur de votre propre corps. Le moment est venu de tout employer, et de bien l'employer.",
 94: "Vous vous agenouillez près du lit. Les yeux d'Ada s'ouvrent, et elle vous reconnaît. « Regarde-toi, dit-elle d'une voix mince. Dehors par un temps pareil, pour une vieille femme. » Elle sourit, à peine. Faible et transie, mais là, éveillée, et heureuse de vous. Maintenant, il faut la réchauffer, et vite.",
 95: "Vous posez le poêle à pétrole au milieu de la pièce et l'allumez. Il prend dans un doux ronflement, et un cercle de vraie chaleur se répand. Ada tend ses mains maigres vers la lueur. « Oh, dit-elle doucement. Oh, que c'est bon. » La petite pièce commence enfin à dégeler.",
 96: "Vous n'avez pas de poêle. Alors vous employez tout le reste. Vous entassez sur le lit toutes les couvertures de la maison. Vous allumez des bougies pour leur petite chaleur, vous asseyez près d'elle, la gardez éveillée et parlante, partagez votre propre chaleur. Ce n'est pas grand-chose. Mais parfois peu, donné pleinement, suffit.",
 97: "Vous faites tout ce que vous pouvez, mais le froid est profond et Ada est vieille et faible. Couvertures et chaleur du corps ne suffiront peut-être pas à retenir une nuit pareille. Il faut plus — plus de chaleur, plus de mains, plus d'aide. Et en bas, si vous les avez rassemblés plus tôt, des gens pourraient encore venir.",
 98: "De la fenêtre d'Ada, vous voyez la colline noire. Et la revoilà : l'unique lumière chaude, brûlant dans la vieille maison Harrow, où personne ne devrait être. Ada suit votre regard. « Cette maison, dit-elle lentement. Cette maison est éteinte depuis des années. » Mais elle ne l'est pas, cette nuit.",
 99: "La lumière sur la colline ne quitte pas votre esprit. Une lumière chaude, dans une maison qui devrait être froide et vide. Ce n'est peut-être rien. C'est peut-être quelqu'un. Par une nuit pareille, une lumière là où personne ne devrait être est une question qu'on ne peut tout à fait ignorer. Mais Ada a besoin de vous, ici, maintenant.",
 100: "Vient maintenant la longue veille jusqu'à l'aube. Vous gardez la chaleur dedans et le froid dehors. Vous surveillez le souffle d'Ada, entretenez le feu ou les bougies, lui parlez doucement à travers les petites heures. Heure après heure, vous tenez la nuit loin de sa porte — et vous attendez la lumière.",
 101: "Lentement, le ciel passe du noir au gris. L'aube. Et avec elle, loin en bas, des phares — les équipes enfin, remontant péniblement la neige. Quelque part, dans un bourdonnement sourd, le courant revient ; une lampe s'allume dans un coin. La longue nuit est finie, et vous l'avez tenue.",
 102: "C'est l'heure la plus longue — juste avant que le noir ne s'éclaircisse. Le froid est au plus dur. Ada dort, se réveille, se rendort. Vous luttez vous-même pour rester éveillé. Vous êtes venu de si loin, vous avez tenu si longtemps ; vous ne pouvez pas lâcher maintenant, la lumière si proche.",
 103: "Vous regardez la ville du haut de la fenêtre. Tout en bas, de petits feux et des bougies brûlent à fenêtre après fenêtre. La ville ne s'est pas assise seule dans le noir ; elle s'est tenue chaud, maison aidant maison, toute la nuit. C'est beau à voir. La ville s'en est sortie.",
 104: "Enfin, phares et camions de sel remontent péniblement vers vous. Les secours sont là — des hommes en vestes vives descendent, portant lampes et matériel chaud. La longue attente est finie. Quoi que la nuit ait donné, ici, dans cette pièce froide, tout se règle presque, d'une façon ou d'une autre.",
 105: "L'aube s'étale sur la ville gelée, pâle, nette et calme. La neige passe du gris au blanc doux puis à l'or sur les bords. Après la longue nuit noire, la lumière est un cadeau qu'on avait presque oublié d'attendre. Vous êtes à la fenêtre et regardez le monde revenir lentement.",
 106: "Quelque part, dans le blanc froid, un seul oiseau se met à chanter. Cela paraît absurde, et brave, et beau, par-dessus toute cette glace. Le matin vient ; la vie revient. Vous l'écoutez, épuisé jusqu'aux os, et quelque chose se soulève dans votre poitrine. Vous avez réussi — tous les deux, jusqu'à la lumière.",
 107: "De la fenêtre d'Ada, vous voyez les feux des voisins brûler tout le long de la colline — chaque fenêtre une petite lumière chaude. Toute la rue est restée éveillée ensemble, s'est tenu chaud, a refusé de laisser le noir gagner. C'est vous qui l'avez lancé, tout en bas, il y a des heures et toute une vie.",
 110: "Enfin la première lumière. Les équipes remontent la colline, le courant revient en bourdonnant, et la longue nuit est enfin finie. Maintenant, dans le gris mince du matin, vous pouvez voir ce que tout cela a donné. Chaque choix fait dans le noir, s'additionnant enfin en ceci.",
 111: "La nuit s'additionne, choix après choix, en ce qu'elle a vraiment été. Tout ce que vous avez fait dehors dans le froid, et tout ce que vous avez choisi de ne pas faire, vous revient ici, dans la lumière grise du matin. Vous respirez lentement, et vous le pesez.",
 112: "Il y a plus encore à peser dans ce qu'a tenu la nuit. Tout ne se ramène pas à une victoire nette ou à une perte claire ; une part en est plus petite, plus discrète, facile à manquer. Mais elle vaut tout de même d'être comptée, dans la lumière froide du matin.",
 113: "Et puis il y a ce que la nuit vous laisse, simplement, quand le gagner et le perdre sont tous deux finis. Ni un prix, ni une punition. Juste la vérité nue de la façon dont tout s'est passé, et de qui vous vous êtes révélé être quand les lumières se sont éteintes.",
 114: "Et puis il y a la dure fin de la nuit, si c'est ainsi qu'elle a tourné pour vous. Toutes les nuits ne se sauvent pas, quelque effort qu'on y mette. Parfois le froid, ou le noir, ou un seul mauvais tournant est simplement plus fort que vous. C'est là que ces nuits finissent.",
}


def main():
    data = json.load(open(OUT, encoding="utf-8"))
    added = 0
    for nid, text in FR.items():
        k = str(nid)
        if k not in data:
            data[k] = text; added += 1
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"{SLUG}/fr.json: {len(data)} passages total (+{added} added)")


if __name__ == "__main__":
    main()
