#!/usr/bin/env python3
"""Phase 4: build book 2's embedded lexicon.

Two sources, per the playbook:
  1. Words shared with book 1 reuse book 1's exact reviewed-draft glosses, so a word
     a learner already met reads identically across the series (one exception: `reference`,
     which book 1 glosses as a lookup-number — book 2 needs the "someone who vouches" sense,
     so it is redefined here).
  2. New subject words (renting, deposits, the canal room, the day) get fresh draft glosses
     in English + 8 languages. Machine-drafted; the native-language review (phase 5, the
     launch gate) is what finalises them.

Writes the merged lexicon into content/episode-02.json's `lexicon.entries`.
Run: python3 scripts/build_ep02_lexicon.py
"""
import json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
EP1 = os.path.join(ROOT, "content", "episode-01.json")
EP2 = os.path.join(ROOT, "content", "episode-02.json")

# Words shared with book 1 — reuse its glosses verbatim (minus `reference`, redefined below).
REUSE = [
    "actual", "afford", "agency", "anyway", "behalf", "bench", "breath", "ceremony",
    "colleague", "considerable", "daylight", "decent", "entire", "evidence", "fair",
    "feet", "furniture", "further", "genuine", "glad", "glance", "heavy", "hoarding",
    "hollow", "intact", "kettle", "kiosk", "lobby", "neither", "nerve", "nod", "ought",
    "pavement", "photograph", "pity", "proper", "queue", "radiator", "rather", "realise",
    "receipt", "refuse", "scrap", "screen", "somehow", "stack", "stall", "suspect",
    "tiny", "truth", "unkind", "warmth", "wave", "whoever", "within",
]

def e(pos, en, fr, es, pt, it, de, ru, ar, zh):
    return {"pos": pos, "en": en, "fr": fr, "es": es, "pt": pt, "it": it,
            "de": de, "ru": ru, "ar": ar, "zh": zh}

# New draft entries (subject vocabulary for The Room).
NEW = {
 # --- renting: the machinery ---
 "reference": e("noun", "a person who says you are honest and reliable, so someone will trust you",
   "la référence", "la referencia", "a referência", "la referenza", "die Referenz",
   "рекомендатель", "معرّف", "推荐人"),
 "deposit": e("noun", "money you pay first and get back later, to hold a room",
   "la caution", "el depósito", "o depósito", "la caparra", "die Kaution",
   "залог", "عربون", "押金"),
 "guarantor": e("noun", "a person who promises to pay your rent if you cannot",
   "le garant", "el garante", "o fiador", "il garante", "der Bürge",
   "поручитель", "ضامن", "担保人"),
 "landlord": e("noun", "a man who owns a room or flat and rents it to you",
   "le propriétaire", "el casero", "o senhorio", "il padrone di casa", "der Vermieter",
   "домовладелец", "صاحب البيت", "房东"),
 "landlady": e("noun", "a woman who owns a room or flat and rents it to you",
   "la propriétaire", "la casera", "a senhoria", "la padrona di casa", "die Vermieterin",
   "домовладелица", "صاحبة البيت", "女房东"),
 "tenant": e("noun", "a person who pays to live in someone else's room or flat",
   "le locataire", "el inquilino", "o inquilino", "l'inquilino", "der Mieter",
   "жилец", "مستأجر", "租客"),
 "rent": e("noun", "the money you pay each week or month to live somewhere",
   "le loyer", "el alquiler", "a renda", "l'affitto", "die Miete",
   "аренда", "إيجار", "房租"),
 "lease": e("noun", "a written agreement that lets you rent a place for a time",
   "le bail", "el contrato de alquiler", "o contrato de arrendamento", "il contratto d'affitto",
   "der Mietvertrag", "договор аренды", "عقد إيجار", "租约"),
 "letting": e("noun", "the business of renting rooms and flats to people",
   "la location", "el alquiler", "o arrendamento", "l'affitto", "die Vermietung",
   "сдача жилья", "تأجير", "出租"),
 "agent": e("noun", "a person whose job is to rent or sell places for other people",
   "l'agent", "el agente", "o agente", "l'agente", "der Makler",
   "агент", "وكيل", "中介"),
 "advert": e("noun", "a notice that tells people something is for sale or for rent",
   "l'annonce", "el anuncio", "o anúncio", "l'annuncio", "die Anzeige",
   "объявление", "إعلان", "广告"),
 "listing": e("noun", "a room or flat shown on a list of places to rent",
   "l'annonce immobilière", "el anuncio inmobiliario", "o anúncio imobiliário",
   "l'annuncio immobiliare", "das Wohnungsangebot", "объявление о жилье",
   "إعلان سكن", "房源"),
 "viewing": e("noun", "a time when you go to look at a room before you rent it",
   "la visite", "la visita", "a visita", "la visita", "die Besichtigung",
   "просмотр", "معاينة", "看房"),
 "bedsit": e("noun", "one small cheap room to live in, with a shared bathroom",
   "le studio", "la habitación individual", "o quarto individual", "il monolocale",
   "das möblierte Zimmer", "однокомнатная каморка", "غرفة صغيرة", "单间"),
 "afford": None,  # placeholder overwritten below (kept from book1 via REUSE)

 # --- the canal building & the room ---
 "canal": e("noun", "a long narrow path of water made for boats",
   "le canal", "el canal", "o canal", "il canale", "der Kanal",
   "канал", "قناة", "运河"),
 "quay": e("noun", "a hard edge by water where boats stop",
   "le quai", "el muelle", "o cais", "la banchina", "der Kai",
   "набережная", "رصيف", "码头"),
 "stairwell": e("noun", "the open space that the stairs go up through in a building",
   "la cage d'escalier", "el hueco de la escalera", "a caixa de escada", "la tromba delle scale",
   "das Treppenhaus", "лестничный пролёт", "بيت الدرج", "楼梯间"),
 "sill": e("noun", "the flat shelf at the bottom of a window",
   "le rebord de fenêtre", "el alféizar", "o parapeito", "il davanzale", "die Fensterbank",
   "подоконник", "عتبة النافذة", "窗台"),
 "hook": e("noun", "a bent piece of metal on a wall for hanging things on",
   "le crochet", "el gancho", "o gancho", "il gancio", "der Haken",
   "крючок", "خطاف", "挂钩"),
 "coat": e("noun", "a long warm piece of clothing you wear outside",
   "le manteau", "el abrigo", "o casaco", "il cappotto", "der Mantel",
   "пальто", "معطف", "外套"),
 "notebook": e("noun", "a small book of empty pages for writing notes in",
   "le carnet", "el cuaderno", "o caderno", "il taccuino", "das Notizbuch",
   "блокнот", "دفتر", "笔记本"),
 "button": e("noun", "a small round thing that holds clothes closed",
   "le bouton", "el botón", "o botão", "il bottone", "der Knopf",
   "пуговица", "زر", "纽扣"),
 "tin": e("noun", "a small metal box with a lid for keeping things in",
   "la boîte en métal", "la lata", "a lata", "il barattolo", "die Dose",
   "жестянка", "علبة", "铁盒"),
 "rope": e("noun", "thick strong cord made of twisted threads",
   "la corde", "la cuerda", "a corda", "la corda", "das Seil",
   "верёвка", "حبل", "绳子"),
 "damp": e("adjective", "a little wet, in a cold unpleasant way",
   "humide", "húmedo", "húmido", "umido", "feucht",
   "сырой", "رطب", "潮湿的"),
 "bathroom": e("noun", "the room with a toilet and a place to wash",
   "la salle de bain", "el baño", "a casa de banho", "il bagno", "das Badezimmer",
   "ванная", "حمام", "浴室"),
 "doorway": e("noun", "the open space where a door is",
   "l'embrasure de la porte", "el umbral", "o vão da porta", "la soglia", "die Türöffnung",
   "дверной проём", "مدخل الباب", "门口"),
 "lane": e("noun", "a narrow road or path between buildings",
   "la ruelle", "el callejón", "a viela", "il vicolo", "die Gasse",
   "переулок", "زقاق", "小巷"),

 # --- money & the day ---
 "cash": e("noun", "money in coins and notes, not a card",
   "l'argent liquide", "el efectivo", "o dinheiro", "i contanti", "das Bargeld",
   "наличные", "نقد", "现金"),
 "fare": e("noun", "the money you pay to travel on a bus or train",
   "le prix du billet", "el pasaje", "a tarifa", "il biglietto", "der Fahrpreis",
   "плата за проезд", "أجرة", "车费"),
 "wage": e("noun", "the money you are paid for the work you do",
   "le salaire", "el salario", "o salário", "il salario", "der Lohn",
   "зарплата", "أجر", "工资"),
 "purse": e("noun", "a small bag for keeping money in",
   "le porte-monnaie", "el monedero", "a carteira", "il portamonete", "der Geldbeutel",
   "кошелёк", "محفظة", "钱包"),
 "penny": e("noun", "a coin of very little money; the smallest amount",
   "le centime", "el centavo", "o cêntimo", "il centesimo", "der Cent",
   "грош", "قرش", "一分钱"),
 "coin": e("noun", "a small round piece of metal money",
   "la pièce", "la moneda", "a moeda", "la moneta", "die Münze",
   "монета", "عملة معدنية", "硬币"),
 "midday": e("noun", "twelve o'clock in the middle of the day",
   "midi", "el mediodía", "o meio-dia", "mezzogiorno", "der Mittag",
   "полдень", "منتصف النهار", "正午"),
 "dusk": e("noun", "the time when the light goes and night begins",
   "le crépuscule", "el anochecer", "o anoitecer", "il crepuscolo", "die Dämmerung",
   "сумерки", "الغسق", "黄昏"),
 "nightfall": e("noun", "the moment when it becomes dark",
   "la tombée de la nuit", "el anochecer", "o cair da noite", "il calar della notte",
   "der Einbruch der Nacht", "наступление ночи", "حلول الليل", "夜幕降临"),
 "deadline": e("noun", "the latest time by which something must be done",
   "l'échéance", "la fecha límite", "o prazo", "la scadenza", "die Frist",
   "крайний срок", "الموعد النهائي", "截止时间"),

 # --- the street & people ---
 "trolley": e("noun", "a small cart on wheels for carrying things",
   "le chariot", "el carrito", "o carrinho", "il carrello", "der Handwagen",
   "тележка", "عربة", "手推车"),
 "crate": e("noun", "a strong open box for carrying goods",
   "la caisse", "la caja", "o caixote", "la cassa", "die Kiste",
   "ящик", "صندوق", "板条箱"),
 "shutter": e("noun", "a cover that pulls down over a shop window or front",
   "le volet", "la persiana", "a portada", "la serranda", "der Rollladen",
   "ставень", "مصراع", "卷帘"),
 "delivery": e("noun", "the job of taking goods to the place they are sent to",
   "la livraison", "el reparto", "a entrega", "la consegna", "die Lieferung",
   "доставка", "توصيل", "送货"),
 "cousin": e("noun", "the child of your aunt or uncle",
   "le cousin", "el primo", "o primo", "il cugino", "der Cousin",
   "двоюродный брат", "ابن العم", "表亲"),
 "employer": e("noun", "the person or company that pays you to work",
   "l'employeur", "el empleador", "o empregador", "il datore di lavoro", "der Arbeitgeber",
   "работодатель", "صاحب العمل", "雇主"),
 "resident": e("noun", "a person who lives in a place, not a visitor",
   "le résident", "el residente", "o residente", "il residente", "der Bewohner",
   "житель", "مقيم", "居民"),
 "stranger": e("noun", "a person you do not know",
   "l'inconnu", "el desconocido", "o desconhecido", "lo sconosciuto", "der Fremde",
   "незнакомец", "غريب", "陌生人"),
 "knee": e("noun", "the joint in the middle of your leg where it bends",
   "le genou", "la rodilla", "o joelho", "il ginocchio", "das Knie",
   "колено", "ركبة", "膝盖"),
 "eyebrow": e("noun", "the line of hair above your eye",
   "le sourcil", "la ceja", "a sobrancelha", "il sopracciglio", "die Augenbraue",
   "бровь", "حاجب", "眉毛"),
 "chest": e("noun", "the front part of your body between your neck and stomach",
   "la poitrine", "el pecho", "o peito", "il petto", "die Brust",
   "грудь", "صدر", "胸口"),

 # --- trust, feeling, the scam ---
 "trap": e("noun", "a clever trick made to catch or cheat someone",
   "le piège", "la trampa", "a armadilha", "la trappola", "die Falle",
   "ловушка", "فخ", "陷阱"),
 "trick": e("noun", "a clever act meant to fool someone",
   "le tour", "el truco", "o truque", "il trucco", "der Trick",
   "уловка", "خدعة", "把戏"),
 "pitch": e("noun", "a talk made to sell you something",
   "le baratin", "el discurso de venta", "o discurso de venda", "il discorso di vendita",
   "die Verkaufsmasche", "зазывная речь", "خطاب بيع", "推销话术"),
 "doubt": e("noun", "a feeling that something may not be true or right",
   "le doute", "la duda", "a dúvida", "il dubbio", "der Zweifel",
   "сомнение", "شك", "怀疑"),
 "threat": e("noun", "a warning that something bad will happen to you",
   "la menace", "la amenaza", "a ameaça", "la minaccia", "die Drohung",
   "угроза", "تهديد", "威胁"),
 "guilt": e("noun", "the bad feeling that you have done something wrong",
   "la culpabilité", "la culpa", "a culpa", "la colpa", "das Schuldgefühl",
   "чувство вины", "شعور بالذنب", "内疚"),
 "favour": e("noun", "a kind act you do for someone to help them",
   "le service", "el favor", "o favor", "il favore", "der Gefallen",
   "одолжение", "معروف", "帮忙"),
 "handshake": e("noun", "the act of holding and shaking someone's hand",
   "la poignée de main", "el apretón de manos", "o aperto de mão", "la stretta di mano",
   "der Händedruck", "рукопожатие", "مصافحة", "握手"),
 "welcome": e("noun", "a warm friendly greeting when you arrive",
   "l'accueil", "la bienvenida", "as boas-vindas", "l'accoglienza", "der Empfang",
   "приём", "ترحيب", "欢迎"),
 "counsel": e("noun", "careful private thought or advice you keep to yourself",
   "le conseil", "el consejo", "o conselho", "il consiglio", "der Rat",
   "суждение", "رأي", "主见"),
 "knowledge": e("noun", "the things you know",
   "la connaissance", "el conocimiento", "o conhecimento", "la conoscenza", "das Wissen",
   "знание", "معرفة", "知识"),
 "comfort": e("noun", "a feeling of being calmer and less worried",
   "le réconfort", "el consuelo", "o conforto", "il conforto", "der Trost",
   "утешение", "عزاء", "安慰"),
 "satisfaction": e("noun", "the good feeling of getting something you wanted",
   "la satisfaction", "la satisfacción", "a satisfação", "la soddisfazione", "die Zufriedenheit",
   "удовлетворение", "رضا", "满足"),
 "loss": e("noun", "the fact of no longer having something you had",
   "la perte", "la pérdida", "a perda", "la perdita", "der Verlust",
   "потеря", "خسارة", "损失"),

 # --- verbs ---
 "vouch": e("verb", "to say that someone is honest and can be trusted",
   "se porter garant", "responder por", "responder por", "garantire per", "sich verbürgen",
   "поручиться", "يكفل", "担保"),
 "afford ": None,
 "weigh": e("verb", "to think carefully about something before you decide",
   "peser", "sopesar", "ponderar", "soppesare", "abwägen",
   "взвешивать", "يزن", "权衡"),
 "hesitate": e("verb", "to wait a moment because you are not sure",
   "hésiter", "dudar", "hesitar", "esitare", "zögern",
   "колебаться", "يتردد", "犹豫"),
 "mutter": e("verb", "to say something quietly and not clearly",
   "marmonner", "murmurar", "resmungar", "borbottare", "murmeln",
   "бормотать", "يتمتم", "咕哝"),
 "struggle": e("verb", "to try hard to do something difficult",
   "avoir du mal", "batallar", "esforçar-se", "faticare", "sich abmühen",
   "с трудом справляться", "يكافح", "挣扎"),
 "wrestle": e("verb", "to fight to control or carry something heavy",
   "se débattre avec", "forcejear con", "lutar com", "lottare con", "ringen mit",
   "бороться с", "يصارع", "费力搬"),
 "cheat": e("verb", "to trick someone to take their money unfairly",
   "escroquer", "estafar", "enganar", "truffare", "betrügen",
   "обманывать", "يحتال", "欺骗"),
 "earn": e("verb", "to get something by working or deserving it",
   "gagner", "ganarse", "ganhar", "guadagnare", "verdienen",
   "заслужить", "يكسب", "赚得"),
 "soften": e("verb", "to become gentler or kinder",
   "s'adoucir", "ablandarse", "abrandar", "addolcirsi", "weicher werden",
   "смягчаться", "يلين", "变温和"),
 "stiffen": e("verb", "to become suddenly tense and still",
   "se raidir", "ponerse tenso", "enrijecer", "irrigidirsi", "erstarren",
   "напрягаться", "يتيبس", "僵住"),
 "straighten": e("verb", "to make something neat and not crooked",
   "redresser", "enderezar", "endireitar", "raddrizzare", "geraderücken",
   "поправлять", "يعدّل", "弄直"),
 "trudge": e("verb", "to walk slowly with heavy tired steps",
   "marcher péniblement", "caminar con esfuerzo", "arrastar-se", "arrancarsi", "sich schleppen",
   "тащиться", "يجرّ قدميه", "沉重地走"),
 "scroll": e("verb", "to move text or pictures up and down on a screen",
   "faire défiler", "desplazar", "rolar", "scorrere", "scrollen",
   "прокручивать", "يتصفح", "滑动浏览"),
 "admire": e("verb", "to look at something with pleasure and respect",
   "admirer", "admirar", "admirar", "ammirare", "bewundern",
   "любоваться", "يعجب بـ", "欣赏"),
 "grasp": e("verb", "to understand something fully",
   "saisir", "captar", "compreender", "afferrare", "begreifen",
   "осознавать", "يدرك", "领会"),
 "mention": e("verb", "to say something briefly, in passing",
   "mentionner", "mencionar", "mencionar", "menzionare", "erwähnen",
   "упоминать", "يذكر", "提到"),
 "greet": e("verb", "to say hello to someone when they arrive",
   "accueillir", "saludar", "cumprimentar", "salutare", "begrüßen",
   "приветствовать", "يحيّي", "迎接"),
 "jingle": e("verb", "to make a light ringing sound, like keys",
   "faire tinter", "tintinear", "tilintar", "tintinnare", "klimpern",
   "звенеть", "يرنّ", "叮当作响"),
 "rattle": e("verb", "to move with a lot of short hard sounds",
   "faire du bruit", "traquetear", "chocalhar", "sferragliare", "rattern",
   "громыхать", "يقعقع", "咔嗒作响"),
 "shine": e("verb", "to give out bright light",
   "briller", "brillar", "brilhar", "brillare", "leuchten",
   "сиять", "يلمع", "闪耀"),
 "cling": e("verb", "to hold on tightly to someone or something",
   "s'accrocher", "aferrarse", "agarrar-se", "aggrapparsi", "sich klammern",
   "цепляться", "يتشبث", "紧抓"),
 "swallow": e("verb", "to take in and make disappear",
   "engloutir", "tragar", "engolir", "inghiottire", "verschlucken",
   "поглощать", "يبتلع", "吞没"),
 "owe": e("verb", "to have to pay money back to someone",
   "devoir", "deber", "dever", "dovere", "schulden",
   "быть должным", "يدين", "欠"),
 "unlock": e("verb", "to open something that was locked",
   "déverrouiller", "abrir con llave", "destrancar", "sbloccare", "aufschließen",
   "отпирать", "يفتح", "解锁"),
 "sweep": e("verb", "to clean a floor with a brush",
   "balayer", "barrer", "varrer", "spazzare", "fegen",
   "подметать", "يكنس", "打扫"),
 "frighten": e("verb", "to make someone feel afraid",
   "effrayer", "asustar", "assustar", "spaventare", "erschrecken",
   "пугать", "يخيف", "使害怕"),
 "distrust": e("verb", "to not trust someone or something",
   "se méfier de", "desconfiar de", "desconfiar de", "diffidare di", "misstrauen",
   "не доверять", "لا يثق بـ", "不信任"),
 "chase": e("verb", "to hurry after something to catch it",
   "courir après", "perseguir", "perseguir", "rincorrere", "nachjagen",
   "гнаться", "يطارد", "追赶"),
 "commit": e("verb", "to promise firmly to do something",
   "s'engager", "comprometerse", "comprometer-se", "impegnarsi", "sich festlegen",
   "обязываться", "يلتزم", "许诺"),
 "sign": e("noun", "a board with words that gives information or advertises something",
   "l'enseigne", "el letrero", "a placa", "l'insegna", "das Schild",
   "вывеска", "لافتة", "招牌"),

 # --- adjectives ---
 "grim": e("adjective", "gloomy, hard and not pleasant",
   "sinistre", "lúgubre", "sombrio", "tetro", "trostlos",
   "мрачный", "كئيب", "阴森的"),
 "steep": e("adjective", "rising or falling sharply; (of a price) very high",
   "raide", "empinado", "íngreme", "ripido", "steil",
   "крутой", "شديد الانحدار", "陡的"),
 "glossy": e("adjective", "smooth and shiny, and made to look expensive",
   "sur papier glacé", "brillante", "brilhante", "patinato", "hochglänzend",
   "глянцевый", "لامع", "光鲜的"),
 "brisk": e("adjective", "quick and businesslike, with no time to waste",
   "vif", "enérgico", "enérgico", "spiccio", "forsch",
   "деловитый", "سريع حازم", "干练的"),
 "wary": e("adjective", "careful because you think something may be wrong",
   "méfiant", "receloso", "cauteloso", "diffidente", "misstrauisch",
   "настороженный", "حذر", "警惕的"),
 "bare": e("adjective", "empty, with nothing on or in it",
   "nu", "desnudo", "nu", "spoglio", "kahl",
   "голый", "خالٍ", "空荡的"),
 "breathless": e("adjective", "unable to breathe easily, after effort",
   "essoufflé", "sin aliento", "sem fôlego", "senza fiato", "atemlos",
   "запыхавшийся", "لاهث", "上气不接下气的"),
 "hopeful": e("adjective", "feeling that good things may happen",
   "plein d'espoir", "esperanzado", "esperançoso", "speranzoso", "hoffnungsvoll",
   "полный надежды", "متفائل", "满怀希望的"),
 "patient": e("adjective", "able to wait calmly without getting cross",
   "patient", "paciente", "paciente", "paziente", "geduldig",
   "терпеливый", "صبور", "耐心的"),
 "solemn": e("adjective", "very serious and quiet",
   "solennel", "solemne", "solene", "solenne", "ernst",
   "серьёзный", "جاد", "严肃的"),
 "sore": e("adjective", "painful, especially from being used too much",
   "endolori", "dolorido", "dolorido", "dolorante", "wund",
   "ноющий", "مؤلم", "酸痛的"),
 "blank": e("adjective", "empty, with nothing written or shown on it",
   "vierge", "en blanco", "em branco", "vuoto", "leer",
   "пустой", "فارغ", "空白的"),
 "modest": e("adjective", "small and plain, not grand",
   "modeste", "modesto", "modesto", "modesto", "bescheiden",
   "скромный", "متواضع", "简朴的"),
 "weary": e("adjective", "very tired",
   "las", "fatigado", "cansado", "stanco", "müde",
   "утомлённый", "منهك", "疲惫的"),
 "suspicious": e("adjective", "making you feel that something is wrong",
   "suspect", "sospechoso", "suspeito", "sospetto", "verdächtig",
   "подозрительный", "مريب", "可疑的"),
 "generous": e("adjective", "glad to give more than is needed",
   "généreux", "generoso", "generoso", "generoso", "großzügig",
   "щедрый", "كريم", "慷慨的"),
 "plain": e("adjective", "simple and clear, with nothing added",
   "simple", "sencillo", "simples", "semplice", "schlicht",
   "простой", "بسيط", "朴素的"),
 "flashy": e("adjective", "bright and showy in a way you should not trust",
   "tape-à-l'œil", "ostentoso", "espalhafatoso", "vistoso", "protzig",
   "кричащий", "براق", "浮华的"),
 "unfair": e("adjective", "not right or equal; treating someone badly",
   "injuste", "injusto", "injusto", "ingiusto", "ungerecht",
   "несправедливый", "غير عادل", "不公平的"),
 "tight": e("adjective", "held firmly and closely",
   "serré", "apretado", "apertado", "stretto", "fest",
   "тугой", "محكم", "紧的"),
 "cold": e("adjective", "having a low temperature; not warm",
   "froid", "frío", "frio", "freddo", "kalt",
   "холодный", "بارد", "冷的"),

 # --- adverbs & useful function words ---
 "gently": e("adverb", "in a soft, careful, kind way",
   "doucement", "suavemente", "suavemente", "delicatamente", "sanft",
   "мягко", "بلطف", "轻轻地"),
 "firmly": e("adverb", "in a strong, sure way that will not change",
   "fermement", "firmemente", "firmemente", "fermamente", "bestimmt",
   "твёрдо", "بحزم", "坚定地"),
 "barely": e("adverb", "almost not; only just",
   "à peine", "apenas", "mal", "a malapena", "kaum",
   "едва", "بالكاد", "几乎不"),
 "outright": e("adverb", "openly and directly, all at once",
   "franchement", "sin rodeos", "sem rodeios", "apertamente", "geradeheraus",
   "напрямик", "صراحةً", "直截了当地"),
 "aloud": e("adverb", "in a voice that can be heard, not silently",
   "à voix haute", "en voz alta", "em voz alta", "ad alta voce", "laut",
   "вслух", "بصوت عالٍ", "出声地"),
 "ahead": e("adverb", "in front, or in the time to come",
   "devant", "adelante", "à frente", "avanti", "voraus",
   "впереди", "أمام", "前方"),
 "apart": e("adverb", "separated, away from each other",
   "à part", "aparte", "à parte", "a parte", "getrennt",
   "порознь", "منفصلين", "分开"),
 "toward": e("preposition", "in the direction of",
   "vers", "hacia", "em direção a", "verso", "auf ... zu",
   "к", "نحو", "朝向"),

 # --- high-frequency content words the coverage pass flagged ---
 "firm": e("noun", "a company or business",
   "l'entreprise", "la empresa", "a empresa", "l'azienda", "die Firma",
   "фирма", "شركة", "公司"),
 "slip": e("noun", "a small piece of paper",
   "le bout de papier", "el papelito", "o pedaço de papel", "il foglietto", "der Zettel",
   "листок", "قصاصة", "纸条"),
 "fold": e("verb", "to bend something over onto itself",
   "plier", "doblar", "dobrar", "piegare", "falten",
   "складывать", "يطوي", "折叠"),
 "hang": e("verb", "to fix something at the top so it drops down",
   "accrocher", "colgar", "pendurar", "appendere", "hängen",
   "вешать", "يعلّق", "挂"),
 "sense": e("noun", "a feeling you have without being told",
   "l'impression", "la sensación", "a sensação", "la sensazione", "das Gefühl",
   "ощущение", "إحساس", "感觉"),
 "lean": e("verb", "to bend or rest your body against something",
   "s'appuyer", "apoyarse", "encostar-se", "appoggiarsi", "sich lehnen",
   "опираться", "يتّكئ", "倚靠"),
 "boss": e("noun", "the person who is in charge of you at work",
   "le patron", "el jefe", "o chefe", "il capo", "der Chef",
   "начальник", "رئيس", "老板"),
 "alarm": e("noun", "a clock or sound that wakes you or warns you",
   "le réveil", "la alarma", "o alarme", "la sveglia", "der Wecker",
   "будильник", "منبه", "闹钟"),
 "builder": e("noun", "a person whose job is to build houses",
   "le maçon", "el albañil", "o pedreiro", "il muratore", "der Bauarbeiter",
   "строитель", "بنّاء", "建筑工"),
 "child": e("noun", "a young person, not yet grown up",
   "l'enfant", "el niño", "a criança", "il bambino", "das Kind",
   "ребёнок", "طفل", "小孩"),
 "spare": e("adjective", "kept extra, ready to be used if needed",
   "de rechange", "de sobra", "sobressalente", "di riserva", "übrig",
   "запасной", "احتياطي", "备用的"),
}


def main():
    ep1 = json.load(open(EP1, encoding="utf-8"))["lexicon"]["entries"]
    book = json.load(open(EP2, encoding="utf-8"))

    entries = {}
    missing_reuse = []
    for w in REUSE:
        if w in ep1:
            entries[w] = ep1[w]
        else:
            missing_reuse.append(w)

    for w, v in NEW.items():
        if v is None:
            continue
        entries[w.strip()] = v

    book["lexicon"]["entries"] = dict(sorted(entries.items()))
    json.dump(book, open(EP2, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    print(f"Lexicon written: {len(entries)} entries "
          f"({len([w for w in REUSE if w in ep1])} reused from book 1, "
          f"{len([v for v in NEW.values() if v])} new).")
    if missing_reuse:
        print("WARNING reuse words not found in book 1:", ", ".join(missing_reuse))


if __name__ == "__main__":
    main()
