#!/usr/bin/env python3
"""Per-passage clue text (gist) for book 4, The Cool of Evening.
Scoped per book: content/gist/cool-of-evening/<lang>.json. "Where needed": opening, forks, the
con, the stranger, the shortcut, the giving, the mystery, and all 12 endings. fr/es/it/de/pt
vouched; ru/ar/zh draft PENDING NATIVE REVIEW. Run: python3 scripts/build_gists_ep04.py
"""
import json, os
LANGS = ["fr", "es", "it", "de", "pt", "ru", "ar", "zh"]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "cool-of-evening")
os.makedirs(OUT, exist_ok=True)
G = {
 1: {
  "fr": "À l'heure la plus chaude, le bus tombe en panne, à des heures de la ville, sans réseau. À bord, Sami, un enfant d'environ huit ans qui voyage seul, s'est tu, le visage rouge de chaleur, et il reste peu d'eau.",
  "es": "En la hora más calurosa, el autobús se avería, a horas del pueblo y sin cobertura. A bordo, Sami, un niño de unos ocho años que viaja solo, se ha quedado callado y colorado por el calor, y queda poca agua.",
  "it": "Nell'ora più calda, l'autobus si guasta, a ore dalla città e senza segnale. A bordo c'è Sami, un bambino di circa otto anni che viaggia solo, zitto e paonazzo per il caldo, e resta poca acqua.",
  "de": "In der heißesten Stunde bleibt der Bus liegen, Stunden von der Stadt entfernt, ohne Empfang. An Bord ist Sami, ein etwa achtjähriges Kind, das allein reist, still und hochrot vor Hitze, und es ist kaum noch Wasser da.",
  "pt": "Na hora mais quente, o autocarro avaria, a horas da cidade e sem rede. A bordo está o Sami, uma criança de uns oito anos a viajar sozinha, calada e corada de calor, e resta pouca água.",
  "ru": "В самый зной автобус ломается, до города далеко, связи нет. На борту Сами, ребёнок лет восьми, едет один; он притих и раскраснелся от жары, а воды почти не осталось.",
  "ar": "في أشدّ ساعات الحرّ تتعطّل الحافلة، على بُعد ساعات من المدينة وبلا إشارة. على متنها سامي، طفلٌ في الثامنة تقريباً يسافر وحده، صمت ووجهه محمرّ من الحرّ، ولم يبقَ إلا قليل من الماء.",
  "zh": "正是一天最热的时候，大巴抛了锚，离最近的镇子还要几个钟头，手机也没有信号。车上有个独自旅行、约莫八岁的孩子萨米，热得脸通红、不出声了，而水也不多了。",
 },
 9: {
  "fr": "M. Bello, le chauffeur, ouvre la soute, honteux : des bouteilles d'eau, une trousse de secours, une grande bâche, des chiffons. « Prends ce qu'il te faut. » Un homme bon, mais dépassé.",
  "es": "El Sr. Bello, el conductor, abre la bodega, avergonzado: botellas de agua, un botiquín, una lona grande, trapos. «Toma lo que necesites». Un hombre bueno, pero superado.",
  "it": "Il signor Bello, l'autista, apre la stiva, pieno di vergogna: bottiglie d'acqua, una cassetta di pronto soccorso, un grande telone, stracci. «Prendi ciò che ti serve». Un brav'uomo, ma in difficoltà.",
  "de": "Herr Bello, der Fahrer, öffnet beschämt den Gepäckraum: Wasserflaschen, ein Verbandskasten, eine große Plane, Lappen. „Nimm, was du brauchst.“ Ein guter Mann, aber überfordert.",
  "pt": "O Sr. Bello, o motorista, abre o porão, envergonhado: garrafas de água, um estojo de primeiros socorros, uma lona grande, trapos. «Leva o que precisares». Um homem bom, mas ultrapassado.",
  "ru": "Водитель, мистер Белло, со стыдом открывает багажный отсек: бутылки воды, аптечка, большой брезент, тряпки. «Бери что нужно». Добрый человек, но не справляется.",
  "ar": "يفتح السائق السيد بيلو صندوق الأمتعة، والخجل على وجهه: زجاجات ماء، وصندوق إسعاف، ومشمّع كبير، وخِرَق. «خذ ما تحتاج». رجلٌ طيّب، لكنّه عاجز عن الموقف.",
  "zh": "司机贝洛先生满脸羞愧地打开行李舱：几箱瓶装水、一个急救箱、一大块帆布、几条抹布。“需要什么就拿。”他是个好人，只是应付不来。",
 },
 10: {
  "fr": "Le vieux M. Danso, désorienté et la bouche sèche, tire sur son col. Il ne sait plus trop où il est et vous regarde avec des yeux effrayés. Vous avez beaucoup à faire — mais il est là, et il a peur.",
  "es": "El anciano Sr. Danso, confuso y con la boca seca, se tira del cuello. No sabe muy bien dónde está y te mira con ojos asustados. Tienes mucho que hacer, pero él está ahí y tiene miedo.",
  "it": "Il vecchio signor Danso, confuso e con la bocca secca, si tira il colletto. Non sa bene dove si trovi e ti guarda con occhi spaventati. Hai molto da fare, ma lui è lì, e ha paura.",
  "de": "Der alte Herr Danso, verwirrt und mit trockenem Mund, zupft an seinem Kragen. Er weiß kaum, wo er ist, und sieht dich mit ängstlichen Augen an. Du hast viel zu tun – aber er ist hier, und er hat Angst.",
  "pt": "O velho Sr. Danso, confuso e de boca seca, puxa o colarinho. Mal sabe onde está e olha para ti com olhos assustados. Tens muito que fazer, mas ele está ali, e tem medo.",
  "ru": "Старый мистер Дансо, растерянный, с пересохшим ртом, теребит воротник. Он плохо понимает, где он, и смотрит на тебя испуганными глазами. У тебя много дел — но он здесь, и ему страшно.",
  "ar": "العجوز السيد دانسو، مشوّشٌ وفمه جاف، يشدّ ياقته. لا يكاد يعرف أين هو، وينظر إليك بعينين خائفتين. أمامك الكثير لتفعله — لكنه هنا، وهو خائف.",
  "zh": "年老的丹索先生神志恍惚、口干舌燥，不停拉扯着衣领。他几乎不知道自己在哪儿，用惊恐的眼神望着你。你还有许多事要做——可他就在这儿，他害怕。",
 },
 12: {
  "fr": "Vous passez de siège en siège, demandant la même chose à chacun : partagez votre eau, votre ombre, et veillons ensemble sur les plus faibles. Quelques-uns acquiescent — et il n'en faut que quelques-uns pour commencer.",
  "es": "Vas de asiento en asiento pidiendo lo mismo a cada uno: comparte tu agua, tu sombra, y cuidemos juntos de los más débiles. Unos pocos asienten, y con unos pocos basta para empezar.",
  "it": "Vai di sedile in sedile chiedendo a ciascuno la stessa cosa: condividi la tua acqua, la tua ombra, e vegliamo insieme sui più deboli. Alcuni annuiscono — e bastano pochi per cominciare.",
  "de": "Du gehst von Sitz zu Sitz und bittest jeden um dasselbe: Teilt euer Wasser, euren Schatten, und lasst uns gemeinsam über die Schwachen wachen. Ein paar nicken – und ein paar genügen für den Anfang.",
  "pt": "Vais de banco em banco a pedir o mesmo a cada um: partilha a tua água, a tua sombra, e vigiemos juntos os mais fracos. Alguns acenam — e bastam alguns para começar.",
  "ru": "Ты идёшь от сиденья к сиденью и просишь каждого об одном: поделись водой, тенью, и давайте вместе приглядим за слабыми. Несколько человек кивают — а чтобы начать, хватит и нескольких.",
  "ar": "تمرّ من مقعد إلى مقعد طالباً من كلٍّ الأمر نفسه: شارِك ماءك وظلّك، ولنحمِ الضعفاء معاً. يومئ بعضهم — ويكفي القليل للبدء.",
  "zh": "你一个座位一个座位地走过去，对每个人说同样的话：分出你的水、你的阴凉，咱们一起照看体弱的人。有几个人点了头——而要开始，几个就够了。",
 },
 27: {
  "fr": "La plaine couperait la route de moitié et la crête paraît si proche. Mais le terrain est ouvert, sans piste ni ombre, écrasé de chaleur. Rose vous a dit de ne pas vous y risquer — et elle ne plaisantait pas.",
  "es": "El llano acortaría el camino a la mitad y la loma parece muy cerca. Pero el terreno es abierto, sin senda ni sombra, aplastado por el calor. Rose te dijo que no lo cruzaras, y no bromeaba.",
  "it": "La piana dimezzerebbe il cammino e il crinale sembra vicinissimo. Ma il terreno è aperto, senza sentiero né ombra, schiacciato dal caldo. Rose ti ha detto di starne alla larga — e non scherzava.",
  "de": "Die Ebene würde den Weg halbieren, und der Kamm scheint so nah. Doch das Gelände ist offen, ohne Pfad, ohne Schatten, von Hitze erdrückt. Rose hat dir geraten, die Finger davon zu lassen – und sie hat nicht gescherzt.",
  "pt": "A planície cortaria o caminho a meio e a crista parece tão perto. Mas o terreno é aberto, sem trilho nem sombra, esmagado pelo calor. A Rose disse-te para não arriscares — e não estava a brincar.",
  "ru": "Равнина сократила бы путь вдвое, и гребень кажется таким близким. Но местность открытая, без тропы и тени, раздавленная зноем. Роуз велела туда не соваться — и не шутила.",
  "ar": "السهل يختصر الطريق إلى النصف، والتلّة تبدو قريبة جداً. لكن الأرض مكشوفة بلا مسلك ولا ظلّ، يجثم عليها الحرّ كيدٍ ثقيلة. قالت لك روز أن تبتعد عنه — ولم تكن تمزح.",
  "zh": "走那片开阔地能把路程缩短一半，山脊看着也近。可那地方没有路、没有阴凉，热浪像一只重手压在上面。罗斯叫你千万别走——她不是开玩笑。",
 },
 32: {
  "fr": "Près d'une voiture en panne, une famille sans eau, un petit enfant qui pleure, rouge de chaleur. Les parents vous regardent, épuisés et sans espoir. Vous avez un peu d'eau — pas beaucoup, mais plus qu'eux.",
  "es": "Junto a un coche averiado, una familia sin agua, un niño pequeño que llora, rojo de calor. Los padres te miran, agotados y sin esperanza. Tienes algo de agua, no mucha, pero más que ellos.",
  "it": "Accanto a un'auto in panne, una famiglia senz'acqua, un bambino piccolo che piange, rosso per il caldo. I genitori ti guardano, sfiniti e senza speranza. Hai un po' d'acqua — non molta, ma più di loro.",
  "de": "Neben einem liegengebliebenen Auto eine Familie ohne Wasser, ein kleines Kind weint, hochrot vor Hitze. Die Eltern sehen dich erschöpft und hoffnungslos an. Du hast etwas Wasser – nicht viel, aber mehr als sie.",
  "pt": "Junto a um carro avariado, uma família sem água, uma criança pequena a chorar, vermelha de calor. Os pais olham para ti, exaustos e sem esperança. Tens alguma água — não muita, mas mais do que eles.",
  "ru": "У заглохшей машины семья без воды, маленький ребёнок плачет, красный от жары. Родители смотрят на тебя устало и безнадёжно. У тебя есть немного воды — немного, но больше, чем у них.",
  "ar": "قرب سيارة متعطّلة عائلةٌ بلا ماء، وطفلٌ صغير يبكي محمرّاً من الحرّ. ينظر إليك الوالدان بإرهاقٍ ويأس. معك بعض الماء — ليس كثيراً، لكنه أكثر ممّا لديهم.",
  "zh": "一辆抛锚的车旁，一家人没了水，一个小孩热得满脸通红，哭个不停。父母疲惫而绝望地看着你。你还有点水——不多，但比他们多。",
 },
 40: {
  "fr": "L'homme du pick-up vous sourit : « De l'eau ? Un trajet en ville ? Je peux aider — aujourd'hui seulement, en liquide. » Ses bouteilles chauffent au soleil, et son sourire n'atteint pas ses yeux. Ce genre d'aide, vous connaissez.",
  "es": "El hombre de la camioneta te sonríe: «¿Agua? ¿Un viaje al pueblo? Puedo ayudar, solo hoy, solo en efectivo». Sus botellas se calientan al sol y su sonrisa no le llega a los ojos. Esa clase de ayuda ya la conoces.",
  "it": "L'uomo del pick-up ti sorride: «Acqua? Un passaggio in città? Posso aiutare — solo oggi, solo contanti». Le sue bottiglie si scaldano al sole e il sorriso non gli arriva agli occhi. Quel tipo di aiuto lo conosci.",
  "de": "Der Mann vom Pick-up lächelt dich an: „Wasser? Eine Fahrt in die Stadt? Ich kann helfen – nur heute, nur bar.“ Seine Flaschen werden in der Sonne warm, und sein Lächeln erreicht die Augen nicht. Diese Art Hilfe kennst du.",
  "pt": "O homem da carrinha sorri-te: «Água? Boleia à cidade? Posso ajudar — só hoje, só dinheiro». As garrafas aquecem ao sol e o sorriso não lhe chega aos olhos. Esse tipo de ajuda já conheces.",
  "ru": "Мужчина с пикапа улыбается: «Вода? Подвезти до города? Могу помочь — только сегодня, только наличными». Его бутылки греются на солнце, а улыбка не доходит до глаз. Такую «помощь» ты уже видел.",
  "ar": "يبتسم لك رجل الشاحنة: «ماء؟ توصيلة إلى المدينة؟ أستطيع المساعدة — اليوم فقط، نقداً فقط». زجاجاته تسخن في الشمس، وابتسامته لا تبلغ عينيه. هذا النوع من «المساعدة» تعرفه.",
  "zh": "开皮卡的男人朝你笑：“要水？还是搭车进城？我能帮忙——只限今天，只收现金。”他的水瓶在太阳下晒得发烫，笑意却到不了眼底。这种“帮忙”，你见过。",
 },
 41: {
  "fr": "Le prix est du vol pur. Il voit votre visage se décomposer et se penche : « Ce gamin ne tiendra pas, l'ami. Combien vaut un enfant pour toi ? » C'est cruel — et fait pour marcher. Cette phrase, c'est tout le piège.",
  "es": "El precio es un robo descarado. Ve que se te cae el alma y se inclina: «Ese niño no aguanta, amigo. ¿Cuánto vale un niño para ti?». Es cruel, y busca funcionar. Esa frase es toda la trampa.",
  "it": "Il prezzo è un furto bell'e buono. Vede il tuo viso spegnersi e si china: «Quel bambino non regge, amico. Quanto vale un figlio per te?». È crudele — e pensato per funzionare. Quella frase è tutto l'inganno.",
  "de": "Der Preis ist glatter Raub. Er sieht dein Gesicht sinken und beugt sich vor: „Das Kind hält nicht durch, Freund. Was ist dir ein Kind wert?“ Grausam – und darauf berechnet zu wirken. Dieser Satz ist der ganze Trick.",
  "pt": "O preço é um roubo puro. Vê o teu rosto cair e inclina-se: «Esse miúdo não aguenta, amigo. Quanto vale uma criança para ti?». É cruel — e feito para resultar. Essa frase é toda a armadilha.",
  "ru": "Цена — чистый грабёж. Он видит, как вытягивается твоё лицо, и наклоняется: «Этот малыш не дотянет, друг. Сколько стоит ребёнок для тебя?» Жестоко — и рассчитано сработать. В этой фразе весь обман.",
  "ar": "الثمن سرقةٌ صريحة. يرى وجهك ينهار فيميل نحوك: «هذا الطفل لن يصمد يا صديق. كم يساوي عندك طفل؟». كلامٌ قاسٍ — ومقصودٌ ليؤثّر. تلك الجملة هي الخدعة كلها.",
  "zh": "那价钱根本是抢钱。他看着你脸色一沉，凑近来：“那孩子撑不住了，朋友。一个孩子，对你值多少？”这话狠毒——而且就是要戳中你。这一句，就是整个圈套。",
 },
 69: {
  "fr": "Une maison fermée depuis des années pèse sur vous — poussière, silence, chaleur ancienne, un lieu sans vie. Puis vous l'entendez : un souffle lent et léger, tout près, dans la pièce du fond. Quelqu'un est vivant ici.",
  "es": "Una casa cerrada desde hace años te oprime: polvo, silencio, calor viejo, un lugar sin vida. Entonces lo oyes: una respiración lenta y leve, muy cerca, en el cuarto del fondo. Hay alguien vivo aquí.",
  "it": "Una casa chiusa da anni ti pesa addosso — polvere, silenzio, calore vecchio, un luogo senza vita. Poi lo senti: un respiro lento e lieve, vicinissimo, nella stanza in fondo. Qui dentro c'è qualcuno di vivo.",
  "de": "Ein seit Jahren verschlossenes Haus lastet auf dir – Staub, Stille, alte Hitze, ein Ort ohne Leben. Dann hörst du es: ein langsamer, schwacher Atem, ganz nah, aus dem hinteren Zimmer. Hier drinnen lebt jemand.",
  "pt": "Uma casa fechada há anos pesa sobre ti — pó, silêncio, calor velho, um lugar sem vida. Então ouve-lo: uma respiração lenta e leve, muito perto, no quarto do fundo. Há alguém vivo aqui.",
  "ru": "Запертый годами дом давит на тебя — пыль, тишина, старая жара, место без жизни. И вдруг ты слышишь: медленное, слабое дыхание совсем рядом, из дальней комнаты. Здесь кто-то живой.",
  "ar": "يُطبِق عليك بيتٌ مغلق منذ سنين — غبار، صمت، حرٌّ قديم، مكانٌ بلا حياة. ثم تسمعه: نَفَسٌ بطيء خافت، قريبٌ جداً، من الغرفة الخلفية. ثمّة حيٌّ هنا.",
  "zh": "一座关了多年的屋子压得你喘不过气——灰尘、寂静、陈年的热气，一个毫无生气的地方。忽然你听见了：缓慢而微弱的呼吸，就在近旁，从里屋传来。这屋里，还有一个活人。",
 },
 120: {
  "fr": "FIN (bonne) — Vous avez fait durer l'eau à travers le pire de la chaleur — gorgées comptées, ombre tenue, chaque goutte partagée. Le soleil baisse, un camion vous trouve. Sami arrive en ville sain et sauf. L'enfant est vivant parce que vous vous êtes levé de votre siège.",
  "es": "FINAL (bueno) — Hiciste durar el agua en lo peor del calor: sorbos contados, sombra sostenida, cada gota compartida. Baja el sol, un camión os encuentra. Sami llega a la ciudad sano y salvo. El niño está vivo porque te levantaste del asiento.",
  "it": "FINALE (buono) — Hai fatto durare l'acqua nel peggio del caldo — sorsi contati, ombra retta, ogni goccia condivisa. Il sole cala, un camion vi trova. Sami arriva in città sano e salvo. Il bambino è vivo perché ti sei alzato dal sedile.",
  "de": "ENDE (gut) — Du hast das Wasser durch die schlimmste Hitze gestreckt – abgezählte Schlucke, hochgehaltener Schatten, jeder Tropfen geteilt. Die Sonne sinkt, ein Lastwagen findet euch. Sami kommt heil in der Stadt an. Das Kind lebt, weil du von deinem Sitz aufgestanden bist.",
  "pt": "FIM (bom) — Fizeste a água durar no pior do calor — goles contados, sombra erguida, cada gota partilhada. O sol baixa, um camião encontra-vos. O Sami chega à cidade são e salvo. A criança está viva porque te levantaste do banco.",
  "ru": "КОНЦОВКА (хорошая) — Ты растянул воду на весь жар — считанные глотки, поднятая тень, каждая капля поделена. Солнце садится, грузовик находит вас. Сами добирается до города целым. Ребёнок жив, потому что ты поднялся с места.",
  "ar": "النهاية (جيدة) — جعلتَ الماء يكفي خلال أشدّ الحرّ — رشفات محسوبة، وظلٌّ مرفوع، وكلّ قطرة مقسومة. تهبط الشمس، وتجدكم شاحنة. يصل سامي إلى المدينة سالماً. الطفل حيٌّ لأنك نهضتَ من مقعدك.",
  "zh": "结局（好）——你在最毒的热浪里把水撑了下来——一口一口数着喝、把阴凉举着、每一滴都分着用。太阳落下，一辆卡车找到了你们。萨米平安抵达城里。孩子活下来，只因你从座位上站了起来。",
 },
 121: {
  "fr": "FIN (bonne, secrète) — Vous êtes allé vers la fumée inexpliquée et avez trouvé le vieux M. Faro à terre, épuisé, seul ; vous l'avez rafraîchi à temps. Son puits profond a abreuvé tout le bus, sa vieille radio a enfin appelé des secours. Et Rose, du bus, a reconnu son visage : deux vieux amis retrouvés.",
  "es": "FINAL (bueno, secreto) — Fuiste hacia el humo inexplicable y hallaste al viejo Sr. Faro caído y agotado, solo; lo refrescaste a tiempo. Su pozo profundo dio agua a todo el autobús, su vieja radio pidió ayuda al fin. Y Rose, del autobús, reconoció su cara: dos viejos amigos reencontrados.",
  "it": "FINALE (buono, segreto) — Sei andato verso il fumo inspiegabile e hai trovato il vecchio signor Faro a terra, allo stremo, solo; l'hai rinfrescato in tempo. Il suo pozzo profondo ha dissetato tutto il bus, la sua vecchia radio ha chiamato aiuto finalmente. E Rose, dal bus, ha riconosciuto il suo volto: due vecchi amici ritrovati.",
  "de": "ENDE (gut, geheim) — Du bist zum unerklärlichen Rauch gegangen und hast den alten Herrn Faro am Boden, entkräftet, allein gefunden; du hast ihn rechtzeitig gekühlt. Sein tiefer Brunnen tränkte den ganzen Bus, sein altes Funkgerät holte endlich Hilfe. Und Rose aus dem Bus erkannte sein Gesicht: zwei alte Freunde, wiedergefunden.",
  "pt": "FIM (bom, secreto) — Foste até ao fumo inexplicável e encontraste o velho Sr. Faro caído e esgotado, sozinho; arrefeceste-o a tempo. O poço fundo dele deu água ao autocarro todo, o rádio velho pediu ajuda enfim. E a Rose, do autocarro, reconheceu-lhe o rosto: dois velhos amigos reencontrados.",
  "ru": "КОНЦОВКА (хорошая, тайная) — Ты пошёл к необъяснимому дыму и нашёл старого мистера Фаро — он лежал, обессиленный, один; ты вовремя его охладил. Его глубокий колодец напоил весь автобус, его старое радио наконец вызвало помощь. А Роуз из автобуса узнала его лицо: двое старых друзей встретились вновь.",
  "ar": "النهاية (جيدة، سرّية) — ذهبتَ نحو الدخان الذي لا يُفسَّر فوجدتَ العجوز السيد فارو ساقطاً منهكاً وحيداً؛ وبرّدتَه في الوقت المناسب. بئره العميقة سقت الحافلة كلّها، ومذياعه القديم استدعى النجدة أخيراً. وروز، من الحافلة، عرفت وجهه: صديقان قديمان التقيا من جديد.",
  "zh": "结局（好·隐藏）——你朝那道无法解释的烟走去，发现老法罗先生倒在地上、精疲力竭、孤身一人；你及时替他降了温。他那口深井供了整车人的水，他的旧收音机终于叫来了救援。而车上的罗斯认出了他的脸：两位老友，久别重逢。",
 },
 122: {
  "fr": "FIN (bonne) — Pas un seul acte héroïque, mais mieux : vous avez transformé un bus d'inconnus effrayés en gens qui s'entraident — eau partagée, ombre tenue, les faibles veillés par les forts. Ensemble, tout le bus a passé la journée. Personne n'y est resté seul.",
  "es": "FINAL (bueno) — No un acto heroico, sino algo mejor: convertiste un autobús de desconocidos asustados en gente que se ayuda — agua compartida, sombra sostenida, los débiles cuidados por los fuertes. Juntos, todo el autobús pasó el día. Nadie quedó solo.",
  "it": "FINALE (buono) — Non un singolo atto eroico, ma qualcosa di meglio: hai trasformato un bus di sconosciuti spaventati in gente che si aiuta — acqua condivisa, ombra retta, i deboli vegliati dai forti. Insieme, tutto il bus ha passato la giornata. Nessuno è rimasto solo.",
  "de": "ENDE (gut) — Keine einzelne Heldentat, sondern etwas Besseres: Du hast einen Bus voll verängstigter Fremder in Menschen verwandelt, die einander helfen – Wasser geteilt, Schatten gehalten, die Schwachen von den Starken behütet. Gemeinsam kam der ganze Bus durch den Tag. Niemand blieb allein.",
  "pt": "FIM (bom) — Não um ato heroico, mas algo melhor: transformaste um autocarro de estranhos assustados em gente que se ajuda — água partilhada, sombra erguida, os fracos vigiados pelos fortes. Juntos, o autocarro todo passou o dia. Ninguém ficou sozinho.",
  "ru": "КОНЦОВКА (хорошая) — Не единичный подвиг, а нечто лучшее: ты превратил автобус перепуганных чужаков в людей, что помогают друг другу — вода поделена, тень поднята, слабых берегут сильные. Вместе весь автобус пережил день. Никто не остался один.",
  "ar": "النهاية (جيدة) — ليس عملاً بطولياً واحداً، بل ما هو أفضل: حوّلتَ حافلةً من الغرباء الخائفين إلى أناسٍ يتعاونون — ماءٌ يُقتسم، وظلٌّ يُرفع، والأقوياء يحرسون الضعفاء. ومعاً اجتازت الحافلة كلّها النهار. لم يُترَك فيها أحدٌ وحده.",
  "zh": "结局（好）——不是某一桩英勇之举，而是更好的事：你把一车惊慌的陌生人，变成了彼此照应的人——分水、举阴凉、强者护着弱者。就这样，一整车人一起熬过了这一天。没有谁被独自丢下。",
 },
 123: {
  "fr": "FIN (bonne) — Vous avez refusé l'arnaque — vu le piège et tourné le dos. Tête froide, argent gardé, eau trouvée par des moyens honnêtes, à la dure. Journée imparfaite, tout le monde n'est pas sauvé ; mais c'était propre, et propre, au bout du compte, suffit.",
  "es": "FINAL (bueno) — Rechazaste el timo: viste la trampa y le diste la espalda. Cabeza fría, dinero a salvo, agua conseguida por medios honrados, a las duras. Un día imperfecto, no salvaste a todos; pero lo hiciste limpio, y limpio, al final, basta.",
  "it": "FINALE (buono) — Hai rifiutato la truffa — hai visto l'inganno e gli hai voltato le spalle. Testa lucida, soldi salvi, acqua trovata con mezzi onesti, alla dura. Giornata imperfetta, non hai salvato tutti; ma l'hai fatto pulito, e pulito, alla fine, basta.",
  "de": "ENDE (gut) — Du hast den Betrug abgelehnt – den Trick erkannt und ihm den Rücken gekehrt. Kühler Kopf, Geld behalten, Wasser auf ehrliche, harte Weise gefunden. Kein perfekter Tag, nicht alle gerettet; aber sauber gemacht, und sauber ist am Ende genug.",
  "pt": "FIM (bom) — Recusaste a vigarice — viste a cilada e viraste-lhe as costas. Cabeça fria, dinheiro a salvo, água obtida por meios honestos, à força. Dia imperfeito, não salvaste todos; mas fizeste-o limpo, e limpo, no fim, basta.",
  "ru": "КОНЦОВКА (хорошая) — Ты отверг аферу — разглядел уловку и отвернулся. Холодная голова, деньги целы, вода добыта честно, трудным путём. День неидеален, спасены не все; но сделано чисто, а чисто в конце концов — достаточно.",
  "ar": "النهاية (جيدة) — رفضتَ الاحتيال — رأيتَ الخدعة وأدرتَ ظهرك لها. رأسٌ هادئ، ومالٌ محفوظ، وماءٌ وُجد بطرقٍ نزيهة، بالطريق الصعب. يومٌ غير كامل، لم تُنقذ الجميع؛ لكنك فعلتها نظيفة، والنظيف، في النهاية، يكفي.",
  "zh": "结局（好）——你拒绝了骗局——看穿了把戏，转身走开。头脑冷静、钱袋保住，用正道、靠苦功找到了水。这一天并不完美，你没能救下每个人；但你做得干净，而干净，到头来，就够了。",
 },
 124: {
  "fr": "FIN (mitigée) — Vous n'avez pas tout réussi, mais vous vous êtes arrêté une fois pour un inconnu, lui donnant du temps quand le temps manquait. Dans la fraîcheur du soir, ce même inconnu revient avec un véhicule et vous emmène, Sami et vous, vers la ville. Une gentillesse revient toujours.",
  "es": "FINAL (agridulce) — No lo lograste todo, pero te paraste una vez por un desconocido, dándole tu tiempo cuando el tiempo escaseaba. En el fresco de la tarde, ese mismo desconocido vuelve con un vehículo y os lleva, a Sami y a ti, hacia el pueblo. Una amabilidad siempre vuelve.",
  "it": "FINALE (agrodolce) — Non è andato tutto bene, ma ti sei fermato una volta per uno sconosciuto, dandogli tempo quando il tempo mancava. Nel fresco della sera, quello stesso sconosciuto torna con un mezzo e porta te e Sami verso la città. Una gentilezza torna sempre.",
  "de": "ENDE (zwiespältig) — Nicht alles ist gelungen, aber du bist einmal für einen Fremden stehen geblieben und hast ihm Zeit geschenkt, als die Zeit knapp war. In der Abendkühle kommt eben dieser Fremde mit einem Fahrzeug zurück und bringt dich und Sami in Richtung Stadt. Eine Freundlichkeit kommt immer zurück.",
  "pt": "FIM (agridoce) — Não acertaste em tudo, mas paraste uma vez por um estranho, dando-lhe tempo quando o tempo faltava. No fresco da tarde, esse mesmo estranho volta com um veículo e leva-vos, a ti e ao Sami, rumo à cidade. Uma gentileza volta sempre.",
  "ru": "КОНЦОВКА (неоднозначная) — Не всё удалось, но однажды ты задержался ради незнакомца, отдав время, когда его не хватало. В вечерней прохладе тот самый незнакомец возвращается с машиной и везёт тебя и Сами к городу. Доброта всегда возвращается.",
  "ar": "النهاية (مُرّة حلوة) — لم يُصب كل شيء، لكنك توقّفت مرّةً من أجل غريب، ومنحتَه وقتاً حين كان الوقت ضيّقاً. وفي برودة المساء يعود الغريب نفسه بسيارة ويأخذك أنت وسامي نحو المدينة. المعروف يعود دائماً.",
  "zh": "结局（苦乐参半）——你并非事事做成，但你曾为一个陌生人停下，在时间紧迫时给了他你的时间。到了傍晚的凉意里，正是那个陌生人开着车回来，载上你和萨米，朝城里去。一份善意，终会绕回来。",
 },
 125: {
  "fr": "FIN (mitigée) — Vous avez donné votre propre eau — à un enfant en pleurs, à une famille démunie. Dans la fraîcheur du soir, vous voilà vous-même assoiffé et éreinté. Mais vous n'êtes pas seul : ceux que vous avez aidés sont près de vous. Quelque chose a changé dans ce bus. Pas une pleine victoire — mais un début.",
  "es": "FINAL (agridulce) — Diste tu propia agua: a un niño que lloraba, a una familia sin nada. En el fresco de la tarde, eres tú quien está sediento y agotado. Pero no estás solo: los que ayudaste están cerca. Algo cambió en ese autobús. No es una victoria plena, pero es un comienzo.",
  "it": "FINALE (agrodolce) — Hai dato la tua acqua — a un bambino in lacrime, a una famiglia senza nulla. Nel fresco della sera sei tu a essere assetato e sfinito. Ma non sei solo: chi hai aiutato ti è vicino. Qualcosa è cambiato su quel bus. Non una vittoria piena, ma un inizio.",
  "de": "ENDE (zwiespältig) — Du hast dein eigenes Wasser weggegeben – einem weinenden Kind, einer Familie ohne alles. In der Abendkühle bist du selbst durstig und erschöpft. Aber nicht allein: Die, denen du geholfen hast, sind bei dir. In diesem Bus hat sich etwas verändert. Kein voller Sieg – aber ein Anfang.",
  "pt": "FIM (agridoce) — Deste a tua própria água — a uma criança a chorar, a uma família sem nada. No fresco da tarde, és tu que estás sedento e esgotado. Mas não estás sozinho: quem ajudaste está perto. Algo mudou naquele autocarro. Não é uma vitória plena, mas é um começo.",
  "ru": "КОНЦОВКА (неоднозначная) — Ты отдал свою воду — плачущему ребёнку, семье без всего. В вечерней прохладе уже ты сам измучен жаждой. Но ты не один: те, кому ты помог, рядом. Что-то в этом автобусе тихо изменилось. Не полная победа — но начало.",
  "ar": "النهاية (مُرّة حلوة) — أعطيتَ ماءك — لطفلٍ يبكي، ولعائلةٍ بلا شيء. وفي برودة المساء صرتَ أنت الظمآن المنهك. لكنك لست وحدك: من ساعدتهم قريبون منك. شيءٌ تغيّر في تلك الحافلة بهدوء. ليس نصراً كاملاً — لكنه بداية.",
  "zh": "结局（苦乐参半）——你把自己的水给了出去——给哭泣的孩子、给一无所有的一家人。到了傍晚的凉意里，口渴、疲惫的成了你自己。但你并不孤单：被你帮过的人都在你身边。那辆车上，有什么悄悄变了。不是完胜——却是一个开始。",
 },
 126: {
  "fr": "FIN (mitigée) — Vous avez passé le pire de justesse — pas de victoire nette ni de plan habile, juste tenir, heure après heure, jusqu'à ce que la chaleur tombe et qu'un camion arrive enfin, tard et à contrecœur. Pas un triomphe, mais vous êtes passé — et c'est, à soi seul, un soulagement.",
  "es": "FINAL (agridulce) — Pasaste lo peor por los pelos: ni victoria limpia ni plan astuto; solo aguantar, hora tras hora, hasta que cedió el calor y al fin llegó un camión, tarde y a regañadientes. No es un triunfo, pero saliste, y eso ya es un alivio en sí.",
  "it": "FINALE (agrodolce) — Hai superato il peggio per un soffio — nessuna vittoria netta né piano astuto; solo resistere, ora dopo ora, finché il caldo è calato e un camion è arrivato infine, tardi e a malincuore. Non un trionfo, ma ce l'hai fatta — ed è, di per sé, un sollievo.",
  "de": "ENDE (zwiespältig) — Du bist gerade so durch das Schlimmste gekommen – kein klarer Sieg, kein cleverer Plan; nur Durchhalten, Stunde um Stunde, bis die Hitze nachließ und endlich ein Lastwagen kam, spät und widerwillig. Kein Triumph, aber du bist durch – und das allein ist eine Erleichterung.",
  "pt": "FIM (agridoce) — Passaste o pior à justa — nem vitória limpa nem plano esperto; só aguentar, hora após hora, até o calor ceder e um camião chegar enfim, tarde e a contragosto. Não é um triunfo, mas conseguiste — e isso, por si só, é um alívio.",
  "ru": "КОНЦОВКА (неоднозначная) — Ты впритык пережил худшее — ни чистой победы, ни хитрого плана; только держаться, час за часом, пока жара не спала и не пришёл наконец грузовик, поздно и нехотя. Не триумф, но ты выбрался — а это уже само по себе облегчение.",
  "ar": "النهاية (مُرّة حلوة) — تجاوزتَ الأسوأ بالكاد — لا نصر ناصع ولا خطّة بارعة؛ فقط الصمود، ساعةً بعد ساعة، حتى انكسر الحرّ وجاءت شاحنةٌ أخيراً، متأخرةً على مضض. ليس انتصاراً، لكنك نجوت — وهذا وحده راحة.",
  "zh": "结局（苦乐参半）——你勉勉强强熬过了最糟的时段——没有漂亮的胜利，也没有高明的计划；只是一个钟头一个钟头地撑着，直到暑气退去，一辆卡车终于姗姗来迟、极不情愿地出现。算不上凯旋，可你挺过来了——单这一点，本身就是一种宽慰。",
 },
 127: {
  "fr": "FIN (mitigée) — Vous n'avez pas tout réussi, loin de là. Mais tout le bus vous a vu faire une chose : quand c'était dur, brûlant et facile de rester assis, vous vous êtes levé pour agir. Les autres sont restés à leur place ; pas vous. Et ça, on s'en souvient. Désormais, cette route vous connaît.",
  "es": "FINAL (agridulce) — No lo lograste todo, ni de lejos. Pero todo el autobús te vio hacer una cosa: cuando era duro, caluroso y fácil quedarse quieto, te levantaste a actuar. Los demás siguieron sentados; tú no. Y eso se recuerda. Desde hoy, este camino te conoce.",
  "it": "FINALE (agrodolce) — Non hai gestito tutto, tutt'altro. Ma l'intero bus ti ha visto fare una cosa: quando era dura, rovente e facile restare seduti, ti sei alzato ad agire. Gli altri sono rimasti al loro posto; tu no. E questo si ricorda. Da oggi, questa strada ti conosce.",
  "de": "ENDE (zwiespältig) — Du hast nicht alles geschafft, bei Weitem nicht. Aber der ganze Bus sah dich eines tun: Als es hart und heiß war und Sitzenbleiben leicht, bist du aufgestanden und hast gehandelt. Die anderen blieben sitzen; du nicht. Und das merkt man sich. Von heute an kennt dich diese Straße.",
  "pt": "FIM (agridoce) — Não geriste tudo, longe disso. Mas o autocarro inteiro viu-te fazer uma coisa: quando era duro, quente e fácil ficar sentado, levantaste-te e agiste. Os outros ficaram nos lugares; tu não. E isso lembra-se. A partir de hoje, esta estrada conhece-te.",
  "ru": "КОНЦОВКА (неоднозначная) — Ты справился не со всем, далеко не со всем. Но весь автобус видел одно: когда было трудно, жарко и легко сидеть на месте, ты встал и начал действовать. Другие остались в креслах; ты — нет. А это запоминают. С сегодняшнего дня эта дорога тебя знает.",
  "ar": "النهاية (مُرّة حلوة) — لم تُدِر كل شيء، أبداً. لكن الحافلة كلّها رأتك تفعل أمراً واحداً: حين كان الوضع صعباً حارّاً، والجلوس أسهل، نهضتَ وتصرّفت. بقي الآخرون في مقاعدهم؛ أما أنت فلا. وهذا يُذكَر. من اليوم، صار هذا الطريق يعرفك.",
  "zh": "结局（苦乐参半）——你远没有把一切都办成。但整车人都看见你做了一件事：当天气又热又难、安坐最省事时，你站了起来，动手去做。别人留在座位上，你没有。这种事，人们会记住。从今天起，这条路记住了你。",
 },
 128: {
  "fr": "FIN (mauvaise) — Vous avez payé l'homme du pick-up — remis votre argent, dans la chaleur, pris par la peur. Pour quoi ? De l'eau tiède comme un bain, à moitié vide ; un trajet qui n'est jamais venu. L'argent est perdu, la soif intacte. Il savait que vous paieriez. C'était tout le jeu.",
  "es": "FINAL (malo) — Pagaste al hombre de la camioneta: entregaste tu dinero, en el calor, llevado por el miedo. ¿A cambio de qué? Agua tibia como el baño, medio vacía; un viaje que nunca llegó. El dinero se fue, la sed sigue igual. Sabía que pagarías. Ese era todo el juego.",
  "it": "FINALE (cattivo) — Hai pagato l'uomo del pick-up — consegnato i soldi, nel caldo, preso dalla paura. Per cosa? Acqua tiepida come un bagno, mezza vuota; un passaggio mai arrivato. I soldi sono persi, la sete intatta. Sapeva che avresti pagato. Era tutto qui il gioco.",
  "de": "ENDE (schlecht) — Du hast den Mann vom Pick-up bezahlt – dein Geld hergegeben, in der Hitze, aus Angst. Wofür? Wasser lauwarm wie Badewasser, halb leer; eine Fahrt, die nie kam. Das Geld ist weg, der Durst unverändert. Er wusste, dass du zahlst. Das war das ganze Spiel.",
  "pt": "FIM (mau) — Pagaste ao homem da carrinha — entregaste o dinheiro, no calor, levado pelo medo. Para quê? Água morna como banho, meia vazia; uma boleia que nunca veio. O dinheiro foi-se, a sede ficou igual. Ele sabia que ias pagar. Era esse o jogo todo.",
  "ru": "КОНЦОВКА (плохая) — Ты заплатил человеку с пикапа — отдал деньги, в жару, со страху. За что? Вода, тёплая как в ванне, наполовину пустая; обещанной поездки так и нет. Деньги пропали, жажда прежняя. Он знал, что ты заплатишь. В этом вся игра.",
  "ar": "النهاية (سيّئة) — دفعتَ لرجل الشاحنة — سلّمتَ مالك، في الحرّ، بدافع الخوف. مقابل ماذا؟ ماءٌ فاترٌ كماء الحمّام، نصفه ناقص؛ وتوصيلةٌ لم تأتِ قط. ذهب المال، وبقي العطش كما هو. كان يعلم أنك ستدفع. تلك هي اللعبة كلها.",
  "zh": "结局（坏）——你付了钱给开皮卡的人——在酷热里、在恐惧中，把钱交了出去。换来什么？温得像洗澡水、还少了一半的水；一趟始终没来的车。钱打了水漂，渴还是那个渴。他早料到你会付钱。这，就是整场把戏。",
 },
 129: {
  "fr": "FIN (mauvaise) — La plaine était un piège, exactement comme Rose l'avait dit. La crête n'approchait jamais, la route derrière vous s'effaçait, et la chaleur, sans ombre, a failli vous emporter pour de bon. Vous êtes revenu — de justesse — mais bien trop tard. La plaine a pris tout l'après-midi, et l'après-midi était tout ce que vous aviez.",
  "es": "FINAL (malo) — El llano era una trampa, tal como avisó Rose. La loma nunca se acercaba, el camino de atrás se borraba, y el calor, sin sombra, casi te lleva para siempre. Volviste —por los pelos—, pero demasiado tarde. El llano se tragó toda la tarde, y la tarde era cuanto tenías.",
  "it": "FINALE (cattivo) — La piana era una trappola, proprio come aveva detto Rose. Il crinale non si avvicinava mai, la strada dietro si cancellava, e il caldo, senza ombra, per poco non ti portava via per sempre. Sei tornato — per un pelo — ma troppo tardi. La piana si è presa tutto il pomeriggio, e il pomeriggio era tutto ciò che avevi.",
  "de": "ENDE (schlecht) — Die Ebene war eine Falle, genau wie Rose warnte. Der Kamm kam nie näher, der Weg hinter dir verschwand, und die Hitze ohne Schatten hätte dich fast für immer geholt. Du bist zurückgekommen – knapp – aber viel zu spät. Die Ebene nahm den ganzen Nachmittag, und der Nachmittag war alles, was du hattest.",
  "pt": "FIM (mau) — A planície era uma armadilha, tal como a Rose avisou. A crista nunca se aproximava, o caminho atrás apagava-se, e o calor, sem sombra, quase te levava de vez. Voltaste — à justa — mas tarde demais. A planície levou a tarde toda, e a tarde era tudo o que tinhas.",
  "ru": "КОНЦОВКА (плохая) — Равнина оказалась ловушкой, ровно как предупреждала Роуз. Гребень не приближался, дорога позади таяла, а зной без тени едва не забрал тебя навсегда. Ты вернулся — чудом — но слишком поздно. Равнина съела весь день, а день был всем, что у тебя было.",
  "ar": "النهاية (سيّئة) — كان السهل فخّاً، تماماً كما حذّرت روز. لم تقترب التلّة قط، وتلاشى الطريق خلفك، وكاد الحرّ بلا ظلّ أن يأخذك إلى الأبد. عدتَ — بالكاد — لكن متأخراً جداً. ابتلع السهل الظهيرة كلّها، والظهيرة كانت كلّ ما تملك.",
  "zh": "结局（坏）——那片开阔地是个陷阱，正如罗斯所警告。山脊始终不见靠近，身后的路也渐渐消失，而毫无遮荫的暑热，差点把你永远留在那里。你回来了——九死一生——却太迟了。那片平地吞掉了整个下午，而那个下午，是你仅有的时间。",
 },
 130: {
  "fr": "FIN (mauvaise) — Vous avez passé la journée sur de mauvaises choses — un mauvais marché, un détour, du temps perdu sans retour. Quand enfin vous vous agenouillez près de Sami, la chaleur était en lui depuis trop longtemps. Au soir, on porte l'enfant jusqu'à un camion, inerte et gris. Vous vous êtes levé, vous êtes sorti — mais vous n'êtes pas arrivé à temps.",
  "es": "FINAL (malo) — Pasaste el día en cosas equivocadas: un mal trato, un desvío, tiempo perdido sin remedio. Cuando por fin te arrodillas junto a Sami, el calor llevaba demasiado en el niño. Al atardecer lo llevan a un camión, inerte y gris. Te levantaste, saliste, pero no llegaste a tiempo.",
  "it": "FINALE (cattivo) — Hai passato la giornata sulle cose sbagliate — un cattivo affare, una deviazione, tempo perso per sempre. Quando infine ti inginocchi accanto a Sami, il caldo era nel bambino da troppo tempo. A sera lo portano a un camion, inerte e grigio. Ti sei alzato, sei uscito — ma non sei arrivato in tempo.",
  "de": "ENDE (schlecht) — Du hast den Tag mit den falschen Dingen verbracht – ein schlechtes Geschäft, ein Umweg, unwiederbringlich verlorene Zeit. Als du endlich neben Sami kniest, war die Hitze zu lange im Kind. Am Abend tragen sie es zu einem Lastwagen, reglos und grau. Du bist aufgestanden, hinausgegangen – aber nicht rechtzeitig angekommen.",
  "pt": "FIM (mau) — Passaste o dia nas coisas erradas — um mau negócio, um desvio, tempo perdido sem volta. Quando enfim te ajoelhas junto ao Sami, o calor já estava na criança há tempo demais. Ao entardecer levam-no para um camião, inerte e cinzento. Levantaste-te, saíste — mas não chegaste a tempo.",
  "ru": "КОНЦОВКА (плохая) — Ты потратил день не на то — плохая сделка, не туда свернул, время утекло безвозвратно. Когда ты наконец склоняешься над Сами, жара была в ребёнке слишком долго. К вечеру его несут к грузовику, обмякшего и серого. Ты поднялся, ты вышел — но не успел.",
  "ar": "النهاية (سيّئة) — أمضيتَ النهار في أمور خاطئة — صفقة سيّئة، ومنعطف غلط، ووقتٌ ضاع بلا رجعة. وحين تركع أخيراً إلى جوار سامي، يكون الحرّ قد سكن الطفل وقتاً أطول من اللازم. عند المساء يحملونه إلى شاحنة، واهناً شاحباً. نهضتَ، وخرجتَ — لكنك لم تصل في الوقت.",
  "zh": "结局（坏）——你把这一天花在了不该花的事上——一桩坏交易、一个错弯、再也追不回的时间。等你终于跪到萨米身边，热气已在孩子体内待得太久。傍晚，人们把孩子抬上一辆卡车，瘫软、灰白。你站起来了，也走出去了——却没能及时赶到。",
 },
 131: {
  "fr": "FIN (mauvaise) — Au bout du compte, vous êtes resté à votre place, votre bouteille bouchée. Vous vous êtes dit que ce n'était pas votre affaire, que l'aide viendrait le soir, qu'un autre agirait sûrement. Tout cela était vrai. Et un petit enfant, trois sièges plus loin, s'est tu dans la chaleur. Rien ne vous est arrivé. Vous y penserez très, très longtemps.",
  "es": "FINAL (malo) — Al final te quedaste en tu asiento, con tu botella cerrada. Te dijiste que no era asunto tuyo, que la ayuda llegaría al anochecer, que otro actuaría. Todo era cierto. Y un niño pequeño, tres asientos más allá, se quedó callado por el calor. A ti no te pasó nada. Pensarás en eso mucho, mucho tiempo.",
  "it": "FINALE (cattivo) — Alla fine sei rimasto al tuo posto, la bottiglia tappata. Ti sei detto che non erano affari tuoi, che gli aiuti sarebbero arrivati a sera, che qualcun altro avrebbe agito. Tutto vero. E un bambino, tre sedili più in là, è ammutolito nel caldo. A te non è successo nulla. Ci penserai a lungo, a lungo.",
  "de": "ENDE (schlecht) — Am Ende bist du auf deinem Platz geblieben, deine Flasche zu. Du hast dir gesagt, es sei nicht deine Sache, Hilfe komme am Abend, ein anderer werde schon handeln. Alles wahr. Und ein kleines Kind, drei Sitze weiter, verstummte in der Hitze. Dir ist nichts passiert. Du wirst noch lange, lange daran denken.",
  "pt": "FIM (mau) — No fim, ficaste no teu lugar, a garrafa fechada. Disseste a ti mesmo que não era contigo, que a ajuda viria à noite, que outro agiria. Tudo verdade. E uma criança pequena, três bancos adiante, calou-se no calor. A ti não aconteceu nada. Vais pensar nisso durante muito, muito tempo.",
  "ru": "КОНЦОВКА (плохая) — В итоге ты остался на месте, с закрытой бутылкой. Ты твердил, что это не твоё дело, что помощь придёт к вечеру, что кто-нибудь другой уж точно вмешается. Всё это было правдой. А маленький ребёнок, тремя сиденьями дальше, затих от жары. С тобой ничего не случилось. Ты будешь думать об этом очень, очень долго.",
  "ar": "النهاية (سيّئة) — في النهاية بقيتَ في مقعدك، وقارورتك مغلقة. قلتَ لنفسك إن الأمر لا يعنيك، وإن النجدة ستأتي مساءً، وإن غيرك سيتصرّف حتماً. كلّ ذلك كان صحيحاً. وطفلٌ صغير، على بُعد ثلاثة مقاعد، صمت في الحرّ. لم يصبك مكروه. ستفكّر في ذلك وقتاً طويلاً طويلاً.",
  "zh": "结局（坏）——到头来，你留在座位上，水瓶盖得严严的。你对自己说这不关你的事，说救援到傍晚就会来，说总会有别人出手。这些都没错。而三排开外，一个小小的孩子，在热浪里渐渐没了声息。你毫发无伤。而这件事，你会想很久，很久。",
 },
}
for lg in LANGS:
    json.dump({str(n): G[n][lg] for n in sorted(G)},
              open(os.path.join(OUT, lg + ".json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("Wrote %d gist files (%d passages each) to content/gist/cool-of-evening/" % (len(LANGS), len(G)))
