#!/usr/bin/env python3
"""Full Spanish per-passage gist for High Water (book 7). Draft, pending native review."""
import json, os
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "high-water", "es.json")
G = {
1: "Es la noche más lluviosa en años. El río ha subido todo el día bajo una lluvia dura. En la calle baja el agua ya está en los umbrales. Entonces la vieja Nora Kettle cae en el escalón mojado y no puede levantarse. El muro de sacos de arena no está levantado, y el agua ya pasa el bordillo. Mantener el río fuera de las casas depende ahora de ti.",
2: "Reúnes lo que hay en el cobertizo: una pila de sacos, una pala, una bomba pequeña, una buena linterna. Fuera, la lluvia cae recta y el río sigue subiendo. El agua ya cruza el callejón. Tienes que decidir qué hacer, y rápido.",
3: "Pruebas el teléfono. Al fin llega la voz de Tom desde el astillero. Ninguna cuadrilla saldrá antes de la mañana, dice — no con el río así. Levanta el muro por el callejón, te dice, y sostenlo como puedas hasta que el agua baje.",
4: "Llegas a Nora al pie del escalón y la pones caliente y seca. Pero el río sigue subiendo, y el refugio no basta. Las casas necesitan el muro, levantado y sostenido. Necesitas sacos, un plan y la cabeza clara antes de salir.",
5: "Sales al callejón. La noche es enorme y llena de lluvia, y el agua negra brilla bajo la linterna. El río aprieta toda la calle baja como una mano. Luego, a lo lejos, al borde del agua, una lucecita se mueve donde nadie debería estar esta noche.",
6: "Te obligas a pensar. Podrías levantar el muro primero y preocuparte del resto después. O ir con Nora y los vecinos. O despertar a toda la calle para tener manos. Cada opción cuesta un tiempo que no tienes — y fuera, el río ya sube.",
8: "El frío se te asienta en el pecho. Piensas en las casas de la calle baja: todo lo que esta gente tiene. Si el muro sigue sin levantar mucho más, el río está dentro al amanecer. No es un miedo; es un hecho. Nadie más vendrá. Eres tú, esta noche, o nadie.",
9: "Tom abre de par en par el almacén del astillero y alza la linterna. Dentro: palés de sacos de arena, una bomba, rollos de cuerda, arpillera seca. «Coge lo que necesites, dice. Me quedo junto al teléfono y llamo a quien pueda.» Es un hombre firme, y una noche así lo demuestra.",
10: "Llamas por la hilera, y el viejo señor Hollis abre, pálido en la oscuridad. Sin luz, la linterna muerta, las manos temblando demasiado para alzar un saco. «No puedo contenerlo», dice. Tienes una larga noche por delante. Pero él está aquí, asustado, y es a ti a quien pide.",
11: "Vas derecho al callejón a apilar lo que puedas. Un saco, una palada de arena, una línea baja que sube aquí y allá. Pero el muro es fino y bajo. Sin sacos de verdad no aguantará una hora. No puedes levantar un poco y esperar.",
12: "Vas de puerta en puerta con las mismas palabras. Trae arena. Echa una mano en el muro. Ayúdame a sostener la línea. Algunos se apartan y cierran. Pero unos pocos se ponen el abrigo y salen bajo la lluvia. Esta noche, unos pocos bastan para empezar.",
13: "Te haces cargo tú mismo de los sacos y la bomba. El palé pesa, y cada saco cuenta ahora. Bien apilados, aguantan el río toda la noche; malgastados, el agua pasa las puertas antes del alba. Así que los aprietas contra ti y sales al callejón.",
14: "Coges solo una linterna y una pala. Para ver y mover arena. Pero no el muro en sí. Y no has apartado sacos de verdad. Harán falta sacos reales, y pronto. Si no, el callejón se inunda y el río gana.",
15: "El viejo Jack Reed conoce este río mejor que nadie. «No cruces la pasarela del azud, dice. Parece un atajo. No lo es — es ahogarse.» Te advierte también del comerciante. «Cuida tus sacos, sostén el muro — ese es todo el trabajo de esta noche.»",
16: "Levantas una línea de sacos ante la puerta del señor Hollis y lo acomodas con una manta. Poco a poco deja de temblar. «Dios te bendiga», dice apretándote la mano. Prometes volver a mirarlo. Luego sales de nuevo a la lluvia y al callejón que espera.",
17: "El muro va primero. El resto puede esperar un momento. ¿Pero cómo empezar? Podrías coger sacos de verdad del astillero primero. O ir derecho al callejón.",
18: "El trabajo te consume. Las piernas arden, el pecho jadea, la lluvia te pelea a cada paso. Estás al límite, y lo sabes. Si caes aquí, no queda nadie para sostener el muro. Así que ve despacio, con cuidado.",
19: "La calle despierta. La gente empieza a moverse. Un hombre saca una carretilla de arena. Una mujer arrastra un rollo de sacos. De puerta en puerta, toma forma un plan. Ya no estás solo. Y eso lo cambia todo.",
20: "Nadie se mueve. Las puertas siguen cerradas, los rostros se apartan de las ventanas. Tienen miedo, y la gente asustada calla. No puedes forzarlos. Así que sigues solo. Es más duro así. Pero el río no los esperará.",
21: "El muro cercano aguanta. Ahora las casas del fondo. Dos caminos para bajar. El callejón largo es seguro pero lento. La pasarela del azud es rápida, derecha. Pero con una crecida así, el agua puede matar.",
22: "Te tomas a pecho las palabras de Jack Reed. Cuida los sacos. Lejos de la pasarela. No creas al comerciante. Y sostén el muro ante todo. Consejo simple, y bueno. Solo falta seguirlo.",
23: "El buen gesto te afianza. Ayudar a alguien te afianza también, curiosamente. La cabeza más clara, las manos más seguras. Queda una noche dura. Pero te sientes capaz de afrontarla.",
24: "Un hombre está en el callejón, una linterna en el puño: el comerciante. Tiene bombas que vender y brazos que prestar, y sonríe con demasiada facilidad. «La calle no es cosa tuya esta noche, amigo», dice. Ya has visto a los de su clase.",
25: "Guías a una pequeña cuadrilla hacia el muro. Juntos os sentís más fuertes. Llevan arena, sacos, la bomba. «¡Por aquí!» gritas bajo la lluvia, y vienen. Sienta bien, en una hora tan dura.",
26: "El callejón está negro y anegado, la lluvia lo barre, sin refugio en ninguna parte. Pero el suelo es firme bajo tus pies, y lleva adonde hace falta. Así que sigues caminando, paso a paso.",
27: "La pasarela del azud reduciría a la mitad el camino, con las casas del fondo justo detrás. Pero las tablas son viejas y resbaladizas sobre una corriente rápida y honda. Jack Reed te dijo que no fueras — y no bromeaba.",
28: "Pones el pie en las tablas, y al momento suena mal. La corriente espera debajo, negra, honda, rápida. Cada paso es una apuesta — y estás en ella, solo. No hay vuelta una vez empezado.",
29: "La bomba no ceba. Tose, prende un segundo, y muere. Dura pérdida, con una crecida así. Habrá que llenar y apilar sacos a mano. O volver al astillero por otra bomba.",
30: "El callejón sigue a lo largo de la hilera, el agua más honda cada hora. Abajo, una casa oscura, el río ya en su puerta. Delante, la lluvia batiente parece empujarte. Y un poste indicador, medio caído en la crecida.",
31: "Un anciano ha caído en el callejón inundado y no puede levantarse. El frío ya lo gana. Pararte es perder un tiempo que no tienes. No hacerlo, y puede no aguantar la hora.",
32: "Una familia está atrapada en una casa inundada — sin luz, sin lámpara, un niño llorando. El agua sube a sus pies. Los padres te miran, cansados, sin esperanza. Tienes una lámpara y un abrigo. Poca cosa. Pero más que ellos.",
33: "Empujas por lo peor de la lluvia, cada paso un combate, el agua tirándote de las piernas. Hay opciones delante. Quizá el comerciante. Esa luz extraña al borde del agua. O ir derecho al muro.",
34: "Levantas al anciano y lo calientas como puedes. Se le llenan los ojos, y te pone una cuerda en las manos. «Tómala, dice, por tu molestia.» Poca cosa — pero dada de buena gana. La coges y sigues.",
35: "No puedes quedarte — pero tampoco dejarlos. Así que prometes mandar ayuda. «¡Aguantad! gritas. Subid arriba, juntos — no os olvido.» Y lo dices en serio. Luego te vuelves y sigues.",
36: "La calle levanta primero un buen tramo de muro — un banco de sacos firme en el peor hueco, que echa atrás el agua. Se agolpan a pasar sacos de mano en mano. No es todo el callejón. Pero es real, aguanta, y es un comienzo.",
37: "Casa a casa, la calle asustada se vuelve una calle que trabaja. Cada uno tiene su tarea: uno llena sacos, uno los lleva, uno vigila el agua. El miedo se vuelve acción. Y la acción vale más que esperar, siempre.",
38: "El largo esfuerzo roe tu voluntad. Una vocecita dice: para, entra, descansa — nadie te lo reprocharía, sería tan fácil. Pero piensas en las casas, el agua en sus puertas. Y apartas la voz. Todavía no. No mientras se puedan salvar.",
39: "Llegas al viejo poste, pero la crecida lo ha partido y medio tumbado. Apenas se lee. Un brazo señala el callejón. El otro, el borde del agua. ¿Por dónde? Tendrás que adivinar, y acertar.",
40: "El comerciante te dirige su amplia sonrisa fácil. «Trabajo mojado, este, dice. Tengo bombas que vender y brazos que prestar — y la calle no es cosa tuya esta noche, amigo.» Su linterna se balancea. Su sonrisa nunca llega a los ojos.",
41: "La oferta es un anzuelo, y lo sientes clavarse. Se inclina. «Esa calle ya está perdida, dice bajo. Deja que el río la lleve — y hay una parte para ti.» Es cruel decirlo. Y está hecho para trabajar tu miedo.",
42: "Le das la espalda y lo dejas a su comercio helado. Da gusto marcharse. Te llama, pero no te vuelves. Los de su clase siempre encuentran a alguien, al final. Pero no a ti, no esta noche.",
43: "Coges su bomba y su trato. Las manos se cierran sobre ellos, y algo en ti ya lo sabe. Su sonrisa se ensancha. «Sabio», dice. Pero no se siente sabio. Se siente como una puerta que se cierra despacio.",
44: "Le preguntas sin rodeos: qué quiere de verdad, y por qué debería hundirse la calle. Sonríe y mira a lo lejos. «Las casas salen baratas tras una inundación, dice. Una noche así es un favor — para un comprador como yo.»",
45: "Llevas sus sacos al muro. Pero al apilarlos, la arena se escapa enseguida. La tela está rota y podrida — no retienen nada. La línea se hunde, baja e inútil.",
46: "Abres un saco, y se te cae el alma. La tela está rota, podrida. Estos sacos nunca aguantarán el agua. Pagaste buen dinero, y no valen nada. La duda de tus tripas tenía razón.",
47: "Lo buscas, pero la furgoneta del comerciante ya se ha ido. Nunca te ayudaba. Esperaba la inundación, las casas arruinadas, el terreno barato después. Te engañaron, sin más.",
48: "Se ha ido, el callejón vacío — solo la lluvia ahora, la oscuridad, y lo que le diste por nada. Aprendiste una dura lección. Y la pagaste demasiado cara. Sigues con menos de lo que empezaste.",
49: "La gente asustada le pone el dinero en las manos. Puños llenos de monedas, voces rogando una bomba. Él lo toma despacio, con la misma sonrisa. Elige a quién ayudar según quién paga más.",
50: "Lejos en el puente, las casas del fondo parecen más cerca — ¿o no? Ya no estás seguro. La oscuridad engaña, y tus ojos cansados también. Y estás lejos de ambas orillas.",
51: "Las tablas, la oscuridad, la corriente honda debajo — y una tabla cruje bajo tu pie. Es el momento. Caer al agua rápida. O echarte atrás del hueco, mientras aún puedes.",
52: "Llegas al fin a las casas del fondo, empapado, temblando, las manos en carne viva — pero cruzado. No sabes cómo, pero lo lograste. Ahora hay que decidir: seguir, agotado, o enfrentar lo que perdiste en el agua.",
53: "Te echas atrás del hueco mientras aún puedes — la decisión dura, la correcta. Gateas el último tramo y alcanzas la orilla, sacudido y lento. La noche no está perdida. Pero te costó un tiempo que echarás en falta.",
54: "Levantas una línea baja de sacos en su puerta y achicas lo peor del agua con un cubo. Contiene un poco el río. Pero no hay lámpara que dejarles, y la noche dista de acabar.",
55: "Les das tu abrigo y tu lámpara, y la familia se acurruca arriba junto a la pequeña llama, el alivio en sus rostros. El niño deja al fin de llorar. «Gracias», dice la madre — y luego te señala una luz, al borde del agua.",
56: "Sin abrigo, el frío y el agua te encuentran rápido — los dientes castañetean, los dedos se agarrotan. Lo diste para ayudar, y lo harías de nuevo. Pero al río no le importa. Solo sube.",
57: "Un desconocido te hace señas a un portal iluminado. «Solo un minuto, dice. Fuera de la lluvia — recobra aliento.» Es cálido y seco, y todo el cuerpo te ruega quedarte. Pero un minuto así resbala pronto a una hora.",
58: "Empujas bajo la lluvia, calado hasta los huesos, el viento peleando cada paso, los ojos ardiendo de agua. Cada paso es una pequeña batalla. Pero los encadenas, uno tras otro, hacia las casas.",
60: "Alguien señala el borde del agua: una figura ha salido por allí, sola, en la oscuridad. Allá solo hay la crecida y la corriente honda y rápida. Si nadie va tras ella, puede no volver.",
61: "Los encuentras al borde del agua, empapados y perdidos, el frío desgarrándolos. No parecen reconocer tu cara. Los agarras firme del brazo. «Ven conmigo, dices. Ya pasó. Te tengo.»",
62: "No puedes hacerlo todo, y el muro te necesita más. Así que mandas a otro tras ellos y sigues. Te pesa — pero esta noche hay que elegir, una y otra vez.",
63: "Los llevas a salvo a las casas, donde su familia grita de alivio. Te envuelven en un abrigo seco y te hacen sitio junto al fuego. «Gracias», repiten. Pero el callejón espera, y no puedes quedarte.",
64: "Miras toda la calle baja — oscura, subiendo. La crecida brilla, negra, entre las casas. No hay luz en ninguna parte salvo al borde del agua. Toda la calle parece contener el aliento y esperar el alba.",
65: "La crecida sube a su peor momento. El agua llega a su punto más alto, y el aliento te sale corto en el frío húmedo. Cuesta pensar, moverse, hasta importarte. Es la hora más dura de toda la noche.",
67: "Tom te pone en las manos la última buena linterna. «Para el callejón, dice. Ve — yo me quedo al teléfono.» Su cara está gris de preocupación. Es la ayuda que puede dar esta noche, y la da de todo corazón.",
68: "En el astillero, la gente se abalanza sobre los sacos — suben las voces, agarran, el miedo cunde rápido. Un empujón más y es pelea. Puedes intentar calmarlos y repartir con justicia. O coger los tuyos y marchar.",
69: "Una casa cerrada hace tiempo te envuelve — humedad, silencio, frío viejo, un sitio donde nada parece vivo. Entonces lo oyes: una respiración, débil y cercana, desde el fondo. Alguien vive aquí, después de todo.",
70: "Lejos, al borde del agua, una lucecita se alza y se apaga. Donde nadie debería estar esta noche — aparece, se va, reaparece. Nadie puede explicarla. Y algo en ti quiere ir a responderle.",
71: "Llegas al borde del agua y llamas en la oscuridad. Solo responde la lluvia. Luego la ves: una forma pequeña, junto a la crecida, medio en el agua oscura. Alguien está fuera, después de todo. Y apenas se mueve.",
72: "Los alcanzas, y el corazón te da un vuelco. Es un niño — Wren — acurrucado junto a la crecida, empapado, apenas consciente. El frío lo tiene. No hay tiempo de esperar. Hay que actuar ya.",
73: "Vuelves a llamar en la oscuridad. Un instante, nada. Luego una voz fina regresa, rota por el frío: «¡Aquí! ¡Por aquí!» Alguien está fuera, junto al agua, y necesita ayuda. Y no suena nada fuerte.",
74: "Sacas a Wren del agua y lo envuelves en tu abrigo. Despacio vuelve en sí, agarrado a tu brazo. «El muro, susurra. Sostén el muro. Las casas...» Aun así, empapado, piensa en la calle.",
75: "Te vuelves para correr a por ayuda — y te paras en seco. No hay ayuda fuera, no hasta la mañana. Ni cuadrilla, ni nadie. Eres tú o nadie, y Wren lo sabe también. Sus ojos asustados te siguen en la oscuridad.",
76: "Wren alza la vista, la mirada más clara. «La anciana, Nora — es mi abuela, dice. No nos hablamos. No desde que mi padre y ella riñeron. Es una historia larga y triste.» Y oyes cuán larga es.",
77: "Decides reunirlos antes de que acabe la noche — Wren y la vieja Nora, tras todos estos años. Poca cosa, al lado del muro y la crecida. Pero no es nada. Algunas puertas cerradas aún pueden abrirse.",
78: "La forma pequeña no se mueve, y la crecida repta hacia ella, fría y paciente. Y aun así alguien vino hasta aquí, en la oscuridad, solo. No puedes dejarlo. Hay que acercarse y saber quién es.",
79: "Te acercas, y los reconoces al instante. Es Wren — el nieto de la vieja Nora, no visto aquí en años, desde que la familia riñó. Luego un débil sonido sube del agua, a tus pies. Te apresuras.",
80: "El comerciante vuelve una última vez, su linterna balanceándose. «¿Aún peleando? dice. Deja que el río se lo lleve. Última oportunidad de estar del lado ganador, amigo.» La misma sonrisa fácil. La misma vieja mentira.",
90: "Vuelves al callejón, empapado, lo peor de la crecida pesando sobre todo. Junto al escalón, Nora yace gris e inmóvil. Por el callejón, el muro está bajo y empieza a filtrar. Es la hora en que todo se decide.",
91: "Llegas al muro: la línea baja, el fondo filtrando fuerte. Hacia las casas del fondo, el río está a punto de pasar por encima para siempre. Hay que subir el muro, firme y alto — y ahora mismo, rápido.",
92: "Entonces la ayuda te alcanza al fin — más brazos, más sacos, gente firme que conoce el trabajo. Ya no estás solo; otros comparten el peso. Es como dejar algo pesado que cargaste demasiado tiempo.",
93: "Ahora sostienes el muro — y lo que puedas hacer depende de lo que trajiste. Con sacos de verdad, hay con qué trabajar. Sin ellos, hay que pelear cada palmo a mano. En cualquier caso, la noche dista de acabar.",
94: "Bajas a ver a Nora, y sus ojos se abren un poco. Hay miedo en ellos — luego, al verte, un poco menos. «Lo sostuviste», susurra. «Así es, dices suave. Descansa ahora.»",
95: "Los buenos sacos lo logran. Subes la línea y la apisonas bien, y por el callejón el muro se alza firme y fuerte. El río se lanza contra él y queda contenido. Esto, piensas, es para lo que fue toda la noche.",
96: "Sin sacos de verdad, peleas cada palmo a mano. Metes barro y arena en los huecos, sosteniendo la línea con tu cuerpo, tu aliento, tu voluntad. Puede que no baste. Pero no la soltarás sin pelear.",
97: "El muro está bajo y filtra, y temes que sostenerlo solo no baste. Hiciste todo lo posible con lo que tenías. Pero puede no aguantar. Necesitas más — más sacos, más manos, o ambos.",
98: "Miras fuera y la ves. Lejos, al borde del agua, una luz prende y cae — donde nadie debería estar, mostrándose y escondiéndose. Te tira del ojo. Y de algo más hondo.",
99: "La luz al borde del agua reaparece — donde todos juran que nadie estaría. Pero una luz supone una mano, y una mano supone una persona. Una persona, fuera, sola, en una crecida así.",
100: "Viene entonces la larga vela: alimentas el muro, mantienes a Nora caliente, vigilas el agua hora tras hora. Nada emocionante — solo trabajo constante, duro, cuidadoso. Pero es todo el trabajo de esta noche, y es tuyo.",
101: "Y entonces, al fin, cambia. El río deja de subir. Aguanta, luego baja un palmo, luego otro. El cielo grisea sobre los tejados, y llega la primera luz. La crecida pierde. Casi has sostenido toda la noche.",
102: "Es la hora más dura, justo antes del quiebre. El río no ha bajado; los brazos duelen, los ojos arden. Pero sientes la noche empezar a cambiar, en algún sitio debajo. Aguanta un poco más.",
103: "Por el callejón los ves — linternas, figuras oscuras, muros de sacos conteniendo la crecida. Otra gente, fuera bajo la lluvia como tú. La calle también pasó esta noche. Nunca estuviste tan solo como sentías.",
104: "Al fin, la ayuda sube por el callejón — un camión, más brazos, más sacos, ayuda de verdad a buena marcha. Te apoyas en el muro y la miras venir, las piernas temblando. Pero lo peor de la noche quedó atrás.",
105: "El alba sube sobre la calle, la luz se vuelve gris, luego pálida y limpia. La lluvia cede al fin, y el río baja por la orilla. Las casas siguen en pie, secas por dentro. Lo peor pasó al fin.",
106: "Entonces llega — el primer pájaro de la mañana, cantando sobre los tejados mojados como si no hubiera habido crecida. Tras la noche que has tenido, parece casi absurdo. Y es hermoso, y te paras a escuchar.",
107: "Desde el callejón vigilas el borde del agua, donde una luz se alza, cae y crece despacio. Algo viene al fin, aún demasiado lejos para distinguirlo. Pero una luz quiere decir alguien — y alguien vale mucho más que nadie esta noche.",
110: "Llega al fin la primera luz, y la noche hace sus cuentas. Todo lo que hiciste fuera, bajo la lluvia, vuelve a ti — algo de lo que estar orgulloso, y algo menos. Veamos, pues, en qué quedó todo.",
111: "La noche se suma — no con un gran acto, sino con mil pequeños. Lo que sostuviste, lo que rechazaste, por quién saliste bajo la lluvia. Todo cuenta, al final. Todo hizo la noche lo que fue.",
112: "Queda más que pesar; la noche guardó otras cosas. Un desconocido por quien te paraste. Un abrigo y una lámpara dados con mano abierta. Pequeñas decisiones, bajo la lluvia, cuando habría sido más fácil pasar de largo.",
113: "¿Y qué te deja la noche? Quizá no una victoria limpia. Quizá solo esto: que saliste, que lo intentaste. Cuando estaba oscuro, mojado y era fácil quedarse dentro, no lo hiciste. Eso cuenta.",
114: "Pero no toda noche acaba bien. Algunas decisiones cuestan más de lo que creías; algunas puertas, una vez abiertas, no se cierran. Es el final duro de la noche — donde lo peor vuelve a ti.",
120: "Sostuviste el muro toda la noche por el callejón. A la primera luz, el río baja, la lluvia cesa, y las casas — toda una hilera de hogares — resisten secas. Todo resistió porque te quedaste bajo la lluvia y no dejaste ceder el muro. Eso es todo, y basta.",
121: "Respondiste a la luz que nadie podía explicar. Encontraste a Wren, perdido y helado al borde del agua, y lo calentaste justo a tiempo. Y se salvó más de una vida. Wren es el nieto de Nora. Una puerta cerrada por años se abre de nuevo, en el gris del alba.",
122: "No hubo un solo acto de valentía — hubo algo mejor. Volviste una calle dormida en gente con sacos en cada puerta, y juntos pasaron la noche. Nadie quedó solo en ella. Eso, al fin, es lo que puede ser una calle.",
123: "Rechazaste el engaño — viste el truco del comerciante y le diste la espalda. Mantuviste la cabeza y salvaste lo que pudiste por medios honrados. No fue una noche perfecta; no lo salvaste todo. Pero fue limpio, y limpio basta.",
124: "No salvaste toda la calle. Pero el vecino por quien te paraste vuelve ahora. Te ayuda a salvar las casas cercanas y a calentar a Nora. No es la victoria plena. Pero una bondad, resulta, siempre vuelve.",
125: "Diste tu abrigo y tu lámpara a quienes tenían menos, y acabas la noche helado tú mismo. No lo salvaste todo. Pero no estás solo, ni nadie de los que encontraste. Algo ha cambiado en la calle. Es un comienzo, no un rescate.",
126: "Pasas por los pelos. El río cambia al fin, y un alba escasa halla la mayoría de las casas aún secas. No es un triunfo, y nadie lo cantará. Pero pasaste la noche — y al fin, eso ya es un alivio.",
127: "No lo salvaste todo. Pero la calle te vio al borde del agua cuando otros seguían en la cama — te vio intentarlo, en la peor noche del año. Desde esta noche, eres alguien que este lugar conoce. Y eso no es nada.",
128: "Tomaste el trato del comerciante, y por la mañana la calle ya no es de Nora para salvarla. El río hizo el resto. El cheque en tu bolsillo está frío, y también el agua en la puerta por la mañana. No olvidarás pronto cómo lo ganaste.",
129: "La pasarela del azud era una trampa, como advirtió Jack Reed. La cruzaste en la oscuridad, y se llevó toda la noche. Sales a rastras, empapado y temblando, y alcanzas las casas del fondo demasiado tarde. La corriente te costó todo lo que el atajo prometía.",
130: "Pasaste la noche en lo que no debías, y el muro quedó bajo demasiado tiempo. Al alba, el río está por todas las puertas, y la calle está arruinada. Saliste bajo la lluvia. Pero no sostuviste el muro cuando contaba.",
131: "Al final, te quedaste dentro, caliente y a salvo. Te dijiste que el río era demasiado alto, que no era cosa tuya, que la ayuda vendría al alba. Todo era cierto. Y toda la noche, fuera, el muro quedó sin levantar. Nada malo te pasó. Pensarás en eso mucho, mucho tiempo.",
}
def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    data = json.load(open(OUT, encoding="utf-8")) if os.path.exists(OUT) else {}
    a = 0
    for nid, t in G.items():
        k = str(nid)
        if k not in data: a += 1
        data[k] = t
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print("high-water/es.json: %d (+%d)" % (len(data), a))
if __name__ == "__main__":
    main()
