#!/usr/bin/env python3
"""Full Spanish per-passage gist for The Refuge (book 8). Draft, pending native review."""
import json, os
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "the-refuge", "es.json")
G = {
1: "Es la peor noche del invierno, y la ventisca cae rápida con la oscuridad. La nieve pasa veloz ante la única ventana, y la montaña se pierde en el blanco. Entonces la vieja Marta, que lleva treinta inviernos cuidando este refugio, cae de la escalera del altillo y no puede levantarse. La estufa está baja, la lámpara apagada, y ningún equipo puede subir antes de la mañana. Sostener el refugio depende ahora de ti.",
2: "Reúnes lo que hay en la cabaña: un bidón de queroseno, cerillas, una buena lámpara de tormenta, una brazada de leña seca. Fuera, el viento aúlla y el frío entra recto bajo la puerta. La nieve ya se cuela blanca por debajo. Tienes que decidir qué hacer, y rápido.",
3: "Pruebas la radio. Chisporrotea, y al fin llega la voz de Kerr desde el puesto del valle. Ningún equipo puede subir antes de la mañana, dice — no en una ventisca así. Mantén la estufa encendida y la lámpara en la ventana, te dice, y aguanta si puedes.",
4: "Llegas a Marta al pie de la escalera y la pones caliente y cómoda. Pero la cabaña sigue fría y la ventana oscura. El refugio solo no basta. Quien quede atrapado ahí fuera necesita la lámpara encendida y la estufa en marcha. Necesitas combustible, un plan y la cabeza clara.",
5: "Sales a la tormenta. El viento casi te tira, y la nieve pasa plana y blanca. El frío aprieta toda la montaña como una mano. Luego, muy abajo en la ladera, lo ves: una lucecita que se mueve, donde nadie debería estar esta noche.",
6: "Te obligas a pensar. Encender la estufa y la lámpara primero y preocuparte del resto después. O ir con Marta y los caminantes del dormitorio. O despertar al valle para tener manos. Cada opción cuesta un tiempo que no tienes — y fuera, el frío ya trabaja a quien esté atrapado.",
8: "El frío se te asienta en el pecho como un peso. Piensas en la gente de ahí fuera: un caminante perdido en la ladera, y la cabaña la única calidez en kilómetros. Si la ventana sigue oscura mucho más, el frío los toma al alba. No es un miedo; es un hecho. Nadie más vendrá. Eres tú, esta noche, o nadie.",
9: "Doune abre de par en par el almacén de combustible y alza la lámpara. Dentro hay un bidón de queroseno, cerillas, haces de leña seca y arpillera. «Coge lo que necesites, dice. Me quedo junto a la radio y llamo a quien pueda.» Es un hombre firme, y una noche así lo demuestra.",
10: "Llamas por las literas, y el viejo Breck abre, pálido de frío. Su estufita se ha apagado, se le acabaron las cerillas, y las manos le tiemblan demasiado para encender una. «No consigo prenderla», dice. Tienes una larga noche dura por delante. Pero él está aquí, asustado, y es a ti a quien pide.",
11: "Vas derecho a la estufa y enciendes lo que puedes. Una cerilla, una llamarada de astillas, una llama baja prendiendo en la rejilla. Pero el fuego es flaco y la lámpara parpadea. Sin combustible de verdad no aguantarán una hora. No puedes solo encenderlos y esperar que la noche sea amable.",
12: "Vas de puerta en puerta con las mismas palabras. Trae leña para la estufa. Echa una mano. Ayúdame a tener la lámpara en la ventana. Algunos se apartan y cierran. Pero unos pocos se ponen el abrigo y salen al frío. Esta noche, unos pocos bastan para empezar.",
13: "Te haces cargo tú mismo del combustible y la leña seca. El bidón pesa, y cada gota de queroseno cuenta ahora. Bien usado, mantiene la estufa y la lámpara toda la noche; malgastado, la cabaña queda fría y oscura antes del alba. Así que lo aprietas contra ti y te pones a trabajar.",
14: "Coges solo una lámpara de tormenta y unas astillas. Para ver y arrancar una llama. Pero no la estufa en sí, y no has apartado combustible de verdad. Harán falta, y pronto. Si no, la ventana sigue oscura y el frío gana.",
15: "El viejo Doune ha recorrido esta montaña en la oscuridad más que nadie vivo. «Lejos de la cornisa sobre el circo, dice. Parece un atajo. No lo es — es una larga caída.» Te advierte también de Vane, ese hombre sonriente de la empresa. «Cuida tu combustible, sostén la lámpara — ese es todo el trabajo de esta noche.»",
16: "Haces que la estufa tire y acomodas a Breck a su lado con una manta. Poco a poco cede su temblor. «Dios te bendiga», dice apretándote fuerte la mano. Prometes volver a mirarlo antes de la mañana. Luego sales de nuevo al frío y a la ventana oscura.",
17: "Mantener la cabaña caliente y encendida va primero. El resto puede esperar un momento. Pero ¿cómo? Podrías coger combustible de verdad del almacén primero. O ir derecho a la estufa y la lámpara.",
18: "El trabajo te consume. Las piernas arden, el pecho jadea, y el viento te pelea a cada paso. Estás al límite, y lo sabes. Si caes aquí, no queda nadie para sostener la cabaña. Así que ve despacio, con cuidado.",
19: "El valle despierta, y la gente empieza a moverse. Un hombre se echa al hombro un bidón de combustible. Una mujer saca leña seca y linternas frontales. De puerta en puerta, toma forma un plan. Ya no estás solo. Y eso lo cambia todo.",
20: "Nadie se mueve. Las puertas siguen cerradas, los rostros se apartan de las ventanas. Tienen miedo, y la gente asustada calla. No puedes forzarlos a salir a esto. Así que sigues solo. Es más duro así. Pero la gente de ahí fuera no puede esperarlos.",
21: "La estufa tira y la lámpara está en la ventana. Ahora el almacén lejano y el depósito de combustible. Dos caminos para llegar. El largo sendero que rodea el circo es seguro pero lento. La cornisa, derecha, es rápida. Pero en una noche así, podría ceder.",
22: "Te tomas a pecho las palabras del viejo Doune. Cuida el combustible. Lejos de la cornisa. No confíes en Vane. Y sostén la lámpara en la ventana ante todo. Consejo simple, y bueno. Solo falta seguirlo.",
23: "El buen gesto te afianza. Ayudar a alguien te afianza también, curiosamente. La cabeza más clara, las manos más seguras. Queda una noche dura. Pero te sientes capaz de afrontarla.",
24: "Un hombre surge de la nieve, un farol en el puño — Vane. Tiene combustible que vender y brazos que prestar, y sonríe con demasiada facilidad. «El refugio no es cosa tuya esta noche, amigo», dice. Ya has visto a los de su clase.",
25: "Guías a una pequeña cuadrilla hacia la cabaña. Juntos os sentís más fuertes. Llevan combustible, leña y antorchas. «¡Por aquí!» gritas al viento, y vienen. Sienta bien, en una hora tan dura.",
26: "El sendero está negro y duro, el viento lo barre, sin refugio en ninguna parte. Pero es firme bajo tus pies, y lleva adonde hace falta. Así que sigues caminando, paso a paso.",
27: "La cornisa reduciría a la mitad el camino, con el almacén justo detrás. Pero el borde es fino y la nieve floja sobre una larga caída mortal. Doune te dijo que no fueras — y no bromeaba.",
28: "Pones el pie en la cornisa, y al momento suena mal. El vacío espera debajo, negro, lejano, helado. Cada paso es una apuesta — y estás en ella, solo. No hay vuelta una vez empezado.",
29: "La leña está húmeda y no prende. Solo da una llama baja y humeante. Poco útil con un frío así. Tendrás que arreglártelas. O volver al almacén por leña seca.",
30: "El sendero sigue por la ladera, el frío más hondo cada hora. Abajo, un abrigo oscuro, sin fuego. Delante, el aire quieto y duro parece empujarte. Y hay un poste indicador, medio enterrado en la nieve helada.",
31: "Un caminante ha caído en la nieve y no puede levantarse. El frío ya lo gana. Pararte es perder un tiempo que no tienes. No hacerlo, y puede no aguantar la hora.",
32: "Un grupo está encerrado en un abrigo helado — sin fuego, sin lámpara, un niño llorando en la oscuridad. Los adultos te miran, cansados, sin esperanza. Tienes una lámpara y un abrigo. Poca cosa, pero más que ellos.",
33: "Empujas por lo peor del frío, cada paso un combate, la nieve mordiéndote la cara. Hay opciones delante. Quizá Vane. Esa luz extraña en la ladera. O ir derecho a la cabaña.",
34: "Levantas al caminante y lo calientas como puedes. Se le llenan los ojos. Te pone un par de manoplas secas en las manos. «Tómalas, dice, por tu molestia.» Poca cosa — pero dada de buena gana. Las coges y sigues.",
35: "No puedes quedarte — pero tampoco dejarlos. Así que prometes mandar ayuda. «¡Aguantad! gritas. Quedaos calientes, juntos — no os olvido.» Y lo dices en serio. Luego te vuelves y sigues.",
36: "El valle enciende una gran hoguera de señal en la colina — un bidón de leña ardiendo, que lanza luz y calor a la tormenta. Se agolpan a su lado, los viejos y los débiles en lo mejor. No es la noche ganada. Pero es calor de verdad, y un comienzo.",
37: "Abrigo a abrigo, el valle asustado se vuelve uno que trabaja. Cada uno tiene su tarea: uno cuida el fuego, uno lleva leña, uno vigila la ladera. El miedo se vuelve acción. Y la acción vale más que esperar, siempre.",
38: "El largo frío roe tu voluntad. Una vocecita dice: para, entra, descansa — nadie te lo reprocharía, sería tan fácil. Pero piensas en la gente de la ladera. Y apartas la voz. Todavía no. No mientras se les pueda alcanzar.",
39: "Llegas al viejo poste, pero la nieve lo ha enterrado y medio tumbado. Apenas se lee. Un brazo señala el sendero. El otro, la ladera. ¿Por dónde? Tendrás que adivinar, y acertar.",
40: "Vane te dirige su amplia sonrisa fácil. «Trabajo frío, este, dice. Tengo combustible que vender y brazos que prestar — y el refugio no es cosa tuya esta noche, amigo.» Su farol se balancea. Su sonrisa nunca llega a los ojos.",
41: "La oferta es un anzuelo, y lo sientes clavarse. Se inclina. «Ese refugio ya está perdido, dice bajo. Deja que el frío lo lleve — y hay una parte para ti.» Es cruel decirlo. Y está hecho para trabajar tu miedo.",
42: "Le das la espalda y lo dejas a su comercio helado. Da gusto marcharse. Te llama, pero no te vuelves. Los de su clase siempre encuentran a alguien, al final. Pero no a ti, no esta noche.",
43: "Coges su combustible y su trato. Las manos se cierran sobre ellos, y algo en ti ya lo sabe. Su sonrisa se ensancha. «Sabio», dice. Pero no se siente sabio. Se siente como una puerta que se cierra despacio.",
44: "Le preguntas sin rodeos: qué quiere de verdad, y por qué debería caer el refugio. Sonríe y mira hacia la nieve. «La tierra sale barata tras un mal año, dice. Una noche así es un favor — para un comprador como yo.»",
45: "Llevas su combustible a la estufa. Pero al verterlo, la llama se ahoga y escupe. Es aguado, cortado con agua — no alimenta el fuego. La llama se hunde, baja, parda, inútil.",
46: "Abres el bidón, y el olor te golpea — ralo, agrio, cortado con agua. Este combustible nunca alimentará una llama. Pagaste buen dinero, y no vale nada. La duda de tus tripas tenía razón.",
47: "Lo buscas, pero el farol de Vane ya se ha ido hacia la nieve. Nunca te ayudaba. Esperaba la tormenta, la noche perdida, la tierra barata después. Te engañaron, sin más.",
48: "Se ha ido, y la ladera está vacía — solo el frío ahora, la oscuridad, y lo que le diste por nada. Aprendiste una dura lección. Y la pagaste demasiado cara. Sigues con menos de lo que empezaste.",
49: "La gente asustada le pone el dinero en las manos. Puños llenos de billetes, voces rogando combustible. Él lo toma despacio, con la misma sonrisa. Elige a quién ayudar según quién paga más.",
50: "Lejos en la cornisa, el otro lado parece más cerca — ¿o no? Ya no estás seguro. La oscuridad engaña, y tus ojos cansados también. Y estás lejos de ambos bordes.",
51: "La cornisa, la oscuridad, la larga caída debajo — y una grieta corre bajo tu pie. Es el momento. Caer con la nieve a la oscuridad. O echarte atrás de la grieta, mientras aún puedes.",
52: "Llegas al otro lado al fin, empapado, temblando, las manos en carne viva — pero cruzado. No sabes cómo, pero lo lograste. Ahora hay que decidir: seguir, agotado, o enfrentar lo que perdiste en la cornisa.",
53: "Te echas atrás de la grieta mientras aún puedes — la decisión dura, la correcta. Gateas el último tramo y alcanzas tierra firme, sacudido y lento. La noche no está perdida. Pero te costó un tiempo que echarás en falta.",
54: "Intentas prender su estufa y bloqueas lo peor de las corrientes de aire con mochilas y una tabla vieja. Contiene un poco el frío. Pero no hay lámpara que dejarles, y la noche dista de acabar.",
55: "Les das tu abrigo y tu lámpara, y el grupo se acurruca junto a la pequeña llama, el alivio en los rostros. El niño deja al fin de llorar. «Gracias», dice la madre — y luego te señala una luz, en la ladera.",
56: "Sin abrigo, el frío y el agua te encuentran rápido — los dientes castañetean, los dedos se agarrotan. Lo diste para ayudar, y lo harías de nuevo. Pero a la tormenta no le importa. Solo muerde más fuerte.",
57: "Un desconocido te hace señas a un portal iluminado. «Solo un minuto, dice. Fuera del frío — recobra aliento.» Es cálido y seco, y todo el cuerpo te ruega quedarte. Pero un minuto así resbala pronto a una hora.",
58: "Empujas en la tormenta, calado hasta los huesos. El frío pelea cada paso. Los ojos te lloran y escuecen. Cada paso es una pequeña batalla. Pero los encadenas, uno tras otro, hacia la cabaña.",
60: "Alguien señala la ladera: un caminante ha salido por allí, solo, al frío y la oscuridad. Allá solo hay nieve y la larga caída mortal. Si nadie va tras él, puede no volver.",
61: "Lo encuentras en la ladera, medio helado y perdido, el frío desgarrándolo. No parece reconocer tu cara. Lo agarras firme del brazo. «Ven conmigo, dices. Ya pasó. Te tengo.»",
62: "No puedes hacerlo todo, y el refugio te necesita más. Así que mandas a otro tras él y sigues. Te pesa — pero esta noche hay que elegir, una y otra vez.",
63: "Lo llevas a salvo al abrigo, donde sus amigos gritan de alivio. Te envuelven en un abrigo seco y te hacen sitio junto a la estufa. «Gracias», repiten. Pero la cabaña espera, y no puedes quedarte.",
64: "Miras toda la montaña — toda blanca, toda quieta. La nieve yace pálida y honda en la oscuridad. No hay luz en ninguna parte salvo en la ladera. Toda la montaña parece contener el aliento y esperar el alba.",
65: "El frío cae a su peor momento. El barómetro baja a su punto más hondo, y el aliento te queda blanco en el aire quieto. Cuesta pensar, moverse, importarte. Es la hora más dura de toda la noche.",
67: "El viejo Doune te pone la última lámpara seca en las manos. «Para la ventana, dice. Ve — yo me quedo aquí con Marta y la radio.» Su cara está gris de preocupación. Es la ayuda que puede dar esta noche, y la da de todo corazón.",
68: "En el almacén, la gente se abalanza sobre los bidones — suben las voces, agarran, el miedo cunde rápido. Un empujón más y es pelea. Puedes intentar calmarlos y repartir con justicia. O coger el tuyo y marchar.",
69: "Un vivac ahogado de nieve te envuelve — blanco, silencioso, frío profundo, un sitio donde nada parece vivo. Entonces lo oyes: una respiración, débil y cercana, bajo la nieve. Alguien vive aquí, después de todo.",
70: "Lejos en la ladera, una lucecita se alza y se apaga. Donde nadie debería estar esta noche — aparece, se va, reaparece. Nadie puede explicarla. Y algo en ti quiere ir a responderle.",
71: "Sales a la ladera y llamas en la oscuridad. Solo responde el viento. Luego la ves: una forma pequeña, en la nieve, medio oculta en el blanco. Alguien está fuera, después de todo. Y apenas se mueve.",
72: "Lo alcanzas, y el corazón te da un vuelco. Es un joven caminante — Rowan — acurrucado en la nieve, medio helado, apenas consciente. El frío lo tiene. No hay tiempo de esperar. Hay que actuar ya.",
73: "Vuelves a llamar en la oscuridad, y un instante, nada. Luego una voz fina regresa, rota por el frío: «¡Aquí! ¡Por aquí!» Alguien está en la ladera, y necesita ayuda. Y no suena nada fuerte.",
74: "Sacas a Rowan de la nieve y lo envuelves en tu abrigo. Despacio vuelve en sí, agarrado a tu brazo. «La lámpara, susurra. Mantén la lámpara en la ventana...» Aun así, medio helado, piensa en la cabaña.",
75: "Te vuelves para correr a por ayuda — y te paras en seco. No hay ayuda fuera, no hasta la mañana. Ni equipo, ni valle, ni nadie. Eres tú o nadie, y Rowan lo sabe también. Sus ojos asustados te siguen en la oscuridad.",
76: "Rowan alza la vista, la mirada más clara. «La guarda, Marta — es mi abuela, dice. No nos hablamos. No desde que mi padre y ella riñeron. Es una historia larga y triste.» Y oyes cuán larga es.",
77: "Decides reunirlos antes de que acabe la noche — Rowan y la vieja Marta, tras todos estos años. Poca cosa, al lado de la tormenta y el frío. Pero no es nada. Algunas puertas cerradas aún pueden abrirse.",
78: "La forma pequeña no se mueve, y el frío la trabaja, lento y paciente. Y aun así alguien vino hasta aquí, a la oscuridad, solo. No puedes dejarlo ahí. Hay que acercarse y saber quién es.",
79: "Te acercas, y lo reconoces al instante. Es Rowan — el nieto de la vieja Marta, no visto aquí en años, desde que la familia riñó. Luego un débil sonido sube de la nieve, a tus pies. Te apresuras.",
80: "Vane vuelve una última vez, su farol balanceándose. «¿Aún peleando? dice. Deja que el frío se lo lleve. Última oportunidad de estar del lado ganador, amigo.» La misma sonrisa fácil. La misma vieja mentira.",
90: "Vuelves al refugio, helado, el peor frío de la noche pesando sobre todo. Junto a la escalera, Marta yace gris e inmóvil. La estufa arde baja, la ventana apagada. Es la hora en que todo se decide.",
91: "Llegas a la estufa: la llama baja, la ventana oscura. En la ladera, el frío está a punto de tomar a quien siga fuera. Hay que poner la estufa a pleno y la lámpara brillante otra vez — y ahora mismo, rápido.",
92: "Entonces la ayuda te alcanza al fin — más brazos, más combustible, gente firme que conoce el trabajo. Ya no estás solo; otros comparten el peso. Es como dejar algo pesado que cargaste demasiado tiempo.",
93: "Ahora mantienes la cabaña caliente y encendida — y lo que puedas hacer depende de lo que trajiste. Con combustible de verdad, hay con qué trabajar. Sin él, hay que sacar cada último parpadeo de llama. En cualquier caso, la noche dista de acabar.",
94: "Vas a ver a Marta, y sus ojos se abren un poco. Hay miedo en ellos — luego, al verte, un poco menos. «Lo mantuviste», susurra. «Así es, dices suave. Descansa ahora.»",
95: "El combustible lo logra. Alimentas la estufa y recortas la mecha, y la llama sube plena y dorada. La ventana arde brillante contra la tormenta. Calor que echa atrás todo ese frío. Esto, piensas, es para lo que fue toda la dura noche.",
96: "Sin combustible de verdad que verter, sacas la poca llama que hay. La proteges de la corriente con tu propio cuerpo, alimentándola de restos, aliento, pura voluntad. Arde baja y flaca. Puede que no baste. Pero no la dejarás morir sin pelear.",
97: "La llama está baja y falla, y temes que protegerla solo no baste. Hiciste todo lo posible con lo que tenías. Pero puede no aguantar. Necesitas más — más combustible, más manos, o ambos.",
98: "Miras fuera y la ves. Lejos en la ladera, una luz prende y cae — donde nadie debería estar, mostrándose y escondiéndose. Te tira del ojo. Y de algo más hondo.",
99: "La luz en la ladera reaparece — donde todos juran que nadie estaría. Pero una luz supone una mano, y una mano supone una persona. Una persona, fuera, sola, en un frío así.",
100: "Viene entonces la larga vela: alimentas la estufa, mantienes a Marta caliente, vigilas el frío hora tras hora. Nada emocionante — solo trabajo constante, duro, cuidadoso. Pero es todo el trabajo de esta noche, y es tuyo.",
101: "Y entonces, al fin, cambia. El viento afloja un poco su presa. El cielo grisea al borde de la cresta, y llega la primera luz. El frío pierde. Casi has sostenido toda la noche.",
102: "Es la hora más dura, justo antes del quiebre. El frío no ha cedido; los brazos duelen, los ojos arden. Pero sientes la noche empezar a cambiar, en algún sitio debajo. Aguanta un poco más.",
103: "En la colina los ves — antorchas, figuras oscuras, fuegos bajos contra la nieve. Otra gente, fuera en el frío como tú. El valle también pasó esta noche. Nunca estuviste tan solo como sentías.",
104: "Al fin, la ayuda sube la colina — el equipo, más brazos, más combustible, ayuda de verdad a buena marcha. Te apoyas en la puerta y la miras venir, las piernas temblando. Pero lo peor de la noche quedó atrás.",
105: "El alba sube sobre la montaña, la luz se vuelve gris, luego pálida y limpia. El sol pasa la cresta, y el frío suelta su presa. La lámpara sigue ardiendo en la ventana. Lo peor pasó al fin.",
106: "Entonces llega — el primer pájaro de la mañana, cantando sobre la nieve como si no hubiera habido tormenta. Tras la noche que has tenido, parece casi absurdo. Y es hermoso, y te paras a escuchar.",
107: "Desde la ventana vigilas la ladera, donde una luz se alza, cae y crece despacio. Algo viene al fin, aún demasiado lejos para distinguirlo. Pero una luz quiere decir alguien — y alguien vale mucho más que nadie esta noche.",
110: "Llega al fin la primera luz, y la noche hace sus cuentas. Todo lo que hiciste fuera, en el frío, vuelve a ti — algo de lo que estar orgulloso, y algo menos. Veamos, pues, en qué quedó todo.",
111: "La noche se suma — no con un gran acto, sino con mil pequeños. Lo que mantuviste, lo que rechazaste, por quién saliste al frío. Todo cuenta, al final. Todo hizo la noche lo que fue.",
112: "Queda más que pesar; la noche guardó otras cosas. Un desconocido por quien te paraste. Un abrigo y una lámpara dados con mano abierta. Pequeñas decisiones, en el frío, cuando habría sido más fácil pasar de largo.",
113: "¿Y qué te deja la noche? Quizá no una victoria limpia. Quizá solo esto: que saliste, que lo intentaste. Cuando estaba oscuro, frío y era fácil atrancar la puerta, no lo hiciste. Eso cuenta.",
114: "Pero no toda noche acaba bien. Algunas decisiones cuestan más de lo que creías; algunas puertas, una vez abiertas, no se cierran. Es el final duro de la noche — donde lo peor vuelve a ti.",
120: "Mantuviste la estufa tirando y la lámpara brillante en la ventana toda la noche. A la primera luz la nube se alza sobre la cresta, el equipo te alcanza, y todos los que la montaña guardaba esta noche salen con bien y calientes. Todo resistió porque te quedaste en pie y no dejaste morir la luz. Eso es todo.",
121: "Respondiste a la luz que nadie podía explicar. Encontraste a Rowan, perdido y helado bajo la cornisa, y lo metiste y calentaste justo a tiempo. Y se salvó más de una vida: Rowan es el nieto de Marta. Una puerta cerrada por años se abre de nuevo, en el gris del alba.",
122: "No hubo un solo acto de valentía — hubo algo mejor. Volviste un valle dormido en gente con antorchas en la colina, y juntos pasaron la noche. Nadie quedó solo en ella. Eso, al fin, es lo que puede ser un valle.",
123: "Rechazaste el engaño — viste el truco de Vane y le diste la espalda. Mantuviste la cabeza y sostuviste el refugio por medios honrados. No fue una noche perfecta; no sacaste a todos. Pero fue limpio, y limpio basta.",
124: "No lograste sostenerlo todo. Pero el caminante por quien te paraste vuelve ahora. Te ayuda a mantener la cabaña y a calentar a Marta. No es la victoria plena. Pero una bondad, resulta, siempre vuelve.",
125: "Diste tu abrigo y tu combustible a quienes tenían menos, y acabas la noche helado tú mismo. No lo salvaste todo. Pero no estás solo, ni nadie de los que encontraste. Algo en el valle ha cambiado. Es un comienzo, no un rescate.",
126: "Pasas por los pelos. El viento cae al fin, y un alba escasa trae al equipo por la colina. No es un triunfo, y nadie lo cantará. Pero pasaste la noche — y al fin, eso ya es un alivio.",
127: "No sacaste a todos. Pero el valle te vio en la colina cuando otros atrancaron sus puertas — te vio intentarlo, en la peor noche del año. Desde esta noche, eres alguien que este lugar conoce. Y eso no es nada.",
128: "Tomaste el trato de Vane, y por la mañana el refugio está condenado — ya de nadie. El frío hizo el resto. El dinero en tu bolsillo está frío, y la ventana oscura. No olvidarás pronto cómo lo ganaste.",
129: "La cornisa era una trampa, como advirtió Doune. Cedió bajo ti en la oscuridad, y se llevó toda la noche. Sales a rastras, herido y helado, y alcanzas el otro lado demasiado tarde. La cornisa te costó todo lo que el atajo prometía.",
130: "Pasaste la noche en lo que no debías, y la estufa quedó apagada demasiado tiempo. Al alba la cabaña está fría, y a quien estuviera en la ladera no se le halló a tiempo. Saliste al frío. Pero no mantuviste la luz cuando de verdad contaba.",
131: "Al final, te quedaste dentro, caliente y a salvo. Te dijiste que la tormenta era demasiado dura, que no era cosa tuya, que la ayuda vendría al alba. Todo era cierto. Y toda la noche, fuera, la ventana quedó oscura. Nada malo te pasó. Pensarás en eso mucho, mucho tiempo.",
}
def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    data = json.load(open(OUT, encoding="utf-8")) if os.path.exists(OUT) else {}
    a = 0
    for nid, t in G.items():
        k = str(nid)
        if k not in data: a += 1
        data[k] = t
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print("the-refuge/es.json: %d (+%d)" % (len(data), a))
if __name__ == "__main__":
    main()
