#!/usr/bin/env python3
"""The Orchard — full Italian per-passage gist coverage (merges to 112/112).
Run: python3 scripts/g_it_ep06.py"""
import json, os
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "the-orchard", "it.json")

G = {
 2: "Raccogli ciò che c'è nel capanno: una lattina d'olio, fiammiferi, una buona lanterna, una bracciata di paglia secca. Fuori, l'aria è immobile e gela da far male. La brina già si stende bianca sull'erba. Devi decidere cosa fare, e farlo in fretta.",
 3: "Provi il telefono. Squilla e squilla, poi alla fine la voce di Tom arriva dalla cooperativa. Nessuna squadra può uscire prima del mattino, dice — non con una gelata così. Accendi i fuochi lungo i filari, ti dice, e tienili vivi se proprio puoi.",
 4: "Raggiungi Edith ai piedi dei gradini. La sistemi e la riscaldi come puoi. Ma i filari sono ancora bui e freddi. Il riparo da solo non basta. I fiori là fuori hanno bisogno dei fuochi accesi. Ti servono olio, un piano e la mente lucida prima di uscire tra gli alberi.",
 5: "Esci tra i filari. La notte è immensa e immobile, e i fiori pallidi paiono brillare nel buio. Il freddo preme su tutto il frutteto come una mano. Poi, lontano tra gli alberi in fondo, la cogli: una lucina che si muove, là dove nessuno dovrebbe essere stanotte.",
 6: "Ti costringi a fermarti e pensare. Potresti accendere prima i fuochi e pensare al resto dopo. Potresti andare invece da Edith e dai vicini. O potresti svegliare il paese e portare più mani. Ogni scelta costa tempo che non hai — e là fuori nel buio la brina sta già lavorando gli alberi.",
 8: "Il freddo si posa nel petto come un peso. Pensi ai fiori là fuori: il frutto di un intero anno, il frutteto che è tutto ciò che resta a Edith. Se i fuochi restano spenti ancora a lungo, la brina si prende tutto entro l'alba. Non è paura; è un fatto semplice. Nessun altro verrà a buttarsi in questo e a farlo. Sei tu, stanotte, o nessuno.",
 11: "Esci dritto ai filari e accendi ciò che puoi. Un fiammifero, un lampo di paglia, un braciere che prende qua e là. Ma le fiamme sono sottili e basse. Senza olio vero non dureranno un'ora. Non puoi solo accenderle, andartene e sperare.",
 13: "Ti prendi carico tu stesso dell'olio e della paglia. Il fusto è pesante, e ora ogni goccia conta. Curato con attenzione, terrà i fuochi accesi lungo i filari tutta la notte; sprecato, e i fiori gelano prima dell'alba. Così te lo stringi addosso e vai verso gli alberi.",
 14: "Prendi solo una lanterna e un fascio di legna minuta. Ti danno luce per lavorare e un modo per accendere una fiamma. Ma non i fuochi stessi. E non hai messo da parte olio vero. Ti servirà comunque olio vero, e presto. Se no, i filari restano bui e la brina vince.",
 15: "Il vecchio Jack Hale conosce questo frutteto al buio meglio di chiunque. «Sta' lontano dallo stagno ghiacciato», dice. «Sembra una scorciatoia. Non lo è: è annegare.» Ti mette in guardia anche dal compratore, quell'uomo sorridente della ditta. «Bada all'olio, tieni i fuochi: è tutto il lavoro di stanotte.»",
 16: "Accendi la stufa del signor Hollis e lo sistemi accanto con una coperta. Pian piano il suo tremore si placa. «Che tu sia benedetto», dice, stringendoti forte la mano. Prometti di tornare a vederlo prima del mattino. Poi ti volti di nuovo nella brina e nei filari che aspettano.",
 17: "Tenere i fuochi viene prima. Il resto può aspettare un momento. Ma devi ancora scegliere come. Potresti prendere prima olio vero dal magazzino. O potresti uscire dritto ai filari e cominciare.",
 18: "Il lavoro ti sfinisce. Le gambe bruciano, il petto ansima, e il freddo ti combatte a ogni passo. Sei vicino al tuo limite, e lo sai. Se crolli qui, non resta nessuno a tenere i fuochi. Quindi va' piano, e va' con attenzione.",
 19: "Il paese si risveglia, e la gente comincia a muoversi. Un uomo fa rotolare un barile d'olio. Una donna trascina fuori legna secca. Porta dopo porta, un piano prende forma. Non sei più solo in questo. E questo cambia tutto.",
 20: "Nessuno si muove. Le porte restano chiuse, e i volti si girano dalle finestre. Hanno paura, e gli impauriti tacciono. Non puoi costringerli ad aiutare. Così ti giri e vai avanti da solo. È più dura così. Ma i fiori non possono aspettarli.",
 21: "I fuochi vicini vanno. Ora i filari in fondo. Ci sono due modi per arrivarci. Il viottolo lungo che gira è sicuro ma lento. Lo stagno ghiacciato è rapido, dritto attraverso. Ma con una gelata così, il ghiaccio potrebbe uccidere.",
 22: "Prendi a cuore le parole di Jack Hale. Bada bene all'olio. Tieniti ben lontano dallo stagno ghiacciato. Non fidarti del compratore. E tieni i fuochi sopra ogni altra cosa. È un consiglio semplice, e buono. Ora devi solo seguirlo.",
 23: "Ti senti più saldo per il gesto buono che hai fatto. Aiutare qualcuno, stranamente, pare rinfrancare anche te. Hai la testa più lucida, e le mani più sicure. C'è ancora una notte dura davanti. Ma ora ti senti all'altezza di affrontarla.",
 24: "Un uomo sta nel viottolo, una lanterna che dondola nel pugno: il compratore. Ha olio da vendere e una schiena forte da offrire, e sorride con troppa facilità. «Il frutteto non è proprio compito tuo stanotte, amico», dice. Ne hai già conosciuti, dei suoi pari.",
 25: "Guidi un gruppetto verso i fuochi. Camminando insieme, vi sentite tutti più forti. Portano olio, legna e paglia. «Di qua!», gridi nel freddo, e vengono. È una bella sensazione, in un'ora difficile.",
 26: "Il viottolo è nero e duro, il freddo che vi preme, nessun riparo da nessuna parte. Ma è saldo sotto i piedi, e porta dove devi andare. Così continui a camminare, passo dopo passo.",
 28: "Esci sul ghiaccio, e subito senti che è sbagliato. L'acqua aspetta sotto, nera e profonda e gelida. Ogni passo è una scommessa ora — e sei là fuori, solo. Non si torna indietro una volta che cominci ad attraversare.",
 29: "La paglia è umida e non prende. Dà solo una fiamma bassa e vacillante. Serve a poco in una gelata così. Dovrai arrangiarti con quella. O tornare al magazzino per paglia secca.",
 30: "Il viottolo prosegue lungo i filari, il freddo che si approfondisce di ora in ora. Sotto, una casa sta buia, senza fuoco dentro. Davanti, l'aria immobile e dura pare respingerti. E c'è un segnafilare, mezzo caduto nella brina.",
 31: "Un vecchio è caduto sul viottolo ghiacciato e non riesce a rialzarsi. Il freddo lo sta già prendendo. Se ti fermi, perdi tempo che non hai. Se no, potrebbe non reggere l'ora.",
 33: "Avanzi nel peggio del freddo, ogni passo ormai una lotta, la brina che ti punge il viso. Davanti ci sono scelte. Il compratore potrebbe essere vicino. C'è quella luce strana tra gli alberi in fondo. Oppure puoi puntare dritto ai filari.",
 34: "Tiri su il vecchio in piedi e lo riscaldi come puoi. Gli si riempiono gli occhi, e ti caccia in mano un sacco asciutto. «Prendilo», dice, «per il disturbo». Poca cosa — ma data di cuore, e la prendi e vai avanti.",
 35: "Non puoi fermarti ora — ma non puoi neanche lasciarli così. Allora prometti di mandare aiuto presto. «Resistete!», gridi. «State al caldo, state uniti; non vi dimenticherò.» E lo pensi davvero. E poi ti giri e vai.",
 36: "Il paese accende un grande fuoco tra i filari — un barile in fiamme, che getta luce e calore nella brina. La gente si accalca vicino, ai vecchi e ai deboli il posto migliore. Non è tutto il frutteto salvato. Ma è un calore vero, e un inizio.",
 37: "Casa dopo casa, il paese impaurito diventa uno che funziona. Ora la gente ha compiti: uno bada al fuoco, uno porta la paglia, uno sorveglia i filari. La paura diventa azione. E l'azione batte l'attesa, ogni singola volta.",
 38: "Il lungo freddo ti rode la volontà. Una vocina dice: fermati, entra, riposa; nessuno ti biasimerebbe, e sarebbe così facile. Ma pensi ai fiori là fuori sugli alberi. E scacci la voce. Non ancora. Non finché si può ancora salvarli.",
 39: "Raggiungi il vecchio segnafilare, ma la brina lo ha incrinato e mezzo abbattuto. Lo leggi a stento ora. Un braccio indica lungo i filari. L'altro indica verso gli alberi in fondo. Da che parte? Dovrai indovinare, e indovinare giusto.",
 42: "Gli volti le spalle e lo lasci al suo commercio freddo. Fa bene andarsene. Ti chiama a gran voce, ma non ti giri. Quelli come lui trovano sempre qualcuno, alla fine. Ma non sarai tu, non stanotte.",
 43: "Prendi il suo olio e i suoi soldi. Le mani vi si chiudono sopra, e qualcosa in te già lo sa. Il suo sorriso si allarga. «Saggio», dice. Ma non ti senti affatto saggio. Ti senti come una porta che si chiude in silenzio.",
 44: "Glielo chiedi senza giri: cosa vuole davvero, e perché il frutteto dovrebbe fallire? Sorride e guarda giù per il viottolo. «La terra si compra a poco dopo un anno brutto», dice. «Una gelata così è una grazia — per un compratore come me.»",
 45: "Porti il suo olio ai bracieri. Ma quando lo versi, la fiamma soffoca e sputa. L'olio è sottile, tagliato con acqua: non alimenta il fuoco. Le fiamme sprofondano basse e brune e inutili.",
 46: "Apri la lattina, e l'odore ti colpisce: sottile, acido, tagliato con acqua. Quest'olio non alimenterà mai una fiamma. L'hai pagato caro, e non vale nulla. Il dubbio nello stomaco aveva ragione fin dall'inizio.",
 47: "Lo cerchi, ma la lanterna del compratore è già sparita, giù per il viottolo. Non ti stava aiutando affatto. Aspettava la brina, il raccolto perduto, la terra a poco prezzo dopo. Sei stato gabbato, puro e semplice.",
 48: "È sparito, e il viottolo è vuoto — ora solo il freddo, il buio, e ciò che gli hai dato per niente. Hai imparato una dura lezione stanotte. E l'hai pagata troppo cara. Ora vai avanti con meno di quanto avevi all'inizio.",
 49: "La gente impaurita gli spinge addosso le monete. Le mani piene di denaro, le voci che implorano olio. Lui le prende lento, con quello stesso sorriso. Sceglie chi aiutare in base a chi può pagare di più.",
 50: "Lontano sul ghiaccio, i filari in fondo sembrano finalmente più vicini... o no? Non ne sei più certo. Il buio inganna, e così i tuoi occhi stanchi. E ora sei lontano da entrambe le rive.",
 51: "Il ghiaccio, il buio, l'acqua profonda sotto — e una crepa corre da sotto il tuo piede. È questo il momento. Puoi sprofondare nell'acqua gelida. Oppure puoi buttarti indietro dalla crepa, finché puoi.",
 52: "Raggiungi i filari in fondo alla fine, fradicio e tremante, le mani scorticate — ma dall'altra parte. In qualche modo, ce l'hai fatta. Ora devi decidere: andare avanti, sfinito come sei, o affrontare ciò che hai perso sul ghiaccio.",
 53: "Ti butti indietro dalla crepa finché puoi — la scelta dura e giusta. Fai l'ultimo tratto a quattro zampe, e raggiungi la riva scosso e lento. La notte non è perduta. Ma ti è costata tempo che rimpiangerai.",
 54: "Provi ad accendere la loro stufa, e blocchi il peggio degli spifferi con sacchi e una vecchia cassapanca. Trattiene un po' il freddo. Ma non c'è ancora lampada da lasciare loro, e la notte è lungi dall'essere finita.",
 55: "Consegni il tuo cappotto e la tua lampada, e la famiglia si stringe attorno alla piccola fiamma, il sollievo che si allarga sui volti. Il bambino smette di piangere alla fine. «Grazie», dice la madre — e poi ti indica una luce, là tra gli alberi in fondo.",
 56: "Senza il cappotto, il freddo e l'umido ti trovano in fretta — i denti che battono, le dita che si irrigidiscono. L'hai dato per aiutare, e lo rifaresti. Ma alla brina non importa niente di tutto ciò. Morde solo più forte.",
 57: "Uno sconosciuto ti fa cenno verso una porta illuminata. «Solo un minuto», dice. «Fuori dal freddo; riprendi fiato.» È caldo e asciutto, e tutto il corpo ti implora di restare. Ma un minuto così può scivolare in silenzio in un'ora.",
 58: "Avanzi nella brina, gelato fino all'osso, il freddo che combatte ogni passo, gli occhi che lacrimano e bruciano. Ogni passo è una piccola battaglia a sé. Ma continui a farne, uno dopo l'altro, verso i filari.",
 60: "Qualcuno indica verso gli alberi in fondo: una figura è uscita da quella parte, sola, nel freddo e nel buio. Là fuori non c'è che brina e il terreno basso e assassino. Se nessuno le va dietro, potrebbe non tornare.",
 61: "La trovi tra gli alberi in fondo, mezza gelata e smarrita, il freddo che la lacera. Non pare riconoscere affatto il tuo viso. Le prendi saldo il braccio. «Vieni con me», dici. «Ora stai bene. Ti tengo io.»",
 62: "Non puoi fare tutto insieme, e i fuochi sono quelli che hanno più bisogno di te. Così mandi a dire che un altro le vada dietro, e vai avanti. Ti pesa — ma stanotte devi scegliere, e continuare a scegliere.",
 63: "La riporti sana e salva alle case, dove la sua famiglia grida di sollievo. Ti avvolgono in un cappotto asciutto e ti fanno un posto accanto al fuoco. «Grazie», continuano a dire. Ma i filari aspettano, e non puoi restare a lungo.",
 64: "Guardi tutto il frutteto — tutto bianco, tutto immobile. I fiori brillano pallidi e fragili nel buio. Non si vede luce da nessuna parte se non tra gli alberi in fondo. Tutto il frutteto pare trattenere il fiato e aspettare l'alba.",
 65: "Il freddo si approfondisce ora al suo peggio assoluto. Il termometro scende più in basso che può, e il tuo fiato pende bianco nell'aria immobile. È dura pensare, dura muoversi, dura importarsene. È l'ora più dura dell'intera notte.",
 67: "Tom ti caccia in mano l'ultima lanterna asciutta. «Per i filari», dice. «Va'; io resto qui vicino al telefono.» Ha il viso grigio per la preoccupazione. È l'aiuto che ha da dare stanotte, e lo dà tutto volentieri.",
 68: "Al magazzino del combustibile, la gente si avventa sulle lattine — voci che si alzano, mani che afferrano, la paura che prende e si diffonde in fretta. Una spinta in più ed è rissa. Puoi provare a calmarli e distribuire l'olio con giustizia. Oppure puoi solo prendere il tuo e andartene.",
 70: "Lontano tra gli alberi in fondo, una lucina si alza e svanisce. È là dove nessuno dovrebbe essere stanotte — appare, poi sparisce, poi appare di nuovo. Nessuno sa spiegarlo. E qualcosa in te vuole andare a risponderle.",
 71: "Esci fino agli alberi in fondo e chiami nel buio. Non risponde che il freddo. Poi la vedi: una piccola sagoma, là tra gli alberi, mezza nascosta nella brina bianca. Qualcuno è là fuori, dopotutto. E si muove appena.",
 72: "Li raggiungi, e il cuore ti si rivolta. È un bambino — Wren — rannicchiato nella brina, mezzo gelato e sveglio a stento. Il freddo lo tiene nella sua morsa. Non c'è tempo di aspettare e pensare. Devi fare qualcosa ora.",
 73: "Chiami di nuovo nel buio, e per un momento non c'è nulla. Poi torna una voce sottile, lacerata dal freddo: «Qui! Qua fuori!» Qualcuno è là tra gli alberi, e ha bisogno d'aiuto. E non suona affatto forte.",
 74: "Tiri su Wren dalla brina e lo avvolgi stretto nel tuo cappotto. Piano si riprende, stringendoti il braccio. «I fuochi», sussurra. «Tieni i fuochi accesi. I fiori...» Anche ora, mezzo gelato, pensa al frutteto.",
 75: "Ti giri per correre a cercare aiuto — poi ti fermi di colpo. Qui fuori non c'è aiuto, non fino al mattino. Niente squadra, niente vicini, nessuno in arrivo. Sei tu o nessuno, e Wren lo sa anche lui. I suoi occhi spaventati ti seguono nel buio.",
 76: "Wren alza lo sguardo su di te, gli occhi più limpidi ora. «La coltivatrice, Edith — è mia nonna», dice. «Non ci parliamo da anni. Non da quando mio padre e lei litigarono. È una lunga, triste storia.» E senti proprio quanto è lunga.",
 77: "Decidi di farli incontrare faccia a faccia prima che la notte finisca — Wren e la vecchia Edith, dopo tutti questi anni. È poca cosa, accanto ai fuochi e alla brina. Ma non è nulla. Certe porte chiuse si possono ancora aprire.",
 78: "La piccola sagoma non si muove, e la brina ci lavora, fredda e paziente. Eppure qualcuno è venuto fin qui, nel buio, solo. Non puoi lasciarlo lì disteso. Devi avvicinarti e sapere chi è.",
 79: "Ti avvicini, e li riconosci subito. È Wren — il nipote della vecchia Edith, non visto qui da anni, non da quando la famiglia litigò. Poi un suono debole viene dalla brina ai tuoi piedi. Ti muovi in fretta ora.",
 80: "Il compratore arriva un'ultima volta, la lanterna che dondola. «Ancora a lottare?», dice. «Lascia che la brina se lo prenda. Ultima occasione di stare dalla parte dei vincitori, amico.» Lo stesso sorriso facile. La stessa vecchia bugia.",
 90: "Sei di nuovo al frutteto, gelato fino al midollo, il freddo più duro della notte che preme su tutto. Accanto ai gradini sul retro, Edith giace grigia e immobile. Fuori nei filari, i fuochi ardono bassi. È l'ora da cui dipende l'intera notte.",
 91: "Raggiungi i fuochi: le fiamme basse, i bracieri in fondo ormai freddi. Tra i filari in fondo, la brina è vicina a prendersi i fiori per sempre. Devi rendere i fuochi pieni e di nuovo accesi — e devi farlo ora, in fretta.",
 92: "Poi l'aiuto ti raggiunge alla fine — più mani, più olio, gente salda che conosce il lavoro. Ora non sei più solo in questo; ci sono altri a dividere il peso. È come posare qualcosa di pesante che hai portato fin troppo a lungo.",
 93: "Ora tieni i fuochi accesi — e ciò che puoi fare dipende da ciò che hai portato qui. Con olio vero, hai di che lavorare. Senza, devi coltivare ogni ultimo guizzo di fiamma. In un modo o nell'altro, la notte è lungi dall'essere finita.",
 94: "Scendi a controllare Edith, e i suoi occhi si aprono appena. C'è paura dentro — poi, vedendo il tuo viso, un po' meno paura. «L'hai tenuto acceso», sussurra. «Sì», le dici piano. «Ora riposa.»",
 95: "L'olio ce la fa. Alimenti i bracieri e li ravvivi, e uno a uno i fuochi si levano pieni e dorati lungo tutti i filari. Luce calda che respinge tutto quel freddo. È per questo, pensi, che è stata l'intera dura notte.",
 96: "Non hai olio vero da versare, così coltivi la poca fiamma che c'è. La ripari dalla corrente col tuo stesso corpo, nutrendola di ritagli, fiato, pura volontà. Arde bassa e sottile. Può non bastare. Ma non la lascerai morire senza lottare.",
 97: "La fiamma è bassa e vacilla, e temi che ripararla da sola non basti. Hai fatto tutto il possibile con ciò che hai. Ma potrebbe comunque non reggere. Ti serve di più ora — più olio, più mani, o entrambi.",
 98: "Guardi fuori e la vedi. Lontano tra gli alberi in fondo, una luce divampa e cala — là dove nessuno dovrebbe essere, che appare e si nasconde e appare di nuovo. Ti tira l'occhio. E tira qualcosa di più profondo di quello.",
 99: "La luce là tra gli alberi appare di nuovo — là dove tutti giurano che nessuno sarebbe. Ma una luce vuol dire una mano che l'ha accesa, e una mano vuol dire una persona. Una persona là fuori, sola, in un freddo come questo.",
 100: "Ora viene la lunga resistenza: tieni i fuochi alimentati, tieni Edith al caldo, e sorvegli il freddo ora dopo ora. Non è emozionante — solo lavoro costante, duro, attento. Ma è tutto il lavoro di stanotte, ed è tuo.",
 101: "E poi, finalmente, cambia. Il freddo allenta un po' la presa. Il cielo si fa grigio all'orlo del crinale, e sale la prima luce sottile. La brina sta perdendo. Hai quasi tenuto l'intera notte.",
 102: "È l'ora peggiore, quella appena prima della svolta. Il freddo non ha ancora ceduto; le braccia ti dolgono, gli occhi ti bruciano. Ma senti la notte che comincia a volgere, da qualche parte sotto tutto. Resisti ancora un po'.",
 103: "Lungo i filari li vedi — lanterne, figure scure in movimento, fuochi che ardono bassi contro la brina. Altra gente, fuori nel freddo con te. Il paese ha passato anche questa notte. Non eri così solo come ti sentivi.",
 104: "Alla fine, l'aiuto risale il viottolo — un camion, più mani, più olio, aiuto vero a velocità vera. Ti appoggi a un albero e lo guardi venire, le gambe che ti tremano ormai. Ma il peggio della notte è alle tue spalle.",
 105: "L'alba sale sul frutteto, la luce che si fa grigia, poi pallida e pulita. Il sole sale il crinale, e la brina molla la presa. I fiori sono ancora lì sugli alberi. Il peggio è passato alla fine.",
 106: "Poi arriva — il primo uccello del mattino, che canta sopra gli alberi come se non ci fosse stata brina alcuna. Dopo la notte che hai avuto, sembra quasi assurdo. Ed è bellissimo, e ti fermi ad ascoltare.",
 107: "Dal frutteto guardi gli alberi in fondo, dove una luce si alza e cala e cresce piano. Qualcosa arriva alla fine, ancora troppo lontano per capire. Ma una luce vuol dire qualcuno là fuori — e qualcuno è molto meglio di nessuno stanotte.",
 110: "La prima luce arriva alla fine, e la notte fa la somma di ciò che è. Qualunque cosa tu abbia fatto là fuori nel freddo torna a casa ora — parte di cui andare fiero, parte no. Vediamo, allora, in cosa si è risolto tutto.",
 111: "La notte fa la somma — non sempre con un gesto grande, ma con tanti piccoli. Ciò che hai tenuto, ciò che hai rifiutato, per chi sei uscito nel freddo. Tutto conta alla fine. Tutto ha fatto della notte ciò che è stata.",
 112: "C'è altro da pesare; la notte ha tenuto anche altre cose. Uno sconosciuto per cui ti sei fermato. Un cappotto e una lampada dati a mano aperta. Piccole scelte, fatte nel freddo, quando sarebbe stato più facile passare oltre.",
 113: "E con cosa ti lascia la notte? Forse non con una vittoria netta. Forse solo col fatto che sei uscito, che hai provato. Quando era buio e freddo e facile sbarrare la porta, non l'hai fatto. Conta qualcosa.",
 114: "Ma non ogni notte finisce bene. Certe scelte costano più di quanto sapessi allora; certe porte, una volta aperte, non si richiudono più. È la fine dura della notte — il luogo dove torna a casa il peggio.",
}

def main():
    data = json.load(open(OUT, encoding="utf-8")); a = 0
    for nid, t in G.items():
        k = str(nid)
        if k not in data:
            data[k] = t; a += 1
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"the-orchard/it.json: {len(data)} (+{a})")

if __name__ == "__main__":
    main()
