#!/usr/bin/env python3
"""Full Italian per-passage gist for High Water (book 7). Draft, pending native review."""
import json, os
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "high-water", "it.json")
G = {
1: "È la notte più piovosa da anni. Il fiume è salito tutto il giorno sotto una pioggia dura. Lungo la via bassa l'acqua è già sulle soglie. Poi la vecchia Nora Kettle cade sul gradino bagnato e non riesce a rialzarsi. Il muro di sacchi di sabbia non è costruito, e l'acqua ha già superato il cordolo. Tenere il fiume fuori dalle case ora tocca a te.",
2: "Raccogli ciò che c'è nel capanno: una pila di sacchi, una pala, una piccola pompa, una buona torcia. Fuori la pioggia cade dritta e il fiume sale ancora. L'acqua attraversa già il vicolo. Devi decidere cosa fare, e in fretta.",
3: "Provi il telefono. Alla fine la voce di Tom arriva dal cantiere. Nessuna squadra può uscire prima del mattino, dice — non con il fiume così. Costruisci il muro lungo il vicolo, ti dice, e tienilo come puoi finché l'acqua non cala.",
4: "Raggiungi Nora ai piedi del gradino e la metti al caldo e all'asciutto. Ma il fiume sale ancora, e il riparo non basta. Le case hanno bisogno del muro, costruito e tenuto. Ti servono sacchi, un piano e la testa lucida prima di uscire.",
5: "Esci nel vicolo. La notte è immensa e piena di pioggia, e l'acqua nera luccica sotto la torcia. Il fiume preme su tutta la via bassa come una mano. Poi, lontano, al bordo dell'acqua, una lucina si muove dove stanotte non dovrebbe esserci nessuno.",
6: "Ti sforzi di pensare. Potresti costruire il muro prima e pensare al resto dopo. O andare da Nora e dai vicini. O svegliare tutta la via per avere braccia. Ogni scelta costa un tempo che non hai — e fuori, il fiume sale già.",
8: "Il freddo ti si posa sul petto come un peso. Pensi alle case della via bassa: tutto ciò che questa gente ha. Se il muro resta non costruito ancora a lungo, il fiume è dentro all'alba. Non è una paura; è un fatto. Nessun altro verrà. Sei tu, stanotte, o nessuno.",
9: "Tom spalanca il magazzino del cantiere e alza la torcia. Dentro: pallet di sacchi di sabbia, una pompa, rotoli di corda, tela asciutta. «Prendi ciò che ti serve, dice. Resto al telefono e chiamo chi posso.» È un uomo saldo, e una notte così lo mostra.",
10: "Bussi lungo la fila, e il vecchio signor Hollis apre, pallido nel buio. Niente corrente, torcia morta, le mani che tremano troppo per sollevare un sacco. «Non riesco a tenerlo fuori», dice. Hai davanti una lunga notte. Ma lui è qui, spaventato, ed è a te che chiede.",
11: "Vai dritto nel vicolo a impilare ciò che puoi. Un sacco, una palata di sabbia, una linea bassa che sale qua e là. Ma il muro è sottile e basso. Senza veri sacchi non terrà un'ora. Non puoi costruirne un po' e sperare.",
12: "Vai di porta in porta con le stesse parole. Porta sabbia. Dai una mano al muro. Aiutami a tenere la linea. Alcuni si voltano e chiudono. Ma pochi infilano il cappotto ed escono sotto la pioggia. Stanotte, pochi bastano per cominciare.",
13: "Prendi tu stesso in mano i sacchi e la pompa. Il pallet è pesante, e ogni sacco conta adesso. Ben impilati, tengono il fiume tutta la notte; sprecati, l'acqua passa le porte prima dell'alba. Così li stringi a te ed esci nel vicolo.",
14: "Prendi solo una torcia e una pala. Per vedere e spostare la sabbia. Ma non il muro in sé. E non hai messo da parte veri sacchi. Serviranno sacchi veri, e presto. Altrimenti il vicolo si allaga e il fiume vince.",
15: "Il vecchio Jack Reed conosce questo fiume meglio di chiunque. «Stai lontano dalla passerella della chiusa, dice. Sembra una scorciatoia. Non lo è — è un annegamento.» Ti mette in guardia anche sul venditore. «Bada ai sacchi, tieni il muro — è tutto il lavoro di stanotte.»",
16: "Costruisci una linea di sacchi davanti alla porta del signor Hollis e lo sistemi con una coperta. Pian piano smette di tremare. «Che Dio ti benedica», dice stringendoti la mano. Prometti di ripassare. Poi torni fuori nella pioggia e nel vicolo che aspetta.",
17: "Il muro viene prima. Il resto può aspettare un momento. Ma come cominciare? Potresti prendere veri sacchi al cantiere prima. O andare dritto nel vicolo.",
18: "Il lavoro ti consuma. Le gambe bruciano, il petto ansima, la pioggia ti combatte a ogni passo. Sei al tuo limite, e lo sai. Se cadi qui, non resta nessuno a tenere il muro. Allora vai piano, con attenzione.",
19: "La via si sveglia. La gente comincia a muoversi. Un uomo spinge una carriola di sabbia. Una donna trascina un rotolo di sacchi. Di porta in porta, prende forma un piano. Non sei più solo. E questo cambia tutto.",
20: "Nessuno si muove. Le porte restano chiuse, i volti si voltano dalle finestre. Hanno paura, e la gente spaventata tace. Non puoi costringerli. Così vai avanti da solo. È più dura così. Ma il fiume non li aspetterà.",
21: "Il muro vicino tiene. Ora le case in fondo. Due vie per scendere. Il lungo vicolo è sicuro ma lento. La passerella della chiusa è rapida, dritta. Ma con una piena così, l'acqua può uccidere.",
22: "Prendi a cuore le parole di Jack Reed. Bada ai sacchi. Lontano dalla passerella. Non fidarti del venditore. E tieni il muro sopra ogni cosa. Consiglio semplice, e buono. Resta solo da seguirlo.",
23: "Il buon gesto ti rinsalda. Aiutare qualcuno rinsalda anche te, stranamente. La testa più chiara, le mani più sicure. C'è ancora una notte dura. Ma ti senti capace di affrontarla.",
24: "Un uomo sta nel vicolo, una torcia in pugno: il venditore. Ha pompe da vendere e braccia da prestare, e sorride troppo facilmente. «La via non è davvero affar tuo stanotte, amico», dice. Ne hai già visti, di tipi come lui.",
25: "Guidi un piccolo gruppo verso il muro. Insieme vi sentite più forti. Portano sabbia, sacchi, la pompa. «Di qua!» gridi sotto la pioggia, e vengono. Fa bene, in un'ora così dura.",
26: "Il vicolo è nero e allagato, la pioggia lo spazza, nessun riparo da nessuna parte. Ma il terreno è saldo sotto i piedi, e porta dove serve. Così continui a camminare, passo dopo passo.",
27: "La passerella della chiusa dimezzerebbe il cammino, con le case in fondo appena oltre. Ma le assi sono vecchie e scivolose su una gora rapida e profonda. Jack Reed ti ha detto di starne lontano — e non scherzava.",
28: "Metti piede sulle assi, e subito suona storto. La gora aspetta sotto, nera, profonda, rapida. Ogni passo è una scommessa — e ci sei sopra, solo. Niente ritorno una volta partito.",
29: "La pompa non si adesca. Tossisce, prende un secondo, e muore. Dura perdita, con una piena così. Toccherà riempire e impilare i sacchi a mano. O tornare al cantiere per un'altra pompa.",
30: "Il vicolo prosegue lungo la fila, l'acqua più profonda di ora in ora. Sotto, una casa buia, il fiume già alla porta. Davanti, la pioggia battente sembra respingerti. E un palo indicatore, mezzo caduto nella piena.",
31: "Un vecchio è caduto nel vicolo allagato e non riesce a rialzarsi. Il freddo lo prende già. Fermarti è perdere un tempo che non hai. Non farlo, e potrebbe non reggere l'ora.",
32: "Una famiglia è chiusa in una casa allagata — niente corrente, niente luce, un bambino che piange. L'acqua sale ai loro piedi. I genitori ti guardano, stanchi, senza speranza. Hai una lampada e un cappotto. Poca cosa. Ma più di loro.",
33: "Spingi nel peggio della pioggia, ogni passo una lotta, l'acqua che ti tira le gambe. Davanti ci sono scelte. Forse il venditore. Quella strana luce al bordo dell'acqua. O tirare dritto al muro.",
34: "Rimetti in piedi il vecchio e lo riscaldi come puoi. Gli si riempiono gli occhi, e ti mette una corda tra le mani. «Prendila, dice, per il disturbo.» Poca cosa — ma data di cuore. La prendi e vai.",
35: "Non puoi fermarti — ma neanche lasciarli. Allora prometti di mandare aiuto. «Tenete duro! gridi. Salite di sopra, restate uniti — non vi dimentico.» E lo pensi davvero. Poi ti volti e vai.",
36: "La via costruisce prima un buon tratto di muro — un banco di sacchi solido sul peggior varco, che respinge l'acqua. Ci si accalca a passare i sacchi di mano in mano. Non è tutto il vicolo. Ma è reale, tiene, ed è un inizio.",
37: "Casa dopo casa, la via spaventata diventa una via al lavoro. Ognuno ha un compito: uno riempie i sacchi, uno li porta, uno sorveglia l'acqua. La paura diventa azione. E l'azione batte l'attesa, ogni volta.",
38: "Il lungo sforzo rode la tua volontà. Una vocina dice: fermati, entra, riposa — nessuno ti biasimerebbe, sarebbe così facile. Ma pensi alle case, l'acqua alle porte. E scacci la voce. Non ancora. Non finché si possono salvare.",
39: "Raggiungi il vecchio palo, ma la piena l'ha spaccato e mezzo rovesciato. Si legge a stento. Un braccio indica il vicolo. L'altro il bordo dell'acqua. Da che parte? Dovrai indovinare, e indovinare giusto.",
40: "Il venditore ti rivolge il suo ampio sorriso facile. «Lavoro bagnato, questo, dice. Ho pompe da vendere e braccia da prestare — e la via non è davvero affar tuo stanotte, amico.» La torcia oscilla. Il sorriso non arriva mai agli occhi.",
41: "L'offerta è un amo, e lo senti agganciarsi. Si china. «Quella via è già persa, dice piano. Lascia che il fiume faccia — e c'è una parte per te.» È crudele da dire. Ed è fatto per lavorare la tua paura.",
42: "Gli volti le spalle e lo lasci al suo commercio gelido. Fa bene andarsene. Ti chiama dietro, ma non ti volti. I suoi pari trovano sempre qualcuno, alla fine. Ma non te, non stanotte.",
43: "Prendi la sua pompa e il suo patto. Le mani ci si chiudono sopra, e qualcosa in te già sa. Il sorriso si allarga. «Saggio», dice. Ma non è per niente saggio. È come una porta che si chiude piano.",
44: "Gli chiedi senza giri: cosa vuole davvero, e perché la via dovrebbe affondare. Sorride e guarda lontano. «Le case costano poco dopo una piena, dice. Una notte così è un favore — per un compratore come me.»",
45: "Porti i suoi sacchi al muro. Ma impilandoli, la sabbia scola subito. La tela è lacera e marcia — non trattengono nulla. La linea cede, bassa e inutile.",
46: "Apri un sacco, e ti cade il cuore. La tela è lacera, marcia. Questi sacchi non terranno mai l'acqua. Li hai pagati bene, e non valgono nulla. Il dubbio nelle tue viscere aveva ragione.",
47: "Lo cerchi, ma il furgone del venditore è già andato. Non ti aiutava affatto. Aspettava la piena, le case rovinate, il terreno a buon mercato dopo. Ti hanno ingannato, semplicemente.",
48: "Se n'è andato, il vicolo vuoto — solo la pioggia ora, il buio, e ciò che gli hai dato per niente. Hai imparato una dura lezione. E pagata troppo cara. Vai avanti con meno di quanto avevi.",
49: "La gente spaventata gli mette i soldi in mano. Pugni pieni di monete, voci che implorano una pompa. Lui prende con calma, con lo stesso sorriso. Sceglie chi aiutare in base a chi paga di più.",
50: "Lontano sul ponte, le case in fondo paiono più vicine — o no? Non ne sei più sicuro. Il buio inganna, e i tuoi occhi stanchi pure. E sei lontano da entrambe le rive.",
51: "Le assi, il buio, la gora profonda sotto — e un'asse si spezza sotto il tuo piede. È il momento. Scendere nell'acqua rapida. O gettarti indietro dal varco, finché puoi ancora.",
52: "Raggiungi infine le case in fondo, fradicio, tremante, le mani a vivo — ma di là. Chissà come, ce l'hai fatta. Ora devi decidere: spingere avanti, sfinito, o affrontare ciò che hai perso nell'acqua.",
53: "Ti getti indietro dal varco finché puoi — la scelta dura, quella giusta. Strisci l'ultimo tratto a quattro zampe e raggiungi la riva, scosso e lento. La notte non è persa. Ma ti è costata un tempo che mancherà.",
54: "Costruisci una linea bassa di sacchi alla loro porta e aggotti il peggio dell'acqua con un secchio. Trattiene un po' il fiume. Ma non c'è una lampada da lasciare, e la notte è lontana dalla fine.",
55: "Dai loro il tuo cappotto e la tua lampada, e la famiglia si stringe di sopra attorno alla piccola fiamma, il sollievo sui volti. Il bambino smette infine di piangere. «Grazie», dice la madre — poi ti indica una luce, al bordo dell'acqua.",
56: "Senza cappotto, il freddo e l'umido ti trovano in fretta — i denti che battono, le dita rigide. L'hai dato per aiutare, e lo rifaresti. Ma al fiume non importa. Sale e basta.",
57: "Uno sconosciuto ti fa cenno di entrare in una porta illuminata. «Solo un minuto, dice. Fuori dalla pioggia — riprendi fiato.» È caldo e asciutto, e tutto il corpo ti implora di restare. Ma un minuto così scivola presto in un'ora.",
58: "Spingi nella pioggia, infreddolito fino alle ossa, il vento che lotta a ogni passo, gli occhi che bruciano d'acqua. Ogni passo è una piccola battaglia. Ma li incateni, uno dopo l'altro, verso le case.",
60: "Qualcuno indica il bordo dell'acqua: una figura è uscita di là, sola, nel buio. Là fuori c'è solo la piena e la gora profonda e rapida. Se nessuno la segue, potrebbe non tornare.",
61: "Li trovi al bordo dell'acqua, fradici e persi, il freddo che li lacera. Non sembrano riconoscere il tuo volto. Li prendi saldi per il braccio. «Vieni con me, dici. È finita. Ti tengo.»",
62: "Non puoi fare tutto, e il muro ti vuole di più. Così mandi un altro a cercarli e spingi avanti. Ti pesa — ma stanotte bisogna scegliere, e scegliere ancora.",
63: "Li riporti sani e salvi alle case, dove la famiglia grida di sollievo. Ti avvolgono in un cappotto asciutto e ti fanno posto accanto al fuoco. «Grazie», ripetono. Ma il vicolo aspetta, e non puoi restare.",
64: "Guardi tutta la via bassa — buia, in piena. La piena luccica, nera, tra le case. Nessuna luce da nessuna parte, salvo al bordo dell'acqua. Tutta la via sembra trattenere il respiro e aspettare l'alba.",
65: "La piena sale al suo peggio. L'acqua tocca il punto più alto, e il fiato ti esce corto nel freddo umido. Difficile pensare, muoversi, perfino importartene. È l'ora più dura di tutta la notte.",
67: "Tom ti mette in mano l'ultima buona torcia. «Per il vicolo, dice. Vai — io resto al telefono.» Il viso grigio di preoccupazione. È l'aiuto che può dare stanotte, e lo dà di cuore.",
68: "Al cantiere, ci si butta sui sacchi — le voci salgono, le mani strappano, la paura corre veloce. Un'altra spinta ed è rissa. Puoi tentare di calmarli e dividere equamente. O prendere i tuoi e filare.",
69: "Una casa chiusa da tempo ti stringe attorno — umidità, silenzio, freddo vecchio, un luogo dove niente sembra vivo. Poi lo senti: un respiro, debole e vicino, dal retro. Qualcuno è vivo qui, dopotutto.",
70: "Lontano, al bordo dell'acqua, una lucina si alza e si spegne. Dove stanotte non dovrebbe esserci nessuno — appare, sparisce, riappare. Nessuno sa spiegarla. E qualcosa in te vuole andare a risponderle.",
71: "Raggiungi il bordo dell'acqua e chiami nel buio. Risponde solo la pioggia. Poi la vedi: una piccola forma, presso la piena, mezza nell'acqua scura. Qualcuno è fuori, dopotutto. E si muove appena.",
72: "Li raggiungi, e il cuore ti si rivolta. È un bambino — Wren — rannicchiato presso la piena, fradicio, a malapena sveglio. Il freddo lo tiene. Non c'è tempo di aspettare. Bisogna agire, ora.",
73: "Richiami nel buio. Un istante, niente. Poi una voce esile torna, spezzata dal freddo: «Qui! Quassù!» Qualcuno è fuori, presso l'acqua, e ha bisogno d'aiuto. E non suona per niente forte.",
74: "Tiri Wren fuori dall'acqua e lo avvolgi nel tuo cappotto. Piano torna in sé, aggrappato al tuo braccio. «Il muro, sussurra. Tieni il muro. Le case...» Anche così, fradicio, pensa alla via.",
75: "Ti volti per correre a cercare aiuto — poi ti fermi di colpo. Niente aiuto qui fuori, non prima del mattino. Nessuna squadra, nessuno. Sei tu o nessuno, e Wren lo sa anche lui. I suoi occhi spaventati ti seguono nel buio.",
76: "Wren alza lo sguardo, gli occhi più chiari. «La vecchia signora, Nora — è mia nonna, dice. Non ci parliamo. Non da quando mio padre e lei litigarono. È una storia lunga e triste.» E senti quanto è lunga.",
77: "Decidi di riunirli prima che finisca la notte — Wren e la vecchia Nora, dopo tutti questi anni. Poca cosa, accanto al muro e alla piena. Ma non è nulla. Certe porte chiuse possono ancora aprirsi.",
78: "La piccola forma non si muove, e la piena striscia verso di lei, fredda e paziente. Eppure qualcuno è venuto fin qui, nel buio, solo. Non puoi lasciarlo lì. Devi avvicinarti e sapere chi è.",
79: "Ti avvicini, e li riconosci subito. È Wren — il nipote della vecchia Nora, non visto qui da anni, da quando la famiglia litigò. Poi un debole suono sale dall'acqua, ai tuoi piedi. Fai in fretta.",
80: "Il venditore torna un'ultima volta, la torcia che oscilla. «Ancora a lottare? dice. Lascia che il fiume se la prenda. Ultima occasione di stare dalla parte dei vincenti, amico.» Lo stesso sorriso facile. La stessa vecchia bugia.",
90: "Sei di nuovo nel vicolo, fradicio, il peggio della piena che pesa su tutto. Presso il gradino, Nora giace grigia e immobile. Lungo il vicolo, il muro è basso e comincia a perdere. È l'ora in cui tutto si decide.",
91: "Raggiungi il muro: la linea bassa, il fondo che perde forte. Verso le case in fondo, il fiume è prossimo a passare sopra per sempre. Devi rialzare il muro, solido e alto — e subito, in fretta.",
92: "Poi l'aiuto ti raggiunge infine — più braccia, più sacchi, gente salda che conosce il lavoro. Non sei più solo; altri condividono il peso. È come posare qualcosa di pesante portato troppo a lungo.",
93: "Ora tieni il muro — e ciò che puoi fare dipende da cosa hai portato. Con veri sacchi, hai con cui lavorare. Senza, devi lottare per ogni palmo a mano. In ogni caso, la notte è lontana dalla fine.",
94: "Scendi a vedere Nora, e i suoi occhi si aprono un poco. C'è paura dentro — poi, vedendoti, un po' meno. «L'hai tenuto», sussurra. «Sì, dici piano. Riposa adesso.»",
95: "I buoni sacchi ci riescono. Rialzi la linea e la pressi bene, e lungo il vicolo il muro si erge, solido e forte. Il fiume vi si getta contro ed è trattenuto. Questo, pensi, è a cosa è servita tutta la notte.",
96: "Niente veri sacchi: lotti per ogni palmo a mano. Pressi fango e sabbia nei varchi, tenendo la linea col tuo corpo, il tuo fiato, la tua volontà. Forse non basterà. Ma non la lascerai senza lottare.",
97: "Il muro è basso e perde, e temi che tenerlo da solo non basti. Hai fatto tutto il possibile con ciò che avevi. Ma potrebbe non reggere. Ti serve di più — più sacchi, più braccia, o entrambi.",
98: "Guardi fuori e la vedi. Lontano, al bordo dell'acqua, una luce divampa e cade — dove non dovrebbe esserci nessuno, mostrandosi e nascondendosi. Ti tira l'occhio. E qualcosa di più profondo.",
99: "La luce al bordo dell'acqua riappare — dove tutti giurano che non ci sarebbe nessuno. Ma una luce vuol dire una mano, e una mano vuol dire una persona. Una persona, fuori, sola, in una piena così.",
100: "Viene allora la lunga veglia: nutri il muro, tieni Nora al caldo, sorvegli l'acqua ora dopo ora. Niente di eccitante — solo lavoro costante, duro, attento. Ma è tutto il lavoro di stanotte, ed è tuo.",
101: "E poi, infine, gira. Il fiume smette di salire. Tiene, poi cala di un palmo, poi di un altro. Il cielo si fa grigio sopra i tetti, e viene la prima luce. La piena perde. Hai quasi tenuto tutta la notte.",
102: "È l'ora più dura, proprio prima della svolta. Il fiume non è calato; le braccia dolgono, gli occhi bruciano. Ma senti la notte cominciare a girare, da qualche parte sotto. Tieni duro ancora un poco.",
103: "Lungo il vicolo li vedi — torce, figure scure, muri di sacchi che tengono la piena. Altra gente, fuori sotto la pioggia come te. Anche la via ha passato questa notte. Non eri così solo come sembrava.",
104: "Infine, l'aiuto risale il vicolo — un camion, più braccia, più sacchi, vero aiuto a buona andatura. Ti appoggi al muro e lo guardi venire, le gambe tremanti. Ma il peggio della notte è alle spalle.",
105: "L'alba sale sulla via, la luce si fa grigia, poi pallida e pulita. La pioggia cede infine, e il fiume ridiscende la riva. Le case sono ancora in piedi, asciutte dentro. Il peggio è passato, finalmente.",
106: "Poi arriva — il primo uccello del mattino, che canta sui tetti bagnati come se non ci fosse stata nessuna piena. Dopo la notte che hai avuto, pare quasi assurdo. Ed è bello, e ti fermi ad ascoltare.",
107: "Dal vicolo scruti il bordo dell'acqua, dove una luce si alza, cade e cresce piano. Qualcosa viene infine, ancora troppo lontano per distinguerlo. Ma una luce vuol dire qualcuno — e qualcuno vale assai più di nessuno stanotte.",
110: "La prima luce viene infine, e la notte fa i conti. Tutto ciò che hai fatto fuori, sotto la pioggia, torna a te — di che essere fiero, e di che meno. Vediamo, dunque, a cosa è approdato tutto.",
111: "La notte si somma — non con un grande atto, ma con mille piccoli. Ciò che hai tenuto, ciò che hai rifiutato, per chi sei uscito sotto la pioggia. Tutto conta, alla fine. Tutto ha fatto la notte ciò che è stata.",
112: "C'è altro da pesare; la notte teneva altre cose. Uno sconosciuto per cui ti sei fermato. Un cappotto e una lampada dati a mano aperta. Piccole scelte, sotto la pioggia, quando sarebbe stato più facile passare oltre.",
113: "E cosa ti lascia la notte? Forse non una vittoria netta. Forse solo questo: che sei uscito, che hai provato. Quando era buio, bagnato e facile restare dentro, non l'hai fatto. Questo conta.",
114: "Ma non ogni notte finisce bene. Certe scelte costano più di quanto sapevi; certe porte, una volta aperte, non si richiudono. È la fine dura della notte — dove il peggio torna a te.",
120: "Hai tenuto il muro tutta la notte lungo il vicolo. Alla prima luce il fiume ridiscende, la pioggia cessa, e le case — un'intera fila di focolari — reggono asciutte. Tutto ha retto perché sei rimasto sotto la pioggia e non hai lasciato cedere il muro. È tutto qui, e basta.",
121: "Hai risposto alla luce che nessuno sapeva spiegare. Hai trovato Wren, perso e gelato al bordo dell'acqua, e l'hai riscaldato appena in tempo. E più di una vita fu salvata. Wren è il nipote di Nora. Una porta chiusa da anni si riapre, nel grigio dell'alba.",
122: "Non ci fu un solo atto di coraggio — ci fu qualcosa di meglio. Hai trasformato una via addormentata in gente con sacchi a ogni porta, e insieme hanno passato la notte. Nessuno vi fu lasciato solo. Questo, alla fine, è ciò che può essere una via.",
123: "Hai rifiutato l'inganno — hai visto il trucco del venditore e gli hai voltato le spalle. Hai mantenuto la testa e salvato ciò che potevi con mezzi onesti. Non una notte perfetta; non hai salvato tutti. Ma l'hai fatto pulito, e pulito basta.",
124: "Non hai salvato tutta la via. Ma il vicino per cui ti sei fermato torna ora. Ti aiuta a salvare le case vicine e a scaldare Nora. Non la piena vittoria. Ma una gentilezza, si scopre, torna sempre.",
125: "Hai dato il tuo cappotto e la tua lampada a chi aveva meno, e finisci la notte gelato tu stesso. Non hai salvato tutto. Ma non sei solo, né lo è nessuno di quelli che hai incontrato. Qualcosa nella via è cambiato. È un inizio, non un salvataggio.",
126: "Ce la fai per un soffio. Il fiume gira infine, e un'alba scarna trova la maggior parte delle case ancora asciutte. Non un trionfo, e nessuno lo canterà. Ma hai passato la notte — e alla fine, è già un sollievo tutto suo.",
127: "Non hai salvato tutto. Ma la via ti ha visto al bordo dell'acqua quando altri restavano a letto — ti ha visto provare, nella peggiore notte dell'anno. Da stanotte, sei qualcuno che questo posto conosce. E non è nulla.",
128: "Hai preso il patto del venditore, e al mattino la via non è più di Nora da salvare. Il fiume ha fatto il resto. L'assegno in tasca è freddo, e così l'acqua alla porta al mattino. Non dimenticherai presto come l'hai guadagnato.",
129: "La passerella della chiusa era una trappola, come Jack Reed aveva avvertito. L'hai attraversata nel buio, e si è presa tutta la notte. Ti trascini fuori, fradicio e tremante, e raggiungi le case in fondo troppo tardi. La gora ti è costata tutto ciò che la scorciatoia prometteva.",
130: "Hai passato la notte sulle cose sbagliate, e il muro è rimasto basso troppo a lungo. All'alba, il fiume è a ogni porta, e la via è rovinata. Sei uscito sotto la pioggia. Ma non hai tenuto il muro quando contava.",
131: "Alla fine, sei rimasto dentro, al caldo e al sicuro. Ti sei detto che il fiume era troppo alto, che non era affar tuo, che l'aiuto sarebbe venuto all'alba. Era tutto vero. E tutta la notte, fuori, il muro è rimasto non costruito. Non ti è successo nulla di male. Ci penserai a lungo, a lungo.",
}
def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    data = json.load(open(OUT, encoding="utf-8")) if os.path.exists(OUT) else {}
    a = 0
    for nid, t in G.items():
        k = str(nid)
        if k not in data: a += 1
        data[k] = t
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print("high-water/it.json: %d (+%d)" % (len(data), a))
if __name__ == "__main__":
    main()
