#!/usr/bin/env python3
"""The Keeper — full Portuguese per-passage gist coverage (merges to 112/112).
Native review: complete. Run: python3 scripts/g_pt_ep05.py"""
import json, os
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "the-keeper", "pt.json")

G = {
 2: "Reúnes o que há na torre: uma lata de óleo, pavios sobresselentes, uma caixa de fósforos, um bom candeeiro de tempestade. Lá fora, o vento uiva na balaustrada da galeria e a chuva bate no vidro como pedras atiradas. Tens de decidir o que fazer, e depressa.",
 3: "Tentas o rádio. Chia e cospe, mas por fim a voz do Tam chega da estação da costa. Nenhum barco salva-vidas pode sair para um mar destes, diz ele — não até acalmar ou vir a aurora. Mantém a luz acesa, se puderes.",
 4: "Chegas junto da Nan ao pé das escadas e acomoda-la o melhor que podes. Mas a luz continua apagada, e abrigo sozinho não chega: aquele barco lá fora precisa do feixe. Precisas de óleo, de um plano e de cabeça fria antes de subir.",
 5: "Sais para a galeria. O mar é negro e imenso, a chuva achatada pelo vento. Ao longe, passada a ponta, as luzes do barco mostram-se pequenas e a lutar. Debaixo de ti a enseada é um poço de escuridão, e toda a costa ruge.",
 6: "Obrigas-te a pensar. Podias acender a luz primeiro e preocupar-te com o resto depois. Podias ir direto à Nan e às casas. Ou podias acordar a costa para ajudar. Cada escolha custa tempo — e esta noite, o tempo é um barco a aproximar-se das rochas.",
 8: "Sentes a tempestade instalar-se no teu peito. Pensas naquele barco passada a ponta, a fechar sobre as rochas sem luz que o guie. Uma noite destas pode afogar uma tripulação inteira. Não é medo; é um facto. Mais ninguém vai subir aquela torre. Então tens de ser tu.",
 11: "Sobes depressa ao candeeiro com o pouco que tens. Um fósforo, uma faísca, um lampejo de chama — pega, mas é fraca, e não aguenta sem óleo a sério. Não podes deixá-la assim e esperar.",
 13: "Assumes o óleo e o pavio. A lata é pesada, e agora cada gota conta. Bem cuidada, mantém o candeeiro aceso toda a noite; desperdiçada, e a luz apaga-se. Por isso mante-la bem junto a ti e começas a subir.",
 14: "Pegas num candeeiro de tempestade e num rolo de corda. Dão-te alguma luz e uma forma de te amarrares — mas não o feixe, e não tens óleo a sério guardado. Vais precisar de óleo a sério na mesma, e depressa, ou a torre fica às escuras.",
 15: "O contramestre Carrick conhece esta costa; vigia-a há anos. «Fica longe do trilho da falésia», diz. «Parece rápido. Mata.» Também te avisa do saqueador. «Cuida do teu óleo, segura a luz — é todo o trabalho desta noite.»",
 16: "Acomodas o velho Finch com um candeeiro aceso e um cobertor, e devagar o tremor dele acalma. «Que sejas abençoado», diz, apertando-te a mão. Prometes voltar a vê-lo, e viras-te para a tempestade.",
 17: "Segues para manter a luz; isso vem primeiro, e o resto pode esperar um momento. Mas ainda tens de decidir como — garantir óleo a sério primeiro, ou subir direto ao candeeiro.",
 18: "A subida esgota-te: pernas a arder, peito ofegante, o vento a combater-te a cada degrau. Estás perto do teu próprio limite, e sabe-lo. Se caíres aqui, não sobra ninguém para manter a luz. Por isso vai devagar, e agarra-te ao corrimão.",
 19: "A costa acorda para si mesma. As pessoas começam a mexer-se. Um homem faz rolar um barril de óleo, uma mulher arrasta lenha seca, e um plano toma forma porta a porta. Já não fazes isto sozinho — e isso muda tudo.",
 20: "Ninguém se mexe. As portas ficam fechadas, as caras viram-se das janelas: têm medo, e os assustados calam-se. Não podes forçá-los. Então viras-te e segues sozinho; é mais difícil assim, mas aquele barco não pode esperar que eles sejam corajosos.",
 21: "A luz está tratada; agora a enseada e aquele barco. Há dois caminhos para descer. O longo, à volta do cabo, é seguro mas lento. O da falésia, direto para baixo, é rápido — e um assassino com um vento destes.",
 22: "Levas a sério as palavras do Carrick. Cuidar bem do óleo, manter-te bem longe da falésia, não confiar no saqueador, e segurar a luz acima de tudo. É um conselho simples, e bom. Agora só tens de o seguir mesmo, aqui fora no escuro e no vento.",
 23: "Sentes-te mais firme pelo bom gesto que fizeste — ajudar alguém, por estranho que pareça, parece firmar-te também. Tens a cabeça mais clara, as mãos mais seguras. Há ainda uma noite dura pela frente, mas sentes-te capaz de a enfrentar.",
 24: "Um homem está na rebentação, um lampião a baloiçar-lhe no punho: o saqueador. Tem óleo para vender e costas fortes para oferecer, e sorri com demasiada facilidade. «A luz não é trabalho teu esta noite, amigo», diz. Já conheces os da laia dele.",
 25: "Guias um pequeno bando rumo à luz. A caminhar juntos, sentem-se todos mais fortes; levam óleo, lenha, corda. «Por aqui!», gritas por cima do vento, e vêm — uma boa sensação, numa hora difícil.",
 26: "O trilho do cabo é negro e duro, a chuva a escorrer por ele, o vento a empurrar-te as costas, sem abrigo em parte nenhuma. Mas é firme sob os pés, e vai para onde precisas. Então continuas a andar.",
 28: "Sais para o rebordo, e logo sentes que está errado. O precipício abre-se em baixo, negro e fundo; o vento bate na falésia e puxa-te o casaco. Cada passo é uma aposta — e agora estás lá fora, sozinho.",
 29: "O pavio do candeeiro de mão está estragado; dá só uma chama baixa e vacilante que não alcança longe. De pouco serve numa tempestade destas. Vais ter de te arranjar — ou voltar ao armazém por um melhor.",
 30: "O trilho continua ao longo do cabo, a tempestade pior a cada hora. Em baixo, uma casa baixa tem o mar a entrar. À frente, o vento quase te deita ao chão. E há um poste de marcação, meio arrancado pelo vendaval.",
 31: "Um barco pequeno está inundado na rampa, um velho preso nos cabos, o mar a arrastá-lo — não consegue soltar-se. Se paras, perdes tempo; se não, a próxima onda grande pode levá-lo.",
 33: "Avanças pelo pior da tempestade, cada passo agora uma luta, a chuva a ferir-te a cara. À frente há escolhas: o saqueador pode estar perto, ou a luz estranha sobre a água — ou podes ir direto à torre.",
 34: "Libertas o velho, e o barco solta-o. Enchem-se-lhe os olhos; enfia-te um oleado seco nas mãos. «Leva», diz, «pelo incómodo». Pouca coisa — mas dada de bom grado, e aceita-la e segues.",
 35: "Não podes parar agora — mas também não os podes deixar assim. Então prometes mandar ajuda. «Aguentem!», gritas. «Fiquem no alto, fiquem juntos — não me esqueço de vocês.» E é a sério — depois viras-te e vais.",
 36: "A costa acende uma fogueira de sinal no cabo: um barril em chamas, a lançar luz e calor na tempestade. As pessoas apertam-se perto, aos velhos e aos fracos o melhor dela. Não é o feixe. Mas é uma luz, e agora é de todos.",
 37: "Casa a casa, a costa assustada torna-se uma que funciona. Agora as pessoas têm tarefas: um trata do fogo, um enrola a corda, um vigia o mar. O medo vira ação, e a ação vence a espera sempre.",
 38: "A tempestade rói-te a vontade. Uma vozinha diz: para, entra, descansa — ninguém te censuraria, e seria tão fácil. Mas pensas naquele barco sobre as rochas, e afastas a voz. Ainda não. Não enquanto a luz estiver apagada.",
 39: "Chegas ao poste de marcação, mas o vendaval arrancou-lhe metade; mal o consegues ler. Um braço aponta ao longo do trilho, o outro para a água. Por onde? Vais ter de adivinhar, e adivinhar certo.",
 42: "Viras-lhe as costas e deixa-lo com a rebentação e o seu comércio frio. Sabe bem afastar-se. Ele chama por ti, mas não te viras. Os da laia dele arranjam sempre alguém — mas não a ti, e não esta noite.",
 43: "Aceitas o óleo dele, a moeda dele; as tuas mãos fecham-se à volta deles, e algo em ti já sabe. O sorriso dele alarga-se. «Sensato», diz. Mas não parece sensato. Parece uma porta a fechar-se algures no escuro.",
 44: "Perguntas-lhe sem rodeios: o que quer ele mesmo? Porque é que a luz deve ficar apagada? Sorri e olha para o mar. «Os navios dão nas rochas», diz. «O mar é generoso, depois.» Não diz mais nada — e isso, ali mesmo, é a tua resposta.",
 45: "Levas o óleo dele até ao candeeiro. Mas quando o despejas, a chama sufoca e cospe: o óleo está contaminado com água do mar, e não alimenta o pavio. O feixe vacila baixo e acastanhado. Ele deu-te ruína, não ajuda.",
 46: "Abres a lata e o cheiro atinge-te: salgado, ralo, cortado com água. Este óleo nunca alimentará uma chama; pagaste por ele, e não vale nada. A dúvida nas tuas tripas tinha razão sobre ele desde o início.",
 47: "Procura-lo, mas o lampião do saqueador já se foi, a descer para a enseada. Ele nunca te esteve a ajudar — esperava o escuro, o naufrágio, o frio presente do mar. Ficas ali, enganado, com o óleo inútil dele nas mãos.",
 48: "O saqueador foi-se, a enseada vazia: agora só a tempestade, o escuro, e o que lhe entregaste por nada. Aprendeste uma lição dura e pagaste demais por ela. Agora segues com o pouco que resta.",
 49: "As pessoas assustadas empurram-lhe as moedas: as mãos cheias de dinheiro, as vozes a implorar óleo, uma saída. E ele aceita, devagar, com aquele sorriso, escolhendo a quem ajudar conforme quem pode pagar. Agora vês o truque todo, claro e feio.",
 50: "Lá longe no rebordo, a enseada parece enfim mais perto... ou será? Já não tens a certeza; o escuro engana, o vento engana, os teus olhos cansados enganam. Estás encharcado e a tremer. Mas avanças pela beira.",
 51: "O rebordo, o vento, o negro precipício em baixo — e o teu pé escorrega na rocha molhada. É este o momento: cair pela beira no escuro, ou atirar-te para trás dela agora, enquanto ainda podes.",
 52: "Chegas à enseada enfim, encharcado e a tremer, as mãos em carne viva — mas em baixo. De algum modo, conseguiste. Agora tens de decidir: seguir em frente, esgotado como estás, ou enfrentar o que perdeste pelo caminho.",
 53: "Atiras-te para trás da beira enquanto ainda podes — a escolha dura e certa. Fazes o último troço de gatas, e chegas ao trilho abalado e lento. A noite consome-se. Mas estás vivo, e ainda capaz de ajudar.",
 54: "Tentas escorar a porta contra a água: uma arca arrastada, sacos empilhados, o que conseguires. Segura um pouco o pior do mar. Mas não há candeeiro para lhes deixar, e um quarto escuro e inundado é um mau sítio para esperar. Tens de escolher.",
 55: "Entregas o teu próprio casaco e o teu candeeiro, e a família aconchega-se à volta da pequena chama, o alívio a espalhar-se nos rostos. A criança para de chorar enfim. «Obrigada», diz a mãe, vezes sem conta. Tens agora menos com que aguentar — mas fizeste bem.",
 56: "Sem o teu casaco, o frio e a chuva encontram-te depressa: os dentes a bater, os dedos a enrijecer. Deste-o para ajudar, e voltarias a fazê-lo; mas à tempestade não importa. Só continua a fustigar. Tens de manter a cabeça, e continuar a andar.",
 57: "Um desconhecido acena-te para um portal. «Só um minuto», diz. «Fora da chuva — recupera o fôlego.» É quente e seco, e o corpo implora-te que fiques. Mas um minuto pode virar uma hora — e a luz continua apagada.",
 58: "Avanças para a tempestade, encharcado até aos ossos, o vento a combater cada passo, a chuva a cegar-te. Cada passo é uma pequena batalha — mas continuas a dá-los, um atrás do outro. Devagar está bem esta noite. Parar é o que mata.",
 60: "Alguém aponta para o cabo: uma figura saiu por ali, para a tempestade, rumo à ponta e sozinha. Daquele lado não há senão rocha, vento e o negro precipício. Se ninguém for atrás dela, não volta.",
 61: "Encontra-la agarrada às rochas, meio afogada e perdida, o vento a rasgar-lhe o casaco. Não parece reconhecer o teu rosto. Agarra-la firme pelo braço. «Vem comigo!», gritas por cima da tempestade. «Por aqui. Devagar agora.»",
 62: "Não podes fazer tudo ao mesmo tempo, e a luz é quem mais precisa de ti. Então mandas recado para outro ir atrás dela, e segues. Custa-te — mas tens de escolher, e escolhes a luz.",
 63: "Leva-la em segurança de volta às casas, onde a sua família grita de alívio. Envolvem-te num casaco seco e fazem-te um lugar junto ao fogo. «Obrigado», repetem — porque uma bondade nunca fica parada; move-se.",
 64: "Olhas a costa: toda escura, toda a rugir. Grandes ondas rebentam brancas nas rochas, e não se vê luz senão o barco distante e a lutar. Toda a costa parece suster a respiração, à espera que a tempestade quebre. E tu também, apercebes-te.",
 65: "O vento sobe ao seu pior e quase te arranca dos pés. Agachas-te e agarras-te, o ar cheio de salpicos e espuma rasgada. É difícil ver, difícil respirar. É a hora de sobreviver — passa-a, e aquele barco ainda tem uma hipótese.",
 67: "O Tam enfia-te o último candeeiro seco nas mãos. «Para a subida», diz. «Vai — eu fico no rádio.» Tem a cara cinzenta de preocupação. É a ajuda que tem para dar, e dá-a. Aceita-la, e agradeces-lhe.",
 68: "No armazém do óleo, as pessoas atiram-se às latas: vozes a subir, mãos a agarrar, o medo a pegar e a alastrar depressa. Mais um empurrão e é briga. Podes tentar acalmá-los e repartir com justiça, ou abrir caminho à força até ao óleo.",
 70: "Lá longe, passada a ponta, uma segunda luz sobe e desce. Está onde nenhum barco devia estar esta noite, a mostrar-se e a esconder-se e a mostrar-se outra vez no ondular. Ninguém sabe explicá-lo. Algo está lá fora, ou alguém.",
 71: "Desces à enseada e chamas para o escuro. Não responde senão o mar — depois vê-lo: a silhueta de um barco, baixo sobre as rochas, meio engolido pelas ondas. Alguém armou aquela luz. Alguém está lá fora.",
 72: "Vadeias até às rochas. Ali, no barco inundado, está um velho pescador — o Ash — enredado nos cabos e a aguentar-se a custo. O mar arrasta-o a cada onda. Não há tempo a perder.",
 73: "Chamas de novo para o escuro, e por um momento não há nada. Depois volta uma voz, fraca e rasgada pelo vento: «Aqui! Aqui fora!» Alguém está nas rochas, e precisa de ajuda. Já não podes virar costas a isto.",
 74: "Arrastas o Ash para fora dos cabos, sobe-lo pelas rochas e envolve-lo no teu casaco. Devagar volta a si, agarrando-te o braço. «A luz», arqueja. «Mantém a luz. Pode haver outros lá fora.»",
 75: "Viras-te para correr atrás de ajuda — depois paras. Aqui fora não há ajuda; não até à aurora. Sem salva-vidas, sem tripulação, ninguém a vir. É contigo ou com ninguém, e o Ash também o sabe. Os olhos dele seguem-te pelas rochas.",
 76: "O Ash olha para ti, os olhos mais claros agora. «A faroleira, lá em cima na torre — a Nan?», diz. «É minha mãe. Não falamos há anos. Não desde — enfim. É uma longa história, e uma noite fria para ela.»",
 77: "Decides juntá-los cara a cara antes de a noite acabar — o Ash e a velha Nan, após todos estes anos. É pouca coisa, ao lado da luz e da tempestade. Mas não é nada; certas portas ficam anos fechadas só porque ninguém se atreve a bater. Tu atreves-te.",
 78: "O barco está rombado, meio submerso, o mar a trabalhá-lo a cada onda — não aguenta muito. E no entanto alguém pôs uma luz a arder nele, alguém saiu para estas rochas no escuro. Alguém está aqui.",
 79: "Vadeias mais perto e vês o nome na proa, e reconhece-lo. É o próprio barco da Nan — o que se perdeu há anos, ou assim diziam sempre. Depois, de baixo do casco partido, um som fraco: uma tosse. Alguém está vivo lá dentro.",
 80: "O saqueador sobe uma última vez, o lampião a baloiçar. «Ainda a lutar?», diz. «Deixa-a apagar-se. Última hipótese de estar no lado vencedor, amigo.» O mesmo sorriso, a mesma mentira. Sabe que estás esgotado, e conta com isso. Agora escolhes, de vez.",
 90: "Estás de volta à torre, encharcado, o fim da pior tempestade a fustigar o vidro. Em baixo, a Nan jaz cinzenta ao pé das escadas; em cima, o candeeiro arde baixo. É a hora que conta; o que fizeres agora, fá-lo bem. Aquele barco está perto das rochas.",
 91: "Chegas ao candeeiro: a chama baixa, a grande lente parada. Passado o vidro, as luzes do barco estão perto das rochas agora, perto demais. Tens de pôr o feixe cheio e a girar, e já. Tudo o que fizeste esta noite resume-se a isto.",
 92: "Então chega ajuda à torre atrás de ti: mãos, óleo, cabeças calmas, gente que conhece a luz. Já não estás sozinho nisto; há outros para dividir o peso. É como pousar uma carga pesada, e enfim deixas sair o ar.",
 93: "Agora manténs o feixe — e o que podes fazer depende do que levaste. Com óleo a sério, tens muito com que trabalhar; sem ele, tens de afagar cada último lampejo da chama. De uma maneira ou de outra, começas.",
 94: "Desces a ver a Nan, e os olhos dela abrem-se um pouco: medo neles, depois, ao ver-te, um pouco menos. «Mantiveste-a acesa», sussurra. «Mantive», dizes-lhe. «Agora descansa. Eu tenho a luz.»",
 95: "O óleo consegue-o. Apara-la o pavio a rigor, rodas a grande lente como um relógio, e o feixe varre cheio e dourado a água negra. Uma luz em toda aquela escuridão. É para isto que serve a torre; sabia-lo, e agora vê-lo.",
 96: "Não tens óleo a sério para despejar, por isso afagas a chama que há. Proteges-la da corrente com o teu próprio corpo, alimentando-a de restos, de fôlego, de vontade. Arde baixa e fina. Pode bastar. Pode não bastar. Mas não a vais deixar apagar.",
 97: "A chama está baixa e a falhar, e temes que protegê-la não baste. Fizeste tudo o que podes com o que tens — mas pode não aguentar. Precisas de mais: óleo, ou mãos, ou ambos, e depressa.",
 98: "Olhas para fora e vê-la. Lá longe no mar, uma luz chameja e cai, onde nenhum barco devia estar, a mostrar-se e a esconder-se e a mostrar-se outra vez. Puxa-te o olhar, e algo dentro de ti. Alguém está lá fora.",
 99: "A luz sobre a água mostra-se de novo, onde todos juram que nenhum barco estaria. Mas uma luz significa uma mão que a acendeu, e uma mão significa uma pessoa, e uma pessoa lá fora esta noite está em apuros a sério. Pressente-lo.",
 100: "Agora vem a longa resistência: manténs o feixe a girar, manténs a Nan quente e a respirar, vigias a água negra hora após hora. Não é emocionante — só trabalho firme, duro, cuidadoso. Mas é o trabalho firme que salva as pessoas, por isso fá-lo, e não paras.",
 101: "E então, por fim, vira. O vento baixa um tom, a chuva acalma, o céu acinzenta na borda do mar. E uma luz contorna a ponta: o salva-vidas, enfim lá fora. Seguraste a luz até à primeira luz. Conseguiste.",
 102: "É a pior hora, a mesmo antes da viragem. A tempestade ainda não cedeu; os braços doem-te da lente; os olhos ardem-te. Mas sentes a noite a começar a virar. Aguenta. Aguenta mais um pouco. O fim está perto agora.",
 103: "Ao longo do cabo vê-los: candeeiros, figuras escuras a mover-se, fogueiras de sinal a arder baixo contra a chuva. Outras pessoas, lá fora também. A costa também passou esta noite, e não foste o único de vigia. Isso aquece-te, de algum modo.",
 104: "Por fim, o salva-vidas: o seu candeeiro e um penacho de salpicos a contornar a ponta, a direito no mar. Ajuda a sério, a velocidade a sério. Agarras o corrimão e observas, as pernas a tremer debaixo de ti. Está quase a acabar. Quase. Permites-te acreditar.",
 105: "A aurora sobe sobre o mar bravo, a luz a tornar-se cinzenta, depois pálida e limpa, a tempestade a esgotar-se onda a onda. As grandes vagas ainda correm, mas o pior passou. A costa, tão cruel toda a noite, é quase gentil agora. Ficas a ver, e respiras.",
 106: "Então chega: a primeira gaivota, sobre a água cinzenta, a cavalgar o vento à vontade, como se não tivesse havido tempestade alguma. Depois da noite que tiveste, parece absurdo, e belo. Vê-la partir. Conseguiste. Conseguiram todos.",
 107: "Da torre observas a água, onde ao longe um candeeiro sobe e desce no ondular e cresce devagar. Algo vem enfim, ainda longe demais para distinguir. Mas um candeeiro lá fora significa uma mão — e uma mão, agora mesmo, significa esperança. Não lhe tiras os olhos, e esperas.",
 110: "A primeira luz chega por fim, e a noite soma o que é. O que fizeste lá em cima naquela torre, na tempestade, volta a casa agora: parte de que te orgulhar, parte não. É aqui que tudo se esclarece.",
 111: "A noite soma — nem sempre com um grande gesto, mas com muitos pequenos. O que mantiveste, o que recusaste, por quem subiste. Tudo conta no fim; tudo fez da noite o que foi. Então, em que deu a noite?",
 112: "Há mais a pesar; a noite guardou outras coisas também. Um desconhecido que ajudaste. Um casaco e um candeeiro que deste de mão aberta. Pequenas escolhas feitas na tempestade, quando passar ao lado teria sido fácil. Têm o seu próprio peso. Em que deram?",
 113: "E com que te deixa a noite? Talvez não com uma vitória limpa. Talvez só com o facto de teres subido, de teres tentado. Quando estava escuro e bravo e era fácil trancar a porta, não trancaste. Isso vale algo. Sempre valeu.",
 114: "Mas nem toda a noite acaba bem. Certas escolhas custam mais do que sabias; certas portas, uma vez abertas, não se voltam a fechar. É o fim duro da noite, onde o pior volta a casa. Não é fácil de olhar — mas é verdade. Então olha.",
}

def main():
    data = json.load(open(OUT, encoding="utf-8")); a = 0
    for nid, t in G.items():
        k = str(nid)
        if k not in data:
            data[k] = t; a += 1
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"the-keeper/pt.json: {len(data)} (+{a})")

if __name__ == "__main__":
    main()
