#!/usr/bin/env python3
"""The Orchard — full Portuguese per-passage gist coverage (merges to 112/112).
DRAFT quality — pending native review. Run: python3 scripts/g_pt_ep06.py"""
import json, os
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "the-orchard", "pt.json")

G = {
 2: "Reúnes o que há no barracão: uma lata de óleo, fósforos, um bom candeeiro, um braçado de palha seca. Lá fora, o ar está numa calmaria morta e faz um frio cortante. A geada já se arrasta branca pela relva. Tens de decidir o que fazer, e fazê-lo depressa.",
 3: "Tentas o telefone. Toca e toca, e por fim a voz do Tom chega da cooperativa. Nenhuma equipa pode sair antes de manhã, diz ele — não com uma geada destas. Acende as fogueiras ao longo das fileiras, diz-te, e mantém-nas se de algum modo conseguires.",
 4: "Chegas junto da Edith ao pé dos degraus. Acomoda-la e aquece-la o melhor que podes. Mas as fileiras continuam escuras e frias. Abrigo sozinho não chega. A flor lá fora precisa das fogueiras acesas. Precisas de óleo, de um plano e de cabeça fria antes de sair por entre as árvores.",
 5: "Sais por entre as fileiras. A noite é imensa e numa calmaria morta, e a flor pálida parece brilhar no escuro. O frio comprime todo o pomar como uma mão. Então, ao longe, entre as árvores do fundo, apanha-lo: uma luzinha a mover-se, ali onde ninguém devia estar esta noite.",
 6: "Obrigas-te a parar e a pensar. Podias acender primeiro as fogueiras e preocupar-te com o resto depois. Podias ir ter com a Edith e os vizinhos em vez disso. Ou podias acordar a aldeia e trazer mais mãos. Cada escolha custa um tempo que não tens — e lá fora no escuro a geada já trabalha as árvores.",
 8: "O frio instala-se no teu peito como um peso. Pensas na flor lá fora: a fruta de um ano inteiro, o pomar que é tudo o que resta à Edith. Se as fogueiras ficarem apagadas muito mais, a geada leva cada pedacinho dela até à aurora. Não é medo; é um facto simples. Mais ninguém vem meter-se nisto e fazê-lo. És tu, esta noite, ou ninguém.",
 11: "Sais direto às fileiras e acendes o que podes. Um fósforo, um clarão de palha, um braseiro a pegar aqui e ali. Mas as chamas são finas e baixas. Sem óleo a sério não duram uma hora. Não podes só acendê-las, ir-te embora e esperar.",
 13: "Assumes tu próprio o óleo e a palha. O bidão é pesado, e agora cada gota conta. Cuidado com atenção, mantém as fogueiras a arder ao longo das fileiras toda a noite; desperdiçado, e a flor gela antes da aurora. Por isso mante-lo bem junto a ti e segues para as árvores.",
 14: "Pegas só num candeeiro e num molho de lenha miúda. Dão-te luz para trabalhar e um modo de acender uma chama. Mas não as fogueiras em si. E não puseste óleo a sério de parte. Vais precisar de óleo a sério na mesma, e depressa. Se não, as fileiras ficam às escuras e a geada vence.",
 15: "O velho Jack Hale conhece este pomar no escuro melhor do que ninguém. «Fica longe do lago gelado», diz. «Parece um atalho. Não é: é afogares-te.» Também te avisa do comprador, aquele homem sorridente da empresa. «Cuida do teu óleo, segura as fogueiras — é todo o trabalho desta noite.»",
 16: "Acendes o fogão do senhor Hollis e acomoda-lo ao lado com um cobertor. Aos poucos o tremor dele acalma. «Que sejas abençoado», diz, apertando-te forte a mão. Prometes voltar a vê-lo antes de manhã. Depois viras-te de novo para a geada e para as fileiras que esperam.",
 17: "Manter as fogueiras vem primeiro. O resto pode esperar um momento. Mas ainda tens de escolher como. Podias ir buscar óleo a sério ao armazém primeiro. Ou podias sair direto às fileiras e começar.",
 18: "O trabalho esgota-te. As pernas ardem, o peito ofega, e o frio combate-te a cada passo. Estás perto do teu próprio limite, e sabe-lo. Se caíres aqui, não sobra ninguém para manter as fogueiras. Por isso vai devagar, e vai com cuidado.",
 19: "A aldeia acorda para si mesma, e as pessoas começam a mexer-se. Um homem faz rolar um barril de óleo. Uma mulher arrasta lenha seca. Porta a porta, um plano toma forma. Já não fazes isto sozinho. E isso muda tudo.",
 20: "Ninguém se mexe. As portas ficam fechadas, e as caras viram-se das janelas. Têm medo, e os assustados calam-se. Não podes forçá-los a ajudar. Então viras-te e segues sozinho. É mais difícil assim. Mas a flor não pode esperar por eles.",
 21: "As fogueiras próximas vão a arder. Agora as fileiras do fundo. Há duas maneiras de lá chegar. O carreiro longo à volta é seguro mas lento. O lago gelado é rápido, a direito. Mas com uma geada destas, o gelo pode matar.",
 22: "Levas a sério as palavras do Jack Hale. Cuida bem do óleo. Mantém-te bem longe do lago gelado. Não confies no comprador. E segura as fogueiras acima de tudo o resto. É um conselho simples, e bom. Agora só tens de o seguir.",
 23: "Sentes-te mais firme pelo bom gesto que fizeste. Ajudar alguém, por estranho que pareça, parece firmar-te também. Tens a cabeça mais clara, e as mãos mais seguras. Há ainda uma noite dura pela frente. Mas agora sentes-te capaz de a enfrentar.",
 24: "Um homem está no carreiro, um lampião a baloiçar-lhe no punho: o comprador. Tem óleo para vender e costas fortes para oferecer, e sorri com demasiada facilidade. «O pomar não é bem trabalho teu esta noite, amigo», diz. Já conheces os da laia dele.",
 25: "Guias um pequeno bando rumo às fogueiras. A caminhar juntos, sentem-se todos mais fortes. Levam óleo, lenha e palha. «Por aqui!», chamas para o frio, e vêm. É uma boa sensação, numa hora difícil.",
 26: "O carreiro é negro e duro, o frio a comprimi-lo, sem abrigo em parte nenhuma. Mas é firme sob os teus pés, e vai para onde precisas. Então continuas a andar, passo após passo.",
 28: "Sais para o gelo, e logo sentes que está errado. A água espera em baixo, negra e funda e gelada. Cada passo é uma aposta agora — e estás lá fora, sozinho. Não há volta atrás depois de começares a atravessar.",
 29: "A palha está húmida e não pega. Dá só uma chama baixa e vacilante. De pouco serve numa geada destas. Vais ter de te arranjar com ela. Ou voltar ao armazém por palha seca.",
 30: "O carreiro continua ao longo das fileiras, o frio a aprofundar-se a cada hora. Em baixo, uma casa está às escuras, sem lume dentro. À frente, o ar parado e duro parece empurrar-te para trás. E há um marcador de fileira, meio caído na geada.",
 31: "Um velho caiu no carreiro gelado e não consegue levantar-se. O frio já se apodera dele. Se paras, perdes um tempo que não tens. Se não, pode não aguentar a hora.",
 33: "Avanças pelo pior do frio, cada passo agora uma luta, a geada a ferir-te a cara. À frente há escolhas. O comprador pode estar perto. Há aquela luz estranha entre as árvores do fundo. Ou podes seguir direto para as fileiras.",
 34: "Pões o velho de pé e aquece-lo o melhor que podes. Enchem-se-lhe os olhos, e enfia-te um saco seco nas mãos. «Leva», diz, «pelo incómodo». Pouca coisa — mas dada de bom grado, e aceita-la e segues.",
 35: "Não podes parar agora — mas também não os podes deixar assim. Então prometes mandar ajuda em breve. «Aguentem!», gritas. «Fiquem quentes, fiquem juntos — não me esqueço de vocês.» E é a sério, além disso. E depois viras-te e vais.",
 36: "A aldeia acende uma grande fogueira entre as fileiras — um barril em chamas, a lançar luz e calor na geada. As pessoas apertam-se perto, aos velhos e aos fracos o melhor dela. Não é o pomar todo salvo. Mas é um calor a sério, e um começo.",
 37: "Casa a casa, a aldeia assustada torna-se uma que funciona. Agora as pessoas têm tarefas: um trata do lume, um acarreta palha, um vigia as fileiras. O medo vira ação. E a ação vence a espera, uma vez após outra.",
 38: "O longo frio rói-te a vontade. Uma vozinha diz: para, entra, descansa — ninguém te censuraria, e seria tão fácil. Mas pensas na flor lá fora nas árvores. E afastas a voz. Ainda não. Não enquanto ainda puder ser salva.",
 39: "Chegas ao velho marcador de fileira, mas a geada rachou-o e meio derrubou-o. Mal o consegues ler agora. Um braço aponta ao longo das fileiras. O outro aponta para as árvores do fundo. Por onde? Vais ter de adivinhar, e adivinhar certo.",
 42: "Viras-lhe as costas e deixa-lo com o seu comércio frio. Sabe bem afastar-se. Ele chama por ti, mas não te viras. Os da laia dele arranjam sempre alguém, no fim. Mas não serás tu, não esta noite.",
 43: "Aceitas o óleo dele e o dinheiro dele. As tuas mãos fecham-se à volta deles, e algo em ti já sabe. O sorriso dele alarga-se. «Sensato», diz. Mas não parece nada sensato. Parece uma porta a fechar-se em silêncio.",
 44: "Perguntas-lhe sem rodeios: o que quer ele mesmo, e porque é que o pomar deve falhar? Sorri e olha carreiro abaixo. «A terra sai barata depois de um ano mau», diz. «Uma geada destas é uma bênção — para um comprador como eu.»",
 45: "Levas o óleo dele até aos braseiros. Mas quando o despejas, a chama sufoca e cospe. O óleo é ralo, cortado com água — não alimenta o lume. As chamas afundam-se baixas e acastanhadas e inúteis.",
 46: "Abres a lata, e o cheiro atinge-te: ralo, azedo, cortado com água. Este óleo nunca alimentará uma chama. Pagaste bom dinheiro por ele, e não vale nada. A dúvida nas tuas tripas tinha razão desde o início.",
 47: "Procura-lo, mas o lampião do comprador já se foi, carreiro abaixo. Ele nunca te esteve a ajudar. Esperava a geada, a colheita perdida, a terra barata depois. Foste enganado, pura e simplesmente.",
 48: "Ele foi-se, e o carreiro está vazio — agora só o frio, o escuro, e o que lhe entregaste por nada. Aprendeste uma lição dura esta noite. E pagaste demais por ela. Agora segues com menos do que começaste.",
 49: "As pessoas assustadas empurram-lhe as moedas. As mãos cheias de dinheiro, as vozes a implorar óleo. Ele aceita devagar, com aquele mesmo sorriso. Escolhe a quem ajudar conforme quem pode pagar mais.",
 50: "Lá longe no gelo, as fileiras do fundo parecem enfim mais perto... ou será? Já não tens a certeza. O escuro engana, e os teus olhos cansados também. E agora estás longe de ambas as margens.",
 51: "O gelo, o escuro, a água funda em baixo — e uma fenda corre de sob o teu pé. É este o momento. Podes afundar-te na água gelada. Ou podes atirar-te para trás da fenda, enquanto ainda podes.",
 52: "Chegas às fileiras do fundo enfim, encharcado e a tremer, as mãos em carne viva — mas do outro lado. De algum modo, conseguiste. Agora tens de decidir: seguir em frente, esgotado como estás, ou enfrentar o que perdeste no gelo.",
 53: "Atiras-te para trás da fenda enquanto ainda podes — a escolha dura e certa. Fazes o último troço de gatas, e chegas à margem abalado e lento. A noite não está perdida. Mas custou-te um tempo que vais sentir falta.",
 54: "Tentas pôr o fogão deles a trabalhar, e tapas o pior das correntes de ar com sacos e uma arca velha. Segura um pouco do frio. Mas ainda não há candeeiro para lhes deixar, e a noite está longe de acabar.",
 55: "Entregas o teu próprio casaco e o teu candeeiro, e a família aconchega-se à volta da pequena chama, o alívio a espalhar-se nos rostos. A criança para de chorar enfim. «Obrigada», diz a mãe — e depois aponta-te para uma luz, lá entre as árvores do fundo.",
 56: "Sem o teu casaco, o frio e a humidade encontram-te depressa — os dentes a bater, os dedos a enrijecer. Deste-o para ajudar, e voltarias a fazê-lo. Mas à geada não importa nada disso. Só morde com mais força.",
 57: "Um desconhecido acena-te para um portal iluminado. «Só um minuto», diz. «Fora do frio — recupera o fôlego.» É quente e seco, e todo o teu corpo implora-te que fiques. Mas um minuto assim pode deslizar em silêncio para uma hora.",
 58: "Avanças para a geada, gelado até aos ossos, o frio a combater cada passo, os olhos a lacrimejar e a arder. Cada passo é uma pequena batalha por si. Mas continuas a dá-los, um atrás do outro, rumo às fileiras.",
 60: "Alguém aponta para as árvores do fundo: uma figura saiu por ali, sozinha, para o frio e o escuro. Lá fora não há senão geada e o chão baixo e mortal. Se ninguém for atrás dela, pode não voltar.",
 61: "Encontra-la entre as árvores do fundo, meio gelada e perdida, o frio a rasgá-la. Não parece reconhecer de todo o teu rosto. Agarra-la firme pelo braço. «Vem comigo», dizes. «Já estás bem. Eu tenho-te.»",
 62: "Não podes fazer tudo ao mesmo tempo, e as fogueiras são as que mais precisam de ti. Então mandas recado para outro ir atrás dela, e segues. Custa-te — mas esta noite tens de escolher, e continuar a escolher.",
 63: "Leva-la em segurança de volta às casas, onde a sua família grita de alívio. Envolvem-te num casaco seco e fazem-te um lugar junto ao lume. «Obrigado», repetem. Mas as fileiras esperam, e não podes ficar muito.",
 64: "Olhas todo o pomar — tudo branco, tudo parado. A flor brilha pálida e frágil no escuro. Não se vê luz em parte nenhuma a não ser entre as árvores do fundo. Todo o pomar parece suster a respiração e esperar a aurora.",
 65: "O frio aprofunda-se agora ao seu pior absoluto. O termómetro desce o mais que pode, e o teu fôlego pende branco no ar parado. É difícil pensar, difícil mexer-se, difícil importares-te. É a hora mais dura de toda a noite.",
 67: "O Tom enfia-te o último candeeiro seco nas mãos. «Para as fileiras», diz. «Vai — eu fico aqui junto ao telefone.» Tem a cara cinzenta de preocupação. É a ajuda que tem para dar esta noite, e dá-a toda de bom grado.",
 68: "No armazém do combustível, as pessoas atiram-se às latas — vozes a subir, mãos a agarrar, o medo a pegar e a alastrar depressa. Mais um empurrão e é briga. Podes tentar acalmá-los e repartir o óleo com justiça. Ou podes simplesmente agarrar o teu e ir.",
 70: "Lá longe entre as árvores do fundo, uma luzinha sobe e esmorece. Está ali onde ninguém devia estar esta noite — a mostrar-se, depois nada, depois a mostrar-se outra vez. Ninguém sabe explicá-lo. E algo em ti quer ir responder-lhe.",
 71: "Sais até às árvores do fundo e chamas para o escuro. Não responde senão o frio. Depois vê-lo: uma pequena silhueta, ali entre as árvores, meio escondida na geada branca. Alguém está aqui fora, afinal. E mal se mexe.",
 72: "Chegas junto deles, e o coração dá-te um baque. É uma criança — o Wren — enroscado na geada, meio gelado e mal acordado. O frio tem-no na sua garra. Não há tempo de esperar e pensar. Tens de fazer alguma coisa já.",
 73: "Chamas de novo para o escuro, e por um momento não há nada. Depois volta uma voz fina, rasgada pelo frio: «Aqui! Aqui fora!» Alguém está entre as árvores, e precisa de ajuda. E não soa nada forte.",
 74: "Levantas o Wren da geada e envolve-lo bem no teu casaco. Devagar volta a si, agarrando-te o braço. «As fogueiras», sussurra. «Mantém as fogueiras acesas. A flor...» Mesmo agora, meio gelado, pensa no pomar.",
 75: "Viras-te para correr atrás de ajuda — depois paras de repente. Aqui fora não há ajuda, não até de manhã. Sem equipa, sem vizinhos, ninguém a vir. É contigo ou com ninguém, e o Wren também o sabe. Os olhos assustados dele seguem-te no escuro.",
 76: "O Wren olha para ti, os olhos mais claros agora. «A cultivadora, a Edith — é a minha avó», diz. «Não falamos há anos. Não desde que o meu pai e ela se zangaram. É uma longa e triste história.» E ouves bem como é longa.",
 77: "Decides juntá-los cara a cara antes de a noite acabar — o Wren e a velha Edith, após todos estes anos. É pouca coisa, ao lado das fogueiras e da geada. Mas não é nada. Algumas portas fechadas ainda se podem abrir.",
 78: "A pequena silhueta não se mexe, e a geada trabalha sobre ela, fria e paciente. E no entanto alguém veio até aqui, ao escuro, sozinho. Não o podes deixar ali estendido. Tens de te aproximar e saber quem é.",
 79: "Aproximas-te, e reconhece-los logo. É o Wren — o neto da velha Edith, não visto por aqui há anos, não desde que a família se zangou. Depois um som fraco vem da geada aos teus pés. Mexes-te depressa agora.",
 80: "O comprador sobe uma última vez, o lampião a baloiçar. «Ainda a lutar?», diz. «Deixa a geada ficar com ele. Última hipótese de estar no lado vencedor, amigo.» O mesmo sorriso fácil. A mesma velha mentira.",
 90: "Estás de volta ao pomar, gelado até ao tutano, o frio mais duro da noite a comprimir tudo. Junto aos degraus das traseiras, a Edith jaz cinzenta e imóvel. Fora, nas fileiras, as fogueiras ardem baixas. É a hora de que depende toda a noite.",
 91: "Chegas às fogueiras: as chamas baixas, os braseiros do fundo já frios. Entre as fileiras do fundo, a geada está perto de levar a flor para sempre. Tens de pôr as fogueiras cheias e a arder de novo — e tens de o fazer já, depressa.",
 92: "Então chega-te ajuda enfim — mais mãos, mais óleo, gente firme que conhece o trabalho. Já não estás sozinho nisto; há outros para dividir o peso. É como pousar algo pesado que carregaste demasiado tempo.",
 93: "Agora manténs as fogueiras acesas — e o que podes fazer depende do que trouxeste aqui para fora. Com óleo a sério, tens muito com que trabalhar. Sem ele, tens de afagar cada último lampejo de chama. De uma maneira ou de outra, a noite está longe de acabar.",
 94: "Desces a ver a Edith, e os olhos dela abrem-se um pouco. Há medo neles — depois, ao ver o teu rosto, um pouco menos medo. «Mantiveste-as acesas», sussurra. «Mantive», dizes-lhe baixinho. «Agora descansa.»",
 95: "O óleo consegue-o. Alimentas os braseiros e aviva-los, e uma a uma as fogueiras levantam-se cheias e douradas por todas as fileiras. Luz quente a empurrar para trás todo aquele frio. É para isto, pensas, que serviu toda a noite dura.",
 96: "Não tens óleo a sério para despejar, por isso afagas a pouca chama que há. Proteges-la da corrente com o teu próprio corpo, alimentando-a de restos, de fôlego, de pura vontade. Arde baixa e fina. Pode não bastar. Mas não a vais deixar morrer sem lutar.",
 97: "A chama está baixa e a falhar, e temes que protegê-la sozinho não baste. Fizeste tudo o que podes com o que tens. Mas pode ainda assim não aguentar. Precisas de mais agora — mais óleo, mais mãos, ou ambos.",
 98: "Olhas para fora e vê-la. Lá entre as árvores do fundo, uma luz chameja e cai — onde ninguém devia estar, a mostrar-se e a esconder-se e a mostrar-se outra vez. Puxa-te o olhar. E puxa algo mais fundo do que isso.",
 99: "A luz lá entre as árvores mostra-se de novo — onde todos juram que ninguém estaria. Mas uma luz significa uma mão que a acendeu, e uma mão significa uma pessoa. Uma pessoa lá fora, sozinha, num frio como este.",
 100: "Agora vem a longa resistência: manténs as fogueiras alimentadas, manténs a Edith quente, e vigias o frio hora após hora. Não é emocionante — só trabalho firme, duro, cuidadoso. Mas é todo o trabalho desta noite, e é teu.",
 101: "E então, por fim, vira. O frio alivia um pouco o aperto. O céu acinzenta na borda da serra, e sobe a primeira luz ténue. A geada está a perder. Quase seguraste a noite inteira.",
 102: "É a pior hora, a mesmo antes da viragem. O frio ainda não cedeu; os braços doem-te, os olhos ardem-te. Mas sentes a noite a começar a virar, algures por baixo de tudo. Aguenta mais um pouco.",
 103: "Ao longo das fileiras vê-los — candeeiros, figuras escuras a mover-se, fogueiras a arder baixas contra a geada. Outras pessoas, lá fora no frio contigo. A aldeia também passou esta noite. Nunca estiveste tão sozinho como te sentias.",
 104: "Por fim, a ajuda sobe o carreiro — um camião, mais mãos, mais óleo, ajuda a sério a velocidade a sério. Encosta-te a uma árvore e vê-la vir, as pernas a tremer debaixo de ti agora. Mas o pior da noite ficou para trás.",
 105: "A aurora sobe sobre o pomar, a luz a tornar-se cinzenta, depois pálida e limpa. O sol trepa a serra, e a geada larga o aperto. A flor ainda está ali nas árvores. O pior passou enfim.",
 106: "Então chega — o primeiro pássaro da manhã, a cantar sobre as árvores como se não tivesse havido geada alguma. Depois da noite que tiveste, parece quase absurdo. E é belo, e paras para escutar.",
 107: "Do pomar observas as árvores do fundo, onde uma luz sobe e desce e cresce devagar. Algo vem enfim, ainda longe demais para distinguir. Mas uma luz significa alguém lá fora — e alguém é muito melhor do que ninguém esta noite.",
 110: "A primeira luz chega por fim, e a noite soma o que é. O que fizeste lá fora no frio volta a casa agora — parte de que te orgulhar, parte não. Vejamos, então, em que deu tudo.",
 111: "A noite soma — nem sempre com um grande gesto, mas com muitos pequenos. O que mantiveste, o que recusaste, por quem saíste para o frio. Tudo conta no fim. Tudo fez da noite o que foi.",
 112: "Há mais a pesar; a noite guardou outras coisas também. Um desconhecido por quem paraste. Um casaco e um candeeiro que deste de mão aberta. Pequenas escolhas, feitas no frio, quando teria sido mais fácil passar ao lado.",
 113: "E com que te deixa a noite? Talvez não com uma vitória limpa. Talvez só com o facto de teres saído, de teres tentado. Quando estava escuro e frio e era fácil trancar a porta, não trancaste. Isso vale algo.",
 114: "Mas nem toda a noite acaba bem. Certas escolhas custam mais do que sabias na altura; certas portas, uma vez abertas, não se voltam a fechar. É o fim duro da noite — o sítio onde o pior dela volta a casa.",
}

def main():
    data = json.load(open(OUT, encoding="utf-8")); a = 0
    for nid, t in G.items():
        k = str(nid)
        if k not in data:
            data[k] = t; a += 1
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"the-orchard/pt.json: {len(data)} (+{a})")

if __name__ == "__main__":
    main()
