#!/usr/bin/env python3
"""The Cool of Evening — full Portuguese per-passage gist coverage (merges to 112/112).
Run: python3 scripts/g_pt_ep04.py"""
import json, os
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "gist", "cool-of-evening", "pt.json")

G = {
 2: "Reúnes o que há no autocarro: umas garrafas de água, uma pequena caixa de primeiros socorros e uma grande lona de tela. Podia armar-se para dar sombra. O ar lá dentro já se adensa de calor, e o suor corre-te pelas costas. Tens de decidir o que fazer, e depressa.",
 3: "Tentas o rádio, mas está morto, e nenhum telefone tem rede. Chega a voz do motorista, o senhor Bello: com um calor destes nada se mexe, só virá ajuda ao anoitecer. Fiquem quietos, diz ele, e ao fresco. Mas o Sami é pequeno e vai-se apagando, e falta muito para a tarde.",
 4: "Levas o Sami para a estreita faixa de sombra junto ao autocarro. Ajuda um pouco, mas a sombra sozinha não chega — a criança precisa de água, e tu de um plano. Ficas um momento e percebes: de mãos vazias não podes fazer muito aqui.",
 5: "Desces para a estrada. O brilho é branco e duro, planícies ocres até à crista que tremeluz ao longe, o calor denso o bastante para nos encostarmos nele. A estrada está vazia nos dois sentidos — exceto, muito longe, por uma pequena figura que se afasta.",
 6: "Obrigas-te a pensar. Podias tratar primeiro dos mantimentos — água, sombra, um plano. Podias ir direto ao Sami e ficar com a criança. Ou podias ir banco a banco e pôr os passageiros a ajudar. Cada escolha custa tempo, e com este calor, o tempo custa água.",
 8: "Sentes o calor pesado no peito, e pensas no Sami — pequeno, calado agora, sem água, num ar como um forno. Um calor destes pode matar uma criança. Não é medo; é um facto. Mais ninguém se vai mexer. Então tens de ser tu.",
 11: "Chegas depressa ao Sami com o pouco que tens — uns goles, um pano molhado, um resto de sombra. Acalma a criança por um momento. Mas não aguenta; precisas de água a sério, e mais, e depressa. Não podes só sentar-te e esperar.",
 13: "Assumes a caixa de água. É pesada, e agora cada garrafa conta. Repartida devagar e com justiça, dá para aguentar; agarrada e desperdiçada, não. Por isso contas, e mante-la por perto.",
 14: "Pegas na lona e nos trapos. Vão dar sombra, e isso ajuda — mas não garantiste água. A sombra tira o sol; não molha uma boca seca. Vais ter de encontrar água na mesma, e encontrá-la depressa.",
 15: "A tia Rose conhece esta estrada; atravessou-a muitas vezes. «Fica longe das planícies abertas», diz. «Parecem perto. Não estão.» Também te avisa do homem da carrinha. «Raciona cada gota, espera que o sol baixe. É assim que se vive aqui.»",
 16: "Acomodas o senhor Danso à sombra e dás-lhe um gole lento de água. Aos poucos os olhos clareiam-lhe e volta a si. «Obrigado», diz, com a mão a tremer na tua. Prometes voltar a vê-lo, e voltas ao dia.",
 17: "Segues para tratar do Sami; a criança vem primeiro, e tudo o resto pode esperar um momento. Mas ainda tens de decidir como — se garantir água a sério primeiro, ou ir direto para o lado da criança.",
 18: "O calor está agora também em ti — a cabeça leve, a boca seca, as pernas estranhamente distantes. Estás perto do teu próprio limite, e sabe-lo. Se caíres, não sobra ninguém para o Sami. Por isso move-te devagar, e com cuidado.",
 19: "O autocarro acorda para si mesmo. As pessoas começam a mexer-se e a partilhar. Uma mulher tira um grande garrafão de água; um homem arma a lona para a sombra; e um plano toma forma banco a banco. Já não fazes isto sozinho — e isso muda tudo.",
 20: "Ninguém se mexe. As pessoas fitam as mãos, ou lá fora o brilho — assustadas, e os assustados calam-se. Não podes forçá-los. Então viras-te e segues sozinho; é mais difícil assim, mas o Sami não pode esperar que eles sejam corajosos.",
 21: "Os mantimentos estão tratados; agora precisas de água a sério. Há dois caminhos para a crista. Seguir a estrada, longa mas fácil de seguir. Ou cortar direto pelas planícies abertas — muito mais curto, mas sem trilho, sem sombra e desconhecido.",
 22: "Levas a sério as palavras da Rose. Racionar a água. Ficar longe das planícies. Não confiar no homem da carrinha, e esperar que passe o pior do sol. É um conselho simples, e bom. Agora só tens de o seguir mesmo.",
 23: "Sentes-te mais firme pelo bom gesto que fizeste — ajudar alguém, por estranho que pareça, parece ajudar-te também. Tens a cabeça mais clara, o passo mais seguro. Há mais que fazer, e o sol ainda está alto, mas sentes-te capaz.",
 24: "Uma carrinha está parada na berma, o motor a tiquetaquear no calor. Um homem encosta-se a ela, todo sorrisos, com água engarrafada e boleias à vila para oferecer. Uma pequena multidão juntou-se à volta dele — assustada, sedenta e pronta a pagar.",
 25: "Guias um grupinho rumo ao Sami e à sombra. A caminhar juntos, sentem-se todos mais fortes; as pessoas levam água, trapos, um pouco de esperança. «Por aqui», dizes, e seguem-te — uma boa sensação, numa hora difícil.",
 26: "A estrada é longa e castiga. O alcatrão amolece sob os pés; poças de miragem brilham à frente e somem quando chegas; e não há um resto de sombra em parte nenhuma. Mas está livre, e vai para onde precisas. Então continuas a andar.",
 28: "Sais para as planícies abertas, e logo sentes que está errado. A crista não se aproxima; atrás de ti a estrada esbate-se e perde-se no tremeluzir. Aqui fora não há senão calor e luz dura — e estás no meio, sozinho.",
 29: "A lona está rasgada e curta demais para dar muita sombra; ficas só com os trapos, que não cobrem todos. Vais ter de te arranjar — ou voltar aos mantimentos por algo melhor.",
 30: "A estrada continua sob o sol branco, o calor pior a cada hora, a tua sombra encolhida e dura sob os pés. À frente, um carro parado na berma; o sol martela-te a nuca; e há um sinal, com a tinta há muito estalada pelo calor.",
 31: "Um carro preso na areia, um velho tombado sobre o volante, o vidro descido, a cabeça pendida. Está sobreaquecido e esgotado demais para se mexer. Se paras, perdes tempo; se não, pode não aguentar a tarde.",
 33: "Avanças pelo pior do calor, cada passo mais duro que o anterior, o ar a queimar-te a garganta. À frente há escolhas: o homem da carrinha pode estar perto, ou o fumo estranho no desvio — ou podes ir direto ao autocarro.",
 34: "Encostas o ombro, e o carro solta-se. Ao velho enchem-se-lhe os olhos; enfia-te uma garrafa morna nas mãos. «Leva», diz, «pelo incómodo». Não está fria — mas é água, dada de bom grado, e aceita-la e segues.",
 35: "Não podes parar agora — mas também não os podes deixar assim. Então prometes mandar ajuda. «Aguentem», dizes-lhes. «Fiquem à sombra. Não me esqueço de vocês.» E é a sério — depois viras-te e vais.",
 36: "O autocarro constrói um único ponto de sombra. A lona armada no alto, a água reunida ao centro, os mais fracos — os velhos, os pequenos — acomodados onde é mais fresco. Não é muito. Mas é um plano, e agora é de todos.",
 37: "Banco a banco, o autocarro assustado torna-se um que funciona. Agora as pessoas têm tarefas: um vigia as crianças, um reparte a água, um segura a sombra. O medo vira ação, e a ação vence a espera sempre.",
 38: "O calor rói-te a vontade. Uma vozinha diz: para, senta-te, descansa — ninguém te censuraria, e seria tão fácil. Mas pensas no Sami à espera, e afastas a voz. Ainda não. Não enquanto a criança precisar de ti.",
 39: "Chegas ao sinal, mas o sol comeu-lhe a tinta toda; não resta uma palavra para ler. Um braço aponta estrada abaixo, o outro para o fumo. Por onde? Vais ter de adivinhar, e adivinhar certo.",
 42: "Viras-lhe as costas e deixa-lo com a multidão assustada e o dinheiro dela. Sabe bem afastar-se. Ele chama por ti, mas não te viras. Os da laia dele arranjam sempre alguém — mas não a ti, e não hoje.",
 43: "Contas o dinheiro — dói entregá-lo — e ele dá-te garrafas mornas e aquele sorriso largo. «A boleia vem», diz. «Espera aqui.» Algo em ti não acredita nele. Mas está feito, e o dinheiro foi-se.",
 44: "Perguntas-lhe sem rodeios: a água está sequer fria? Está limpa? Sorri e olha para o lado. «Molha, não molha?», diz, e não promete nada. Aí tens a tua resposta: um homem que não promete tem algo a esconder.",
 45: "Levas as garrafas de volta, e nas tuas mãos escaldam — quentes como água de banho, inúteis para uma criança. E a boleia prometida? Nunca vem. Esperas, olhas a estrada: nada. Levou-te o dinheiro e deu-te quase nada.",
 46: "Abres uma garrafa, e a água sabe a errado — morna, rala, levemente podre. Algo não está bem; isto não davas a uma criança. Pagaste bom dinheiro por água má, e a dúvida nas tuas tripas tinha razão desde o início.",
 47: "Procura-lo, mas a carrinha já se foi — só o seu pó paira na estrada distante, a rarear no calor. A boleia nunca foi real, nunca ia vir. Ficas ali, enganado, no meio da estrada vazia, com a tua água má e morna.",
 48: "A carrinha foi-se, a multidão dispersou-se — agora só o calor, a estrada vazia, os bolsos vazios. Aprendeste uma lição dura e pagaste demais por ela. Agora segues com o pouco que resta, e não é muito.",
 49: "A multidão empurra-lhe dinheiro — as mãos cheias de notas, as caras a implorar que o aceite. E ele aceita, devagar, com aquele sorriso, escolhendo a quem ajudar conforme quem pode pagar. Agora vês o truque todo, claro e cru. É feio.",
 50: "Lá longe nas planícies, a crista parece enfim mais perto... ou será? Já não tens a certeza; o calor dobra o ar, dobra o que vês, talvez dobre o que pensas. Estás tão cansado, tão seco. Mas segues.",
 51: "As planícies seguem sem fim, a crista nunca a crescer, a cabeça a girar enquanto o horizonte se parte e flutua. As pernas já não são tuas. É este o momento: cair aqui, a céu aberto — ou voltar atrás agora, enquanto ainda podes.",
 52: "Chegas enfim ao pé da crista, aos tropeções, a língua grossa e seca — mas lá. De algum modo, atravessaste-a. Agora tens de decidir: seguir em frente, esgotado como estás, ou enfrentar o que perdeste pelo caminho.",
 53: "Voltas para a estrada enquanto ainda podes — a escolha dura e certa. Fazes o último troço de joelhos, e chegas ao alcatrão abalado e lento. A tarde consome-se. Mas estás vivo, e ainda capaz de ajudar.",
 54: "Tentas armar alguma sombra à família — uma porta escorada, um pano pendurado, o que conseguires. Tira o sol um pouco. Mas não há água para dar, e sombra sem água só compra tempo. Tens de escolher.",
 55: "Entregas a tua própria garrafa, e a família bebe, devagar e com cuidado, o alívio a espalhar-se nos rostos. A criança pequena para de chorar enfim. «Obrigada», diz a mãe, vezes sem conta. Agora tens menos água — mas fizeste bem.",
 56: "Sem a tua água, o calor encontra-te depressa — a boca a secar, a cabeça a doer. Deste para ajudar, e voltarias a fazê-lo; mas ao sol isso não importa. Só carrega. Tens de manter a cabeça, e continuar a andar.",
 57: "Um desconhecido acena-te para uma faixa de sombra. «Só um minuto», diz. «Senta-te. Respira.» Fora do sol o fresco é uma bênção, e o corpo implora-te que fiques. Mas um minuto pode virar uma hora — e o Sami espera.",
 58: "Avanças para o brilho, a boca como papel, a luz brilhante o bastante para doer. Cada passo é uma pequena luta — mas continuas a dá-los, um atrás do outro. Devagar está bem aqui. Parar é o que te mata.",
 60: "Alguém aponta estrada abaixo: um passageiro afastou-se, dizem, rumo ao tremeluzir, atordoado pelo calor. Sozinho, a sol aberto, com nada daquele lado senão calor e distância. Se ninguém for atrás dele, não volta.",
 61: "Encontra-lo num barranco seco, aos tropeções, a pestanejar, sem reconhecer o teu rosto. O sol bateu-lhe com força; a pele está seca, não húmida, o que é mau sinal. Agarra-lo pelo braço. «Vem comigo», dizes. «Por aqui. Devagar agora.»",
 62: "Não podes fazer tudo ao mesmo tempo, e o Sami é quem mais precisa de ti. Então mandas recado para outro ir atrás do passageiro perdido, e segues. Custa-te — mas tens de escolher, e escolhes a criança.",
 63: "Leva-lo em segurança de volta ao autocarro, onde a família grita de alívio. Enfiam-te uma garrafa para partilhar e fazem-te um lugar à sombra. «Obrigado», repetem — porque uma bondade nunca fica parada; move-se.",
 64: "Olhas a planície — enorme, vazia, a tremeluzir no calor, nada a mexer-se em parte alguma. O mundo inteiro parece ficar imóvel, à espera que o sol baixe enfim. E tu também, apercebes-te.",
 65: "O sol sobe ao seu pior; é o pico do calor. O alcatrão amolece sob os pés, o próprio ar parece arder, e pensar ficou lento e difícil. É a hora de sobreviver. Passa-a, e quase ganhaste o dia.",
 67: "O Bello enfia-te a última garrafa fresca nas mãos. «Para a criança», diz. «Vai — eu fico com o motor.» Tem as mãos negras de óleo, e a tremer um pouco. É a ajuda que tem para dar, e dá-a. Aceita-la, e agradeces-lhe.",
 68: "À frente do autocarro, as pessoas atiram-se à água — vozes a subir, mãos a agarrar, o medo a pegar e a alastrar depressa. Mais um empurrão e é briga. Podes tentar acalmá-los e repartir com justiça, ou abrir caminho à força até à caixa.",
 70: "No desvio baixo ergue-se uma velha estação de comboio, fechada há anos; dizem-no todos. E no entanto hoje um fio fino de fumo sobe dela, e um velho moinho de vento gira devagar ao lado. Ninguém sabe explicá-lo. Algo, ou alguém, está ali.",
 71: "Chegas ao velho desvio, que de perto parece menos morto. Bates: nenhuma resposta. Bates outra vez: nada. Mas a porta não está fechada; está entreaberta, e pela fresta saem ar quente e cheiro a fumo.",
 72: "Entras, numa sala em penumbra e sufocante — e ali no chão jaz um velho, ao lado de um rádio morto, mal se mexendo. A respiração é curta, a pele seca e cinzenta. Está aqui caído há algum tempo, sozinho. Não há tempo a perder.",
 73: "Chamas à porta, e por um momento não há nada. Depois volta uma voz — fraca, seca, velha. «Aqui», diz. «Aqui dentro.» Há alguém lá dentro, e precisa de ajuda. Já não podes virar costas a isto.",
 74: "Pões mãos à obra — água aos lábios, devagar e firme, um pano molhado no pescoço, o ar quente abanado do rosto. Aos poucos o velho volta. Abre os olhos. «O poço», rouqueja. «Lá atrás. Fundo e frio. E o rádio, se o conseguires pôr a falar.»",
 75: "Viras-te para correr atrás de ajuda — depois paras. Aqui fora não há ajuda; não até ao anoitecer. Sem equipas, sem telefones, ninguém a vir. É contigo ou com ninguém, e o velho no chão também o sabe. Os olhos dele seguem-te até à porta.",
 76: "O velho olha para ti, os olhos mais claros agora. «Vieram no autocarro do meio-dia?», diz. «Então aposto que vem a bordo uma velha amiga minha — a Rose. Conhecemo-nos há muito, nesta estrada. Diz-lhe que o Faro ainda cá está.»",
 77: "Decides juntá-los cara a cara antes de o dia acabar — a Rose e o velho Faro, após todos estes anos. É pouca coisa, ao lado de água e sombra. Mas não é nada; certas portas ficam anos fechadas só porque ninguém se lembra de bater. Tu lembras.",
 78: "Lá dentro, o lugar guarda anos de pó — o ar seco, velho e parado, a madeira estalada pelo calor, nada movido há muito. E no entanto algo se moveu aqui: alguém acendeu aquele fogo; alguém pôs aquele moinho a girar.",
 79: "Na parede pende uma foto antiga, enrolada e amarelada. Nela, um jovem junto a este mesmo moinho, uma jovem a seu lado, ambos a rir. Conheces aquele rosto — é a Rose, a do autocarro, há muito tempo. Depois, da sala de trás, um som fraco.",
 80: "A carrinha volta uma última vez, o vidro a descer. «Ainda preso? Ainda com sede?», diz. «Última oportunidade, amigo.» O mesmo sorriso, a mesma mentira. Sabe que estás cansado, e conta com isso. Agora escolhes, de vez.",
 90: "Estás de volta ao autocarro, no fim do pior calor, o fôlego seco, a cabeça a martelar. E ali está o Sami — pálido à sombra, parado demais. É a hora que conta; o que fizeres agora, fá-lo bem. A vida da criança está por um fio.",
 91: "Ajoelhas-te ao lado do Sami. A criança escalda ao toque, respira rápido e curto, os lábios gretados e secos — mau, e a piorar. Tens de a arrefecer, e arrefecê-la já. Tudo o que fizeste hoje resume-se a este momento.",
 92: "Então chega ajuda ao autocarro atrás de ti — mãos, água, cabeças calmas, gente que sabe o que fazer. Já não estás sozinho nisto; há outros para dividir o peso. É como pousar uma carga pesada, e enfim deixas sair o ar.",
 93: "Agora arrefeces a criança — e o que podes fazer depende do que levaste. Se guardaste uma boa reserva de água, tens muito com que trabalhar; se não, tens de tirar o máximo do pouco que resta. De uma maneira ou de outra, começas.",
 94: "Examinas a criança, com suavidade e cuidado, e os olhos do Sami abrem-se um pouco — medo neles, depois, ao ver-te, um pouco menos. «Voltaste», sussurra a criança. «Disse que voltava», dizes-lhe. «Agora vamos arrefecer-te.»",
 95: "Abres a caixa de água, e faz toda a diferença. Goles regulares, panos molhados mudados muitas vezes no pescoço e nos pulsos, o calor da febre a ceder devagar. A respiração do Sami acalma. A água, bem repartida, é vida; sabia-lo, e agora vê-lo.",
 96: "Não tens caixa para abrir, por isso usas o que há. Trapos molhados na tua última água. Cada resto de sombra arrastado sobre a criança, o Sami a falar e aqueles olhos mantidos abertos. Pode bastar. Pode não bastar. Mas não vais parar de tentar.",
 97: "O calor está fundo na criança agora, e temes que trapos e sombra não o travem. Fizeste tudo o que podes com o que tens — mas pode não chegar. Precisas de mais: ajuda, ou água, ou ambos, e depressa.",
 98: "Ergues o olhar e vê-lo: lá longe, pelas planícies, um fio de fumo, e ao lado um moinho a girar devagar. Está onde não devia haver nada, onde a velha estação está fechada. Puxa-te o olhar, e algo dentro de ti.",
 99: "O fumo sobe onde não vive ninguém; todos juram que o lugar está morto. Mas fumo é fogo, e fogo é uma mão que o acendeu, e uma mão é uma pessoa. E uma pessoa aqui sozinha, num dia destes, pode estar em apuros a sério. Pressente-lo.",
 100: "Agora vem a longa resistência: manténs a criança fresca, fazes a água circular, esperas que o sol baixe hora após hora lenta. Não é emocionante — só trabalho firme, duro, cuidadoso. Mas é o trabalho firme que salva as pessoas, por isso fá-lo, e não paras.",
 101: "E então, por fim, vira. O brilho suaviza-se; o sol branco desliza para a crista; o ar começa, de leve, a arrefecer. E lá longe na estrada sobe pó: um camião, um a sério, a vir para aqui. Chegaste ao fresco da tarde.",
 102: "É a pior hora, a mesmo antes da viragem — o calor ainda sem ceder, o corpo gasto, a vontade puída. Mas sentes o dia a começar a pender. Aguenta. Aguenta mais um pouco. O fim está perto agora.",
 103: "Pela estrada longa vê-los — pó, brilhos de vidro ao sol baixo, outras pessoas, outros veículos. Outros também passaram este dia. Não foste o único aqui a lutar contra o calor, e esse pensamento aquece-te na luz que se apaga.",
 104: "Por fim, faróis — e uma longa coluna de pó atrás, a subir a estrada em direção a ti. Um camião. Ajuda a sério, a vir a velocidade a sério. Pões-te de pé e acenas, as pernas a tremer debaixo de ti. Está quase a acabar. Quase. Permites-te acreditar.",
 105: "A tarde desce sobre as planícies. A luz fica longa, dourada e limpa, o calor assassino a levantar-se fôlego a fôlego, as sombras a esticar-se de cada pedra. A terra, tão cruel há uma hora, é quase amável agora. Ficas a vê-la, e respiras.",
 106: "Então chega — o primeiro sopro fresco de vento, a atravessar as planícies para te tocar o rosto. Depois do dia que tiveste, parece um presente não merecido. Fechas os olhos e deixa-lo arrefecer o suor na pele. Conseguiste. Conseguiram todos.",
 107: "Do autocarro observas a estrada, onde uma coluna de pó se ergue ao longe e cresce. Algo vem enfim — ainda longe demais para distinguir, mas pó aqui significa rodas, e rodas, agora mesmo, significam esperança. Não lhe tiras os olhos, e esperas.",
 110: "O fresco da tarde chega por fim, e o dia soma o que é. O que fizeste aqui no calor volta a casa agora — parte de que te orgulhar, parte não. É aqui que tudo se esclarece.",
 111: "A tarde soma — nem sempre com um grande gesto, mas com muitos pequenos: o que partilhaste, o que recusaste, por quem paraste. Tudo conta no fim; tudo fez do dia o que foi. Então, em que deu o dia?",
 112: "Há mais a pesar; o dia guardou outras coisas também. Um desconhecido que ajudaste. Água que deste de mão aberta. Pequenas escolhas feitas no calor, quando olhar para o lado teria sido fácil. Têm o seu próprio peso. Em que deram?",
 113: "E com que te deixa o dia? Talvez não com uma vitória limpa. Talvez só com o facto de te teres levantado, de teres tentado, de que quando era duro e quente e fácil ficar parado, não ficaste. Isso vale algo. Sempre valeu.",
 114: "Mas nem todo o dia acaba bem. Certas escolhas custam mais do que sabias; certos caminhos, uma vez tomados, não se desandam. É o fim duro do dia, onde o pior volta a casa. Não é fácil de olhar — mas é verdade. Então olha.",
}

def main():
    data = json.load(open(OUT, encoding="utf-8")); a = 0
    for nid, t in G.items():
        k = str(nid)
        if k not in data:
            data[k] = t; a += 1
    data = {k: data[k] for k in sorted(data, key=lambda x: int(x))}
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"cool-of-evening/pt.json: {len(data)} (+{a})")

if __name__ == "__main__":
    main()
