#!/usr/bin/env python3
"""Phase 3 — B1 polish: thicken the thin beats, split the long sentences.

Rewrites the flagged new nodes so B1 sits cleanly inside its band (paragraph ≥ 35 words,
sentences ≤ 25, mean ≤ 16) while keeping the voice — present tense, second person, spare,
humane. Only the B1 slot is touched; A2/B2 stay ⟨pending⟩ for their own passes.
"""
import json, os

EP = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "episode-01.json")
book = json.load(open(EP, encoding="utf-8"))

B1 = {
 41: "The last doors close and the platform empties around you. A few travellers hurry towards the exit with their collars up. One of them stops under a light — a young traveller with a heavy rucksack — and reads a scrap of paper, then reads it again. They look as lost as you feel.",
 46: "You almost miss it: a narrow side door, half hidden behind the hoarding. A thin line of light runs along the bottom of it. Someone is inside after all, this late. For a moment you simply stand and look at that small yellow line.",
 48: "On the next bench a man sits with no bag and no coat, only a paper cup. He is not asking for anything. He has missed the last train, and has nowhere to be until morning. The same as you — except that he has done this on many more nights than you have.",
 49: "You take a wrong turn, and then another. The same shuttered shop slides past twice. The map in your hand has stopped meaning anything at all. The streets have gone quiet in the way they do at one in the morning, when the city belongs to no one.",
 50: "The light comes from a launderette, open all night and empty except for one attendant folding towels. He is glad of the company. He knows these streets by heart, he says, and draws the way in the air with a warm, certain hand.",
 51: "On the glass of an inner door at the back, a painted name is half scraped away. You can still read ROWE under the marks. Someone left in a hurry once, or someone wanted the name gone. In the dark, it is hard to say which is worse.",
 52: "An upstairs window at number 16 is lit. A girl of about ten watches you from behind the glass, quite calm, the way children watch when they are used to strangers at odd hours. She does not wave. She only looks, and waits to see what you will do.",
 53: "A night bus swings round the far corner, its windows warm and yellow, heading the way you think the river lies. It does not slow down. You have a few seconds to decide, and your feet are already tired of deciding.",
 54: "A bridge crosses the black water. On the far side the new offices stand dark and clean, all glass. Only one window is lit, high up, a single square of light. You stand on the bridge a moment and watch it, and it does not go out.",
 55: "A night watchman leans out of a lit hut by the gate. \"Kessler and Rowe? Second floor. But there's nobody in till nine, love.\" He says it kindly, and nods you towards the warmth of the hut. \"Go on. Get out of the cold.\"",
 56: "The Blue Kettle is shut, but there is a light in the back, and the shape of someone stacking chairs. The business card is still taped inside the window, exactly where it was. You cup your hands to the glass and breathe, and wait to be noticed.",
 57: "The woman inside lets you say your piece through a gap in the door. \"Kessler and Rowe? Ada Rowe, you mean. She's down at the river now.\" She almost smiles. \"Comes in here for her coffee, every morning. You'll not miss her.\"",
 58: "The cleaner who woke you is not unkind about it. She pours you half a cup from a flask before you can say no. \"Where've you come from, then,\" she asks, without much curiosity, in the way of someone who has asked it many times before.",
 59: "At breakfast, Mara is there too; she took a room here as well. She leans across the little table. \"There's an agency across the road,\" she says, low. \"They wanted money off me last night, before they'd find me anything. Don't. Whatever they say, don't.\"",
 60: "A queue has already formed outside WORK FOR EVERYONE, before it is even open. Tired faces, early light, breath showing in the cold. Near the front a woman counts out the last of her notes, twice, as if the number might change if she is careful enough.",
 61: "The man in the good suit slides a form across the desk. \"Two hundred for registration, then we place you today. Everybody pays it.\" The small print underneath is grey and very small. He is already reaching for your money before you have read a word.",
 62: "Outside, a man leans on the wall with a receipt like the one you would have had. \"Paid them last week,\" he says. \"They never called.\" He looks at you, almost sorry for you. \"You didn't, did you. Tell me you didn't.\"",
 63: "On the reception desk there is a tray of returned post — old letters, each with the Rosewater Street address crossed out by hand. You look again. One of them, you realise slowly, is your own: the letter that brought you across a country to the wrong door.",
 65: "The driver settles into the story as he drives. \"They all moved to the river. Glass offices, very smart.\" He catches your eye in the mirror. \"And watch the work agencies near the station. They are not what they look like. Not for people like you.\"",
 67: "First light comes up grey over Mill Quay. A coffee cart is opening; delivery vans hum along the water. You are early, and you are clean, and for the first time since the train you know exactly where you are, and where you are going.",
 68: "Watching the other doors along the quay, you see him: the man in the good suit from the agency. He lets himself into a building two doors down. There is no sign on it, and no name. Something about the way he looks around first tells you everything.",
 69: "In your bag there is the letter, a little money that will not last long, and a photograph you do not take out. You read the letter again, though you know every word of it by heart, as if the words might have quietly changed while you slept.",
 72: "Your phone has one bar of battery left. One. You could use it now to look up the firm and settle the question, or save it for something worse later on. In a strange city at night, a dying phone is a kind of clock, counting down.",
 73: "An old page loads, slowly. The firm's address is not Rosewater Street at all, but somewhere down on the river. Then the screen goes black and stays black, and you are alone again with a paper letter and whatever you can remember.",
 75: "Mara has more sense than money, and you have a little more money than sense. Between you there might just be enough to do this properly — instead of both of you walking half the night in the wrong direction, too proud to say you are lost.",
 77: "A guard walks the concourse, turning off the lights one bank at a time. \"Station's closing. You can't sit here.\" He is not unkind, only tired, and he means it. Behind him the big hall goes dark in pieces, and the cold comes in.",
 79: "From the bus window the city slides past, dark and wet and unfamiliar. You could get off early and find your own feet, or stay on to the proper stop and trust the driver to know his own route better than you do.",
 84: "Reception is warm and smells of coffee. The woman behind the desk is kind, and she looks at you a moment longer than she needs to. Last night is written all over you — the creased coat, the tired eyes — and she reads it without a word.",
 85: "Ms Rowe's office looks out over the water. On the desk is a folder, and on top of the folder is a letter you recognise. It is your own — sent to the wrong street, and come back here again. She sees you see it, and says nothing yet.",
 88: "She reaches the step with a coffee in one hand and keys in the other, and sees you waiting there. She does not seem surprised. \"You look like someone who has been up all night,\" she says, unlocking the door. \"Come in, before we both freeze.\"",
 89: "The quay is waking around you: gulls on the grey water, a coffee cart, delivery vans humming along the stone. You have time, for once, and clean hands, for once. It is a strange thing, after such a night, to be simply early.",
 90: "The man in the good suit from the agency sees you seeing him. For a second neither of you moves. Then he lets himself into the unmarked building and is gone. You understand, standing there, exactly what kind of place you walked out of.",
 91: "\"They wanted money off me too,\" the other candidate says quietly. \"For registration, they called it. I nearly paid.\" She shakes her head at herself. You are not the only one, then. That is worth something, though you could not say quite what.",
 92: "Through the window you can see the bridge you crossed in the dark, and the black water under it, ordinary and grey now in the morning. It does not look far at all by daylight. Most things do not, you are learning, by daylight.",
 94: "She calls in a younger colleague, who goes red to the ears. \"The old letterhead,\" she says, not unkindly. \"We'll sort it.\" Then she turns back to you. \"And you can help us sort it. You clearly know the way better than we do.\"",
 95: "The kiosk woman calls after you, pulling the shutter the last of the way down. \"There's a back way into number 14, through the yard. The front door hasn't opened in years.\" She points with her chin, already turning for home.",
 96: "In the yard a low window is lit. Inside, on a desk, there is a tray of envelopes, stamped and ready to post. You lean closer, and the cold goes through you: every one of them is addressed to Rosewater Street. To here. To no one at all.",
 97: "Before you go, the upstairs window opens and the girl leans out into the cold. \"They're by the river now,\" she says, matter-of-fact, as if you should have known. \"Ada Rowe. My dad used to work for her, before all this.\"",
 98: "\"Three Mill Quay,\" she says, as if everyone in the world knows it. \"Take the number four in the morning; it stops right outside.\" Then her father's voice calls her back inside, and the window shuts, and the street is yours again.",
 99: "By the water you lose the thread of the streets entirely. But a boathouse has its lights on, early. You can hear the knock of long oars being carried down to the river, and low voices, and the ordinary sounds of people with somewhere to be.",
 100: "\"Mill Quay? Straight along, past the second bridge. Ten minutes.\" The rower barely breaks step, an oar balanced on one shoulder. \"You're nearly there,\" he adds, seeing your face. \"Whatever it is, you're nearly there now.\"",
 101: "The new development has a glass lobby, lit and empty, a guard's cap left on an untended desk. Everything here is two years newer than the letter in your bag. You stand outside it in last night's clothes, and feel every one of those two years.",
 102: "You wait for the café to open. The sky goes slowly from black to the colour of dishwater. Your feet have stopped hurting, which you suspect is worse than if they still did. At last a light comes on inside, and a chair scrapes.",
 103: "One of the early regulars looks up from his tea. \"Kessler and Rowe? I did their books, years back. Good people.\" He laughs at some private joke. \"Bad with letters, mind. Always were. Ask anyone who ever waited on one.\"",
 104: "The hotel man leans on the desk, in no hurry. \"Word of advice,\" he says. \"That agency across the way, the yellow sign? Don't. They took a lad's last money on Tuesday, and he's still in my lobby, too ashamed to go home.\"",
 105: "The first bus of the day sighs up to the stop, warm and almost empty, its windows running with the cold. It will go towards Rosewater, or you could change for the river. Either way it is moving, which is more than you have managed all night.",
 106: "The address the agency gave you turns out to be an empty lot behind a fence — weeds, a burnt mattress, nothing else. There was never any job here. There was only the two hundred, and the man in the good suit, and both are long gone.",
 107: "A woman near you in the queue reads the form, folds it in half, and hands it back. \"It's a swindle,\" she says, loud enough for the others to hear. \"Come on. All of you.\" And a few of you, hardly believing it, follow her out into the light.",
 108: "The taxi carries you through streets with nobody on them. Shuttered shops, one all-night café throwing yellow light on the wet road, a fox at a corner. The driver hums to the radio. For a few minutes it is almost restful, being carried, deciding nothing.",
 109: "The man at the desk draws you a better map on the back of a receipt, and marks the river with a small careful square. \"That's where the smart ones went,\" he says, sliding it under the glass. \"Off you go, then. Mind how you go.\"",
 110: "You walk to the quay in the growing light, past people going to work who know exactly where they are going. For the first time, so do you. It changes how you walk, knowing where you are going. You had forgotten that it would.",
 111: "The young woman from number 16 is going the same way. \"Number four,\" she says, nodding at the bus. \"I'll show you where to get off.\" She says it easily, as if helping a stranger to work were the most ordinary thing in the world. Perhaps here it is.",
 112: "You go to the office to explain yourself, late and out of breath, rehearsing the words on the stairs. None of them sound right. All of them begin with sorry. And you have a feeling, climbing, that sorry is not going to be enough this morning.",
 113: "The woman at the coffee cart takes one look at you and puts an extra shot in, no charge. \"Long night,\" she says. It is not a question. You hold the hot cup in both hands and feel it in your fingers first, and then, slowly, everywhere else.",
 114: "You sit with the cold coffee and decide, finally, to trust the letter that brought you here. Or at least to trust the person who wrote it; someone, somewhere, meant you to come. That has to count for something. You fold the letter away and stand up.",
 115: "You cross an empty market square, the stalls folded away for the night, wet cobbles shining under one lamp. A single fox trots along the gutter as though it owns the hour. It glances at you once, and decides you are nothing to worry about.",
 116: "A taxi idles at the kerb, its light on, the driver reading a paper by the dashboard glow. It would cost you more than you want to spend. But it would end the walking, and the walking has begun to feel like the whole of your life.",
 117: "The cleaner sighs and props the door with her foot. \"Leave a note if you must,\" she says. \"I'll put it on Ada's desk in the morning. No promises, mind.\" She holds out a hand for it, already looking past you at all she has to do.",
 118: "You take a photograph of the half-scraped name, twice, in case one comes out blurred. Proof, of a kind, that you were here and looked, and did not simply give up. You are not sure who you are proving it to. Yourself, probably. It will have to do.",
 119: "You wait outside the café for it to open, stamping your feet against the cold. You watch the card in the window as if it might change its mind. It does not. It says exactly what it said an hour ago. But it is something to watch, and you are past being proud.",
 120: "Ms Rowe sits back in her chair and looks at you for a moment. \"Tell me,\" she says. \"Why should I take on someone I have never met, who found us more or less by accident?\" It is a fair question. She waits for the answer, and does not hurry you.",
 121: "You tell her about the bright office, and the man in the good suit, and the two hundred he wanted up front. She listens without a flicker. \"There is one of those on every corner now,\" she says quietly. \"You were right to walk away.\"",
 122: "The late worker is going your way and splits a cab with you. \"You'll never find it on foot in the dark,\" she says, not unkindly. \"And you look done in.\" You get in gratefully. The heater is on, and for ten minutes you let someone else know the way.",
 123: "The watchman waves you into the warmth of his hut and pours something from a flask into a tin cup. \"Nine o'clock,\" he says again, kindly. \"Not a minute before. So you may as well be warm about it.\" You wrap both hands round the cup and stay.",
 124: "In the coffee-cart queue you hear the name before you see anyone. \"...Ada Rowe wants the Thursday figures...\" Two people from the second floor, talking shop, coats over their arms. You are close now. You can hear the ordinary morning of the place you have been trying all night to reach.",
 125: "Mara is at breakfast with the same idea as you. \"The river,\" she says. \"We could go together. Safer, and I hate arriving alone.\" She says the last part quietly, and you understand it completely, because so do you. So you finish your coffee and go together.",
 126: "The cleaner has worked this station for twenty years. \"Kessler and Rowe,\" she says, leaning on her machine. \"They did right by my sister once, when nobody else would.\" She looks at you steadily. \"Go and find them. Don't sleep your chance away on my bench.\"",
 127: "You leave your name and number with the counter man, just in case. \"If they come in,\" you say. He writes it on the back of a docket and nods, as if he has heard it many times before. Which, you understand, he has. Everyone here is looking for someone.",
 128: "Dawn on the bench. Your back is ruined and your money is nearly gone. But you are not, it turns out, ready to give up. Not quite yet. You sit up. The morning is grey and ordinary and full of buses, and one of them is going your way.",
 129: "You cannot afford the room, and the man behind the desk sees it, and something in him gives. \"Sit in the lobby till it's light,\" he says, turning back to his book. \"There's a radiator by the window. I never saw you.\" You sit. You could have wept, but you sit.",
 145: "You share what little you have. The job does not come — the diary is full, the timing wrong. But the man from the bench, it turns out, has a room, a kettle, a spare key. He has a brother, too, always looking for hands. You are not hired. You are also, for the first time since the train, not alone.",
 147: "The morning comes up grey over the station bench, and you let it. You are too cold and too tired to move. It is only for a minute, you tell yourself. But by the time you can feel your feet again, nine o'clock has come and gone — and so has the only reason you came to this city.",
}

for n in book["nodes"]:
    if n["id"] in B1 and isinstance(n.get("text"), dict):
        n["text"]["B1"] = B1[n["id"]]

json.dump(book, open(EP, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
print(f"Polished B1 for {len(B1)} nodes.")
