#!/usr/bin/env python3
"""Phase 3 — the B2 pass: enrich each new node's B1 into B2.

B2 keeps the same events and the same restrained voice, but with richer vocabulary and
more complex sentences (mean ≤ 22 words, sentences ≤ 35). Choices take the B1 label at
B2 (short imperatives need no enrichment). This completes all three levels for every node.
"""
import json, os

EP = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "episode-01.json")
book = json.load(open(EP, encoding="utf-8"))

B2 = {
 41: "The last doors sigh shut and the platform empties around you, the crowd thinning to a few figures hurrying towards the exit with their collars turned up. One of them, a young traveller stooped under a heavy rucksack, stops beneath a light and reads a scrap of paper, then reads it again — precisely the way you keep rereading your own letter, as though the words might have quietly rearranged themselves. They look, it strikes you, exactly as lost as you feel.",
 42: "Her name is Mara, and she came in on the same train — here for work too, and no more at home in this city than you are. For a few minutes, standing together in the flat cold light of the station, neither of you is quite alone. Her address lies somewhere across the river; yours is a street she has never so much as heard of, which does nothing to steady either of you.",
 43: "The man at the newsstand is old and unhurried, and reads your letter through twice before he speaks. \"Rosewater Street,\" he says at last. \"You'll be the third I've sent that way this month. Somebody up there still writes the old address on the letters.\" He folds the paper and hands it back, as though the matter is now closed.",
 44: "\"They moved down to the river years ago,\" he says. \"New offices, all glass and no soul. But the letters still go out with Rosewater Street on the front, and back they come. Not my business.\" He shrugs, and the shrug is entirely convincing. It is somebody's business, though, you think — and by tomorrow, if things go well, it might even be yours.",
 45: "Half of Rosewater Street has vanished behind builders' hoarding. On one panel a torn notice still bears the firm's name in faded, official print, and beneath it someone has written a single word in thick black marker, with an arrow driven hard to the east, towards the water: MOVED.",
 46: "You very nearly miss it — a narrow side door, set half behind the hoarding, with a thin seam of light running along the bottom edge. Someone is inside after all, at this hour, and for a moment you simply stand in the dark and study that small yellow line as though it might tell you something.",
 47: "After a while the door opens and a woman steps out, shrugging herself into a coat. She is tired, but there is nothing unkind in her. \"Nobody works here now,\" she says. \"They're down by the river. If you can't wait until morning, ask at the café on the corner — they know everyone worth knowing on this street.\"",
 48: "On the next bench sits a man with no bag and no coat, only a paper cup held in both hands. He asks you for nothing. He has missed the last train and has nowhere to be until morning — the same predicament as yours, in every particular, except that he has weathered it on a great many more nights than you have.",
 49: "You take a wrong turning, and then another, until the same shuttered shop has slid past you twice and the map in your hand has ceased to mean anything at all. The streets have fallen into the particular silence they keep at one in the morning, the hour when a city belongs to no one and admits it.",
 50: "The light turns out to be a launderette, open through the night and empty but for a single attendant folding towels, who is plainly glad of the company. He knows these streets the way you know your own hands, he says, and sketches the route in the air with a warm and absolute certainty you find yourself wanting to believe.",
 51: "On the glass of an inner door at the back, a painted name has been half scraped away; you can still make out ROWE beneath the scars in the paint. Someone left in a hurry, once, or someone wanted the name gone for good — and standing there in the dark, you find it genuinely hard to say which reading is the more unsettling.",
 52: "An upstairs window at number 16 is lit, and a girl of perhaps ten watches you from behind the glass with perfect composure — the way children watch when strangers at odd hours have long since stopped being remarkable. She does not wave. She simply looks, and waits to see what you will do, and somehow that is worse than if she had called out.",
 53: "A night bus swings round the far corner, its windows warm and yellow, bound the way you believe the river lies. It shows no sign of slowing. You have a handful of seconds in which to decide, and your feet, you realise, are thoroughly tired of being asked to decide anything more tonight.",
 54: "A bridge carries you over the black water. On the far bank the new offices stand dark and immaculate, all glass and right angles, save for a single window lit high up — one small square of yellow in all that emptiness. You pause on the bridge and watch it, half expecting it to go out, and it does not.",
 55: "A night watchman leans out from a lit hut beside the gate. \"Kessler and Rowe? Second floor. But there's nobody in until nine, love, whatever your letter says.\" He says it gently, and tips his head towards the warmth behind him. \"Go on. There's no sense freezing out here for the sake of six hours.\"",
 56: "The Blue Kettle is shut, but a light burns in the back and there is the unmistakable shape of someone stacking chairs. The business card is still taped inside the window, exactly where it was, a small square of hope. You cup your hands against the cold glass, breathe onto it, and wait to be noticed.",
 57: "The woman inside lets you say your piece through a gap in the door, no wider than her patience. \"Kessler and Rowe? Ada Rowe, you'll mean. She's down at the river these days.\" Something in her face softens. \"Comes in here for her coffee every morning, regular as anything. You'll not miss her.\"",
 58: "The cleaner who woke you is decent about it, and pours you half a cup from a battered flask before you can think to refuse. \"Where've you come from, then,\" she asks, without any real curiosity, in the manner of someone who has put the same question to a great many people on a great many cold mornings.",
 59: "At breakfast Mara is there too — she had taken a room here as well — and she leans across the little table with her voice lowered. \"There's an agency across the road,\" she says. \"They wanted money off me last night, up front, before they'd so much as look for work. Don't. Whatever they tell you, don't.\"",
 60: "A queue has already gathered outside WORK FOR EVERYONE, though the door is not yet open: tired faces in the thin early light, breath hanging in the cold. Near the front a woman counts out the last of her notes, and then counts them a second time, as though the total might improve if only she is careful enough.",
 61: "The man in the good suit slides a form across the desk with practised ease. \"Two hundred for registration, and then we place you today. Everybody pays it, it's completely normal.\" The small print beneath is grey and very fine, and his hand is already drifting towards your money before you have managed to read a single line of it.",
 62: "Outside, a man is propped against the wall with a receipt exactly like the one you would have carried away. \"Paid them last week,\" he says, without heat. \"They never rang.\" He looks at you with something close to pity. \"You didn't, did you. Go on — tell me you didn't.\"",
 63: "On the reception desk stands a tray of returned post — old letters, each with the Rosewater Street address struck out by hand. You look again, and then again, and the recognition arrives slowly and coldly: one of them is unmistakably your own, the very letter that carried you the length of a country to a door that no longer opens.",
 65: "The driver settles comfortably into the story as he drives. \"They all moved down to the river. Glass offices, very smart, very modern.\" He finds your eyes in the mirror. \"And you want to watch those work agencies near the station. They are not what they appear to be — not for people newly arrived, people like you.\"",
 67: "First light comes up grey and even over Mill Quay. A coffee cart is cranking open its shutter; delivery vans hum along the water. You are early, and you are clean, and for the first time since you stepped off that train you know with real precision both where you are and where you are going.",
 68: "Watching the other doors strung along the quay, you catch sight of him: the man in the good suit from the agency, letting himself into a building two doors down. There is no sign on it and no name of any kind, and something in the careful, sidelong way he checks the street before he enters tells you everything you needed to know.",
 69: "In your bag there is the letter, a little money that will plainly not stretch far, and a photograph you deliberately do not take out. You read the letter once more, though you have long since known it by heart, half persuaded that the words might have quietly altered themselves while you slept in your seat.",
 72: "Your phone shows a single bar of battery — one — and the choice it forces is oddly stark: you might use it now to look up the firm and settle the question outright, or hoard it against some worse moment still to come. In a strange city after midnight, a dying phone becomes a kind of clock, counting down to a silence you would rather not meet.",
 73: "An old page loads, grudgingly and by degrees. The firm's registered address, it turns out, is not Rosewater Street at all, but somewhere down along the river. Then the screen blinks to black and stays black, and you are returned to your own devices — a paper letter, and whatever you can hold in your head.",
 75: "Mara, you gather, has rather more sense than money, while you have marginally more money than sense; and between the two of you there might just be enough to manage this properly — instead of both of you tramping half the night in the wrong direction, each too proud to be the first to admit to being lost.",
 77: "A guard works his way along the concourse, killing the lights a bank at a time. \"Station's closing. You can't sit about here.\" There is no unkindness in it, only fatigue, and he plainly means it. Behind him the great hall goes dark in sections, and with each one the cold presses a little further in.",
 79: "From the bus window the city unspools past you, dark and wet and wholly unfamiliar. You could get down early and trust your own two feet, or you could stay aboard to the proper stop and trust instead that the driver knows his own route rather better than a stranger with a useless map.",
 84: "Reception is warm and smells faintly of coffee. The woman behind the desk is kind, and she holds your gaze a moment longer than strictly necessary; last night is written all over you — the creased coat, the shadowed eyes, the particular stillness of the very tired — and she reads every line of it without saying a word.",
 85: "Ms Rowe's office gives onto the water. On the desk sits a folder, and squared on top of the folder is a letter you recognise at once: your own, sent to the wrong street, returned, and somehow arrived here ahead of you. She watches you take it in, and for the moment says nothing at all.",
 86: "\"Someone in this office has been posting the old address for two years,\" she says, turning the returned letter over in her fingers. \"You are by no means the first it has sent astray.\" She sets it down and looks at you properly. \"You are, however, the first to have come anyway.\"",
 88: "She arrives at the step with a coffee in one hand and a bunch of keys in the other, and takes you in without the least surprise. \"You have the look of someone who has been up the whole night,\" she says, fitting a key to the lock. \"Come in, for pity's sake, before the pair of us freeze to the pavement.\"",
 89: "The quay is stirring awake around you: gulls riding the grey water, a coffee cart, delivery vans humming along the worn stone. You have time, for once, and clean hands, for once. After a night like the one behind you, there is something almost disorienting in the simple fact of being early.",
 90: "The man in the good suit from the agency catches you watching him. For the length of a breath neither of you so much as moves. Then he lets himself into the unmarked building and is gone — and standing there in the cold morning, you understand with perfect clarity exactly what kind of place it was that you walked out of.",
 91: "\"They wanted money off me too,\" the other candidate murmurs. \"For registration, they called it. I very nearly paid.\" She shakes her head at her own near miss. So you were not the only one, then — a small, cold comfort, and worth something all the same, though you could not easily put into words quite what.",
 92: "Through the window you can pick out the bridge you crossed in the dark, and the black water beneath it, entirely ordinary and grey now in the flat morning light. It does not look remotely far by daylight. Very little does, you are beginning to understand, once the daylight has got at it.",
 94: "She calls in a younger colleague, who colours to the roots of his hair. \"The old letterhead,\" she says, not unkindly. \"We shall sort it out.\" Then she turns back to you, and there is something decided in her face. \"And you can help us sort it out. You clearly know the way to us rather better than we do ourselves.\"",
 95: "The kiosk woman calls after you as she hauls the shutter down the last foot to the ground. \"There's a back way into number 14, mind — through the yard. That front door's not opened in years.\" She tips her chin towards it, already turning for home and whatever warmth is waiting there.",
 96: "In the yard a low window is lit, and inside, laid out on a desk, is a tray of envelopes, stamped and squared and ready for the post. You lean in closer, and the cold goes clean through you: every last one of them is addressed to Rosewater Street. To here. To no one who has worked here in two years.",
 97: "Before you can turn away, the upstairs window opens and the girl leans out into the cold air. \"They're by the river now,\" she says, matter-of-factly, as though it were common knowledge you ought to have arrived with. \"Ada Rowe. My dad used to work for her, before all of this went the way it did.\"",
 98: "\"Three Mill Quay,\" she says, as if it were the most self-evident thing in the world. \"Take the number four in the morning; it stops directly outside.\" Then her father's voice summons her back from somewhere inside, and the window closes, and the street is handed back to you and the cold.",
 99: "Down by the water you lose the thread of the streets entirely. But a boathouse has its lights burning, early, and there comes the hollow knock of long oars being carried down to the river, and low voices with it — the unremarkable sounds of people who know precisely where they are going and why.",
 100: "\"Mill Quay? Straight along the bank, past the second bridge. Ten minutes, no more.\" The rower scarcely breaks his stride, an oar balanced across one shoulder. \"You're nearly there,\" he adds, catching something in your face, \"whatever it is you're chasing. You're nearly there now.\"",
 101: "The new development offers a glass lobby, lit and quite empty, a guard's cap abandoned on an untended desk. Everything in it is two full years newer than the letter folded in your bag, and standing outside it in last night's crumpled clothes, you feel the weight of every one of those two years settle on you.",
 102: "You wait for the café to open. The sky shades by slow degrees from black to the exact colour of dishwater. Your feet have stopped hurting, which you strongly suspect is a worse sign than if they still ached. At long last a light comes on inside, and somewhere a chair scrapes across a floor.",
 103: "One of the early regulars glances up from his tea. \"Kessler and Rowe? I kept their books, years back. Good people, the pair of them.\" He laughs at some joke of his own. \"Hopeless with letters, mind — always were. Ask anyone who ever sat waiting on one to arrive.\"",
 104: "The hotel man leans on the desk, in no particular hurry to be anywhere. \"A word of advice,\" he says. \"That agency across the way, the one with the yellow sign — don't. They had a lad's last penny off him on Tuesday, and he's sitting in my lobby still, too ashamed of himself to go home.\"",
 105: "The first bus of the day sighs up to the stop, warm and all but empty, its windows streaming with condensation. It will carry you towards Rosewater, or you might change for the river. Either way it is moving, and moving, just now, is a great deal more than you have contrived to do all night.",
 106: "The address the agency pressed on you resolves, in daylight, into an empty lot behind a fence — weeds, a burnt mattress, and nothing else whatsoever. There was never any job here to be had. There was only the two hundred, and the man in the good suit who wanted it, and both are comprehensively gone.",
 107: "A woman near you in the queue reads the form through, folds it deliberately in half, and hands it back. \"It's a swindle,\" she announces, pitched loud enough for the whole line to catch. \"Come on. All of you.\" And a few of you, scarcely able to credit that it is permitted, peel away and follow her out into the light.",
 108: "The taxi bears you through streets with not a soul on them — shuttered shops, one all-night café throwing its yellow light across the wet road, a fox picking its way along a gutter. The driver hums quietly along to the radio, and for a few minutes it is almost restful, this business of being carried somewhere and deciding nothing at all.",
 109: "The man behind the desk draws you a far better map on the back of a receipt, and marks the river with one small, careful square. \"That's where the smart ones took themselves off to,\" he says, easing it under the glass. \"Off you go, then. And mind how you go — it's a long walk to be lost on.\"",
 110: "You walk down to the quay in the strengthening light, past people bound for work who know exactly where they are going, and for the first time so, it turns out, do you. It alters the very way you walk, this business of having a destination. You had genuinely forgotten that it would.",
 111: "The young woman from number 16 is headed the same way. \"Number four,\" she says, nodding at the bus. \"I'll show you where to get off.\" She offers it lightly, as though steering a total stranger towards work were the most ordinary act imaginable — and perhaps, in a city like this one, at an hour like this, it genuinely is.",
 112: "You make for the office to explain yourself, late and out of breath, rehearsing your words on the stairs as you climb. Not one of them sounds right in your mouth. Every last version begins with sorry, and you have the sinking sense, arriving at the top, that sorry is not going to be anywhere near enough this morning.",
 113: "The woman at the coffee cart takes one look at you and puts an extra shot in without being asked, and without charging you for it. \"Long night,\" she says. It is not a question. You cradle the hot cup in both hands and feel the warmth of it first in your fingers, and then, by slow degrees, very nearly everywhere.",
 114: "You sit with the coffee going cold in front of you and decide, at long last, to trust the letter that dragged you all this way — or at any rate to trust the person who wrote it, since someone, somewhere, meant for you to come. That has to count for something. You fold the letter away, and you stand up.",
 115: "You cut across an empty market square, the stalls all folded away for the night, the wet cobbles gleaming under a single lamp. A lone fox trots along the gutter as though it holds the freehold on this hour, and perhaps it does; it flicks one glance in your direction and concludes, correctly, that you are nothing whatever to worry about.",
 116: "A taxi idles at the kerb, its light on, the driver reading a paper by the glow of the dashboard. It would cost you rather more than you can comfortably spare. But it would put an end to the walking — and the walking, somewhere in the last hour, has quietly begun to feel like the whole of your life.",
 117: "The cleaner sighs and wedges the door with one foot. \"Leave a note, if you must,\" she says. \"I'll put it on Ada's desk in the morning. No promises, mind.\" She holds out a hand for it, already looking clean past you at the long list of everything else the night has left for her to do.",
 118: "You photograph the half-scraped name, twice over, in case one comes out blurred — proof, of a kind, that you came this far and looked, and did not simply turn round and give it up. Who exactly the proof is for, you could not say. Yourself, most likely. It will have to do.",
 119: "You wait outside the café for it to open, stamping some feeling back into your feet, watching the card in the window as though it might yet reconsider. It does not. It says precisely what it said an hour ago, and an hour before that. But it is something to fix your eyes on, and you are long past the luxury of pride.",
 120: "Ms Rowe settles back in her chair and regards you for a moment. \"Tell me,\" she says, \"why I ought to take on someone I have never met, who found their way to us more or less by accident.\" It is an entirely fair question, and she waits for your answer without the smallest show of hurrying you.",
 121: "You tell her about the too-bright office, and the man in the good suit, and the two hundred he wanted in hand before he would trouble himself to find you any work at all. She listens without a flicker of surprise. \"There is one of those on every corner now,\" she says quietly. \"You were quite right to walk away from it.\"",
 122: "The late worker is bound your way and splits a cab with you. \"You'll never find it on foot in the dark,\" she says, not unkindly, \"and you look completely done in.\" You climb in with something like gratitude. The heater is going, and for ten unearned minutes you surrender the whole problem and let somebody else know the way.",
 123: "The watchman waves you into the warmth of his hut and pours something dark and scalding from a flask into a dented tin cup. \"Nine o'clock,\" he says again, kindly but immovably. \"Not a minute before. So you may as well be warm about the waiting.\" You wrap both hands round the cup, and you stay.",
 124: "In the coffee-cart queue you catch the name before you catch sight of anyone at all. \"...Ada Rowe wants the Thursday figures...\" Two people from the second floor, talking shop with their coats over their arms. You are close now — close enough to overhear the ordinary morning of the very place you have spent the whole night trying to reach.",
 125: "Mara is at breakfast, arrived at the same conclusion as you. \"The river,\" she says. \"We could go together. Safer that way — and I do hate arriving somewhere alone.\" She says the last of it quietly, and you understand her completely, for the plain reason that so, it turns out, do you. So you finish your coffee, and the two of you go.",
 126: "The cleaner has worked this station for twenty years, and says so. \"Kessler and Rowe,\" she says, leaning on the handle of her machine. \"They did right by my sister once, when nobody else in this city would.\" She fixes you with a steady look. \"Go and find them. Don't you dare sleep your one chance away on my bench.\"",
 127: "You leave your name and number with the man behind the counter, on the off-chance. \"If they come in,\" you say. He writes it on the back of a docket and nods, in the manner of someone who has heard the same request more times than he could count — which, you understand, he has. Everyone in this place is looking for someone.",
 128: "Dawn on the bench. Your back is wrecked and your money is very nearly gone. But you are not, it emerges, ready to give the whole thing up. Not quite yet. You sit up, and the morning is grey and ordinary and thick with buses, and one of them, you happen to know, is going your way.",
 129: "You cannot run to the price of the room, and the man behind the desk sees it plainly, and something in him quietly gives way. \"Sit in the lobby till it's light,\" he says, turning back to his book. \"There's a radiator by the window. I never saw you.\" So you sit. You could, without much difficulty, have wept — but you sit.",
 141: "You answer plainly. You tell her what you can do and what you cannot, and you take some care not to pretend to be anyone other than who you are. It proves to be enough. \"We can use someone like that,\" she says. \"Start on Monday.\" No grand story, and no luck to speak of — only work, honestly come by.",
 142: "You walk in rested and clear-headed, owing nothing whatever to any of the people who tried to sell you hope across the small hours; and somehow, unaccountably, it shows. Ms Rowe considers you for a moment and comes very close to smiling. \"You had a good night, for a stranger in a strange city,\" she says. \"Start on Monday.\"",
 143: "There is no job to be had today. But she takes down your name herself, by hand, on a real sheet of paper rather than tapping it into a screen to be lost. \"We shall have something in the spring,\" she says. \"Come back to us then.\" It is not what you came for. But you are in the city now, and someone in it knows your name.",
 144: "Name, number, reference. The whole thing goes off without a hitch, and by lunchtime the job is yours. Nobody thinks to ask how you got here, or what the night took out of you, and you volunteer none of it. You have got precisely what you came for. Standing on the new carpet, you wait to feel something about that, and nothing whatever arrives.",
 145: "You share out what little you have. The job does not materialise — the diary is full, the timing all wrong. But the man from the bench, as it turns out, has a room, a kettle, a spare key, and a brother forever short of a pair of hands. You are not hired. You are also, for the first time since the train pulled in, not alone.",
 146: "You reach Mill Quay at twenty past nine. The diary is closed, the chairs in reception are full of other, punctual people, and the woman behind the desk is kind and entirely final about it. \"Do try us in the spring,\" she says, and the two of you understand perfectly well that she means no. Outside, the river carries on exactly as before.",
 147: "The morning comes up grey over the station bench, and you let it come. You are too cold and too spent to move, and you tell yourself it is only for a minute more. But by the time the feeling has crept back into your feet, nine o'clock has been and gone — and gone with it is the single reason you came to this city at all.",
}

nodes = choices = 0
for n in book["nodes"]:
    if n["id"] in B2 and isinstance(n.get("text"), dict):
        n["text"]["B2"] = B2[n["id"]]; nodes += 1
    for c in n.get("choices", []):
        t = c.get("text")
        if isinstance(t, dict) and str(t.get("B2", "")).startswith("⟨B2 pending"):
            t["B2"] = t.get("B1", ""); choices += 1

json.dump(book, open(EP, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
print(f"B2 pass: wrote B2 for {nodes} nodes and filled {choices} choice B2 slots.")
